// apps/ant-design-vue/src/App.vue
<script setup lang="ts">
import { computed, ref, watchEffect } from "vue"
import { RouterView, useRoute } from "vue-router"
import { ConfigProvider, App as AntApp, theme } from "ant-design-vue"
import AppShell from "./layouts/app-shell.vue"
import router from "./router"

const route = useRoute()
const params = new URLSearchParams(window.location.search)
const dark = ref(params.get("theme") === "dark" || (!params.get("theme") && window.matchMedia("(prefers-color-scheme: dark)").matches))
const font = params.get("font") ?? "default"
const fontMap: Record<string, string> = {
  inter: "'Inter Variable', sans-serif",
  geist: "'Geist Variable', sans-serif",
  "noto-sans-sc": "'Noto Sans SC Variable', sans-serif",
  "lxgw-wenkai": "'LXGW WenKai Screen', serif",
}
const isPublic = computed(() => route.path === "/login" || route.path === "/landing")
const configTheme = computed(() => ({ algorithm: dark.value ? theme.darkAlgorithm : theme.defaultAlgorithm, ...(fontMap[font] ? { token: { fontFamily: `var(--font-sans)` } } : {}) }))
watchEffect(() => {
  document.documentElement.classList.toggle("dark", dark.value)
  document.documentElement.style.colorScheme = dark.value ? "dark" : "light"
  document.documentElement.style.setProperty("--font-sans", fontMap[font] ?? "inherit")
  document.body.style.background = dark.value ? "#141414" : "#f5f5f5"
})
function toggleTheme() {
  dark.value = !dark.value
  const next = new URL(window.location.href)
  next.searchParams.set("theme", dark.value ? "dark" : "light")
  router.push(`${route.path}?${next.searchParams.toString()}`)
}
</script>

<template>
  <ConfigProvider :theme="configTheme">
    <AntApp>
      <template v-if="isPublic">
        <RouterView />
      </template>
      <AppShell v-else :dark="dark" @toggle-theme="toggleTheme">
        <RouterView />
      </AppShell>
    </AntApp>
  </ConfigProvider>
</template>

// apps/antd/src/App.tsx
import { useEffect, useState, type ReactNode } from "react"
import { App as AntApp, ConfigProvider, theme } from "antd"
import zhCN from "antd/locale/zh_CN"
import { createBrowserRouter, RouterProvider } from "react-router-dom"
import { AppShell } from "@/layouts/app-shell"
import { ThemeSettingsContext } from "@/pages/shared"
import { LoginPage } from "@/pages/login"
import { DashboardPage } from "@/pages/dashboard"
import { OrdersPage } from "@/pages/orders"
import { FormPage } from "@/pages/form"
import { SettingsPage } from "@/pages/settings"
import { ComponentsPage } from "@/pages/components"
import { LandingPage } from "@/pages/landing"
import { ChatPage } from "@/pages/chat"

function useUrlSettings() {
  const read = () => {
    const params = new URLSearchParams(window.location.search)
    return (
      params.get("theme") === "dark" ||
      (!params.get("theme") &&
        window.matchMedia("(prefers-color-scheme: dark)").matches)
    )
  }
  const [dark, setDark] = useState(read)
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const fonts: Record<string, string> = {
      inter: "'Inter Variable', sans-serif",
      geist: "'Geist Variable', sans-serif",
      "noto-sans-sc": "'Noto Sans SC Variable', sans-serif",
      "lxgw-wenkai": "'LXGW WenKai Screen', serif",
    }
    const defaultFont = theme.getDesignToken().fontFamily
    document.documentElement.style.setProperty(
      "--font-sans",
      fonts[params.get("font") ?? ""] ?? defaultFont
    )
    document.documentElement.style.colorScheme = dark ? "dark" : "light"
  }, [dark])
  useEffect(() => {
    const sync = () => setDark(read())
    window.addEventListener("themechange", sync)
    return () => window.removeEventListener("themechange", sync)
  }, [])
  return { dark, setDark }
}

function BodyBackground() {
  const { token } = theme.useToken()
  useEffect(() => {
    document.body.style.background = token.colorBgLayout
    return () => {
      document.body.style.background = ""
    }
  }, [token.colorBgLayout])
  return null
}

const shell = (element: ReactNode) => <AppShell>{element}</AppShell>
const router = createBrowserRouter(
  [
    { path: "/login", element: <LoginPage /> },
    { path: "/", element: shell(<DashboardPage />) },
    { path: "/orders", element: shell(<OrdersPage />) },
    { path: "/form", element: shell(<FormPage />) },
    { path: "/settings", element: shell(<SettingsPage />) },
    { path: "/components", element: shell(<ComponentsPage />) },
    { path: "/landing", element: <LandingPage /> },
    { path: "/chat", element: shell(<ChatPage />) },
  ],
  { basename: "/apps/antd" }
)

export default function App() {
  const { dark, setDark } = useUrlSettings()
  return (
    <ThemeSettingsContext.Provider value={{ dark, setDark }}>
      <ConfigProvider
        locale={zhCN}
        theme={{
          algorithm: dark ? theme.darkAlgorithm : theme.defaultAlgorithm,
          token: { fontFamily: "var(--font-sans)" },
          cssVar: true as never,
        }}
      >
        <BodyBackground />
        <AntApp>
          <RouterProvider router={router} />
        </AntApp>
      </ConfigProvider>
    </ThemeSettingsContext.Provider>
  )
}
