// apps/antd/src/layouts/app-shell.tsx
import { useState, type ReactNode } from "react"
import { Link, useLocation, useNavigate } from "react-router-dom"
import {
  App,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  Card,
  Drawer,
  Dropdown,
  Flex,
  Input,
  Layout,
  List,
  Menu,
  Popover,
  Space,
  Typography,
  theme,
} from "antd"
import type { MenuProps } from "antd"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import team from "@ui-gallery/spec/mock/team.json"
import { Icon } from "@/icons"
import { useThemeSettings, avatar } from "@/pages/shared"

export function AppShell({ children }: { children: ReactNode }) {
  const { dark, setDark } = useThemeSettings()
  const { token } = theme.useToken()
  const { message } = App.useApp()
  const [collapsed, setCollapsed] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const location = useLocation()
  const navigate = useNavigate()
  const current =
    nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const navGroups: Array<{ label: string; keys: string[] }> = [
    { label: "工作区", keys: ["dashboard", "orders", "form", "chat"] },
    { label: "资源", keys: ["components", "landing"] },
    { label: "系统", keys: ["settings", "login"] },
  ]
  const menuItems: MenuProps["items"] = navGroups.map((group) => ({
    type: "group",
    key: group.label,
    label: group.label,
    children: nav
      .filter((item) => group.keys.includes(item.key))
      .map((item) => ({
        key: item.path,
        icon: <Icon name={item.icon} />,
        label: item.badge ? (
          <Flex justify="space-between" align="center">
            <span>{item.label}</span>
            <Badge count={item.badge} size="small" />
          </Flex>
        ) : (
          item.label
        ),
        onClick: () => {
          navigate(item.path)
          setMobileOpen(false)
        },
      })),
  }))
  const toggleTheme = () => {
    const next = !dark
    setDark(next)
    const params = new URLSearchParams(window.location.search)
    params.set("theme", next ? "dark" : "light")
    window.history.replaceState(
      {},
      "",
      `${location.pathname}?${params.toString()}`
    )
    window.dispatchEvent(new Event("themechange"))
  }
  const navigation = (
    <Flex vertical style={{ height: "100%", minHeight: 0 }}>
      <Flex
        align="center"
        justify="space-between"
        style={{ padding: "16px 20px", flexShrink: 0 }}
      >
        <Link
          to="/"
          style={{ color: "inherit", fontWeight: 700, fontSize: 18 }}
        >
          Acme Console
        </Link>
        <Button
          className="desktop-only"
          type="text"
          icon={<Icon name="chevron-left" />}
          onClick={() => setCollapsed((value) => !value)}
          aria-label="折叠导航"
        />
      </Flex>
      <div style={{ flex: 1, minHeight: 0, overflowY: "auto" }}>
        <Menu
          mode="inline"
          selectedKeys={[location.pathname]}
          items={menuItems}
          style={{ borderInlineEnd: 0 }}
        />
      </div>
      <div style={{ padding: 16, flexShrink: 0 }}>
        <Card size="small">
          <Space>
            {avatar(team[0].name)}
            <div>
              <div>{team[0].name}</div>
              <Typography.Text type="secondary" style={{ fontSize: 12 }}>
                {team[0].role}
              </Typography.Text>
            </div>
          </Space>
        </Card>
      </div>
    </Flex>
  )
  const noticeContent = (
    <List
      size="small"
      dataSource={notifications}
      renderItem={(item) => (
        <List.Item>
          <List.Item.Meta title={item.title} description={item.time} />
          {item.unread ? <Badge status="processing" /> : null}
        </List.Item>
      )}
    />
  )
  const accountItems: MenuProps["items"] = [
    "个人资料",
    "账号设置",
    "快捷键",
    "帮助中心",
    "退出登录",
  ].map((label) => ({
    key: label,
    label,
    onClick: () => {
      if (label === "退出登录") message.info("演示环境不会退出登录")
      if (label === "账号设置") navigate("/settings")
    },
  }))
  return (
    <Layout style={{ minHeight: "100vh" }}>
      <Layout.Sider
        theme="light"
        breakpoint="md"
        collapsedWidth={0}
        collapsible
        collapsed={collapsed}
        onCollapse={setCollapsed}
        trigger={null}
        width={248}
        style={{
          position: "sticky",
          top: 0,
          height: "100vh",
          borderInlineEnd: `1px solid ${token.colorBorderSecondary}`,
        }}
      >
        {navigation}
      </Layout.Sider>
      <Layout className="shell-main">
        <Layout.Header
          style={{
            paddingInline: 16,
            background: token.colorBgContainer,
            display: "flex",
            alignItems: "center",
            gap: 12,
          }}
        >
          <Button
            className="mobile-only"
            icon={<Icon name="menu" />}
            onClick={() => setMobileOpen(true)}
            aria-label="打开导航"
          />
          <Button
            className="desktop-only"
            type="text"
            icon={<Icon name="menu" />}
            onClick={() => setCollapsed((value) => !value)}
            aria-label="折叠导航"
          />
          <Breadcrumb
            items={[
              { title: <Link to="/">Acme Console</Link> },
              { title: current },
            ]}
          />
          <Input.Search
            className="desktop-only"
            placeholder="搜索..."
            style={{ maxWidth: 300, marginLeft: "auto" }}
          />
          <Space style={{ marginLeft: "auto" }}>
            <Popover
              title="通知"
              content={noticeContent}
              trigger="click"
              placement="bottomRight"
            >
              <Badge count={notifications.filter((item) => item.unread).length}>
                <Button
                  type="text"
                  icon={<Icon name="bell" />}
                  aria-label="通知"
                />
              </Badge>
            </Popover>
            <Button
              type="text"
              icon={<Icon name={dark ? "sun" : "moon"} />}
              onClick={toggleTheme}
              aria-label="切换主题"
            />
            <Dropdown menu={{ items: accountItems }} trigger={["click"]}>
              <Button
                type="text"
                shape="circle"
                aria-label="账号菜单"
                icon={<Avatar size="small">{team[0].name.slice(0, 1)}</Avatar>}
              />
            </Dropdown>
          </Space>
        </Layout.Header>
        <Layout.Content className="app-content" style={{ padding: 24 }}>
          <div className="page">{children}</div>
        </Layout.Content>
      </Layout>
      <Drawer
        title="Acme Console"
        placement="left"
        open={mobileOpen}
        onClose={() => setMobileOpen(false)}
        styles={{ body: { padding: 0 } }}
      >
        {navigation}
      </Drawer>
    </Layout>
  )
}

export function ChatShellHeader({ children }: { children: ReactNode }) {
  return (
    <Typography.Title level={3} style={{ margin: 0 }}>
      {children}
    </Typography.Title>
  )
}

// apps/arco-design-vue/src/layouts/AppShell.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { RouterLink, RouterView, useRoute, useRouter } from "vue-router"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { Icon } from "@/lib/icons"
import { theme, toggleTheme } from "@/lib/settings"

const route = useRoute()
const router = useRouter()
const collapsed = ref(false)
const mobileOpen = ref(false)
const current = computed(() => nav.find((item) => item.path === route.path)?.label ?? "仪表盘")
const unread = notifications.filter((item) => item.unread).length
const groups = [
  { title: "工作区", keys: ["dashboard", "orders", "form", "chat"] },
  { title: "资源", keys: ["components", "landing", "settings", "login"] },
]

function go(key: string) {
  const target = nav.find((item) => item.key === key)
  if (target) router.push({ path: target.path, query: route.query })
  mobileOpen.value = false
}
</script>

<template>
  <a-layout class="shell">
    <a-layout-sider
      class="shell-sider hide-mobile"
      :collapsed="collapsed"
      collapsible
      hide-trigger
      :width="240"
      :collapsed-width="64"
      breakpoint="lg"
      @collapse="(value: boolean) => (collapsed = value)"
    >
      <div class="shell-brand">
        <a-avatar :size="32" shape="square" :style="{ backgroundColor: 'rgb(var(--primary-6))' }">A</a-avatar>
        <span v-if="!collapsed" class="shell-brand-text">Acme Console</span>
      </div>
      <a-menu :selected-keys="[nav.find((item) => item.path === route.path)?.key ?? 'dashboard']" :collapsed="collapsed" :default-open-keys="['g0', 'g1']" @menu-item-click="go">
        <a-sub-menu v-for="(group, index) in groups" :key="`g${index}`">
          <template #icon><Icon name="boxes" /></template>
          <template #title>{{ group.title }}</template>
          <a-menu-item v-for="key in group.keys" :key="key">
            <template #icon><Icon :name="nav.find((item) => item.key === key)?.icon ?? 'circle-help'" /></template>
            <span class="between">
              {{ nav.find((item) => item.key === key)?.label }}
              <a-badge v-if="nav.find((item) => item.key === key)?.badge" :count="nav.find((item) => item.key === key)?.badge" :offset="[0, 0]" :color="'rgb(var(--red-7))'" />
            </span>
          </a-menu-item>
        </a-sub-menu>
      </a-menu>
      <div class="shell-sider-footer">
        <a-button type="text" size="small" @click="collapsed = !collapsed">
          <template #icon><Icon :name="collapsed ? 'chevron-right' : 'chevron-left'" /></template>
        </a-button>
        <RouterLink v-if="!collapsed" :to="{ path: '/settings', query: route.query }" class="shell-user">
          <a-avatar :size="28">林</a-avatar>
          <span class="stack" style="gap: 0">
            <span>林晓</span>
            <span class="muted small">owner · Acme</span>
          </span>
        </RouterLink>
      </div>
    </a-layout-sider>

    <a-drawer :visible="mobileOpen" placement="left" :width="280" :footer="false" title="Acme Console" unmount-on-close @cancel="mobileOpen = false">
      <a-menu :selected-keys="[nav.find((item) => item.path === route.path)?.key ?? 'dashboard']" :default-open-keys="['g0', 'g1']" @menu-item-click="go">
        <a-sub-menu v-for="(group, index) in groups" :key="`g${index}`">
          <template #title>{{ group.title }}</template>
          <a-menu-item v-for="key in group.keys" :key="key">
            <template #icon><Icon :name="nav.find((item) => item.key === key)?.icon ?? 'circle-help'" /></template>
            {{ nav.find((item) => item.key === key)?.label }}
          </a-menu-item>
        </a-sub-menu>
      </a-menu>
    </a-drawer>

    <a-layout class="shell-main">
      <a-layout-header class="shell-header">
        <a-button class="show-mobile" type="text" @click="mobileOpen = true">
          <template #icon><Icon name="menu" /></template>
        </a-button>
        <a-breadcrumb class="hide-mobile">
          <a-breadcrumb-item><RouterLink :to="{ path: '/', query: route.query }">Acme Console</RouterLink></a-breadcrumb-item>
          <a-breadcrumb-item>{{ current }}</a-breadcrumb-item>
        </a-breadcrumb>
        <div class="shell-actions">
          <a-input-search class="hide-mobile shell-search" placeholder="全局搜索..." allow-clear />
          <a-popover trigger="click" position="br" title="通知">
            <a-badge :count="unread" dot>
              <a-button type="text" shape="circle">
                <template #icon><Icon name="bell" /></template>
              </a-button>
            </a-badge>
            <template #content>
              <a-list size="small" :bordered="false" style="width: 280px">
                <a-list-item v-for="item in notifications" :key="item.title">
                  <a-list-item-meta :title="item.title" :description="item.time">
                    <template #avatar><a-badge :count="item.unread ? 1 : 0" dot><a-avatar :size="24"><Icon name="bell" :size="12" /></a-avatar></a-badge></template>
                  </a-list-item-meta>
                </a-list-item>
              </a-list>
            </template>
          </a-popover>
          <a-tooltip content="切换主题">
            <a-button type="text" shape="circle" @click="toggleTheme()">
              <template #icon><Icon :name="theme === 'dark' ? 'sun' : 'moon'" /></template>
            </a-button>
          </a-tooltip>
          <a-dropdown position="br" @select="(value: unknown) => value === 'settings' && go('settings')">
            <a-avatar :size="32" style="cursor: pointer">林</a-avatar>
            <template #content>
              <a-doption value="profile"><template #icon><Icon name="user" /></template>个人资料</a-doption>
              <a-doption value="settings"><template #icon><Icon name="settings" /></template>账户设置</a-doption>
              <a-doption value="team"><template #icon><Icon name="users" /></template>切换团队</a-doption>
              <a-doption value="help"><template #icon><Icon name="circle-help" /></template>帮助中心</a-doption>
              <a-doption value="logout"><template #icon><Icon name="log-out" /></template>退出登录</a-doption>
            </template>
          </a-dropdown>
        </div>
      </a-layout-header>
      <a-layout-content class="shell-content">
        <RouterView />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<style scoped>
.shell {
  min-height: 100vh;
}

.shell-sider {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
}

.shell-sider :deep(.arco-layout-sider-children) {
  display: flex;
  flex-direction: column;
}

.shell-sider :deep(.arco-menu) {
  flex: 1;
}

.shell-brand {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 16px;
  font-weight: 600;
}

.shell-brand-text {
  white-space: nowrap;
}

.shell-sider-footer {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px;
  border-top: 1px solid var(--color-border-2);
}

.shell-user {
  display: flex;
  align-items: center;
  gap: 8px;
  min-height: 40px;
  color: inherit;
  text-decoration: none;
  font-size: 13px;
}

.shell-header :deep(.arco-breadcrumb-item a) {
  display: inline-flex;
  align-items: center;
  min-height: 40px;
}

.shell-main {
  min-width: 0;
}

.shell-header {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  gap: 12px;
  height: 60px;
  padding: 0 16px;
  background: var(--color-bg-2);
  border-bottom: 1px solid var(--color-border-2);
}

.shell-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-left: auto;
}

.shell-search {
  width: 220px;
}

.shell-content {
  padding: 24px;
  min-width: 0;
}

@media (max-width: 767px) {
  .shell-content {
    padding: 16px;
  }
}
</style>
