// apps/element-plus/src/pages/Landing.vue
<script setup lang="ts">
import { ref } from "vue"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import Icon from "@/icons/Icon.vue"
import { useMobile } from "@/composables/useMobile"
const mobile = useMobile()
const menu = ref(false)
const yearly = ref(false)
</script>

<template>
  <div class="landing">
    <header class="landing-nav"><div class="brand"><span class="brand-mark">A</span>Acme Console</div><el-menu mode="horizontal" ellipsis class="hide-mobile"><el-menu-item index="1">产品</el-menu-item><el-menu-item index="2">方案</el-menu-item><el-menu-item index="3">价格</el-menu-item><el-menu-item index="4">资源</el-menu-item><el-menu-item index="5">帮助</el-menu-item></el-menu><div class="nav-actions"><el-button text class="hide-mobile">登录</el-button><el-button type="primary" round>免费开始</el-button><el-button v-if="mobile" text class="icon-btn" @click="menu = true"><Icon name="menu" :size="20" /></el-button></div></header>
    <el-drawer v-model="menu" direction="rtl" size="260px"><el-menu><el-menu-item index="1">产品</el-menu-item><el-menu-item index="2">方案</el-menu-item><el-menu-item index="3">价格</el-menu-item><el-menu-item index="4">资源</el-menu-item><el-menu-item index="5">帮助</el-menu-item></el-menu></el-drawer>
    <main>
      <section class="hero"><el-tag type="success" effect="plain">新一代团队控制台</el-tag><h1>{{ landing.hero.title }}</h1><p>{{ landing.hero.subtitle }}</p><el-space><el-button type="primary" size="large">{{ landing.hero.primary }}</el-button><el-button size="large">{{ landing.hero.secondary }}</el-button></el-space><div class="hero-shot"><el-skeleton animated :rows="5" /></div><div class="social"><el-avatar-group><el-avatar v-for="name in landing.testimonials.slice(0, 5)" :key="name.name">{{ name.name.slice(0, 1) }}</el-avatar></el-avatar-group><span>{{ landing.hero.social }}</span></div></section>
      <section class="logo-cloud"><span v-for="name in ['NORTHWIND','CONTOSO','FABRIKAM','GLOBEX','INITECH','UMBRELLA']" :key="name">{{ name }}</span></section>
      <section id="features" class="section"><h2>为高效团队而生</h2><p class="section-lead">从数据到协作，所有重要工作都在一个地方。</p><el-row :gutter="16"><el-col v-for="feature in landing.features" :key="feature.title" :xs="24" :sm="12" :lg="8"><el-card class="feature-card"><Icon :name="feature.icon" :size="24" /><h3>{{ feature.title }}</h3><p>{{ feature.desc }}</p></el-card></el-col></el-row></section>
      <section class="section split" v-for="(feature, index) in landing.features.slice(0, 3)" :key="feature.title"><div><el-skeleton animated :rows="5" /></div><div><el-tag>{{ `0${index + 1}` }}</el-tag><h2>{{ feature.title }}</h2><p>{{ feature.desc }} 通过清晰的工作流，团队可以快速从想法走向结果。</p><el-link type="primary">了解更多 →</el-link></div></section>
      <section class="numbers"><div v-for="item in landing.numbers" :key="item.label"><strong>{{ item.value }}</strong><span>{{ item.label }}</span></div></section>
      <section id="pricing" class="section"><div class="section-top"><div><h2>简单透明的定价</h2><p class="section-lead">按团队规模选择合适计划。</p></div><el-switch v-model="yearly" active-text="按年付费" /></div><el-row :gutter="16"><el-col v-for="plan in plans" :key="plan.name" :xs="24" :md="8"><el-card :class="{ recommended: plan.recommended }" class="plan-card"><el-tag v-if="plan.recommended" type="success">推荐</el-tag><h3>{{ plan.name }}</h3><strong>{{ plan.price === null ? '联系销售' : plan.price === 0 ? '免费' : `¥${yearly ? plan.price * 10 : plan.price} / ${yearly ? '年' : '月'}` }}</strong><p v-for="item in plan.features" :key="item">✓ {{ item }}</p><el-button :type="plan.recommended ? 'primary' : 'default'" class="full-width">选择计划</el-button></el-card></el-col></el-row></section>
      <section class="section"><h2>团队正在这样使用</h2><div class="testimonials"><el-carousel height="180px" :autoplay="false" arrow="always" indicator-position="outside"><el-carousel-item v-for="quote in landing.testimonials" :key="quote.name"><div class="quote"><p>“{{ quote.quote }}”</p><span>{{ quote.name }} · {{ quote.company }}</span></div></el-carousel-item></el-carousel></div></section>
      <section id="faq" class="section faq"><h2>常见问题</h2><el-collapse accordion><el-collapse-item v-for="item in landing.faq" :key="item.q" :title="item.q"><p>{{ item.a }}</p></el-collapse-item></el-collapse></section>
      <section class="cta"><h2>准备好让团队更高效了吗？</h2><p>从今天开始，把工作放进一个控制台。</p><el-button type="primary" size="large">免费开始</el-button></section>
    </main>
    <footer><div class="brand"><span class="brand-mark">A</span>Acme Console</div><div class="footer-links"><el-link>产品</el-link><el-link>价格</el-link><el-link>帮助中心</el-link><el-link>隐私条款</el-link></div><span class="muted">© 2026 Acme Console · <el-select model-value="zh-CN" style="width: 110px"><el-option label="简体中文" value="zh-CN" /></el-select></span></footer>
  </div>
</template>

<style scoped>
.landing-nav, footer { display: flex; align-items: center; gap: 24px; max-width: 1200px; margin: auto; padding: 18px 24px; }
.landing-nav { justify-content: space-between; min-width: 0; }
.landing-nav :deep(.el-menu) { min-width: 0; flex: 1; }
.brand { display: flex; align-items: center; gap: 10px; font-weight: 700; white-space: nowrap; }
.brand-mark { display: grid; width: 32px; height: 32px; place-items: center; border-radius: 8px; background: var(--el-color-primary); color: #fff; }
.nav-actions { display: flex; gap: 8px; align-items: center; }
.hero { max-width: 900px; margin: auto; padding: 90px 24px 60px; text-align: center; }
.hero h1 { margin: 18px 0; font-size: clamp(36px, 7vw, 68px); line-height: 1.08; }
.hero p, .section-lead { color: var(--el-text-color-secondary); font-size: 18px; }
.hero-shot { max-width: 800px; height: 260px; margin: 50px auto 20px; padding: 32px; overflow: hidden; box-sizing: border-box; border: 1px solid var(--el-border-color); border-radius: 16px; box-shadow: var(--el-box-shadow-light); }
.hero-shot :deep(.el-skeleton), .hero-shot :deep(.el-skeleton__item) { width: 100%; max-width: 100%; box-sizing: border-box; }
.social { display: flex; align-items: center; justify-content: center; gap: 12px; }
.logo-cloud { display: flex; justify-content: space-around; gap: 18px; max-width: 1100px; margin: auto; padding: 30px 24px; color: var(--el-text-color-secondary); font-size: 12px; font-weight: 700; letter-spacing: 2px; flex-wrap: wrap; }
.section { max-width: 1100px; margin: auto; padding: 80px 24px; }
.section h2, .cta h2 { font-size: 34px; margin: 0 0 12px; }
.feature-card { height: 100%; margin-bottom: 16px; }
.feature-card h3 { margin-bottom: 6px; }
.split { display: grid; grid-template-columns: 1fr 1fr; gap: 60px; align-items: center; }
.split > div:first-child { min-height: 230px; padding: 28px; border-radius: 16px; background: var(--el-fill-color-light); }
.numbers { display: flex; justify-content: space-around; gap: 30px; padding: 50px 24px; background: var(--el-fill-color-light); flex-wrap: wrap; }
.numbers div { display: grid; text-align: center; gap: 8px; }
.numbers strong { font-size: 36px; }
.section-top { display: flex; justify-content: space-between; align-items: end; gap: 20px; }
.plan-card { position: relative; height: 100%; margin-bottom: 16px; }
.plan-card.recommended { border-color: var(--el-color-primary); }
.plan-card strong { display: block; margin: 20px 0; font-size: 30px; }
.testimonials { width: 100%; max-width: 100%; overflow: hidden; border-radius: 12px; }
.quote { display: grid; height: 100%; place-content: center; text-align: center; }
.quote p { font-size: 22px; }
.faq { max-width: 800px; }
.cta { max-width: 1100px; margin: 20px auto 80px; padding: 70px 24px; border-radius: 18px; color: var(--el-text-color-primary); background: var(--el-color-primary-light-9); text-align: center; }
.footer-links { display: flex; gap: 20px; flex: 1; justify-content: center; }
footer { border-top: 1px solid var(--el-border-color); max-width: none; justify-content: space-between; }
@media (max-width: 767px) { .split { grid-template-columns: 1fr; gap: 24px; }.section { padding: 56px 16px; }.hero { padding: 55px 16px 42px; }.hero-shot { height: 190px; padding: 18px; }.numbers { gap: 24px; }.numbers strong { font-size: 28px; }.footer-links { display: none; }footer { flex-wrap: wrap; padding: 22px 16px; } }
</style>

// apps/tdesign-react/src/pages/landing.tsx
import { Link } from "react-router-dom"
import { Avatar, AvatarGroup, Button, Card, Collapse, Col, Menu, Row, Select, Space, Switch, Tag, Typography } from "tdesign-react"
import { Icon } from "@/components/icon"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"

export function LandingPage() {
  return <div>
    <LayoutHeader />
    <main>
      <section className="landing-section landing-hero"><div className="stack"><Tag theme="primary">ACME CONSOLE · 2026</Tag><Typography.Title level="h1">{landing.hero.title}</Typography.Title><Typography.Paragraph>{landing.hero.subtitle}</Typography.Paragraph><Space><Link to="/login"><Button theme="primary" size="large">{landing.hero.primary} <Icon name="arrow-right" /></Button></Link><Button variant="outline" size="large">{landing.hero.secondary}</Button></Space><div className="inline"><AvatarGroup max={3}><Avatar>林</Avatar><Avatar>王</Avatar><Avatar>A</Avatar><Avatar>M</Avatar></AvatarGroup><Typography.Text>{landing.hero.social}</Typography.Text></div></div><Card><ProductShot label="产品截图" /></Card></section>
      <section className="landing-section" style={{ paddingTop: 24 }}><div className="grid-three">{["Northwind", "Contoso", "Globex", "Fabrikam", "Initech", "Umbrella"].map((name) => <Typography.Text key={name} style={{ textAlign: "center", color: "var(--td-text-color-secondary)" }}>{name}</Typography.Text>)}</div></section>
      <section id="features" className="landing-section"><div className="page-heading"><div><Typography.Title level="h2">一个地方，完成所有工作</Typography.Title><Typography.Paragraph>从数据到决策，让每一步都更清晰。</Typography.Paragraph></div></div><div className="grid-three">{landing.features.map((item) => <Card key={item.title}><div className="stack"><Tag shape="round"><Icon name={item.icon} /></Tag><Typography.Title level="h4">{item.title}</Typography.Title><Typography.Paragraph>{item.desc}</Typography.Paragraph></div></Card>)}</div></section>
      <section className="landing-section"><div className="stack">{["看见全局", "自动化协作", "AI 就在身边"].map((title, index) => <Row gutter={[32, 24]} align="middle" key={title}><Col xs={24} md={12}><Card><ProductShot label={title} /></Card></Col><Col xs={24} md={12}><div className="stack"><Tag>0{index + 1} / WORKSPACE</Tag><Typography.Title level="h2">{title}</Typography.Title><Typography.Paragraph>{landing.features[index + 1].desc} 汇聚有用的洞察，让团队快速行动并持续交付。</Typography.Paragraph><Button variant="text">了解更多 <Icon name="arrow-right" /></Button></div></Col></Row>)}</div></section>
      <section className="landing-section"><div className="grid-four">{landing.numbers.map((item) => <div style={{ textAlign: "center" }} key={item.label}><Typography.Title level="h2">{item.value}</Typography.Title><Typography.Text>{item.label}</Typography.Text></div>)}</div></section>
      <section id="pricing" className="landing-section"><div className="page-heading"><div><Typography.Title level="h2">选择适合你的方案</Typography.Title><Typography.Paragraph>简单透明，随时升级。</Typography.Paragraph></div><Switch label={["月", "年"]} /></div><div className="grid-three">{plans.map((plan) => <Card key={plan.name} title={<div className="inline" style={{ justifyContent: "space-between" }}><span>{plan.name}</span>{plan.recommended && <Tag theme="primary">推荐</Tag>}</div>} bordered><Typography.Title level="h2">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}`}<Typography.Text> / 月</Typography.Text></Typography.Title><div className="stack">{plan.features.map((feature) => <Typography.Text key={feature}><Icon name="check" /> {feature}</Typography.Text>)}</div><Button block theme={plan.recommended ? "primary" : "default"} style={{ marginTop: 20 }}>开始使用</Button></Card>)}</div></section>
      <section className="landing-section"><Typography.Title level="h2">他们已经在改变工作方式</Typography.Title><div className="landing-testimonials">{landing.testimonials.map((item) => <Card key={item.name}><Typography.Paragraph>“{item.quote}”</Typography.Paragraph><Typography.Text>{item.name} · {item.company}</Typography.Text></Card>)}</div></section>
      <section id="faq" className="landing-section"><Typography.Title level="h2">常见问题</Typography.Title><Collapse>{landing.faq.map((item) => <Collapse.Panel key={item.q} header={item.q} value={item.q}>{item.a}</Collapse.Panel>)}</Collapse></section>
      <section className="landing-section"><Card theme="poster1"><div className="stack"><Typography.Title level="h2">准备好让团队更高效了吗？</Typography.Title><Typography.Paragraph>从今天开始，把工作放进一个控制台。</Typography.Paragraph><Link to="/login"><Button theme="primary">免费开始</Button></Link></div></Card></section>
    </main>
    <footer className="landing-section" style={{ paddingTop: 24, paddingBottom: 24 }}><div className="grid-four"><div><Typography.Title level="h4">Acme Console</Typography.Title><Typography.Text>© 2026 Acme Console</Typography.Text><div className="inline"><Button shape="circle" icon={<Icon name="github" />} /><Button shape="circle" icon={<Icon name="globe" />} /></div></div>{["产品", "资源", "公司", "社交"].map((title) => <div className="stack" key={title}><Typography.Text strong>{title}</Typography.Text><Link to="/dashboard">概览</Link><Link to="/components">组件</Link><Link to="/settings">设置</Link></div>)}<Select options={[{ label: "简体中文", value: "zh-CN" }]} defaultValue="zh-CN" /></div></footer>
  </div>
}

function ProductShot({ label }: { label: string }) {
  return <div className="landing-shot" role="img" aria-label={label}><span /><span /><span /></div>
}

function LayoutHeader() {
  return <header className="landing-header" style={{ position: "sticky", top: 0, zIndex: 2 }}><Link className="app-brand" to="/landing"><span className="app-brand-mark">A</span><span>Acme Console</span></Link><div className="landing-header-spacer" /><Menu.HeadMenu className="desktop-only" value="features"><Menu.MenuItem value="features"><a href="#features">产品</a></Menu.MenuItem><Menu.MenuItem value="pricing"><a href="#pricing">价格</a></Menu.MenuItem><Menu.MenuItem value="faq"><a href="#faq">帮助中心</a></Menu.MenuItem></Menu.HeadMenu><Link to="/login"><Button theme="primary">免费开始</Button></Link></header>
}
