// apps/element-plus/src/pages/Settings.vue
<script setup lang="ts">
import { ref } from "vue"
import { ElMessage, ElMessageBox } from "element-plus"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import { Plus } from "@element-plus/icons-vue"
import { useMobile } from "@/composables/useMobile"
const mobile = useMobile()
const tab = ref("profile")
const danger = ref(false)
const confirm = ref("")
const twoFactor = ref(false)
const removeAccount = async () => {
  if (confirm.value !== "DELETE") return ElMessage.warning("请输入 DELETE")
  await ElMessageBox.confirm("此操作不可撤销，确定继续吗？", "删除账号", { type: "warning" })
  danger.value = false
  ElMessage.success("演示账号已标记为删除")
}
</script>

<template>
  <div class="page">
    <div class="page-header">
      <div>
        <h1 class="page-title">设置</h1>
        <p class="page-subtitle">管理个人资料、团队与订阅偏好。</p>
      </div>
    </div>
    <el-card>
      <el-tabs v-model="tab" :tab-position="mobile ? 'top' : 'left'" class="settings-tabs">
        <el-tab-pane :label="mobile ? '资料' : '个人资料'" name="profile"><el-form label-position="top" class="settings-form"><el-form-item label="头像"><el-upload action="#" list-type="picture-card" :auto-upload="false"><el-icon :size="24"><Plus /></el-icon></el-upload></el-form-item><el-form-item label="姓名"><el-input model-value="林晓" /></el-form-item><el-form-item label="简介"><el-input type="textarea" model-value="负责 Acme Console 的运营与增长。" /></el-form-item><el-form-item label="语言"><el-select model-value="zh-CN"><el-option label="简体中文" value="zh-CN" /><el-option label="English" value="en" /></el-select></el-form-item><el-form-item label="时区"><el-select model-value="Asia/Shanghai" filterable><el-option label="中国标准时间 (UTC+8)" value="Asia/Shanghai" /><el-option
          label="太平洋时间 (UTC-8)"
          value="America/Los_Angeles"
        /></el-select></el-form-item><el-button type="primary" @click="ElMessage.success('资料已保存')">保存更改</el-button></el-form></el-tab-pane>
        <el-tab-pane :label="mobile ? '安全' : '账号安全'" name="security"><el-form label-position="top" class="settings-form"><el-form-item label="当前密码"><el-input type="password" show-password /></el-form-item><el-form-item label="新密码"><el-input type="password" show-password /></el-form-item><el-button type="primary">更新密码</el-button></el-form><el-divider />
          <div class="security-row">
            <div>
              <h3>两步验证</h3>
              <p class="muted">使用验证器应用保护账号。</p>
            </div>
            <el-switch v-model="twoFactor" />
          </div>
          <div v-if="twoFactor" class="qr-placeholder">二维码占位</div>
          <el-divider />
          <h3>活跃会话</h3>
          <el-card v-for="session in sessions" :key="session.device" shadow="never" class="session"><div>
                                                                                                      <b>{{ session.device }}</b>
                                                                                                      <p class="muted">{{ session.location }} · {{ session.time }}</p>
                                                                                                    </div>
            <el-tag v-if="session.current" type="success">当前设备</el-tag><el-button v-else text type="danger">注销</el-button></el-card></el-tab-pane>
        <el-tab-pane label="通知" name="notifications"><el-segmented :options="['邮件', '推送', '站内']" /><el-divider />
          <div v-for="item in ['订单状态更新', '团队动态', '产品公告', '安全提醒']" :key="item" class="security-row">
            <span>{{ item }}</span><el-switch :model-value="item !== '产品公告'" /></div></el-tab-pane>
        <el-tab-pane label="团队" name="team"><div class="invite"><el-input placeholder="成员邮箱" /><el-button type="primary">邀请</el-button></div>
          <el-table :data="team"><el-table-column label="成员" width="150" min-width="150"><template #default="{ row }"><el-avatar :size="28">{{ row.name.slice(0, 1) }}</el-avatar> {{ row.name }}</template></el-table-column><el-table-column prop="email" width="180" min-width="180" label="邮箱" /><el-table-column
            label="角色"
            width="120"
            min-width="120"
          ><template #default="{ row }"><el-select v-model="row.role" size="small"><el-option label="所有者" value="owner" /><el-option label="管理员" value="admin" /><el-option
            label="成员"
            value="member"
          /><el-option label="查看者" value="viewer" /></el-select></template></el-table-column><el-table-column prop="lastActive" width="120" min-width="120" label="最近活跃" /><el-table-column
            label="操作"
            width="100"
            min-width="100"
          ><template #default><el-button text type="danger">移除</el-button></template></el-table-column></el-table></el-tab-pane>
        <el-tab-pane label="计费" name="billing"><el-card shadow="never"><template #header>当前计划</template><strong>Pro · ¥99 / 月</strong>
                                                 <p class="muted">下次续费：2026-10-01</p></el-card><el-row :gutter="12" class="plans"><el-col v-for="plan in plans" :key="plan.name" :xs="24" :md="8"><el-card :class="{ recommended: plan.recommended }"><el-tag v-if="plan.recommended" type="success">推荐</el-tag>
                                                   <h3>{{ plan.name }}</h3>
                                                   <strong class="price">{{ plan.price === null ? "联系销售" : plan.price === 0 ? "免费" : `¥${plan.price}/月` }}</strong>
                                                   <p v-for="feature in plan.features" :key="feature">✓ {{ feature }}</p>
                                                   <el-button :type="plan.recommended ? 'primary' : 'default'" class="full-width">选择计划</el-button></el-card></el-col></el-row>
          <h3>发票</h3>
          <el-table :data="invoices"><el-table-column prop="id" label="编号" /><el-table-column prop="date" label="日期" /><el-table-column
            prop="amount"
            label="金额"
          ><template #default="{ row }">¥{{ row.amount }}</template></el-table-column><el-table-column label="状态"><template #default="{ row }"><el-tag :type="row.status === 'paid' ? 'success' : 'warning'">{{ row.status }}</el-tag></template></el-table-column></el-table></el-tab-pane>
      </el-tabs> </el-card><el-card class="danger-zone"><template #header>危险区</template>
      <p>删除账号将永久移除所有团队数据。</p>
      <el-button type="danger" @click="danger = true">删除账号</el-button></el-card><el-dialog v-model="danger" title="删除账号" width="420px"><p>请输入 DELETE 以确认此操作。</p>
      <el-input v-model="confirm" placeholder="DELETE" /><template #footer><el-button @click="danger = false">取消</el-button><el-button type="danger" @click="removeAccount">确认删除</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.settings-tabs :deep(.el-tab-pane) {
  padding: 0 0 0 28px;
}
.settings-form {
  max-width: 620px;
}
.security-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
.security-row h3 {
  margin: 0;
}
.session {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin: 10px 0;
}
.session p {
  margin: 4px 0 0;
}
.qr-placeholder {
  display: grid;
  width: 140px;
  height: 140px;
  place-items: center;
  margin: 18px 0;
  border: 10px solid var(--el-text-color-primary);
  color: var(--el-bg-color);
  background: repeating-linear-gradient(45deg, var(--el-text-color-primary) 0 4px, var(--el-bg-color) 4px 8px);
  font-size: 12px;
}
.invite {
  display: flex;
  gap: 10px;
  max-width: 480px;
  margin-bottom: 18px;
}
.plans {
  margin: 16px 0 28px;
}
.plans h3 {
  margin-bottom: 8px;
}
.price {
  display: block;
  margin-bottom: 14px;
  font-size: 24px;
}
.recommended {
  border-color: var(--el-color-primary);
}
.danger-zone {
  margin-top: 18px;
  border-color: var(--el-color-danger);
}
@media (max-width: 767px) {
  .settings-tabs :deep(.el-tab-pane) {
    padding: 16px 0 0;
  }
  .settings-tabs :deep(.el-tabs__item) {
    padding: 0 12px;
  }
}
</style>

// apps/tdesign-react/src/pages/settings.tsx
import { useState } from "react"
import { Avatar, Button, Card, DialogPlugin, Form, Input, List, MessagePlugin, QRCode, Radio, Select, Switch, Tabs, Table, Tag, Textarea, Typography, Upload } from "tdesign-react"
import { Icon } from "@/components/icon"
import { useIsMobile } from "@/url-settings"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"

export function SettingsPage() {
  const [tab, setTab] = useState("profile")
  const isMobile = useIsMobile()
  const [deleteText, setDeleteText] = useState("")
  const destroyAccount = () => {
    const dialog = DialogPlugin.confirm({ header: "删除账号", body: <div className="stack"><Typography.Paragraph>此操作不可撤销，请输入“删除”确认。</Typography.Paragraph><Input value={deleteText} onChange={setDeleteText} placeholder="输入删除" /></div>, confirmBtn: { content: "确认删除", theme: "danger", disabled: deleteText !== "删除" }, onConfirm: () => { MessagePlugin.success("已提交删除申请"); dialog.destroy() } })
  }
  const teamColumns = [{ colKey: "name", title: "成员", cell: ({ row }: { row: typeof team[number] }) => <div className="inline"><Avatar size="28px">{row.name.slice(0, 1)}</Avatar>{row.name}</div> }, { colKey: "email", title: "邮箱" }, { colKey: "role", title: "角色", cell: ({ row }: { row: typeof team[number] }) => <Select value={row.role} options={["owner", "admin", "member", "viewer"].map((value) => ({ label: value, value }))} /> }, { colKey: "lastActive", title: "最近活跃" }, { colKey: "op", title: "操作", cell: () => <Button variant="text" theme="danger">移除</Button> }]
  return (
    <div className="stack">
      <div className="page-heading"><div><Typography.Title level="h2">设置</Typography.Title><Typography.Paragraph>管理个人资料、团队与订阅。</Typography.Paragraph></div></div>
      <Tabs value={tab} placement={isMobile ? "top" : "left"} onChange={(value) => setTab(String(value))}>
        <Tabs.TabPanel value="profile" label="个人资料"><Card title="个人资料"><Form layout="vertical"><Form.FormItem label="头像"><Upload autoUpload={false} theme="custom" /></Form.FormItem><Form.FormItem label="姓名"><Input defaultValue="林晓" /></Form.FormItem><Form.FormItem label="简介"><Textarea defaultValue="负责 Acme Console 的增长与运营。" /></Form.FormItem><Form.FormItem label="语言"><Select defaultValue="zh-CN" options={[{ label: "简体中文", value: "zh-CN" }, { label: "English", value: "en-US" }]} /></Form.FormItem><Form.FormItem label="时区"><Select filterable options={["Asia/Shanghai", "Asia/Tokyo", "Europe/Berlin"].map((value) => ({ label: value, value }))} defaultValue="Asia/Shanghai" /></Form.FormItem><Button theme="primary">保存更改</Button></Form></Card></Tabs.TabPanel>
        <Tabs.TabPanel value="security" label="账号安全"><div className="stack"><Card title="修改密码"><Form layout="vertical"><Form.FormItem label="当前密码" rules={[{ required: true, message: "请输入当前密码" }]}><Input type="password" /></Form.FormItem><Form.FormItem label="新密码" rules={[{ required: true, message: "请输入新密码" }]}><Input type="password" /></Form.FormItem><Button theme="primary">更新密码</Button></Form></Card><Card title="两步验证"><div className="inline"><Switch /><span>启用两步验证</span><QRCode value="https://example.com/acme-console" size={100} /></div></Card><Card title="活跃会话"><List>{sessions.map((session) => <List.ListItem key={session.device} action={<Button variant="text" disabled={session.current}>注销</Button>}><List.ListItemMeta title={session.device} description={`${session.location} · ${session.time}`} /></List.ListItem>)}</List></Card></div></Tabs.TabPanel>
        <Tabs.TabPanel value="notifications" label="通知"><Card title="通知偏好"><div className="stack"><Typography.Title level="h4">通知渠道</Typography.Title><div className="inline"><Radio.Group variant="default-filled" defaultValue="email"><Radio value="email">邮件</Radio><Radio value="push">推送</Radio><Radio value="inbox">站内</Radio></Radio.Group></div>{["新订单", "团队动态", "系统维护"].map((label) => <div className="inline" style={{ justifyContent: "space-between" }} key={label}><span>{label}</span><Switch defaultValue /></div>)}</div></Card></Tabs.TabPanel>
        <Tabs.TabPanel value="team" label="团队"><Card title="团队成员"><div className="inline" style={{ marginBottom: 16 }}><Input placeholder="成员邮箱" /><Button theme="primary">邀请</Button></div><div className="table-scroll"><Table rowKey="email" data={team} columns={teamColumns} /></div></Card></Tabs.TabPanel>
        <Tabs.TabPanel value="billing" label="计费"><div className="stack"><div className="grid-three">{plans.map((plan) => <Card key={plan.name} title={<div className="inline" style={{ justifyContent: "space-between" }}><span>{plan.name}</span>{plan.recommended && <Tag theme="primary">推荐</Tag>}</div>} bordered><Typography.Title level="h3">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${plan.price}/月`}</Typography.Title><div className="stack">{plan.features.map((feature) => <div key={feature}><Icon name="check" /> {feature}</div>)}</div><Button block theme={plan.recommended ? "primary" : "default"} style={{ marginTop: 16 }}>选择方案</Button></Card>)}</div><Card title="发票"><Table rowKey="id" data={invoices} columns={[{ colKey: "id", title: "发票号" }, { colKey: "date", title: "日期" }, { colKey: "amount", title: "金额", cell: ({ row }: { row: typeof invoices[number] }) => `¥${row.amount}` }, { colKey: "status", title: "状态", cell: ({ row }: { row: typeof invoices[number] }) => <Tag theme={row.status === "paid" ? "success" : "warning"}>{row.status === "paid" ? "已支付" : "待支付"}</Tag> }]} /></Card></div></Tabs.TabPanel>
      </Tabs>
      <Card className="danger-card" title="危险区"><div className="inline" style={{ justifyContent: "space-between" }}><Typography.Paragraph>删除账号将永久移除所有数据。</Typography.Paragraph><Button theme="danger" onClick={destroyAccount}>删除账号</Button></div></Card>
    </div>
  )
}
