// apps/reference/src/components/ui/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/cn"

/** 语义色调（Tag / Delta / 通知图标共用） */
export type Tone = "info" | "warning" | "danger" | "success" | "neutral" | "muted"

/** 状态标签：hifi .tag —— 胶囊、caption medium、前置圆点表示语义色 */
const tagVariants = cva(
  "inline-flex h-6 shrink-0 items-center gap-1 rounded-full px-2 text-role-caption font-medium whitespace-nowrap [&_svg]:size-icon-sm",
  {
    variants: {
      tone: {
        info: "bg-primary-soft text-on-primary-soft",
        warning: "bg-warning-soft text-warning",
        danger: "bg-danger-soft text-danger",
        success: "bg-success-soft text-success",
        neutral: "bg-neutral-soft text-on-neutral-soft",
        muted: "bg-transparent text-fg-muted shadow-[inset_0_0_0_var(--border-width-hairline)_var(--color-role-border)]",
      },
    },
    defaultVariants: { tone: "neutral" },
  },
)

type TagProps = React.ComponentProps<"span"> & VariantProps<typeof tagVariants> & { dot?: boolean }

function Tag({ className, tone, dot = true, children, ...props }: TagProps) {
  return (
    <span data-slot="tag" data-tone={tone ?? "neutral"} className={cn(tagVariants({ tone }), className)} {...props}>
      {dot ? <i aria-hidden className="size-2 shrink-0 rounded-full bg-current" /> : null}
      {children}
    </span>
  )
}

/** 计数角标：hifi .count-badge —— 导航未读数 / 图标按钮红点 */
const countBadgeVariants = cva(
  "inline-flex h-badge min-w-badge items-center justify-center rounded-full px-1 text-role-caption font-medium tabular-nums",
  {
    variants: {
      tone: {
        neutral: "bg-neutral-soft text-on-neutral-soft",
        warning: "bg-warning-soft text-warning",
        alert: "bg-danger text-on-danger border-2 border-surface",
      },
    },
    defaultVariants: { tone: "neutral" },
  },
)

function CountBadge({ className, tone, ...props }: React.ComponentProps<"span"> & VariantProps<typeof countBadgeVariants>) {
  return <span data-slot="count-badge" className={cn(countBadgeVariants({ tone }), className)} {...props} />
}

export { Tag, tagVariants, CountBadge, countBadgeVariants, type TagProps }

// apps/shadcn-svelte/src/lib/components/ui/badge/badge.svelte
<script lang="ts" module>
  import { type VariantProps, tv } from "tailwind-variants"

  export const badgeVariants = tv({
    base: "h-5 gap-1 rounded-4xl border border-transparent px-2 py-0.5 text-xs font-medium transition-all has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&>svg]:size-3! group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap transition-colors focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none",
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground [a]:hover:bg-primary/80",
        secondary: "bg-secondary text-secondary-foreground [a]:hover:bg-secondary/80",
        destructive:
          "bg-destructive/10 text-destructive focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:focus-visible:ring-destructive/40 [a]:hover:bg-destructive/20",
        outline: "border-border text-foreground [a]:hover:bg-muted [a]:hover:text-muted-foreground",
        ghost: "hover:bg-muted hover:text-muted-foreground dark:hover:bg-muted/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  })

  export type BadgeVariant = VariantProps<typeof badgeVariants>["variant"]
</script>

<script lang="ts">
  import { cn, type WithElementRef } from "$lib/utils.js"
  import type { HTMLAnchorAttributes } from "svelte/elements"

  let {
    ref = $bindable(null),
    href,
    class: className,
    variant = "default",
    children,
    ...restProps
  }: WithElementRef<HTMLAnchorAttributes> & {
    variant?: BadgeVariant
  } = $props()
</script>

<svelte:element
  this={href ? "a" : "span"}
  bind:this={ref}
  data-slot="badge"
  {href}
  class={cn(badgeVariants({ variant }), className)}
  {...restProps}
>
  {@render children?.()}
</svelte:element>
