// apps/quasar/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue"
import { Dark } from "quasar"
import "@fontsource-variable/inter"
import "@fontsource-variable/geist"
import "@fontsource-variable/noto-sans-sc"
import "lxgw-wenkai-screen-webfont/style.css"

onMounted(() => {
  const params = new URLSearchParams(window.location.search)
  const theme = params.get("theme")
  Dark.set(theme === "dark" ? true : theme === "light" ? false : "auto")
  const fonts: Record<string, string> = {
    inter: "'Inter Variable', sans-serif",
    geist: "'Geist Variable', sans-serif",
    "noto-sans-sc": "'Noto Sans SC Variable', sans-serif",
    "lxgw-wenkai": "'LXGW WenKai Screen', serif",
  }
  document.body.style.fontFamily = fonts[params.get("font") ?? ""] ?? ""
})
</script>

<template>
  <router-view />
</template>

// apps/shadcn-ui/src/App.tsx
import { useEffect, type ReactNode } from "react"
import { createBrowserRouter, RouterProvider } from "react-router-dom"
import { AppShell } from "@/layouts/app-shell"
import { ComponentsPage } from "@/pages/components"
import { DashboardPage } from "@/pages/dashboard"
import { FormPage } from "@/pages/form"
import { LandingPage } from "@/pages/landing"
import { LoginPage } from "@/pages/login"
import { ChatPage } from "@/pages/chat"
import { OrdersPage } from "@/pages/orders"
import { SettingsPage } from "@/pages/settings"

function useUrlSettings() {
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const explicit = params.get("theme")
    const dark = explicit === "dark" || (!explicit && window.matchMedia("(prefers-color-scheme: dark)").matches)
    document.documentElement.classList.toggle("dark", dark)
    document.documentElement.classList.toggle("light", !dark)
    const fonts: Record<string, string> = { inter: "'Inter Variable', sans-serif", geist: "'Geist Variable', sans-serif", "noto-sans-sc": "'Noto Sans SC Variable', sans-serif", "lxgw-wenkai": "'LXGW WenKai Screen', serif" }
    document.documentElement.style.setProperty("--font-sans", fonts[params.get("font") ?? ""] ?? "'Geist Variable', sans-serif")
  }, [])
}

const shell = (element: ReactNode) => <AppShell>{element}</AppShell>
const router = createBrowserRouter([
  { path: "/login", element: <LoginPage /> },
  { path: "/", element: shell(<DashboardPage />) },
  { path: "/orders", element: shell(<OrdersPage />) },
  { path: "/form", element: shell(<FormPage />) },
  { path: "/settings", element: shell(<SettingsPage />) },
  { path: "/components", element: shell(<ComponentsPage />) },
  { path: "/landing", element: <LandingPage /> },
  { path: "/chat", element: shell(<ChatPage />) },
], { basename: "/apps/shadcn-ui" })

export default function App() {
  useUrlSettings()
  return <RouterProvider router={router} />
}
