// apps/rsuite/src/pages/chat.tsx
import { useState, type ComponentPropsWithoutRef, type ReactNode } from "react"
import { useSearchParams } from "react-router-dom"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Avatar, Badge, Button, Checkbox, Drawer, IconButton, Input, InputGroup, List, Message, Panel, Placeholder, SelectPicker, Tag, Text, Whisper, Tooltip, Accordion, Loader, toaster } from "rsuite"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Icon } from "@/components/icon"
import { PageHeader, StateSwitch } from "./shared"

export function ChatPage() {
  const [params] = useSearchParams()
  const [draft, setDraft] = useState("")
  const [drawer, setDrawer] = useState(false)
  if (params.get("state") === "loading") return <div className="page-stack"><PageHeader title="AI 对话" actions={<StateSwitch />} /><div className="demo-grid">{[1, 2, 3].map((item) => <Panel bordered key={item}><Placeholder.Paragraph rows={4} active graph="circle" /></Panel>)}</div></div>
  if (params.get("state") === "error") return <div className="page-stack"><PageHeader title="AI 对话" actions={<StateSwitch />} /><Message type="error" showIcon>对话加载失败，请重试。 <Button appearance="primary" size="sm">重试</Button></Message></div>
  if (params.get("state") === "empty") return <div className="page-stack"><PageHeader title="AI 对话" actions={<StateSwitch />} /><Panel bordered style={{ textAlign: "center", padding: 60 }}><Icon name="sparkles" size={36} /><h2>从一个问题开始</h2><Text muted>选择一个建议，开始探索你的业务数据。</Text><div className="demo-row" style={{ justifyContent: "center", marginTop: 24 }}>{chat.suggestions.map((item) => <Button key={item} onClick={() => setDraft(item)}>{item}</Button>)}</div></Panel></div>
  return <div className="page-stack"><PageHeader title="AI 对话" description="与团队智能助手协作，保留完整上下文。" actions={<StateSwitch />} /><Button className="mobile-only" onClick={() => setDrawer(true)}><Icon name="menu" /> 对话列表</Button><div className="chat-layout" style={{ border: "1px solid var(--rs-border-primary)", borderRadius: 8 }}><aside className="chat-sidebar"><ConversationList /></aside><Drawer open={drawer} placement="left" onClose={() => setDrawer(false)}><Drawer.Header><Drawer.Title>对话</Drawer.Title></Drawer.Header><Drawer.Body><ConversationList /></Drawer.Body></Drawer><section className="chat-main"><header style={{ display: "flex", justifyContent: "space-between", gap: 12, padding: 16, borderBottom: "1px solid var(--rs-border-primary)" }}><div><b>{chat.conversations[0].title}</b><br /><Text muted size="sm">GPT-5 · 已连接</Text></div><SelectPicker cleanable={false} searchable={false} data={chat.models.map((model) => ({ label: model, value: model }))} defaultValue={chat.models[0]} /></header><div style={{ flex: 1, padding: 16, overflow: "auto" }}>{chat.messages.map((message, index) => <div key={`${message.role}-${index}`} style={{ display: "flex", flexDirection: "column", marginBottom: 20 }}><div className={`message-bubble ${message.role === "user" ? "message-user" : "message-assistant"}`}><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}><Avatar circle size="sm">{message.role === "user" ? "林" : "AI"}</Avatar><b>{message.role === "user" ? "林晓" : "AI 助手"}</b><Text muted size="sm">刚刚</Text></div>{message.role === "assistant" ? <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ pre: CodeBlock }}>{message.content}</ReactMarkdown></div> : message.content}{message.streaming ? <div className="streaming-row"><Loader size="xs" /><Text muted size="sm">正在输入…</Text></div> : null}{message.sources ? <div className="demo-row" style={{ marginTop: 8 }}>{message.sources.map((source) => <Tag key={source}><Icon name="paperclip" /> {source}</Tag>)}</div> : null}</div>{message.tool ? <Accordion bordered style={{ marginTop: 8 }}><Accordion.Panel header={`工具调用 · ${message.tool.name}`}><pre style={{ overflow: "auto" }}>{JSON.stringify(message.tool.args, null, 2)}</pre></Accordion.Panel></Accordion> : null}</div>)}</div><footer style={{ padding: 16, borderTop: "1px solid var(--rs-border-primary)" }}><div className="demo-row">{chat.suggestions.map((suggestion) => <Tag key={suggestion} onClick={() => setDraft(suggestion)}>{suggestion}</Tag>)}</div><div style={{ display: "flex", gap: 8, alignItems: "flex-end", marginTop: 12 }}><Input as="textarea" rows={3} value={draft} onChange={(value) => setDraft(value)} placeholder="向 AI 助手提问…" style={{ flex: 1 }} /><IconButton appearance="primary" size="lg" aria-label="发送" icon={<Icon name="send" />} /></div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginTop: 8, flexWrap: "wrap" }}><Text muted size="sm">{draft.length} / 2000 · ⌘ + Enter 发送</Text><Whisper speaker={<Tooltip>上传附件</Tooltip>}><Button appearance="subtle" startIcon={<Icon name="paperclip" />}>附件</Button></Whisper></div></footer></section></div></div>
}
function ConversationList() {
  return <><InputGroup inside><InputGroup.Addon><Icon name="search" /></InputGroup.Addon><Input placeholder="搜索对话" /></InputGroup><Button appearance="primary" block style={{ margin: "12px 0" }}><Icon name="plus" /> 新建对话</Button><List hover>{chat.conversations.map((item) => <List.Item key={item.id}><div style={{ display: "flex", justifyContent: "space-between" }}><span><b>{item.title}</b><br /><Text muted size="sm">{item.time}</Text></span>{item.unread ? <Badge content={item.unread} /> : null}</div></List.Item>)}</List><Checkbox>仅显示未读</Checkbox></>
}

function CodeBlock({ children, ...props }: ComponentPropsWithoutRef<"pre">) {
  const text = extractText(children)
  const copy = () => { void navigator.clipboard?.writeText(text); toaster.push(<Message type="success" showIcon>代码已复制</Message>) }
  return <div className="code-block"><div className="code-toolbar"><Text muted size="sm">代码</Text><Button className="code-copy" size="xs" appearance="subtle" startIcon={<Icon name="copy" />} onClick={copy}>复制</Button></div><pre {...props}>{children}</pre></div>
}
function extractText(node: ReactNode): string {
  if (typeof node === "string" || typeof node === "number") return String(node)
  if (Array.isArray(node)) return node.map(extractText).join("")
  if (node && typeof node === "object" && "props" in node) return extractText((node.props as { children?: ReactNode }).children)
  return ""
}

// apps/ant-design-vue/src/pages/chat.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { marked } from "marked"
import { message } from "ant-design-vue"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Icon } from "../icons"
const draft = ref("")
const active = ref(chat.conversations[0].id)
const mobileOpen = ref(false)
const empty = new URLSearchParams(location.search).get("empty") === "1"
const current = computed(() => chat.conversations.find((item) => item.id === active.value))
function markdown(value: string) { return marked.parse(value) as string }
function copy(value: string) { navigator.clipboard?.writeText(value); message.success("已复制") }
</script>
<template>
  <div class="page"><div class="page-header"><div><h1>AI 对话</h1><p class="muted">与团队智能助手协作，保留完整上下文。</p></div><a-button class="mobile-menu" @click="mobileOpen = true"><Icon name="message-square" />会话</a-button></div>
    <a-drawer v-model:open="mobileOpen" title="会话"><div class="chat-list"><a-input-search placeholder="搜索对话" /><a-button block class="section">新建对话</a-button><a-list class="section" :data-source="chat.conversations"><template #renderItem="{ item }"><a-list-item :class="{ active: active === item.id }" @click="active = item.id; mobileOpen = false"><span>{{ item.title }}<small class="muted">{{ item.time }}</small></span><a-badge v-if="item.unread" :count="item.unread" /></a-list-item></template></a-list></div></a-drawer>
    <div class="chat-layout"><aside class="chat-list"><div class="section-title"><strong>对话</strong><a-button type="text" shape="circle"><Icon name="plus" /></a-button></div><a-input-search placeholder="搜索对话" /><a-button block class="section">新建对话</a-button><a-list class="section" :data-source="chat.conversations"><template #renderItem="{ item }"><a-list-item :class="{ active: active === item.id }" @click="active = item.id"><span>{{ item.title }}<small class="muted">{{ item.time }}</small></span><a-badge v-if="item.unread" :count="item.unread" /></a-list-item></template></a-list></aside>
      <section class="chat-main"><header class="chat-header"><strong>{{ current?.title ?? "新对话" }}</strong><a-select :default-value="chat.models[0]" style="width:150px"><a-select-option v-for="model in chat.models" :key="model" :value="model">{{ model }}</a-select-option></a-select></header>
        <div v-if="empty || !current" class="chat-messages"><a-empty description="开始一次新的对话"><template #image><Icon name="bot" :size="36" /></template><a-row :gutter="[12, 12]"><a-col v-for="item in chat.suggestions" :key="item" :xs="24" :sm="12"><a-card hoverable @click="draft = item">{{ item }}</a-card></a-col></a-row></a-empty></div>
        <div v-else class="chat-messages"><div v-for="(item, index) in chat.messages" :key="index" class="message" :class="{ user: item.role === 'user' }"><a-avatar>{{ item.role === 'user' ? '林' : 'AI' }}</a-avatar><div class="bubble"><div class="muted">{{ item.role === 'user' ? '林晓' : 'AI 助手' }} · 刚刚</div><div v-if="item.role === 'assistant'" class="markdown" v-html="markdown(item.content)" /><span v-else>{{ item.content }}</span><div v-if="item.streaming" class="muted">生成中<span class="cursor">▋</span></div><div v-if="item.sources" class="source-list"><a-tag v-for="source in item.sources" :key="source">{{ source }}</a-tag></div><a-collapse v-if="item.tool" class="section"><a-collapse-panel key="tool" :header="`工具调用 · ${item.tool.name}`"><pre>{{ JSON.stringify(item.tool.args, null, 2) }}</pre></a-collapse-panel></a-collapse><a-button v-if="item.role === 'assistant' && item.content.includes('```')" size="small" class="section" @click="copy(item.content)">复制</a-button></div></div></div>
        <div class="composer"><div class="suggestions"><a-tag v-for="suggestion in chat.suggestions" :key="suggestion" @click="draft = suggestion">{{ suggestion }}</a-tag></div><a-textarea v-model:value="draft" :auto-size="{ minRows: 2, maxRows: 5 }" placeholder="向 AI 助手提问..." /><div class="composer-actions"><span class="muted">{{ draft.length }} / 2000 · Enter 发送 / Shift+Enter 换行</span><a-space><a-button type="text"><Icon name="paperclip" /></a-button><a-button type="primary" shape="circle"><Icon name="send" /></a-button></a-space></div></div>
      </section>
    </div>
  </div>
</template>
<style scoped>.chat-header { display:flex; justify-content:space-between; align-items:center; padding:16px 20px; border-bottom:1px solid var(--ant-color-border); }.chat-list :deep(.ant-list-item) { cursor:pointer; border-radius:8px; padding:10px; }.chat-list :deep(.ant-list-item.active), .chat-list :deep(.ant-list-item:hover) { background:var(--ant-color-fill-quaternary); }.chat-list small { display:block; }.suggestions { display:flex; flex-wrap:wrap; gap:8px; margin-bottom:10px; }.suggestions .ant-tag { cursor:pointer; }.composer-actions { display:flex; justify-content:space-between; align-items:center; margin-top:8px; }.markdown :deep(pre) { padding:12px; border-radius:8px; background:#111; color:#eee; overflow:auto; }.markdown :deep(table) { border-collapse:collapse; width:100%; }.markdown :deep(th), .markdown :deep(td) { border:1px solid var(--ant-color-border); padding:6px; }.source-list { display:flex; flex-wrap:wrap; gap:6px; margin-top:10px; }.cursor { animation:blink 1s infinite; } @keyframes blink { 50% { opacity:0; } } @media (max-width:767px) { .chat-layout { display:block; }.chat-layout > .chat-list { display:none; } }</style>
