// apps/rsuite/src/pages/login.tsx
import { forwardRef, useMemo, useState, type ComponentProps } from "react"
import { Link } from "react-router-dom"
import { Button, Checkbox, Divider, Form, Heading, Input, InputGroup, Message, Panel, Schema, Text } from "rsuite"
import { EyeClose, Visible } from "@rsuite/icons"
import { Icon } from "@/components/icon"

const PasswordField = forwardRef<HTMLInputElement, ComponentProps<typeof Input>>(function PasswordField(props, ref) {
  const [visible, setVisible] = useState(false)
  return <InputGroup size="lg"><Input {...props} ref={ref} size="lg" type={visible ? "text" : "password"} /><InputGroup.Button aria-label={visible ? "隐藏密码" : "显示密码"} onClick={() => setVisible((value) => !value)}>{visible ? <EyeClose /> : <Visible />}</InputGroup.Button></InputGroup>
})
export function LoginPage() {
  const [submitting, setSubmitting] = useState(false)
  const model = useMemo(() => Schema.Model({
    email: Schema.Types.StringType().isEmail("请输入有效邮箱").isRequired("请输入邮箱"),
    password: Schema.Types.StringType().minLength(6, "密码至少需要 6 位").isRequired("请输入密码"),
  }), [])
  return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16, background: "var(--rs-bg-well)" }}><Panel bordered style={{ width: "100%", maxWidth: 420 }} header={<Link to="/" style={{ textDecoration: "none", fontWeight: 700 }}><b className="brand-letter" style={{ width: 32, height: 32, borderRadius: 8, marginRight: 8 }}>A</b>Acme Console</Link>}>
    <Heading level={3}>欢迎回来</Heading><Text muted>登录 Acme Console，继续你的工作。</Text><Message type="error" showIcon style={{ margin: "20px 0" }}>密码错误时会在这里显示验证错误。</Message>
    <Form fluid model={model} onSubmit={() => { setSubmitting(true); window.setTimeout(() => setSubmitting(false), 600) }}><Form.Group controlId="email"><Form.ControlLabel>邮箱</Form.ControlLabel><Form.Control name="email" accepter={Input} size="lg" type="email" placeholder="you@example.com" /><Form.HelpText>使用工作邮箱登录。</Form.HelpText></Form.Group><Form.Group controlId="password"><Form.ControlLabel>密码</Form.ControlLabel><Form.Control name="password" accepter={PasswordField} placeholder="请输入密码" /></Form.Group><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, marginBottom: 16 }}><Checkbox>记住我</Checkbox><Link to="#forgot">忘记密码？</Link></div><Button appearance="primary" size="lg" type="submit" block loading={submitting}>登录</Button></Form>
    <Divider>或</Divider><div className="page-stack" style={{ gap: 10 }}>{[{ icon: "globe", label: "Google" }, { icon: "github", label: "GitHub" }, { icon: "message-circle", label: "微信" }].map((item) => <Button key={item.label} appearance="ghost" size="lg" block startIcon={<Icon name={item.icon} />}>使用 {item.label} 登录</Button>)}</div><Text muted style={{ display: "block", textAlign: "center", marginTop: 20 }}>还没有账户？ <Link to="#register">立即注册</Link></Text>
  </Panel></div>
}

// apps/ant-design-vue/src/pages/login.vue
<script setup lang="ts">
import { ref } from "vue"
import { Icon } from "../icons"
const form = ref()
const loading = ref(false)
const failed = ref(false)
const model = ref({ email: "", password: "", remember: true })
const rules = { email: [{ required: true, message: "请输入邮箱" }, { type: "email", message: "请输入有效邮箱" }], password: [{ required: true, message: "请输入密码" }] }
async function submit() {
  failed.value = false
  try { await form.value.validate(); loading.value = true; await new Promise((resolve) => setTimeout(resolve, 1200)); failed.value = true } catch { /* inline form errors */ } finally { loading.value = false }
}
</script>
<template>
  <div class="login-page">
    <a-card class="login-card">
      <div class="login-brand"><span class="brand-mark">A</span><strong>Acme Console</strong></div>
      <h1>欢迎回来</h1><p class="muted">登录你的工作区，继续管理业务。</p>
      <a-alert v-if="failed" type="error" show-icon message="邮箱或密码错误" class="section" />
      <a-form ref="form" :model="model" :rules="rules" layout="vertical" @finish="submit">
        <a-form-item label="邮箱" name="email"><a-input v-model:value="model.email" size="large" placeholder="name@example.com"><template #prefix><Icon name="user" /></template></a-input></a-form-item>
        <a-form-item label="密码" name="password"><a-input-password v-model:value="model.password" size="large" placeholder="请输入密码"><template #prefix><Icon name="lock" /></template></a-input-password></a-form-item>
        <div class="form-row"><a-checkbox v-model:checked="model.remember">记住我</a-checkbox><a-typography-link href="#">忘记密码？</a-typography-link></div>
        <a-button type="primary" html-type="submit" size="large" block :loading="loading">登录</a-button>
      </a-form>
      <a-divider>或</a-divider>
      <a-space direction="vertical" block>
        <a-button block><Icon name="globe" />使用 Google 登录</a-button><a-button block><Icon name="github" />使用 GitHub 登录</a-button><a-button block>使用微信登录</a-button>
      </a-space>
      <p class="login-footer muted">还没有账户？ <a-typography-link href="#">立即注册</a-typography-link></p>
    </a-card>
  </div>
</template>
<style scoped>
.login-page { min-height: 100vh; display: grid; place-items: center; padding: 24px; background: var(--app-color-bg-layout); }
.login-card { width: min(100%, 420px); }
.login-brand { display: flex; align-items: center; gap: 10px; margin-bottom: 24px; }
.login-card h1 { margin-bottom: 4px; }
.form-row { display: flex; justify-content: space-between; margin-bottom: 20px; }
.login-footer { text-align: center; margin: 24px 0 0; }
</style>
