// apps/arco-design/src/pages/login.tsx
import { useState } from "react"
import { Link } from "react-router-dom"
import { Alert, Button, Card, Checkbox, Divider, Form, Input, Message, Space, Typography } from "@arco-design/web-react"
import { Icon } from "@/components/icon"

export function LoginPage() {
  const [visible, setVisible] = useState(false)
  const [loading, setLoading] = useState(false)
  const submit = () => {
    setLoading(true)
    window.setTimeout(() => { setLoading(false); Message.success("登录成功") }, 600)
  }
  return (
    <div className="login-page">
      <Card className="login-card">
        <Space direction="vertical" size={24} style={{ width: "100%" }}>
          <Link className="brand" to="/"><span className="brand-mark">A</span>Acme Console</Link>
          <div>
            <Typography.Title heading={2}>欢迎回来</Typography.Title>
            <Typography.Text type="secondary">登录 Acme Console，继续你的工作。</Typography.Text>
          </div>
          <Alert type="error" title="演示错误状态" content="密码错误时会在这里显示验证错误。" />
          <Form layout="vertical" onSubmit={submit}>
            <Form.Item label="邮箱" field="email" rules={[{ required: true, message: "请输入邮箱" }, { type: "email", message: "邮箱格式不正确" }]}>
              <Input size="large" prefix={<Icon name="user" />} placeholder="you@example.com" />
            </Form.Item>
            <Form.Item label="密码" field="password" rules={[{ required: true, message: "请输入密码" }]}>
              <Input.Password size="large" prefix={<Icon name="lock" />} placeholder="••••••••" visibilityToggle={!visible} onVisibilityChange={setVisible} />
            </Form.Item>
            <div className="between"><Checkbox>记住我</Checkbox><Link to="#forgot">忘记密码？</Link></div>
            <Button size="large" htmlType="submit" type="primary" long loading={loading} style={{ marginTop: 16 }}>登录</Button>
          </Form>
          <Divider>或</Divider>
          <Space wrap style={{ width: "100%" }}>
            <Button size="large" type="secondary" icon={<Icon name="globe" />}>Google</Button>
            <Button size="large" type="secondary" icon={<Icon name="github" />}>GitHub</Button>
            <Button size="large" type="secondary" icon={<Icon name="message-circle" />}>微信</Button>
          </Space>
          <Typography.Text type="secondary" style={{ textAlign: "center", display: "block" }}>还没有账户？ <Link to="#register">立即注册</Link></Typography.Text>
        </Space>
      </Card>
    </div>
  )
}

// apps/ant-design-vue/src/pages/login.vue
<script setup lang="ts">
import { ref } from "vue"
import { Icon } from "../icons"
const form = ref()
const loading = ref(false)
const failed = ref(false)
const model = ref({ email: "", password: "", remember: true })
const rules = { email: [{ required: true, message: "请输入邮箱" }, { type: "email", message: "请输入有效邮箱" }], password: [{ required: true, message: "请输入密码" }] }
async function submit() {
  failed.value = false
  try { await form.value.validate(); loading.value = true; await new Promise((resolve) => setTimeout(resolve, 1200)); failed.value = true } catch { /* inline form errors */ } finally { loading.value = false }
}
</script>
<template>
  <div class="login-page">
    <a-card class="login-card">
      <div class="login-brand"><span class="brand-mark">A</span><strong>Acme Console</strong></div>
      <h1>欢迎回来</h1><p class="muted">登录你的工作区，继续管理业务。</p>
      <a-alert v-if="failed" type="error" show-icon message="邮箱或密码错误" class="section" />
      <a-form ref="form" :model="model" :rules="rules" layout="vertical" @finish="submit">
        <a-form-item label="邮箱" name="email"><a-input v-model:value="model.email" size="large" placeholder="name@example.com"><template #prefix><Icon name="user" /></template></a-input></a-form-item>
        <a-form-item label="密码" name="password"><a-input-password v-model:value="model.password" size="large" placeholder="请输入密码"><template #prefix><Icon name="lock" /></template></a-input-password></a-form-item>
        <div class="form-row"><a-checkbox v-model:checked="model.remember">记住我</a-checkbox><a-typography-link href="#">忘记密码？</a-typography-link></div>
        <a-button type="primary" html-type="submit" size="large" block :loading="loading">登录</a-button>
      </a-form>
      <a-divider>或</a-divider>
      <a-space direction="vertical" block>
        <a-button block><Icon name="globe" />使用 Google 登录</a-button><a-button block><Icon name="github" />使用 GitHub 登录</a-button><a-button block>使用微信登录</a-button>
      </a-space>
      <p class="login-footer muted">还没有账户？ <a-typography-link href="#">立即注册</a-typography-link></p>
    </a-card>
  </div>
</template>
<style scoped>
.login-page { min-height: 100vh; display: grid; place-items: center; padding: 24px; background: var(--app-color-bg-layout); }
.login-card { width: min(100%, 420px); }
.login-brand { display: flex; align-items: center; gap: 10px; margin-bottom: 24px; }
.login-card h1 { margin-bottom: 4px; }
.form-row { display: flex; justify-content: space-between; margin-bottom: 20px; }
.login-footer { text-align: center; margin: 24px 0 0; }
</style>
