// apps/primereact/src/pages/orders.tsx
import { useState, useRef } from "react"
import orders from "@ui-gallery/spec/mock/orders.json"
import { Button } from "primereact/button"
import { Calendar } from "primereact/calendar"
import { ConfirmDialog, confirmDialog } from "primereact/confirmdialog"
import { DataTable } from "primereact/datatable"
import { Column } from "primereact/column"
import { Dropdown } from "primereact/dropdown"
import { IconField } from "primereact/iconfield"
import { InputIcon } from "primereact/inputicon"
import { InputText } from "primereact/inputtext"
import { MultiSelect } from "primereact/multiselect"
import { Paginator } from "primereact/paginator"
import { Sidebar } from "primereact/sidebar"
import { TabPanel, TabView } from "primereact/tabview"
import { Tag } from "primereact/tag"
import { Toast } from "primereact/toast"
import { InputTextarea } from "primereact/inputtextarea"
import { Icon } from "@/components/icon"
import { EmptyState, PageHeader, StatusTag } from "@/components/shared"

export function OrdersPage() {
  const [selected, setSelected] = useState<(typeof orders)[number] | null>(null), [state, setState] = useState("normal"), toast = useRef<Toast>(null)
  const [query, setQuery] = useState("")
  const filtered = orders.filter((item) => item.id.toLowerCase().includes(query.toLowerCase()) || item.customer.toLowerCase().includes(query.toLowerCase())).slice(0, 8)
  const remove = () => toast.current?.show({ severity: "success", summary: "已删除", detail: "订单已移除", life: 2400 })
  return <div className="flex flex-column gap-5"><Toast ref={toast} /><ConfirmDialog /><PageHeader title="订单" description="管理订单、状态与客户信息。" action={<Button outlined icon={<Icon name="download" />} label="导出" />} /><div className="flex flex-wrap gap-2"><IconField iconPosition="left"><InputIcon className="pi pi-search" /><InputText value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索订单或客户" /></IconField><Dropdown options={["全部状态", "paid", "pending", "failed"]} placeholder="状态" className="w-10rem" /><Calendar selectionMode="range" placeholder="日期范围" className="w-12rem" /><MultiSelect options={["web", "ios", "android", "api"]} placeholder="渠道" className="w-10rem" /><Button text icon={<Icon name="filter" />} aria-label="筛选" /></div><div className="flex gap-2"><Button label="正常" outlined={state !== "normal"} onClick={() => setState("normal")} /><Button label="空态" outlined={state !== "empty"} onClick={() => setState("empty")} /><Button label="加载" outlined={state !== "loading"} onClick={() => setState("loading")} /><Button label="错误" outlined={state !== "error"} onClick={() => setState("error")} /></div><div className="surface-card border-round border-1 surface-border table-scroll p-3"><small className="muted md:hidden">← 左右滑动查看更多列 →</small>{state === "empty" ? <EmptyState title="没有匹配订单" description="调整筛选条件后重试。" /> : state === "loading" ? <div className="p-4 flex flex-column gap-3"><div className="p-skeleton h-2rem" /><div className="p-skeleton h-2rem" /><div className="p-skeleton h-2rem" /></div> : state === "error" ? <div className="p-4"><Tag severity="danger" value="加载失败" /><p>订单服务暂时不可用。</p><Button label="重试" onClick={() => setState("normal")} /></div> : <><DataTable value={filtered} selectionMode="single" onSelectionChange={(e) => setSelected(e.value)} paginator rows={5} rowsPerPageOptions={[5, 10, 20]} stripedRows><Column selectionMode="multiple" headerStyle={{ width: "3rem" }} /><Column field="id" header="订单号" sortable /><Column field="customer" header="客户" /><Column field="status" header="状态" body={(row) => <StatusTag value={row.status} />} sortable /><Column field="date" header="日期" sortable /><Column field="amount" header="金额" body={(row) => <span className="block text-right">¥{row.amount.toLocaleString()}</span>} sortable /><Column header="操作" body={(row) => <Button text icon={<Icon name="trash" />} severity="danger" onClick={() => confirmDialog({ message: `确认删除 ${row.id}？`, header: "删除订单", icon: "pi pi-exclamation-triangle", accept: remove })} />} /></DataTable><Paginator first={0} rows={5} totalRecords={filtered.length} /></>}</div><Sidebar visible={Boolean(selected)} position="right" onHide={() => setSelected(null)} className="w-full md:w-30rem">{selected ? <div className="flex flex-column gap-4"><h2>{selected.id}</h2><dl className="grid"><dt className="col-5 muted">客户</dt><dd className="col-7 m-0">{selected.customer}</dd><dt className="col-5 muted">状态</dt><dd className="col-7 m-0"><StatusTag value={selected.status} /></dd><dt className="col-5 muted">金额</dt><dd className="col-7 m-0">¥{selected.amount.toLocaleString()}</dd><dt className="col-5 muted">产品</dt><dd className="col-7 m-0">{selected.product}</dd></dl><TabView><TabPanel header="详情"><p className="muted">订单来自 {selected.channel} 渠道。</p></TabPanel><TabPanel header="备注"><InputTextarea rows={4} className="w-full" placeholder="添加备注..." /></TabPanel></TabView><Button severity="danger" label="删除订单" icon={<Icon name="trash" />} onClick={() => confirmDialog({ message: "此操作无法撤销。", accept: remove })} /></div> : null}</Sidebar></div>
}

// apps/ant-design-vue/src/pages/orders.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { Modal, message } from "ant-design-vue"
import orders from "@ui-gallery/spec/mock/orders.json"
import { PageHeader, statusColor, statusLabel, initials } from "./shared"
const search = ref("")
const status = ref("all")
const mode = ref("normal")
const selected = ref<any[]>([])
const drawer = ref(false)
const current = ref<any>()
const columns = ref(["id", "customer", "product", "status", "amount", "date", "action"])
const filtered = computed(() => orders.filter((item) => (!search.value || `${item.id}${item.customer}${item.product}`.toLowerCase().includes(search.value.toLowerCase())) && (status.value === "all" || item.status === status.value)))
function openRow(record: any) { current.value = record; drawer.value = true }
function remove(record: any) { Modal.confirm({ title: "删除订单", content: `确定删除 ${record.id} 吗？`, okType: "danger", onOk: () => message.success("订单已删除") }) }
function simulate() { if (mode.value === "error") message.error("订单加载失败，请重试") }
</script>
<template>
  <div class="page">
    <PageHeader title="订单" description="管理订单、筛选交易状态并查看详情。" />
    <a-card>
      <div class="toolbar"><a-input-search v-model:value="search" placeholder="搜索订单、客户或产品" style="max-width: 280px" /><a-select v-model:value="status" style="width: 130px"><a-select-option value="all">全部状态</a-select-option><a-select-option v-for="(label, key) in statusLabel" :key="key" :value="key">{{ label }}</a-select-option></a-select><a-range-picker /><a-select mode="multiple" placeholder="渠道" :max-tag-count="1" style="width: 180px"><a-select-option value="web">Web</a-select-option><a-select-option value="ios">iOS</a-select-option><a-select-option value="android">Android</a-select-option><a-select-option value="api">API</a-select-option></a-select><a-button><span>导出</span></a-button><a-select v-model:value="mode" style="width: 110px" @change="simulate"><a-select-option value="normal">正常</a-select-option><a-select-option value="loading">加载</a-select-option><a-select-option value="error">错误</a-select-option><a-select-option value="empty">空</a-select-option></a-select></div>
      <a-alert v-if="mode === 'error'" type="error" message="订单加载失败" show-icon closable><template #description><a-button type="link" @click="mode = 'normal'">重试</a-button></template></a-alert>
      <a-empty v-else-if="mode === 'empty' || !filtered.length" description="没有匹配的订单"><a-button @click="search = ''; status = 'all'; mode = 'normal'">清除筛选</a-button></a-empty>
      <div v-else class="table-wrap"><a-table :data-source="filtered" :loading="mode === 'loading'" :row-selection="{ selectedRowKeys: selected.map((item) => item.id), onChange: (_keys: any, rows: any[]) => selected = rows }" row-key="id" :scroll="{ x: 900 }" @row-click="openRow"><a-table-column v-if="columns.includes('id')" title="订单" data-index="id" sorter /><a-table-column v-if="columns.includes('customer')" title="客户" data-index="customer"><template #default="{ record }"><a-avatar size="small">{{ initials(record.customer) }}</a-avatar> {{ record.customer }}</template></a-table-column><a-table-column v-if="columns.includes('product')" title="产品" data-index="product" /><a-table-column v-if="columns.includes('status')" title="状态"><template #default="{ record }"><a-tag :color="statusColor[record.status]">{{ statusLabel[record.status] }}</a-tag></template></a-table-column><a-table-column v-if="columns.includes('amount')" title="金额" data-index="amount" align="right" sorter><template #default="{ record }">¥{{ record.amount.toLocaleString() }}</template></a-table-column><a-table-column v-if="columns.includes('date')" title="日期" data-index="date" /><a-table-column title="操作" fixed="right"><template #default="{ record }"><a-dropdown><a-button type="text" @click.stop><span>···</span></a-button><template #overlay><a-menu><a-menu-item key="edit">编辑</a-menu-item><a-menu-item key="delete" danger @click="remove(record)">删除</a-menu-item></a-menu></template></a-dropdown></template></a-table-column></a-table></div>
      <a-pagination class="pagination" :total="filtered.length" show-size-changer show-quick-jumper />
    </a-card>
    <a-drawer v-model:open="drawer" title="订单详情" width="min(560px, 100vw)" placement="right"><a-descriptions v-if="current" bordered :column="1"><a-descriptions-item label="订单号">{{ current.id }}</a-descriptions-item><a-descriptions-item label="客户">{{ current.customer }}（{{ current.email }}）</a-descriptions-item><a-descriptions-item label="产品">{{ current.product }}</a-descriptions-item><a-descriptions-item label="金额">¥{{ current.amount.toLocaleString() }}</a-descriptions-item><a-descriptions-item label="状态"><a-tag :color="statusColor[current.status]">{{ statusLabel[current.status] }}</a-tag></a-descriptions-item></a-descriptions><a-tabs class="section"><a-tab-pane key="activity" tab="活动">订单已创建并进入处理流程。</a-tab-pane><a-tab-pane key="notes" tab="备注"><a-textarea :rows="5" placeholder="添加备注" /></a-tab-pane></a-tabs></a-drawer>
  </div>
</template>
<style scoped>.toolbar { display:flex; flex-wrap:wrap; gap:10px; margin-bottom:18px; }.pagination { margin-top:18px; text-align:right; }</style>
