// apps/angular-material/src/app/pages/chat.page.ts
import { Component, ViewChild, inject } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { FormControl } from '@angular/forms';
import { MatSidenav } from '@angular/material/sidenav';
import { marked } from 'marked';
import chatData from '@ui-gallery/spec/mock/chat.json';
import { SHARED_IMPORTS } from '../shared/material';

type ToolCall = { name: string; args: Record<string, unknown>; status: string };
type ChatMessage = { role: string; content: string; sources?: string[]; tool?: ToolCall; streaming?: boolean };
type Segment = { kind: 'text'; html: SafeHtml } | { kind: 'code'; lang: string; code: string };

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="chat-page">
      <mat-sidenav-container class="chat-container">
        <mat-sidenav #sessionsDrawer class="chat-sessions" [mode]="mobile ? 'over' : 'side'" [opened]="mobile ? sessionsOpen : true" (closed)="sessionsOpen = false">
          <div class="chat-sessions-header"><b>会话</b><button mat-icon-button (click)="sessionsDrawer.close()" matTooltip="关闭会话列表"><mat-icon svgIcon="x"></mat-icon></button></div>
          <button mat-flat-button color="primary" class="new-chat" (click)="newConversation()"><mat-icon svgIcon="plus"></mat-icon>新建会话</button><mat-form-field appearance="outline" class="full session-search" subscriptSizing="dynamic"><mat-icon matPrefix svgIcon="search"></mat-icon><input matInput [formControl]="sessionQuery" placeholder="搜索会话"></mat-form-field>
          <mat-nav-list>@for (conversation of filteredConversations(); track conversation.id) {<a mat-list-item [class.active-chat]="conversation.id === activeConversation"><mat-icon matListItemIcon svgIcon="message-square"></mat-icon><span matListItemTitle>{{ conversation.title }}</span><span matListItemLine>{{ conversation.time }}</span>@if (conversation.unread) {<span matListItemMeta class="unread">{{ conversation.unread }}</span>}</a>}</mat-nav-list>
        </mat-sidenav>
        <mat-sidenav-content>
          <header class="chat-toolbar"><div class="chat-title-row"><button mat-icon-button class="chat-session-toggle" (click)="sessionsOpen = true; sessionsDrawer.open()" aria-label="打开会话列表"><mat-icon svgIcon="menu"></mat-icon></button><div><p class="eyebrow">AI WORKSPACE</p><h1>智能助手</h1></div></div><div class="chat-toolbar-actions"><span class="chip toolbar-model">{{ selectedModel }}</span><button mat-icon-button matTooltip="新建对话" (click)="newConversation()"><mat-icon svgIcon="edit"></mat-icon></button></div></header>
          <section class="chat-content">
            @if (emptyState) {
              <div class="chat-empty"><span class="chat-orb"><mat-icon svgIcon="sparkles"></mat-icon></span><h2>今天我能帮你做什么？</h2><p class="muted">分析业务数据、写作和自动化工作都可以交给我。</p><div class="suggestion-cards">@for (suggestion of suggestions; track suggestion) {<button mat-stroked-button (click)="prompt.setValue(suggestion)"><mat-icon svgIcon="sparkles"></mat-icon>{{ suggestion }}</button>}</div></div>
            } @else {
              <div class="message-list">@for (message of messages; track $index) {<article class="message" [class.user-message]="message.role === 'user'"><span class="avatar">{{ message.role === 'user' ? '林' : 'AI' }}</span><div class="message-body"><div class="message-meta"><b>{{ message.role === 'user' ? '你' : 'Assistant' }}</b><small class="muted">{{ message.role === 'user' ? '刚刚' : '1 秒前' }}</small></div><div class="message-content" [class.streaming]="message.streaming">@if (message.tool) {<div class="tool-card" role="status"><div class="tool-head"><mat-icon svgIcon="code"></mat-icon><b>工具调用 · {{ message.tool.name }}</b><span class="chip" [class.positive]="message.tool.status === 'done'">@if (message.tool.status === 'done') {<mat-icon svgIcon="check"></mat-icon>} @else {<mat-spinner diameter="14"></mat-spinner>}{{ message.tool.status }}</span></div><pre class="tool-args"><code>{{ message.tool.args | json }}</code></pre></div>}<div class="message-text markdown-body">@for (segment of segments(message); track $index) {@if (segment.kind === 'code') {<div class="code-block-wrap"><div class="code-block-bar"><span class="muted">{{ segment.lang || 'code' }}</span><button mat-button (click)="copyText(segment.code, '代码已复制')" aria-label="复制代码块"><mat-icon svgIcon="copy"></mat-icon>复制</button></div><pre class="code-block"><code>{{ segment.code }}</code></pre></div>} @else {<div [innerHTML]="segment.html"></div>}}@if (message.streaming) {<span class="typing" aria-label="正在生成"><span></span><span></span><span></span></span>}</div>@if (message.sources?.length) {<div class="sources"><span class="muted">来源</span>@for (source of message.sources; track source) {<span class="chip source-chip"><mat-icon svgIcon="link"></mat-icon>{{ source }}</span>}</div>}@if (message.role === 'assistant') {<div class="message-actions">@if (message.streaming) {<span class="muted streaming-label"><mat-spinner diameter="14"></mat-spinner>正在生成…</span>} @else {<button mat-stroked-button (click)="copyText(message.content, '消息已复制')" aria-label="复制消息"><mat-icon svgIcon="copy"></mat-icon>复制</button>}</div>}</div></div></article>}</div>
            }
          </section>
          <footer class="chat-composer"><mat-chip-set class="suggestion-row">@for (suggestion of suggestions; track suggestion) {<mat-chip (click)="prompt.setValue(suggestion)">{{ suggestion }}</mat-chip>}</mat-chip-set><div class="composer-box"><textarea matInput cdkTextareaAutosize [formControl]="prompt" rows="2" maxlength="4000" placeholder="输入消息，按 Enter 发送"></textarea><div class="composer-actions"><div class="demo-row"><button mat-icon-button matTooltip="添加附件" aria-label="添加附件"><mat-icon svgIcon="paperclip"></mat-icon></button><mat-form-field appearance="outline" subscriptSizing="dynamic"><mat-label>模型</mat-label><mat-select [(value)]="selectedModel">@for (model of models; track model) {<mat-option [value]="model">{{ model }}</mat-option>}</mat-select></mat-form-field></div><div class="composer-meta"><span class="muted">{{ prompt.value?.length ?? 0 }}/4000 · Shift + Enter 换行</span><button mat-flat-button color="primary" (click)="send()" [disabled]="!prompt.value?.trim()"><mat-icon svgIcon="send"></mat-icon>发送</button></div></div></div></footer>
        </mat-sidenav-content>
      </mat-sidenav-container>
    </main>
  `,
})
export class ChatPage {
  @ViewChild('sessionsDrawer') sessionsDrawer?: MatSidenav;
  readonly conversations = chatData.conversations;
  readonly messages: ChatMessage[] = chatData.messages;
  private readonly segmentCache = new Map<string, Segment[]>();
  private readonly snackBar = inject(MatSnackBar);
  readonly suggestions = chatData.suggestions.slice(0, 4);
  readonly models = chatData.models;
  readonly prompt = new FormControl('');
  readonly sessionQuery = new FormControl('');
  filteredConversations(): typeof chatData.conversations { const q = (this.sessionQuery.value ?? '').trim().toLowerCase(); return q ? this.conversations.filter((item) => item.title.toLowerCase().includes(q)) : this.conversations; }
  readonly emptyState = new URLSearchParams(window.location.search).get('state') === 'empty';
  selectedModel = this.models[0];
  sessionsOpen = false;
  activeConversation = this.conversations[0]?.id;
  mobile = window.matchMedia('(max-width: 959px)').matches;
  private readonly sanitizer = inject(DomSanitizer);

  segments(message: ChatMessage): Segment[] {
    const cached = this.segmentCache.get(message.content);
    if (cached) return cached;
    const result: Segment[] = [];
    const fence = /```(\w*)\n([\s\S]*?)```/g;
    let last = 0;
    for (const match of message.content.matchAll(fence)) {
      const text = message.content.slice(last, match.index).trim();
      if (text) result.push({ kind: 'text', html: this.renderMarkdown(text) });
      result.push({ kind: 'code', lang: match[1], code: match[2].replace(/\n$/, '') });
      last = (match.index ?? 0) + match[0].length;
    }
    const tail = message.content.slice(last).trim();
    if (tail) result.push({ kind: 'text', html: this.renderMarkdown(tail) });
    this.segmentCache.set(message.content, result);
    return result;
  }

  copyText(text: string, message: string): void {
    navigator.clipboard?.writeText(text);
    this.snackBar.open(message, undefined, { duration: 1800 });
  }

  private renderMarkdown(content: string): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(marked.parse(content, { async: false }) as string);
  }

  newConversation(): void {
    this.prompt.setValue('');
  }

  send(): void {
    if (this.prompt.value?.trim()) this.prompt.setValue('');
  }
}

// apps/primevue/src/pages/ChatPage.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUpdated, ref } from "vue"
import { marked } from "marked"
import Avatar from "primevue/avatar"
import Accordion from "primevue/accordion"
import AccordionPanel from "primevue/accordionpanel"
import AccordionHeader from "primevue/accordionheader"
import AccordionContent from "primevue/accordioncontent"
import Badge from "primevue/badge"
import Button from "primevue/button"
import Drawer from "primevue/drawer"
import IconField from "primevue/iconfield"
import InputIcon from "primevue/inputicon"
import InputText from "primevue/inputtext"
import Select from "primevue/select"
import Textarea from "primevue/textarea"
import Chip from "primevue/chip"
import PageHeader from "@/components/PageHeader.vue"
import chat from "@ui-gallery/spec/mock/chat.json"

marked.use({ async: false })
type Message = { role: string; content: string; sources?: string[]; tool?: { name: string; args: Record<string, string>; status: string }; streaming?: boolean }
const conversations = ref(chat.conversations.map((item) => ({ ...item })))
const messages = ref<Message[]>(chat.messages as Message[])
const activeConversation = ref(conversations.value[0].id)
const conversationSearch = ref("")
const draft = ref("")
const model = ref(chat.models[0])
const mobileOpen = ref(false)
const filteredConversations = computed(() => conversations.value.filter((item) => item.title.includes(conversationSearch.value)))
const activeConversationTitle = computed(() => conversations.value.find((item) => item.id === activeConversation.value)?.title ?? "新对话")
const rendered = (content: string) => marked.parse(content, { async: false }) as string
function createConversation() { const id = `new-${Date.now()}`; conversations.value.unshift({ id, title: "新对话", time: "刚刚", unread: 0 }); activeConversation.value = id; messages.value = [] }
function send() { const text = draft.value.trim(); if (!text) return; messages.value.push({ role: "user", content: text }); draft.value = ""; nextTick(() => messages.value.push({ role: "assistant", content: "我会基于当前工作区的数据继续分析。", sources: ["stats.json"] })) }
function copyCode(event: Event) { const code = (event.currentTarget as HTMLElement).closest(".code-wrap")?.querySelector("code")?.textContent ?? ""; navigator.clipboard?.writeText(code) }
function wrapCodeBlocks() { document.querySelectorAll(".chat-page .markdown pre").forEach((pre) => { if (pre.parentElement?.classList.contains("code-wrap")) return; const wrap = document.createElement("div"); wrap.className = "code-wrap"; pre.replaceWith(wrap); wrap.append(pre); const button = document.createElement("button"); button.className = "copy-code"; button.type = "button"; button.textContent = "复制"; button.addEventListener("click", copyCode); wrap.append(button) }) }
onMounted(() => nextTick(wrapCodeBlocks))
onUpdated(() => nextTick(wrapCodeBlocks))
</script>

<template>
  <div class="chat-page">
    <PageHeader title="AI 助手" description="与工作区数据对话，快速获得洞察"><Button class="mobile-only" icon="pi pi-comments" label="会话" outlined @click="mobileOpen = true" /></PageHeader>
    <div class="chat-layout">
      <aside class="conversation-sidebar desktop-only"><div class="flex items-center justify-between gap-2 mb-3"><strong>会话</strong><Button label="新建" icon="pi pi-plus" size="small" @click="createConversation" /></div><IconField class="w-full mb-3"><InputIcon class="pi pi-search" /><InputText v-model="conversationSearch" placeholder="搜索会话" fluid /></IconField><div class="conversation-list"><button v-for="item in filteredConversations" :key="item.id" class="conversation-item" :class="{ active: item.id === activeConversation }" @click="activeConversation = item.id"><span class="min-w-0 flex-1"><strong class="truncate">{{ item.title }}</strong><small>{{ item.time }}</small></span><Badge v-if="item.unread" :value="item.unread" severity="danger" /></button></div></aside>
      <Drawer v-model:visible="mobileOpen" header="会话" class="mobile-conversations" position="left"><Button label="新建会话" icon="pi pi-plus" fluid outlined @click="createConversation(); mobileOpen = false" /><div class="conversation-list mt-3"><button v-for="item in filteredConversations" :key="item.id" class="conversation-item" :class="{ active: item.id === activeConversation }" @click="activeConversation = item.id; mobileOpen = false"><span class="min-w-0 flex-1"><strong class="truncate">{{ item.title }}</strong><small>{{ item.time }}</small></span><Badge v-if="item.unread" :value="item.unread" severity="danger" /></button></div></Drawer>
      <section class="chat-main">
        <div class="chat-heading"><div><strong>{{ activeConversationTitle }}</strong><div class="text-xs muted">Acme Console 数据助手</div></div><Select v-model="model" :options="chat.models" size="small" /></div>
        <div v-if="messages.length" class="message-stream"><article v-for="(message, index) in messages" :key="`${index}-${message.content}`" class="message-row" :class="message.role"><Avatar :label="message.role === 'user' ? '林' : 'A'" shape="circle" /><div class="message-content"><div class="message-bubble"><div v-if="message.streaming" class="typing"><span /><span /><span />正在生成…</div><div v-else class="markdown" v-html="rendered(message.content)" /><div v-if="message.sources?.length" class="sources"><span class="text-xs muted">引用来源</span><Chip v-for="source in message.sources" :key="source" :label="source" /></div></div><Accordion v-if="message.tool" class="tool-card"><AccordionPanel value="0"><AccordionHeader>工具调用 · {{ message.tool.name }}</AccordionHeader><AccordionContent><pre class="text-xs">{{ JSON.stringify(message.tool.args, null, 2) }}</pre><span class="text-xs muted">状态：{{ message.tool.status }}</span></AccordionContent></AccordionPanel></Accordion></div></article></div>
        <div v-else class="empty-state chat-empty"><i class="pi pi-sparkles" style="font-size: 2rem" /><h2>你好，我是 Acme 助手</h2><p>选择一个建议，开始探索你的工作区数据。</p><div class="suggestion-grid"><Button v-for="suggestion in chat.suggestions" :key="suggestion" :label="suggestion" severity="secondary" outlined @click="draft = suggestion" /></div></div>
        <div class="composer"><div class="suggestions"><Chip v-for="suggestion in chat.suggestions" :key="suggestion" :label="suggestion" class="suggestion-chip" @click="draft = suggestion" /></div><div class="composer-row"><Button icon="pi pi-paperclip" text rounded severity="secondary" aria-label="添加附件" /><Textarea v-model="draft" auto-resize rows="1" maxlength="2000" placeholder="输入消息，按 Enter 发送" fluid @keydown.enter.exact.prevent="send" /><Button icon="pi pi-send" rounded aria-label="发送" :disabled="!draft.trim()" @click="send" /></div><div class="flex justify-between text-xs muted"><span>{{ draft.length }}/2000</span><span><span class="kbd">Enter</span> 发送 · <span class="kbd">Shift+Enter</span> 换行</span></div></div>
      </section>
    </div>
  </div>
</template>

<style scoped>
.chat-layout { display: grid; grid-template-columns: 260px minmax(0, 1fr); min-height: calc(100vh - 150px); border: 1px solid var(--p-content-border-color); border-radius: var(--p-content-border-radius); overflow: hidden; }
.conversation-sidebar { border-right: 1px solid var(--p-content-border-color); padding: 16px; background: var(--p-content-background); }
.conversation-list { display: flex; flex-direction: column; gap: 4px; } .conversation-item { display: flex; align-items: center; gap: 8px; width: 100%; padding: 10px; border: 0; border-radius: var(--p-content-border-radius); background: transparent; color: var(--p-text-color); text-align: left; cursor: pointer; } .conversation-item:hover, .conversation-item.active { background: var(--p-highlight-background); } .conversation-item strong, .conversation-item small { display: block; } .conversation-item small { color: var(--p-text-muted-color); font-size: 11px; margin-top: 2px; }
.chat-main { display: flex; flex-direction: column; min-width: 0; background: var(--p-surface-50); } .dark .chat-main { background: var(--p-surface-950); }
.chat-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 14px 20px; border-bottom: 1px solid var(--p-content-border-color); background: var(--p-content-background); }
.message-stream { flex: 1; overflow-y: auto; padding: 24px; display: flex; flex-direction: column; gap: 20px; } .message-row { display: flex; align-items: flex-start; gap: 10px; max-width: min(780px, 100%); } .message-row.user { margin-left: auto; flex-direction: row-reverse; } .message-content { min-width: 0; } .message-bubble { padding: 12px 14px; border: 1px solid var(--p-content-border-color); border-radius: 14px; background: var(--p-content-background); } .message-row.user .message-bubble { background: var(--p-highlight-background); }
.markdown :deep(p) { margin: 0 0 10px; } .markdown :deep(p:last-child) { margin-bottom: 0; } .markdown :deep(table) { width: 100%; border-collapse: collapse; margin-top: 10px; } .markdown :deep(th), .markdown :deep(td) { padding: 6px 8px; border: 1px solid var(--p-content-border-color); text-align: left; } .markdown :deep(code) { padding: 2px 4px; border-radius: 4px; background: var(--p-surface-100); } .code-wrap { position: relative; } .code-wrap pre { padding: 12px; padding-top: 34px; overflow: auto; background: var(--p-surface-900); color: var(--p-surface-0); border-radius: 8px; } .copy-code { position: absolute; top: 8px; right: 8px; border: 1px solid var(--p-surface-600); background: transparent; color: inherit; padding: 3px 8px; border-radius: 5px; cursor: pointer; }
.sources { display: flex; align-items: center; flex-wrap: wrap; gap: 6px; margin-top: 10px; } .tool-card { margin-top: 8px; } .tool-card pre { white-space: pre-wrap; margin: 0; }
.composer { padding: 12px 20px 16px; border-top: 1px solid var(--p-content-border-color); background: var(--p-content-background); } .suggestions { display: flex; flex-wrap: nowrap; overflow-x: auto; gap: 6px; margin-bottom: 8px; scrollbar-width: none; } .suggestions::-webkit-scrollbar { display: none; } .suggestion-chip { flex: none; cursor: pointer; white-space: nowrap; } .composer-row { display: flex; align-items: flex-end; gap: 8px; } .composer-row :deep(textarea) { max-height: 140px; } .chat-empty { flex: 1; min-height: 360px; }
.typing { display: flex; align-items: center; gap: 5px; } .typing span { width: 6px; height: 6px; border-radius: 50%; background: var(--p-primary-color); animation: pulse 1s infinite; } .typing span:nth-child(2) { animation-delay: .15s; } .typing span:nth-child(3) { animation-delay: .3s; } @keyframes pulse { 50% { opacity: .25; transform: translateY(-2px); } }
.suggestion-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; max-width: 520px; }
@media (max-width: 767px) { .chat-layout { display: block; border: 0; min-height: calc(100vh - 130px); } .chat-heading { padding: 12px; } .message-stream { padding: 16px 8px; } .composer { padding: 10px 8px 12px; } .suggestion-grid { grid-template-columns: 1fr; } }
</style>
