// apps/reference/src/components/ui/textarea.tsx
import * as React from "react"
import { cn } from "@/lib/cn"

/** 文本域：hifi .textarea —— 最小高 = control.md × 2.5、border、hover 转 fg-muted、focus 转 primary、invalid 加粗 danger；纵向可拉伸 */
function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        "block min-h-[calc(var(--size-control-md)*2.5)] w-full min-w-0 resize-y rounded-md border border-border-strong bg-surface px-3 py-2 text-role-body text-fg transition-colors duration-(--motion-fast) ease-std placeholder:text-fg-muted hover:not-disabled:not-read-only:border-fg-muted focus-visible:border-primary aria-invalid:border-(length:--border-width-accent) aria-invalid:border-danger aria-invalid:focus-visible:outline-danger read-only:bg-surface-muted read-only:text-fg-muted disabled:cursor-not-allowed disabled:bg-surface-muted disabled:text-fg-muted",
        className,
      )}
      {...props}
    />
  )
}

/** 字数计数：hifi .counter —— 右对齐 caption，超限转 danger */
function CharCounter({ value, max, className, ...props }: React.ComponentProps<"span"> & { value: number; max: number }) {
  return (
    <span
      data-slot="char-counter"
      aria-live="polite"
      className={cn("text-right text-role-caption tabular-nums", value > max ? "text-danger" : "text-fg-muted", className)}
      {...props}
    >
      {value}/{max}
    </span>
  )
}

export { Textarea, CharCounter }

// apps/shadcn-svelte/src/lib/components/ui/textarea/textarea.svelte
<script lang="ts">
  import { cn, type WithElementRef, type WithoutChildren } from "$lib/utils.js"
  import type { HTMLTextareaAttributes } from "svelte/elements"

  let {
    ref = $bindable(null),
    value = $bindable(),
    class: className,
    "data-slot": dataSlot = "textarea",
    ...restProps
  }: WithoutChildren<WithElementRef<HTMLTextareaAttributes>> = $props()
</script>

<textarea
  bind:this={ref}
  data-slot={dataSlot}
  class={cn(
    "flex field-sizing-content min-h-16 w-full rounded-lg border border-input bg-transparent px-2.5 py-2 text-base transition-colors outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:bg-input/50 disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 md:text-sm dark:bg-input/30 dark:disabled:bg-input/80 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40",
    className
  )}
  bind:value
  {...restProps}
></textarea>
