// apps/quasar/src/pages/OrdersPage.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { useQuasar } from "quasar"
import orders from "@ui-gallery/spec/mock/orders.json"
import AppIcon from "../icons/AppIcon.vue"
import PageHeader from "../components/PageHeader.vue"
import { statusColors } from "./shared"

type Order = (typeof orders)[number]
const $q = useQuasar()
const query = ref("")
const status = ref("all")
const channels = ref<string[]>([])
const dateRange = ref<{ from: string; to: string } | null>(null)
const dateLabel = computed(() => dateRange.value ? `${dateRange.value.from} - ${dateRange.value.to}` : "")
const selected = ref<Order | null>(null)
const deleting = ref(false)
const notes = ref("")
const state = new URLSearchParams(window.location.search).get("state") ?? ""
const loading = ref(state === "loading")
const error = ref(state === "error")
const empty = ref(state === "empty")
const visible = ref({ id: true, customer: true, status: true, date: true, amount: true, channel: true })
const pagination = ref({ page: 1, rowsPerPage: 10 })
const channelOptions = ["web", "ios", "android", "api"]
const filtered = computed(() => empty.value ? [] : orders.filter((order) =>
  (!query.value || `${order.id} ${order.customer} ${order.product}`.toLowerCase().includes(query.value.toLowerCase())) &&
  (status.value === "all" || order.status === status.value) &&
  (!channels.value.length || channels.value.includes(order.channel)),
))
const columns = computed(() => [
  { name: "id", label: "订单号", field: "id", sortable: true, align: "left" as const, required: true },
  { name: "customer", label: "客户", field: "customer", sortable: true, align: "left" as const },
  { name: "status", label: "状态", field: "status", sortable: true, align: "left" as const },
  { name: "date", label: "日期", field: "date", sortable: true, align: "left" as const },
  { name: "amount", label: "金额", field: "amount", sortable: true, align: "right" as const },
  { name: "channel", label: "渠道", field: "channel", sortable: true, align: "left" as const },
  { name: "actions", label: "", field: "actions", align: "right" as const },
].filter((column) => column.name === "actions" || visible.value[column.name as keyof typeof visible.value]))

function clearFilters() {
  empty.value = false
  query.value = ""
  status.value = "all"
  channels.value = []
  dateRange.value = null
}

function choose(order: Order) {
  selected.value = order
  notes.value = ""
}

function confirmDelete(order: Order) {
  selected.value = order
  deleting.value = true
}

function remove() {
  deleting.value = false
  selected.value = null
  $q.notify({ type: "positive", message: "订单已删除" })
}

function retry() {
  error.value = false
  loading.value = false
}
</script>

<template>
  <div class="q-gutter-y-lg">
    <PageHeader title="订单管理" description="搜索、筛选并查看全部订单。">
      <template #action><q-btn outline color="primary"><AppIcon name="download" :size="18" class="q-mr-sm" />导出</q-btn></template>
    </PageHeader>
    <q-card bordered>
      <q-card-section class="q-gutter-y-md">
        <div class="row q-col-gutter-sm items-center">
          <div class="col-12 col-sm-4"><q-input v-model="query" dense outlined placeholder="搜索订单号、客户或产品"><template #prepend><AppIcon name="search" :size="16" /></template></q-input></div>
          <div class="col-6 col-sm-2"><q-select v-model="status" dense outlined emit-value map-options :options="[{ label: '全部状态', value: 'all' }, ...Object.keys(statusColors).map((value) => ({ label: value, value }))]" label="状态" /></div>
          <div class="col-6 col-sm-2"><q-input :model-value="dateLabel" dense outlined label="日期范围" readonly><template #append><AppIcon name="calendar" :size="18" /></template><q-popup-proxy cover transition-show="scale" transition-hide="scale"><q-date v-model="dateRange" range><div class="row items-center justify-end q-gutter-sm"><q-btn v-close-popup flat color="primary" label="确定" /></div></q-date></q-popup-proxy></q-input></div>
          <div class="col-12 col-sm-2"><q-select v-model="channels" dense outlined multiple use-chips :options="channelOptions" label="渠道" /></div>
          <div class="col-auto"><q-btn outline round><AppIcon name="sliders" /><q-menu><q-list style="min-width: 180px"><q-item-label header>显示列</q-item-label><q-item v-for="column in columns.filter((item) => item.name !== 'actions' && item.name !== 'id')" :key="column.name"><q-item-section>{{ column.label }}</q-item-section><q-item-section side><q-toggle v-model="visible[column.name as keyof typeof visible]" /></q-item-section></q-item></q-list></q-menu></q-btn></div>
        </div>
        <q-banner v-if="error" class="bg-negative text-white rounded-borders"><template #avatar><AppIcon name="alert-triangle" /></template>订单加载失败，请重试。<template #action><q-btn flat color="white" label="重试" @click="retry" /></template></q-banner>
        <div v-if="!loading && !error && !filtered.length" class="column items-center q-pa-xl text-center">
          <AppIcon name="inbox" :size="48" class="text-grey-6" /><div class="text-h6 q-mt-md">没有找到订单</div><div class="text-body2 text-grey-7 q-mt-sm">调整搜索或筛选条件后重试。</div><q-btn outline color="primary" label="清除筛选" class="q-mt-md" @click="clearFilters" />
        </div>
        <div v-else class="table-scroll">
          <q-table
            v-model:pagination="pagination"
            selection="multiple"
            row-key="id"
            :rows="filtered"
            :columns="columns"
            :loading="loading"
            :grid="$q.screen.lt.sm"
            binary-state-sort
            @row-click="(_, row) => choose(row)"
          >
            <template #loading><q-inner-loading showing><q-spinner color="primary" size="40px" /></q-inner-loading></template>
            <template #item="slot">
              <q-card flat bordered class="q-ma-xs full-width" @click="choose(slot.row)">
                <q-card-section class="row items-center justify-between"><div class="text-weight-medium">{{ slot.row.id }}</div><q-chip dense :color="statusColors[slot.row.status] ?? 'grey'" text-color="white">{{ slot.row.status }}</q-chip></q-card-section>
                <q-card-section class="row justify-between text-body2 text-grey-7"><span>{{ slot.row.customer }}</span><span>¥{{ slot.row.amount.toLocaleString() }}</span></q-card-section>
              </q-card>
            </template>
            <template #body-cell-status="slot"><q-td :props="slot"><q-chip dense :color="statusColors[slot.value] ?? 'grey'" text-color="white">{{ slot.value }}</q-chip></q-td></template>
            <template #body-cell-amount="slot"><q-td :props="slot">¥{{ Number(slot.value).toLocaleString() }}</q-td></template>
            <template #body-cell-actions="slot"><q-td :props="slot"><q-btn flat round @click.stop><AppIcon name="more-horizontal" /><q-menu><q-list><q-item clickable v-close-popup @click="choose(slot.row)"><q-item-section avatar><AppIcon name="edit" /></q-item-section><q-item-section>编辑</q-item-section></q-item><q-item clickable v-close-popup @click="confirmDelete(slot.row)"><q-item-section avatar><AppIcon name="trash" /></q-item-section><q-item-section>删除</q-item-section></q-item></q-list></q-menu></q-btn></q-td></template>
          </q-table>
        </div>
      </q-card-section>
    </q-card>

    <q-drawer :model-value="!!selected" side="right" bordered overlay :width="360" @update:model-value="(open) => { if (!open) selected = null }">
      <div v-if="selected" class="q-pa-md">
        <div class="row items-center justify-between"><div class="text-h6">{{ selected.id }}</div><q-btn flat round @click="selected = null"><AppIcon name="x" /></q-btn></div>
        <q-list separator class="q-mt-md">
          <q-item><q-item-section><q-item-label caption>客户</q-item-label><q-item-label>{{ selected.customer }}</q-item-label></q-item-section></q-item>
          <q-item><q-item-section><q-item-label caption>邮箱</q-item-label><q-item-label>{{ selected.email }}</q-item-label></q-item-section></q-item>
          <q-item><q-item-section><q-item-label caption>产品</q-item-label><q-item-label>{{ selected.product }}</q-item-label></q-item-section></q-item>
          <q-item><q-item-section><q-item-label caption>金额</q-item-label><q-item-label>¥{{ selected.amount.toLocaleString() }}</q-item-label></q-item-section></q-item>
          <q-item><q-item-section><q-item-label caption>日期</q-item-label><q-item-label>{{ selected.date }}</q-item-label></q-item-section></q-item>
        </q-list>
        <q-tabs v-model="notes" dense class="q-mt-lg"><q-tab name="" label="详情" /><q-tab name="notes" label="备注" /></q-tabs>
        <q-input v-if="notes === 'notes'" v-model="notes" type="textarea" outlined label="备注" class="q-mt-md" />
        <q-btn color="negative" outline class="full-width q-mt-lg" label="删除订单" @click="deleting = true" />
      </div>
    </q-drawer>
    <q-dialog v-model="deleting"><q-card><q-card-section class="text-h6">确认删除订单？</q-card-section><q-card-section>此操作无法撤销。</q-card-section><q-card-actions align="right"><q-btn flat label="取消" v-close-popup /><q-btn color="negative" label="确认删除" @click="remove" /></q-card-actions></q-card></q-dialog>
  </div>
</template>

// apps/angular-material/src/app/pages/orders.page.ts
import { SelectionModel } from '@angular/cdk/collections';
import { AfterViewInit, Component, ViewChild, inject } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatPaginator } from '@angular/material/paginator';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import orders from '@ui-gallery/spec/mock/orders.json';
import { SHARED_IMPORTS } from '../shared/material';

type Order = (typeof orders)[number];
type OrderStatus = Order['status'];
type OrderColumnKey = 'id' | 'customer' | 'product' | 'amount' | 'status' | 'channel';

@Component({
  selector: 'app-delete-order-dialog',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <h2 mat-dialog-title>删除订单</h2>
    <mat-dialog-content>
      <p>确认删除订单 <strong>{{ order.id }}</strong> 吗？此操作无法撤销。</p>
      <mat-form-field appearance="outline" class="full">
        <mat-label>输入 DELETE 确认</mat-label>
        <input matInput [formControl]="confirmation" autocomplete="off">
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-flat-button color="warn" [disabled]="confirmation.value !== 'DELETE'" (click)="confirm()">删除订单</button>
    </mat-dialog-actions>
  `,
})
export class DeleteOrderDialog {
  readonly confirmation = new FormControl('');
  readonly order = inject<{ order: Order }>(MAT_DIALOG_DATA).order;
  private readonly dialogRef = inject(MatDialogRef<DeleteOrderDialog>);

  confirm(): void {
    this.dialogRef.close(true);
  }
}

@Component({
  selector: 'app-orders',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="page orders-page">
      <header class="page-header">
        <div><p class="eyebrow">OPERATIONS</p><h1>订单</h1><p class="muted">搜索、筛选和管理所有订单。</p></div>
        <div class="demo-row"><button mat-stroked-button><mat-icon svgIcon="download"></mat-icon>导出</button><button mat-flat-button color="primary"><mat-icon svgIcon="plus"></mat-icon>新建订单</button></div>
      </header>

      <mat-card class="filter-card">
        <mat-card-content class="filters">
          <mat-form-field appearance="outline" class="filter-search"><mat-label>搜索订单</mat-label><mat-icon matPrefix svgIcon="search"></mat-icon><input matInput [formControl]="search" placeholder="订单号、客户或邮箱"></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>状态</mat-label><mat-select [formControl]="status"><mat-option value="all">全部状态</mat-option>@for (item of statusOptions; track item.value) {<mat-option [value]="item.value">{{ item.label }}</mat-option>}</mat-select></mat-form-field>
          <mat-form-field appearance="outline" class="date-field"><mat-label>日期范围</mat-label><mat-date-range-input [rangePicker]="picker"><input matStartDate [formControl]="dateStart" placeholder="开始日期"><input matEndDate [formControl]="dateEnd" placeholder="结束日期"></mat-date-range-input><mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle><mat-date-range-picker #picker></mat-date-range-picker></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>渠道</mat-label><mat-select [formControl]="channels" multiple><mat-select-trigger>{{ channelSummary() }}</mat-select-trigger>@for (channel of channelOptions; track channel) {<mat-option [value]="channel">{{ channel }}</mat-option>}</mat-select></mat-form-field>
          <button mat-icon-button [matMenuTriggerFor]="columnsMenu" matTooltip="显示列" aria-label="显示列"><mat-icon svgIcon="tune"></mat-icon></button>
          <mat-menu #columnsMenu="matMenu"><div class="menu-title">显示列</div>@for (column of allColumns; track column.key) {<button mat-menu-item (click)="$event.stopPropagation()"><mat-checkbox [checked]="visibleColumns.includes(column.key)" (click)="$event.stopPropagation()" (change)="toggleColumn(column.key)">{{ column.label }}</mat-checkbox></button>}</mat-menu>
        </mat-card-content>
      </mat-card>

      @if (state === 'loading') {
        <mat-card class="state-card"><mat-progress-spinner mode="indeterminate" diameter="44"></mat-progress-spinner><h2>正在加载订单</h2><p class="muted">请稍候，订单数据马上就绪。</p></mat-card>
      } @else if (state === 'error') {
        <mat-card class="state-card error-state"><mat-icon svgIcon="error"></mat-icon><h2>订单加载失败</h2><p class="muted">暂时无法获取订单数据。</p><button mat-stroked-button (click)="retry()">重试</button></mat-card>
      } @else if (filteredRows.length === 0 || state === 'empty') {
        <mat-card class="state-card"><mat-icon svgIcon="inbox"></mat-icon><h2>没有找到订单</h2><p class="muted">试试调整筛选条件，或创建一笔新订单。</p><button mat-flat-button color="primary" (click)="resetFilters()">清除筛选</button></mat-card>
      } @else {
        <mat-card class="table-card">
          <mat-card-content class="table-wrap">
            <table mat-table [dataSource]="dataSource" matSort>
              <ng-container matColumnDef="select"><th mat-header-cell *matHeaderCellDef><mat-checkbox (change)="$event ? toggleAllRows() : null" [checked]="selection.hasValue() && isAllSelected()" [indeterminate]="selection.hasValue() && !isAllSelected()" aria-label="全选订单"></mat-checkbox></th><td mat-cell *matCellDef="let row"><mat-checkbox (click)="$event.stopPropagation()" (change)="$event ? selection.toggle(row) : null" [checked]="selection.isSelected(row)" aria-label="选择订单"></mat-checkbox></td></ng-container>
              <ng-container matColumnDef="id"><th mat-header-cell *matHeaderCellDef mat-sort-header>订单号</th><td mat-cell *matCellDef="let row"><span class="cell-primary">{{ row.id }}</span><small class="sub-info">{{ row.date }}</small></td></ng-container>
              <ng-container matColumnDef="customer"><th mat-header-cell *matHeaderCellDef mat-sort-header>客户</th><td mat-cell *matCellDef="let row"><div class="row"><span class="avatar">{{ row.customer.slice(0, 1) }}</span><span><span class="cell-primary">{{ row.customer }}</span><small class="sub-info">{{ row.email }}</small></span></div></td></ng-container>
              <ng-container matColumnDef="product"><th mat-header-cell *matHeaderCellDef>产品</th><td mat-cell *matCellDef="let row">{{ row.product }}</td></ng-container>
              <ng-container matColumnDef="amount"><th mat-header-cell *matHeaderCellDef mat-sort-header>金额</th><td mat-cell *matCellDef="let row" class="amount">¥{{ row.amount.toLocaleString() }}</td></ng-container>
              <ng-container matColumnDef="status"><th mat-header-cell *matHeaderCellDef>状态</th><td mat-cell *matCellDef="let row"><span class="status" [class.status-success]="row.status === 'paid'">{{ statusLabel(row.status) }}</span></td></ng-container>
              <ng-container matColumnDef="channel"><th mat-header-cell *matHeaderCellDef>渠道</th><td mat-cell *matCellDef="let row">{{ row.channel }}</td></ng-container>
              <ng-container matColumnDef="actions"><th mat-header-cell *matHeaderCellDef></th><td mat-cell *matCellDef="let row"><button mat-icon-button [matMenuTriggerFor]="rowMenu" (click)="$event.stopPropagation()" aria-label="订单操作"><mat-icon svgIcon="more-vertical"></mat-icon></button><mat-menu #rowMenu="matMenu"><button mat-menu-item (click)="edit(row)"><mat-icon svgIcon="edit"></mat-icon>编辑</button><button mat-menu-item (click)="remove(row)"><mat-icon svgIcon="trash"></mat-icon>删除</button></mat-menu></td></ng-container>
              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr><tr mat-row *matRowDef="let row; columns: displayedColumns" (click)="openDetails(row)"></tr>
            </table>
          </mat-card-content>
          <mat-card-actions class="table-footer"><span class="muted">{{ selection.selected.length ? '已选择 ' + selection.selected.length + ' 项' : '共 ' + filteredRows.length + ' 条订单' }}</span><mat-paginator [pageSizeOptions]="[10, 25, 50]" showFirstLastButtons></mat-paginator></mat-card-actions>
        </mat-card>
      }

      <mat-sidenav-container class="details-container">
        <mat-sidenav #drawer position="end" mode="over" [opened]="!!selectedOrder" (closed)="selectedOrder = undefined" class="details-drawer">
          @if (selectedOrder; as order) {
            <div class="drawer-header"><h2>{{ order.id }}</h2><button mat-icon-button (click)="drawer.close()"><mat-icon svgIcon="close"></mat-icon></button></div>
            <div class="stack drawer-content"><span class="status status-success">{{ statusLabel(order.status) }}</span><mat-list><mat-list-item><span matListItemTitle>客户</span><span matListItemLine>{{ order.customer }} · {{ order.email }}</span></mat-list-item><mat-list-item><span matListItemTitle>产品</span><span matListItemLine>{{ order.product }}</span></mat-list-item><mat-list-item><span matListItemTitle>金额</span><span matListItemLine>¥{{ order.amount.toLocaleString() }}</span></mat-list-item><mat-list-item><span matListItemTitle>日期 / 渠道</span><span matListItemLine>{{ order.date }} · {{ order.channel }}</span></mat-list-item></mat-list><mat-tab-group><mat-tab label="详情"><p class="muted">订单已通过风控检查，发票将于付款完成后发送。</p></mat-tab><mat-tab label="备注"><mat-form-field appearance="outline" class="full"><mat-label>添加备注</mat-label><textarea matInput rows="4"></textarea></mat-form-field></mat-tab></mat-tab-group></div>
          }
        </mat-sidenav>
        <mat-sidenav-content></mat-sidenav-content>
      </mat-sidenav-container>
    </main>
  `,
})
export class OrdersPage implements AfterViewInit {
  @ViewChild(MatPaginator) paginator?: MatPaginator;
  @ViewChild(MatSort) sort?: MatSort;

  readonly dataSource = new MatTableDataSource<Order>(orders);
  readonly selection = new SelectionModel<Order>(true, []);
  readonly search = new FormControl('');
  readonly status = new FormControl('all');
  readonly channels = new FormControl<string[]>([]);
  readonly dateStart = new FormControl<Date | null>(null);
  readonly dateEnd = new FormControl<Date | null>(null);
  readonly statusOptions: ReadonlyArray<{ value: OrderStatus; label: string }> = [
    { value: 'paid', label: '已支付' }, { value: 'pending', label: '待处理' }, { value: 'refunded', label: '已退款' },
    { value: 'failed', label: '失败' }, { value: 'shipped', label: '已发货' },
  ];
  readonly channelOptions = ['web', 'ios', 'android', 'api'];
  readonly allColumns = [
    { key: 'id', label: '订单号' }, { key: 'customer', label: '客户' }, { key: 'product', label: '产品' },
    { key: 'amount', label: '金额' }, { key: 'status', label: '状态' }, { key: 'channel', label: '渠道' },
  ] as const;
  visibleColumns: OrderColumnKey[] = this.allColumns.map((column) => column.key);
  selectedOrder?: Order;
  readonly state = new URLSearchParams(window.location.search).get('state') as 'empty' | 'loading' | 'error' | null;
  private readonly dialog = inject(MatDialog);
  private readonly snackBar = inject(MatSnackBar);

  constructor() {
    this.search.valueChanges.subscribe(() => this.applyFilters());
    this.status.valueChanges.subscribe(() => this.applyFilters());
    this.channels.valueChanges.subscribe(() => this.applyFilters());
    this.dateStart.valueChanges.subscribe(() => this.applyFilters());
    this.dateEnd.valueChanges.subscribe(() => this.applyFilters());
    this.applyFilters();
  }

  get filteredRows(): Order[] {
    return this.dataSource.filteredData;
  }

  get displayedColumns(): string[] {
    return ['select', ...this.visibleColumns, 'actions'];
  }

  ngAfterViewInit(): void {
    this.dataSource.paginator = this.paginator ?? null;
    this.dataSource.sort = this.sort ?? null;
  }

  isAllSelected(): boolean {
    const rows = this.dataSource.filteredData;
    return rows.length > 0 && rows.every((row) => this.selection.isSelected(row));
  }

  toggleAllRows(): void {
    if (this.isAllSelected()) {
      this.selection.clear();
    } else {
      this.dataSource.filteredData.forEach((row) => this.selection.select(row));
    }
  }

  toggleColumn(column: OrderColumnKey): void {
    this.visibleColumns = this.visibleColumns.includes(column)
      ? this.visibleColumns.filter((item) => item !== column)
      : [...this.visibleColumns, column];
  }

  channelSummary(): string {
    const values = this.channels.value ?? [];
    return values.length ? values.join('、') : '全部渠道';
  }

  statusLabel(status: string): string {
    return { paid: '已支付', pending: '待处理', refunded: '已退款', failed: '失败', shipped: '已发货' }[status] ?? status;
  }

  openDetails(order: Order): void {
    this.selectedOrder = order;
  }

  edit(order: Order): void {
    this.snackBar.open(`已进入 ${order.id} 编辑模式`, '知道了', { duration: 2400 });
  }

  remove(order: Order): void {
    const ref = this.dialog.open(DeleteOrderDialog, { data: { order }, width: '420px' });
    ref.afterClosed().subscribe((confirmed: boolean | undefined) => {
      if (confirmed) {
        this.snackBar.open(`订单 ${order.id} 已删除`, '撤销', { duration: 3200 });
      }
    });
  }

  retry(): void {
    window.location.reload();
  }

  resetFilters(): void {
    this.search.setValue('');
    this.status.setValue('all');
    this.channels.setValue([]);
    this.dateStart.setValue(null);
    this.dateEnd.setValue(null);
  }

  private applyFilters(): void {
    const query = (this.search.value ?? '').trim().toLowerCase();
    const status = this.status.value ?? 'all';
    const channels = this.channels.value ?? [];
    const start = this.dateStart.value?.toISOString().slice(0, 10);
    const end = this.dateEnd.value?.toISOString().slice(0, 10);
    this.dataSource.data = orders.filter((order) => {
      const matchesText = !query || [order.id, order.customer, order.email, order.product].some((value) => value.toLowerCase().includes(query));
      const matchesStatus = status === 'all' || order.status === status;
      const matchesChannel = !channels.length || channels.includes(order.channel);
      const matchesDate = (!start || order.date >= start) && (!end || order.date <= end);
      return matchesText && matchesStatus && matchesChannel && matchesDate;
    });
    this.selection.clear();
  }
}
