// apps/quasar/src/pages/SettingsPage.vue
<script setup lang="ts">
import { ref } from "vue"
import { useQuasar } from "quasar"
import team from "@ui-gallery/spec/mock/team.json"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import AppIcon from "../icons/AppIcon.vue"
import PageHeader from "../components/PageHeader.vue"
import { statusColors } from "./shared"

const $q = useQuasar()
const tab = ref("profile")
const notificationMode = ref("mail")
const name = ref(team[0]?.name ?? "")
const bio = ref("Acme Console 管理员")
const language = ref("简体中文")
const timezone = ref("Asia/Shanghai")
const twoStep = ref(true)
const invite = ref("")
const deleteDialog = ref(false)
const deleteText = ref("")
const teamRows = team.map((member) => ({ ...member }))
const currentPassword = ref("")
const newPassword = ref("")
const confirmPassword = ref("")
const roles = ["owner", "admin", "member", "viewer"]
const columns = [
  { name: "name", label: "成员", field: "name", align: "left" as const },
  { name: "role", label: "角色", field: "role", align: "left" as const },
  { name: "lastActive", label: "最近活跃", field: "lastActive", align: "left" as const },
  { name: "actions", label: "", field: "actions", align: "right" as const },
]
const invoiceColumns = [
  { name: "id", label: "发票", field: "id", align: "left" as const },
  { name: "date", label: "日期", field: "date", align: "left" as const },
  { name: "amount", label: "金额", field: "amount", align: "right" as const },
  { name: "status", label: "状态", field: "status", align: "left" as const },
]

function inviteMember() {
  if (!invite.value) return
  $q.notify({ type: "positive", message: "邀请已发送" })
  invite.value = ""
}
</script>

<template>
  <div class="q-gutter-y-lg">
    <PageHeader title="设置" description="管理个人资料、团队与账单。" />
    <div class="row q-col-gutter-lg items-start">
      <div class="col-12 col-md-3">
        <q-tabs v-model="tab" :vertical="$q.screen.gt.sm" :scrollable="$q.screen.lt.md" outside-arrows mobile-arrows dense align="left" active-color="primary" indicator-color="primary" class="settings-tabs text-grey-8">
          <q-tab name="profile" label="个人资料" />
          <q-tab name="security" label="账号安全" />
          <q-tab name="notifications" label="通知" />
          <q-tab name="team" label="团队" />
          <q-tab name="billing" label="计费" />
        </q-tabs>
      </div>
      <div class="col-12 col-md-9">
        <q-tab-panels v-model="tab" animated>
          <q-tab-panel name="profile" class="q-pa-none">
            <q-card bordered><q-card-section><div class="text-h6">个人资料</div></q-card-section><q-card-section class="q-gutter-md">
              <div class="row items-center q-gutter-md"><q-avatar size="72px" color="primary" text-color="white">林</q-avatar><q-btn outline label="上传头像" /></div>
              <q-input v-model="name" label="姓名" />
              <q-input v-model="bio" label="个人简介" type="textarea" />
              <div class="row q-col-gutter-md"><div class="col-12 col-sm-6"><q-select v-model="language" label="语言" :options="['简体中文', 'English', '日本語']" /></div><div class="col-12 col-sm-6"><q-select v-model="timezone" label="时区" use-input :options="['Asia/Shanghai', 'Asia/Tokyo', 'Europe/London']" /></div></div>
              <q-btn color="primary" label="保存更改" />
            </q-card-section></q-card>
          </q-tab-panel>

          <q-tab-panel name="security" class="q-pa-none q-gutter-md">
            <q-card bordered><q-card-section><div class="text-h6">账号安全</div></q-card-section><q-card-section class="q-gutter-md">
              <q-input v-model="currentPassword" label="当前密码" type="password" />
              <q-input v-model="newPassword" label="新密码" type="password" />
              <q-input v-model="confirmPassword" label="确认新密码" type="password" />
              <q-btn color="primary" label="更新密码" />
              <q-separator />
              <q-toggle v-model="twoStep" label="启用两步验证" />
              <div class="qr-placeholder">QR</div>
            </q-card-section></q-card>
            <q-card bordered><q-card-section><div class="text-h6">活跃会话</div></q-card-section><q-list separator><q-item v-for="session in sessions" :key="session.device"><q-item-section avatar><AppIcon name="globe" /></q-item-section><q-item-section><q-item-label>{{ session.device }}</q-item-label><q-item-label caption>{{ session.location }} · {{ session.time }}</q-item-label></q-item-section><q-item-section side><q-badge v-if="session.current" color="positive">当前</q-badge><q-btn v-else flat dense label="注销" /></q-item-section></q-item></q-list></q-card>
          </q-tab-panel>

          <q-tab-panel name="notifications" class="q-pa-none">
            <q-card bordered><q-card-section><div class="text-h6">通知</div></q-card-section><q-card-section class="q-gutter-y-md">
              <div v-for="(label, index) in ['订单状态更新', '团队活动提醒', '每周业务报告', '产品更新']" :key="label" class="row items-center justify-between"><div><div>{{ label }}</div><div class="text-caption text-grey-7">接收相关消息通知</div></div><q-toggle :model-value="index !== 3" /></div>
              <q-separator /><q-btn-toggle spread v-model="notificationMode" toggle-color="primary" :options="[{ label: '邮件', value: 'mail' }, { label: '推送', value: 'push' }, { label: '站内', value: 'inbox' }]" />
            </q-card-section></q-card>
          </q-tab-panel>

          <q-tab-panel name="team" class="q-pa-none q-gutter-md">
            <q-card bordered><q-card-section><div class="text-h6">团队成员</div></q-card-section><div class="table-scroll"><q-table flat :rows="teamRows" :columns="columns" row-key="email">
              <template #body-cell-name="slot"><q-td :props="slot"><div class="row items-center q-gutter-sm"><q-avatar size="30px" color="primary" text-color="white">{{ String(slot.value).slice(0, 1) }}</q-avatar><div><div>{{ slot.value }}</div><div class="text-caption text-grey-7">{{ slot.row.email }}</div></div></div></q-td></template>
              <template #body-cell-role="slot"><q-td :props="slot"><q-select v-model="slot.row.role" dense borderless :options="roles" /></q-td></template>
              <template #body-cell-actions="slot"><q-td :props="slot"><q-btn flat round dense><AppIcon name="trash" /></q-btn></q-td></template>
            </q-table></div><q-card-section><div class="row q-col-gutter-sm"><div class="col"><q-input v-model="invite" dense outlined label="成员邮箱" /></div><div class="col-auto"><q-btn color="primary" label="邀请" @click="inviteMember" /></div></div></q-card-section></q-card>
          </q-tab-panel>

          <q-tab-panel name="billing" class="q-pa-none q-gutter-md">
            <q-card bordered><q-card-section><div class="text-h6">当前方案</div><div class="text-h4 q-mt-sm">Pro</div><div class="text-body2 text-grey-7">适合成长中的团队</div></q-card-section></q-card>
            <div class="row q-col-gutter-md"><div v-for="plan in plans" :key="plan.name" class="col-12 col-md-4"><q-card bordered class="full-height"><q-card-section><div class="row items-center justify-between"><div class="text-h6">{{ plan.name }}</div><q-badge v-if="plan.recommended" color="primary">推荐</q-badge></div><div class="text-h4 q-mt-md">{{ plan.price === null ? "联系我们" : `¥${plan.price}` }}</div><q-list dense class="q-mt-md"><q-item v-for="feature in plan.features" :key="feature"><q-item-section avatar><AppIcon name="check-circle" color="positive" /></q-item-section><q-item-section>{{ feature }}</q-item-section></q-item></q-list><q-btn outline color="primary" class="full-width q-mt-md" label="选择方案" /></q-card-section></q-card></div></div>
            <q-card bordered><q-card-section><div class="text-h6">发票</div></q-card-section><div class="table-scroll"><q-table flat :rows="invoices" :columns="invoiceColumns" row-key="id"><template #body-cell-amount="slot"><q-td :props="slot">¥{{ slot.value }}</q-td></template><template #body-cell-status="slot"><q-td :props="slot"><q-chip dense :color="statusColors[slot.value] ?? 'grey'" text-color="white">{{ slot.value }}</q-chip></q-td></template></q-table></div></q-card>
          </q-tab-panel>
        </q-tab-panels>
        <q-card bordered class="border-negative q-mt-lg"><q-card-section><div class="text-h6 text-negative">危险区</div><div class="text-body2 text-grey-7 q-mt-sm">删除账号后所有数据将无法恢复。</div><q-btn outline color="negative" label="删除账号" class="q-mt-md" @click="deleteDialog = true" /></q-card-section></q-card>
      </div>
    </div>
    <q-dialog v-model="deleteDialog"><q-card style="width: min(100%, 420px)"><q-card-section><div class="text-h6">确认删除账号</div><div class="text-body2 q-mt-sm">请输入 DELETE 以确认。</div><q-input v-model="deleteText" class="q-mt-md" /></q-card-section><q-card-actions align="right"><q-btn flat label="取消" v-close-popup /><q-btn color="negative" label="确认删除" :disable="deleteText !== 'DELETE'" /></q-card-actions></q-card></q-dialog>
  </div>
</template>

// apps/angular-material/src/app/pages/settings.page.ts
import { BreakpointObserver } from '@angular/cdk/layout';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import invoices from '@ui-gallery/spec/mock/invoices.json';
import plans from '@ui-gallery/spec/mock/plans.json';
import sessions from '@ui-gallery/spec/mock/sessions.json';
import team from '@ui-gallery/spec/mock/team.json';
import { SHARED_IMPORTS } from '../shared/material';

@Component({
  selector: 'app-delete-account-dialog',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <h2 mat-dialog-title>删除账户</h2>
    <mat-dialog-content>
      <p>删除账户会永久移除团队、订单和所有配置，无法恢复。</p>
      <mat-form-field appearance="outline" class="full">
        <mat-label>输入 DELETE 确认</mat-label>
        <input matInput [formControl]="confirmation" autocomplete="off">
        @if (confirmation.value && confirmation.value !== 'DELETE') {<mat-error>请输入大写 DELETE</mat-error>}
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-flat-button color="warn" [disabled]="confirmation.value !== 'DELETE'" (click)="confirm()">永久删除</button>
    </mat-dialog-actions>
  `,
})
export class DeleteAccountDialog {
  readonly confirmation = inject(FormBuilder).nonNullable.control('');
  private readonly dialogRef = inject(MatDialogRef<DeleteAccountDialog>);
  readonly accountName = inject<{ accountName: string }>(MAT_DIALOG_DATA).accountName;

  confirm(): void {
    this.dialogRef.close(true);
  }
}

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="page settings-page">
      <header class="page-header"><div><p class="eyebrow">WORKSPACE</p><h1>设置</h1><p class="muted">管理个人资料、团队与订阅偏好。</p></div><button mat-flat-button color="primary" (click)="save()">保存更改</button></header>
      <div class="settings-layout">
        <nav class="settings-nav" aria-label="设置导航">
          @for (item of tabs; track item.key) {<button mat-button [class.active-setting]="activeTab() === item.key" (click)="activeTab.set(item.key)"><mat-icon [svgIcon]="item.icon"></mat-icon>{{ item.label }}</button>}
        </nav>
        <section class="settings-content">
          @if (mobile()) {
            <mat-tab-group animationDuration="0ms" [selectedIndex]="tabIndex()" (selectedIndexChange)="activeTab.set(tabs[$event].key)">
              @for (item of tabs; track item.key) {<mat-tab [label]="item.label"></mat-tab>}
            </mat-tab-group>
          }
          @switch (activeTab()) {
            @case ('profile') {
              <mat-card><mat-card-header><mat-card-title>个人资料</mat-card-title><mat-card-subtitle>这些信息会显示在团队活动和邀请中。</mat-card-subtitle></mat-card-header><mat-card-content>
                <div class="profile-banner"><span class="avatar avatar-large">林</span><div><h3>林晓</h3><p class="muted">管理员 · Acme Console</p></div><button mat-stroked-button>更换头像</button></div>
                <form class="form-grid" [formGroup]="profileForm"><mat-form-field appearance="outline"><mat-label>姓名</mat-label><input matInput formControlName="name"><mat-error>请输入姓名</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>邮箱</mat-label><input matInput formControlName="email" readonly></mat-form-field><mat-form-field appearance="outline"><mat-label>语言</mat-label><mat-select formControlName="language"><mat-option value="zh">简体中文</mat-option><mat-option value="en">English</mat-option></mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>时区</mat-label><input matInput formControlName="timezone" [matAutocomplete]="timezoneOptions"><mat-autocomplete #timezoneOptions="matAutocomplete"><mat-option value="Asia/Shanghai">Asia/Shanghai</mat-option><mat-option value="America/Los_Angeles">America/Los_Angeles</mat-option></mat-autocomplete></mat-form-field><mat-form-field appearance="outline" class="full-span"><mat-label>个人简介</mat-label><textarea matInput formControlName="bio" rows="4"></textarea><mat-hint align="end">{{ profileForm.controls.bio.value.length }}/160</mat-hint></mat-form-field></form>
              </mat-card-content></mat-card>
            }
            @case ('security') {
              <mat-card><mat-card-header><mat-card-title>账号安全</mat-card-title><mat-card-subtitle>定期更新密码并检查活跃设备。</mat-card-subtitle></mat-card-header><mat-card-content class="stack">
                <form class="form-grid" [formGroup]="passwordForm"><mat-form-field appearance="outline"><mat-label>当前密码</mat-label><input matInput type="password" formControlName="current"><mat-error>请输入当前密码</mat-error></mat-form-field><span></span><mat-form-field appearance="outline"><mat-label>新密码</mat-label><input matInput type="password" formControlName="next"><mat-hint>至少 8 个字符</mat-hint><mat-error>请输入至少 8 个字符</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>确认新密码</mat-label><input matInput type="password" formControlName="confirm"><mat-error>两次密码不一致</mat-error></mat-form-field></form>
                <mat-divider></mat-divider><div class="spread"><div><h3>两步验证</h3><p class="muted">登录时要求输入验证码，保护账户安全。</p></div><mat-slide-toggle checked></mat-slide-toggle></div><div class="qr-placeholder"><mat-icon svgIcon="shield"></mat-icon><span>扫码绑定验证器</span></div><mat-divider></mat-divider><h3>活跃会话</h3><mat-list>@for (session of sessions; track session.device) {<mat-list-item><mat-icon matListItemIcon [svgIcon]="session.current ? 'laptop' : 'phone'"></mat-icon><span matListItemTitle>{{ session.device }} @if (session.current) {<span class="chip">当前设备</span>}</span><span matListItemLine>{{ session.location }} · {{ session.time }}</span><button mat-icon-button matListItemMeta matTooltip="注销会话"><mat-icon svgIcon="log-out"></mat-icon></button></mat-list-item>}</mat-list>
              </mat-card-content></mat-card>
            }
            @case ('notifications') {
              <mat-card><mat-card-header><mat-card-title>通知偏好</mat-card-title><mat-card-subtitle>选择希望接收哪些工作台通知。</mat-card-subtitle></mat-card-header><mat-card-content class="stack"><mat-button-toggle-group value="all" aria-label="通知渠道"><mat-button-toggle value="all">全部</mat-button-toggle><mat-button-toggle value="email">邮件</mat-button-toggle><mat-button-toggle value="push">推送</mat-button-toggle><mat-button-toggle value="in-app">站内</mat-button-toggle></mat-button-toggle-group>@for (item of notificationGroups; track item.title) {<div class="spread setting-row"><div><b>{{ item.title }}</b><p class="muted">{{ item.description }}</p></div><mat-slide-toggle [checked]="item.enabled"></mat-slide-toggle></div>}</mat-card-content></mat-card>
            }
            @case ('team') {
              <mat-card><mat-card-header><mat-card-title>团队成员</mat-card-title><mat-card-subtitle>管理成员角色和访问权限。</mat-card-subtitle></mat-card-header><mat-card-content><div class="invite-row"><mat-form-field appearance="outline" class="full"><mat-label>邀请成员邮箱</mat-label><input matInput placeholder="teammate@example.com"></mat-form-field><button mat-flat-button color="primary">发送邀请</button></div><div class="table-wrap"><table mat-table [dataSource]="team"><ng-container matColumnDef="member"><th mat-header-cell *matHeaderCellDef>成员</th><td mat-cell *matCellDef="let member"><div class="row"><span class="avatar">{{ member.name.slice(0, 1) }}</span><span>{{ member.name }}<small class="muted">{{ member.email }}</small></span></div></td></ng-container><ng-container matColumnDef="role"><th mat-header-cell *matHeaderCellDef>角色</th><td mat-cell *matCellDef="let member"><mat-select [value]="member.role"><mat-option value="owner">Owner</mat-option><mat-option value="admin">Admin</mat-option><mat-option value="member">Member</mat-option><mat-option value="viewer">Viewer</mat-option></mat-select></td></ng-container><ng-container matColumnDef="active"><th mat-header-cell *matHeaderCellDef>最近活跃</th><td mat-cell *matCellDef="let member">{{ member.lastActive }}</td></ng-container><tr mat-header-row *matHeaderRowDef="teamColumns"></tr><tr mat-row *matRowDef="let row; columns: teamColumns"></tr></table></div></mat-card-content></mat-card>
            }
            @case ('billing') {
              <div class="stack"><mat-card><mat-card-header><mat-card-title>当前计划</mat-card-title><mat-card-subtitle>Pro · 下次扣款 2026 年 10 月 1 日</mat-card-subtitle></mat-card-header><mat-card-content><div class="billing-current"><div><span class="price">¥99<span class="muted">/月</span></span><p class="muted">已使用 8 / 10 个席位</p></div><button mat-stroked-button>管理订阅</button></div></mat-card-content></mat-card><div class="grid grid-3">@for (plan of plans; track plan.name) {<mat-card [class.recommended-plan]="plan.recommended"><mat-card-content class="card-pad"><div class="spread"><h3>{{ plan.name }}</h3>@if (plan.recommended) {<span class="chip">推荐</span>}</div><div class="price">{{ plan.price === null ? '定制' : plan.price === 0 ? '免费' : '¥' + plan.price }}</div>@for (feature of plan.features; track feature) {<p class="muted">✓ {{ feature }}</p>}<button mat-stroked-button class="full">选择方案</button></mat-card-content></mat-card>}</div><mat-card><mat-card-header><mat-card-title>发票</mat-card-title></mat-card-header><mat-card-content class="table-wrap"><table mat-table [dataSource]="invoices"><ng-container matColumnDef="id"><th mat-header-cell *matHeaderCellDef>编号</th><td mat-cell *matCellDef="let invoice">{{ invoice.id }}</td></ng-container><ng-container matColumnDef="date"><th mat-header-cell *matHeaderCellDef>日期</th><td mat-cell *matCellDef="let invoice">{{ invoice.date }}</td></ng-container><ng-container matColumnDef="amount"><th mat-header-cell *matHeaderCellDef>金额</th><td mat-cell *matCellDef="let invoice">¥{{ invoice.amount }}</td></ng-container><tr mat-header-row *matHeaderRowDef="invoiceColumns"></tr><tr mat-row *matRowDef="let row; columns: invoiceColumns"></tr></table></mat-card-content></mat-card></div>
            }
          }
          <mat-card appearance="outlined" class="danger-zone"><mat-card-header><mat-card-title>危险区域</mat-card-title><mat-card-subtitle>删除账户和工作区数据，操作不可撤销。</mat-card-subtitle></mat-card-header><mat-card-content><div class="spread"><div><b>删除 Acme Console 账户</b><p class="muted">所有订单、成员和配置都会被永久移除。</p></div><button mat-stroked-button color="warn" (click)="deleteAccount()">删除账户</button></div></mat-card-content></mat-card>
        </section>
      </div>
    </main>
  `,
})
export class SettingsPage {
  readonly tabs = [
    { key: 'profile', label: '个人资料', icon: 'user' },
    { key: 'security', label: '账号安全', icon: 'shield' },
    { key: 'notifications', label: '通知', icon: 'bell' },
    { key: 'team', label: '团队', icon: 'users' },
    { key: 'billing', label: '计费', icon: 'credit-card' },
  ] as const;
  readonly activeTab = signal<(typeof this.tabs)[number]['key']>('profile');
  readonly mobile = signal(false);
  readonly profileForm = inject(FormBuilder).nonNullable.group({
    name: ['', Validators.required],
    email: [{ value: 'lin.xiao@acme.dev', disabled: true }],
    language: ['zh'],
    timezone: ['Asia/Shanghai'],
    bio: ['负责 Acme Console 的产品与增长。'],
  });
  readonly passwordForm = inject(FormBuilder).nonNullable.group({
    current: ['', Validators.required],
    next: ['', [Validators.required, Validators.minLength(8)]],
    confirm: ['', Validators.required],
  });
  readonly sessions = sessions;
  readonly team = team;
  readonly plans = plans;
  readonly invoices = invoices;
  readonly teamColumns = ['member', 'role', 'active'];
  readonly invoiceColumns = ['id', 'date', 'amount'];
  readonly notificationGroups = [
    { title: '订单状态更新', description: '支付、退款和发货状态变化', enabled: true },
    { title: '团队活动', description: '成员评论、提及和权限变化', enabled: true },
    { title: '产品更新', description: '新功能和维护通知', enabled: false },
  ];
  private readonly breakpoint = inject(BreakpointObserver);
  private readonly dialog = inject(MatDialog);
  private readonly snackBar = inject(MatSnackBar);

  constructor() {
    this.breakpoint.observe('(max-width: 959px)').subscribe((state) => this.mobile.set(state.matches));
  }

  tabIndex(): number {
    return this.tabs.findIndex((tab) => tab.key === this.activeTab());
  }

  save(): void {
    this.snackBar.open('设置已保存', '知道了', { duration: 2400 });
  }

  deleteAccount(): void {
    const ref = this.dialog.open(DeleteAccountDialog, { width: '440px', data: { accountName: 'Acme Console' } });
    ref.afterClosed().subscribe((confirmed: boolean | undefined) => {
      if (confirmed) {
        this.snackBar.open('账户删除请求已提交', '知道了', { duration: 3200 });
      }
    });
  }
}
