// apps/vuetify/src/pages/SettingsPage.vue
<script setup lang="ts">
import { ref } from "vue"
import { useRoute } from "vue-router"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import Icon from "@/components/Icon.vue"

const route = useRoute()
const tab = ref("profile")
const removeDialog = ref(false)
const deleteText = ref("")
const saved = ref(false)
const noticeMode = ref("邮件")
const channels = ["邮件", "推送", "站内"]
const save = () => { saved.value = true; window.setTimeout(() => { saved.value = false }, 1800) }
</script>

<template>
  <div>
    <template v-if="route.query.state === 'loading'"><v-skeleton-loader type="heading, card, table" /></template>
    <template v-else-if="route.query.state === 'error'"><v-alert type="error" variant="tonal" title="设置加载失败">请重试。</v-alert></template>
    <template v-else>
      <div class="mb-5"><h1 class="text-h5 text-sm-h4">设置</h1><p class="text-body-2 text-medium-emphasis mt-1">管理个人资料、团队与订阅偏好。</p></div>
      <v-row>
        <v-col cols="12" md="3"><v-tabs v-model="tab" direction="vertical" show-arrows class="settings-tabs"><v-tab value="profile">个人资料</v-tab><v-tab value="security">账号安全</v-tab><v-tab value="notifications">通知</v-tab><v-tab value="team">团队</v-tab><v-tab value="billing">计费</v-tab></v-tabs></v-col>
        <v-col cols="12" md="9"><v-window v-model="tab">
          <v-window-item value="profile"><v-card title="个人资料" subtitle="更新你的公开信息"><v-card-text><div class="d-flex align-center ga-4 mb-5"><v-avatar size="72" color="secondary" text="林" /><v-btn variant="outlined"><Icon name="upload" />上传头像</v-btn></div><v-row><v-col cols="12" md="6"><v-text-field label="姓名" model-value="林晓" /></v-col><v-col cols="12" md="6"><v-select label="语言" :items="['简体中文', 'English', '日本語']" model-value="简体中文" /></v-col><v-col cols="12"><v-textarea label="简介" model-value="负责 Acme Console 的产品与团队协作。" /></v-col><v-col cols="12"><v-autocomplete label="时区" :items="['Asia/Shanghai', 'Asia/Tokyo', 'Europe/Berlin']" model-value="Asia/Shanghai" /></v-col></v-row><v-btn color="primary" @click="save">保存修改</v-btn></v-card-text></v-card></v-window-item>
          <v-window-item value="security"><v-card title="账号安全" subtitle="保护你的账户与登录会话"><v-card-text><v-row><v-col cols="12" md="4"><v-text-field label="当前密码" type="password" /></v-col><v-col cols="12" md="4"><v-text-field label="新密码" type="password" /></v-col><v-col cols="12" md="4"><v-text-field label="确认密码" type="password" /></v-col></v-row><v-switch label="启用两步验证" color="primary" /><div class="d-flex flex-wrap align-center ga-4 my-4"><v-sheet border rounded class="d-flex align-center justify-center" width="160" height="160"><Icon name="grid" size="32" /></v-sheet><div><div class="text-subtitle-1">扫码绑定验证器</div><div class="text-body-2 text-medium-emphasis">使用身份验证器应用保护账户。</div></div></div><v-divider class="my-4" /><div class="text-subtitle-1 mb-2">活跃会话</div><v-list lines="two"><v-list-item v-for="session in sessions" :key="session.device" :title="session.device" :subtitle="`${session.location} · ${session.time}`"><template #prepend><v-avatar color="primary" variant="tonal"><Icon name="smartphone" /></v-avatar></template><template #append><v-chip v-if="session.current" size="small" color="success">当前会话</v-chip><v-btn v-else variant="text" size="small">注销</v-btn></template></v-list-item></v-list></v-card-text></v-card></v-window-item>
          <v-window-item value="notifications"><v-card title="通知偏好"><v-card-text><v-btn-toggle v-model="noticeMode" mandatory divided class="mb-5"><v-btn v-for="mode in channels" :key="mode" :value="mode">{{ mode }}</v-btn></v-btn-toggle><v-list lines="two"><v-list-item title="订单更新" subtitle="订单状态发生变化时通知"><template #append><v-switch hide-details color="primary" /></template></v-list-item><v-list-item title="团队活动" subtitle="有人评论、提及或加入团队时通知"><template #append><v-switch hide-details color="primary" /></template></v-list-item><v-list-item title="产品更新" subtitle="获取新功能和服务公告"><template #append><v-switch hide-details color="primary" /></template></v-list-item></v-list></v-card-text></v-card></v-window-item>
          <v-window-item value="team"><v-card title="团队成员" subtitle="管理团队访问权限"><v-card-text><div class="d-flex flex-wrap ga-2 mb-4"><v-text-field label="邀请成员邮箱" density="compact" hide-details /><v-btn color="primary">邀请</v-btn></div><v-data-table :headers="[{ title: '成员', key: 'name' }, { title: '角色', key: 'role' }, { title: '最近活跃', key: 'lastActive' }, { title: '', key: 'actions' }]" :items="team" density="comfortable"><template #[`item.name`]="{ item }"><div class="d-flex align-center ga-2"><v-avatar size="28" color="primary" variant="tonal">{{ item.name.slice(0, 1) }}</v-avatar><div><div>{{ item.name }}</div><div class="text-caption text-medium-emphasis">{{ item.email }}</div></div></div></template><template #[`item.role`]="{ item }"><v-select :items="['owner', 'admin', 'member', 'viewer']" :model-value="item.role" density="compact" hide-details /></template><template #[`item.actions`]="{}"><v-btn variant="text" color="error" size="small">移除</v-btn></template></v-data-table></v-card-text></v-card></v-window-item>
          <v-window-item value="billing"><v-card title="计费" subtitle="管理当前计划与发票"><v-card-text><v-card variant="tonal" color="primary" class="pa-4 mb-5"><div class="d-flex justify-space-between"><div><div class="text-overline">当前计划</div><div class="text-h5">Pro</div></div><v-chip>每月 ¥99</v-chip></div></v-card><v-row><v-col v-for="plan in plans" :key="plan.name" cols="12" sm="4"><v-card height="100%" variant="outlined" class="pa-4"><div class="d-flex justify-space-between align-start"><span class="text-h6">{{ plan.name }}</span><v-chip v-if="plan.recommended" size="small" color="primary">推荐</v-chip></div><div class="text-h5 my-3">{{ plan.price === null ? "联系我们" : `¥${plan.price}/月` }}</div><v-list density="compact"><v-list-item v-for="feature in plan.features" :key="feature" :title="feature"><template #prepend><Icon name="check" size="16" /></template></v-list-item></v-list></v-card></v-col></v-row><div class="text-subtitle-1 mt-6 mb-2">发票记录</div><v-data-table :headers="[{ title: '编号', key: 'id' }, { title: '日期', key: 'date' }, { title: '金额', key: 'amount' }, { title: '状态', key: 'status' }]" :items="invoices" density="comfortable" /></v-card-text></v-card></v-window-item>
        </v-window></v-col>
      </v-row>
      <v-card color="error" variant="outlined" class="mt-6" title="危险区" subtitle="删除账号后所有数据将无法恢复"><template #append><v-btn color="error" variant="outlined" @click="removeDialog = true">删除账号</v-btn></template></v-card>
      <v-snackbar v-model="saved" color="success">设置已保存</v-snackbar>
      <v-dialog v-model="removeDialog" max-width="440"><v-card title="确认删除账号"><v-card-text>请输入 DELETE 以确认删除。</v-card-text><v-card-text><v-text-field v-model="deleteText" label="确认文字" /></v-card-text><v-card-actions><v-spacer /><v-btn variant="text" @click="removeDialog = false">取消</v-btn><v-btn color="error" :disabled="deleteText !== 'DELETE'" @click="removeDialog = false">永久删除</v-btn></v-card-actions></v-card></v-dialog>
    </template>
  </div>
</template>

<style scoped>
.settings-tabs :deep(.v-tab) { justify-content: flex-start; }
@media (max-width: 959px) {
  .settings-tabs { overflow-x: auto; }
  .settings-tabs :deep(.v-slide-group__content) { flex-direction: row; }
  .settings-tabs :deep(.v-tab) { min-width: 110px; }
}
</style>

// apps/angular-material/src/app/pages/settings.page.ts
import { BreakpointObserver } from '@angular/cdk/layout';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import invoices from '@ui-gallery/spec/mock/invoices.json';
import plans from '@ui-gallery/spec/mock/plans.json';
import sessions from '@ui-gallery/spec/mock/sessions.json';
import team from '@ui-gallery/spec/mock/team.json';
import { SHARED_IMPORTS } from '../shared/material';

@Component({
  selector: 'app-delete-account-dialog',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <h2 mat-dialog-title>删除账户</h2>
    <mat-dialog-content>
      <p>删除账户会永久移除团队、订单和所有配置，无法恢复。</p>
      <mat-form-field appearance="outline" class="full">
        <mat-label>输入 DELETE 确认</mat-label>
        <input matInput [formControl]="confirmation" autocomplete="off">
        @if (confirmation.value && confirmation.value !== 'DELETE') {<mat-error>请输入大写 DELETE</mat-error>}
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-flat-button color="warn" [disabled]="confirmation.value !== 'DELETE'" (click)="confirm()">永久删除</button>
    </mat-dialog-actions>
  `,
})
export class DeleteAccountDialog {
  readonly confirmation = inject(FormBuilder).nonNullable.control('');
  private readonly dialogRef = inject(MatDialogRef<DeleteAccountDialog>);
  readonly accountName = inject<{ accountName: string }>(MAT_DIALOG_DATA).accountName;

  confirm(): void {
    this.dialogRef.close(true);
  }
}

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="page settings-page">
      <header class="page-header"><div><p class="eyebrow">WORKSPACE</p><h1>设置</h1><p class="muted">管理个人资料、团队与订阅偏好。</p></div><button mat-flat-button color="primary" (click)="save()">保存更改</button></header>
      <div class="settings-layout">
        <nav class="settings-nav" aria-label="设置导航">
          @for (item of tabs; track item.key) {<button mat-button [class.active-setting]="activeTab() === item.key" (click)="activeTab.set(item.key)"><mat-icon [svgIcon]="item.icon"></mat-icon>{{ item.label }}</button>}
        </nav>
        <section class="settings-content">
          @if (mobile()) {
            <mat-tab-group animationDuration="0ms" [selectedIndex]="tabIndex()" (selectedIndexChange)="activeTab.set(tabs[$event].key)">
              @for (item of tabs; track item.key) {<mat-tab [label]="item.label"></mat-tab>}
            </mat-tab-group>
          }
          @switch (activeTab()) {
            @case ('profile') {
              <mat-card><mat-card-header><mat-card-title>个人资料</mat-card-title><mat-card-subtitle>这些信息会显示在团队活动和邀请中。</mat-card-subtitle></mat-card-header><mat-card-content>
                <div class="profile-banner"><span class="avatar avatar-large">林</span><div><h3>林晓</h3><p class="muted">管理员 · Acme Console</p></div><button mat-stroked-button>更换头像</button></div>
                <form class="form-grid" [formGroup]="profileForm"><mat-form-field appearance="outline"><mat-label>姓名</mat-label><input matInput formControlName="name"><mat-error>请输入姓名</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>邮箱</mat-label><input matInput formControlName="email" readonly></mat-form-field><mat-form-field appearance="outline"><mat-label>语言</mat-label><mat-select formControlName="language"><mat-option value="zh">简体中文</mat-option><mat-option value="en">English</mat-option></mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>时区</mat-label><input matInput formControlName="timezone" [matAutocomplete]="timezoneOptions"><mat-autocomplete #timezoneOptions="matAutocomplete"><mat-option value="Asia/Shanghai">Asia/Shanghai</mat-option><mat-option value="America/Los_Angeles">America/Los_Angeles</mat-option></mat-autocomplete></mat-form-field><mat-form-field appearance="outline" class="full-span"><mat-label>个人简介</mat-label><textarea matInput formControlName="bio" rows="4"></textarea><mat-hint align="end">{{ profileForm.controls.bio.value.length }}/160</mat-hint></mat-form-field></form>
              </mat-card-content></mat-card>
            }
            @case ('security') {
              <mat-card><mat-card-header><mat-card-title>账号安全</mat-card-title><mat-card-subtitle>定期更新密码并检查活跃设备。</mat-card-subtitle></mat-card-header><mat-card-content class="stack">
                <form class="form-grid" [formGroup]="passwordForm"><mat-form-field appearance="outline"><mat-label>当前密码</mat-label><input matInput type="password" formControlName="current"><mat-error>请输入当前密码</mat-error></mat-form-field><span></span><mat-form-field appearance="outline"><mat-label>新密码</mat-label><input matInput type="password" formControlName="next"><mat-hint>至少 8 个字符</mat-hint><mat-error>请输入至少 8 个字符</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>确认新密码</mat-label><input matInput type="password" formControlName="confirm"><mat-error>两次密码不一致</mat-error></mat-form-field></form>
                <mat-divider></mat-divider><div class="spread"><div><h3>两步验证</h3><p class="muted">登录时要求输入验证码，保护账户安全。</p></div><mat-slide-toggle checked></mat-slide-toggle></div><div class="qr-placeholder"><mat-icon svgIcon="shield"></mat-icon><span>扫码绑定验证器</span></div><mat-divider></mat-divider><h3>活跃会话</h3><mat-list>@for (session of sessions; track session.device) {<mat-list-item><mat-icon matListItemIcon [svgIcon]="session.current ? 'laptop' : 'phone'"></mat-icon><span matListItemTitle>{{ session.device }} @if (session.current) {<span class="chip">当前设备</span>}</span><span matListItemLine>{{ session.location }} · {{ session.time }}</span><button mat-icon-button matListItemMeta matTooltip="注销会话"><mat-icon svgIcon="log-out"></mat-icon></button></mat-list-item>}</mat-list>
              </mat-card-content></mat-card>
            }
            @case ('notifications') {
              <mat-card><mat-card-header><mat-card-title>通知偏好</mat-card-title><mat-card-subtitle>选择希望接收哪些工作台通知。</mat-card-subtitle></mat-card-header><mat-card-content class="stack"><mat-button-toggle-group value="all" aria-label="通知渠道"><mat-button-toggle value="all">全部</mat-button-toggle><mat-button-toggle value="email">邮件</mat-button-toggle><mat-button-toggle value="push">推送</mat-button-toggle><mat-button-toggle value="in-app">站内</mat-button-toggle></mat-button-toggle-group>@for (item of notificationGroups; track item.title) {<div class="spread setting-row"><div><b>{{ item.title }}</b><p class="muted">{{ item.description }}</p></div><mat-slide-toggle [checked]="item.enabled"></mat-slide-toggle></div>}</mat-card-content></mat-card>
            }
            @case ('team') {
              <mat-card><mat-card-header><mat-card-title>团队成员</mat-card-title><mat-card-subtitle>管理成员角色和访问权限。</mat-card-subtitle></mat-card-header><mat-card-content><div class="invite-row"><mat-form-field appearance="outline" class="full"><mat-label>邀请成员邮箱</mat-label><input matInput placeholder="teammate@example.com"></mat-form-field><button mat-flat-button color="primary">发送邀请</button></div><div class="table-wrap"><table mat-table [dataSource]="team"><ng-container matColumnDef="member"><th mat-header-cell *matHeaderCellDef>成员</th><td mat-cell *matCellDef="let member"><div class="row"><span class="avatar">{{ member.name.slice(0, 1) }}</span><span>{{ member.name }}<small class="muted">{{ member.email }}</small></span></div></td></ng-container><ng-container matColumnDef="role"><th mat-header-cell *matHeaderCellDef>角色</th><td mat-cell *matCellDef="let member"><mat-select [value]="member.role"><mat-option value="owner">Owner</mat-option><mat-option value="admin">Admin</mat-option><mat-option value="member">Member</mat-option><mat-option value="viewer">Viewer</mat-option></mat-select></td></ng-container><ng-container matColumnDef="active"><th mat-header-cell *matHeaderCellDef>最近活跃</th><td mat-cell *matCellDef="let member">{{ member.lastActive }}</td></ng-container><tr mat-header-row *matHeaderRowDef="teamColumns"></tr><tr mat-row *matRowDef="let row; columns: teamColumns"></tr></table></div></mat-card-content></mat-card>
            }
            @case ('billing') {
              <div class="stack"><mat-card><mat-card-header><mat-card-title>当前计划</mat-card-title><mat-card-subtitle>Pro · 下次扣款 2026 年 10 月 1 日</mat-card-subtitle></mat-card-header><mat-card-content><div class="billing-current"><div><span class="price">¥99<span class="muted">/月</span></span><p class="muted">已使用 8 / 10 个席位</p></div><button mat-stroked-button>管理订阅</button></div></mat-card-content></mat-card><div class="grid grid-3">@for (plan of plans; track plan.name) {<mat-card [class.recommended-plan]="plan.recommended"><mat-card-content class="card-pad"><div class="spread"><h3>{{ plan.name }}</h3>@if (plan.recommended) {<span class="chip">推荐</span>}</div><div class="price">{{ plan.price === null ? '定制' : plan.price === 0 ? '免费' : '¥' + plan.price }}</div>@for (feature of plan.features; track feature) {<p class="muted">✓ {{ feature }}</p>}<button mat-stroked-button class="full">选择方案</button></mat-card-content></mat-card>}</div><mat-card><mat-card-header><mat-card-title>发票</mat-card-title></mat-card-header><mat-card-content class="table-wrap"><table mat-table [dataSource]="invoices"><ng-container matColumnDef="id"><th mat-header-cell *matHeaderCellDef>编号</th><td mat-cell *matCellDef="let invoice">{{ invoice.id }}</td></ng-container><ng-container matColumnDef="date"><th mat-header-cell *matHeaderCellDef>日期</th><td mat-cell *matCellDef="let invoice">{{ invoice.date }}</td></ng-container><ng-container matColumnDef="amount"><th mat-header-cell *matHeaderCellDef>金额</th><td mat-cell *matCellDef="let invoice">¥{{ invoice.amount }}</td></ng-container><tr mat-header-row *matHeaderRowDef="invoiceColumns"></tr><tr mat-row *matRowDef="let row; columns: invoiceColumns"></tr></table></mat-card-content></mat-card></div>
            }
          }
          <mat-card appearance="outlined" class="danger-zone"><mat-card-header><mat-card-title>危险区域</mat-card-title><mat-card-subtitle>删除账户和工作区数据，操作不可撤销。</mat-card-subtitle></mat-card-header><mat-card-content><div class="spread"><div><b>删除 Acme Console 账户</b><p class="muted">所有订单、成员和配置都会被永久移除。</p></div><button mat-stroked-button color="warn" (click)="deleteAccount()">删除账户</button></div></mat-card-content></mat-card>
        </section>
      </div>
    </main>
  `,
})
export class SettingsPage {
  readonly tabs = [
    { key: 'profile', label: '个人资料', icon: 'user' },
    { key: 'security', label: '账号安全', icon: 'shield' },
    { key: 'notifications', label: '通知', icon: 'bell' },
    { key: 'team', label: '团队', icon: 'users' },
    { key: 'billing', label: '计费', icon: 'credit-card' },
  ] as const;
  readonly activeTab = signal<(typeof this.tabs)[number]['key']>('profile');
  readonly mobile = signal(false);
  readonly profileForm = inject(FormBuilder).nonNullable.group({
    name: ['', Validators.required],
    email: [{ value: 'lin.xiao@acme.dev', disabled: true }],
    language: ['zh'],
    timezone: ['Asia/Shanghai'],
    bio: ['负责 Acme Console 的产品与增长。'],
  });
  readonly passwordForm = inject(FormBuilder).nonNullable.group({
    current: ['', Validators.required],
    next: ['', [Validators.required, Validators.minLength(8)]],
    confirm: ['', Validators.required],
  });
  readonly sessions = sessions;
  readonly team = team;
  readonly plans = plans;
  readonly invoices = invoices;
  readonly teamColumns = ['member', 'role', 'active'];
  readonly invoiceColumns = ['id', 'date', 'amount'];
  readonly notificationGroups = [
    { title: '订单状态更新', description: '支付、退款和发货状态变化', enabled: true },
    { title: '团队活动', description: '成员评论、提及和权限变化', enabled: true },
    { title: '产品更新', description: '新功能和维护通知', enabled: false },
  ];
  private readonly breakpoint = inject(BreakpointObserver);
  private readonly dialog = inject(MatDialog);
  private readonly snackBar = inject(MatSnackBar);

  constructor() {
    this.breakpoint.observe('(max-width: 959px)').subscribe((state) => this.mobile.set(state.matches));
  }

  tabIndex(): number {
    return this.tabs.findIndex((tab) => tab.key === this.activeTab());
  }

  save(): void {
    this.snackBar.open('设置已保存', '知道了', { duration: 2400 });
  }

  deleteAccount(): void {
    const ref = this.dialog.open(DeleteAccountDialog, { width: '440px', data: { accountName: 'Acme Console' } });
    ref.afterClosed().subscribe((confirmed: boolean | undefined) => {
      if (confirmed) {
        this.snackBar.open('账户删除请求已提交', '知道了', { duration: 3200 });
      }
    });
  }
}
