// apps/primevue/src/pages/SettingsPage.vue
<script setup lang="ts">
import { ref } from "vue"
import Avatar from "primevue/avatar"
import Button from "primevue/button"
import Card from "primevue/card"
import DataTable from "primevue/datatable"
import Column from "primevue/column"
import Dialog from "primevue/dialog"
import FileUpload from "primevue/fileupload"
import InputGroup from "primevue/inputgroup"
import InputText from "primevue/inputtext"
import AutoComplete from "primevue/autocomplete"
import Password from "primevue/password"
import Select from "primevue/select"
import SelectButton from "primevue/selectbutton"
import Tab from "primevue/tab"
import TabList from "primevue/tablist"
import TabPanel from "primevue/tabpanel"
import TabPanels from "primevue/tabpanels"
import Tabs from "primevue/tabs"
import Tag from "primevue/tag"
import Textarea from "primevue/textarea"
import ToggleSwitch from "primevue/toggleswitch"
import { useToast } from "primevue/usetoast"
import PageHeader from "@/components/PageHeader.vue"
import SectionCard from "@/components/SectionCard.vue"
import StatusTag from "@/components/StatusTag.vue"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"

const toast = useToast()
const deleteDialog = ref(false)
const deleteText = ref("")
const billingCycle = ref("月")
const timezoneSuggestions = ref(["Asia/Shanghai", "Asia/Tokyo", "Europe/Berlin", "America/Los_Angeles"])
const profile = ref({ name: "林晓", bio: "负责 Acme Console 的产品与团队协作。", language: "简体中文", timezone: "Asia/Shanghai" })
const security = ref({ twoFactor: true, current: "", next: "", confirm: "" })
const roleOptions = ["owner", "admin", "member", "viewer"]
const notificationGroups = [
  { title: "产品更新", description: "新功能和版本发布", enabled: true },
  { title: "安全提醒", description: "登录与权限变更", enabled: true },
  { title: "团队动态", description: "评论、提及与任务更新", enabled: false },
]
function saveProfile() { toast.add({ severity: "success", summary: "资料已保存", life: 2200 }) }
function invite() { toast.add({ severity: "success", summary: "邀请已发送", detail: "邀请链接已准备", life: 2200 }) }
function removeMember(name: string) { toast.add({ severity: "info", summary: "已移除成员", detail: name, life: 2200 }) }
function confirmDelete() { deleteDialog.value = false; toast.add({ severity: "success", summary: "删除请求已提交", life: 2200 }); deleteText.value = "" }
</script>

<template>
  <div class="page">
    <PageHeader title="设置" description="管理个人资料、团队与订阅" />
    <Tabs value="0" class="settings-tabs">
      <TabList><Tab value="0">个人资料</Tab><Tab value="1">账号安全</Tab><Tab value="2">通知</Tab><Tab value="3">团队</Tab><Tab value="4">计费</Tab></TabList>
      <TabPanels>
        <TabPanel value="0">
          <SectionCard title="个人资料" description="这些信息会显示在团队活动与邀请中">
            <div class="profile-layout"><div class="col items-center gap-3"><Avatar label="林" size="xlarge" shape="circle" /><FileUpload mode="basic" custom-upload choose-label="更换头像" auto /></div><div class="form-stack"><div class="field"><label for="settings-name">姓名</label><InputText id="settings-name" v-model="profile.name" fluid /></div><div class="field"><label for="settings-bio">简介</label><Textarea id="settings-bio" v-model="profile.bio" rows="4" auto-resize fluid /></div><div class="field"><label>语言</label><Select v-model="profile.language" :options="['简体中文', 'English', '日本語']" fluid /></div><div class="field"><label>时区</label><AutoComplete v-model="profile.timezone" :suggestions="timezoneSuggestions" dropdown fluid /></div><Button label="保存资料" class="self-start" @click="saveProfile" /></div></div>
          </SectionCard>
        </TabPanel>
        <TabPanel value="1">
          <div class="col gap-6"><SectionCard title="修改密码"><div class="form-stack narrow"><div class="field"><label>当前密码</label><Password v-model="security.current" :feedback="false" toggle-mask fluid input-class="w-full" /></div><div class="field"><label>新密码</label><Password v-model="security.next" toggle-mask fluid input-class="w-full" /></div><div class="field"><label>确认新密码</label><Password v-model="security.confirm" :feedback="false" toggle-mask fluid input-class="w-full" /></div><Button label="更新密码" class="self-start" @click="toast.add({ severity: 'success', summary: '密码已更新', life: 2200 })" /></div></SectionCard><SectionCard title="两步验证" description="为账号增加额外的安全保护"><div class="security-layout"><div class="col gap-2"><div class="flex items-center gap-2"><ToggleSwitch v-model="security.twoFactor" /><span>启用两步验证</span></div><small class="muted">使用身份验证器生成一次性验证码。</small></div><div class="qr-placeholder"><i class="pi pi-qrcode" /><span>二维码占位</span></div></div></SectionCard><SectionCard title="活跃会话"><div class="session-list"><div v-for="session in sessions" :key="session.device" class="session-row"><Avatar :label="session.device.includes('iPhone') ? 'i' : 'M'" shape="circle" /><div class="min-w-0 flex-1"><div>{{ session.device }}</div><div class="text-xs muted">{{ session.location }} · {{ session.time }}</div></div><Tag v-if="session.current" value="当前" severity="success" /><Button v-else label="注销" text size="small" severity="danger" @click="toast.add({ severity: 'info', summary: '会话已注销', life: 1800 })" /></div></div></SectionCard></div>
        </TabPanel>
        <TabPanel value="2">
          <SectionCard title="通知偏好" description="选择你希望接收的通知"><div class="notification-list"><div v-for="item in notificationGroups" :key="item.title" class="notification-row"><div><div class="font-medium">{{ item.title }}</div><div class="text-sm muted">{{ item.description }}</div></div><ToggleSwitch v-model="item.enabled" /></div></div><Divider class="my-4" /><div class="field"><label>通知渠道</label><SelectButton :options="['邮件', '推送', '站内']" :allow-empty="false" /></div></SectionCard>
        </TabPanel>
        <TabPanel value="3">
          <SectionCard title="团队成员" description="管理成员角色与访问权限" flush><div class="table-scroll"><DataTable :value="team" size="small" striped-rows><Column header="成员"><template #body="{ data }"><div class="flex items-center gap-2"><Avatar :label="data.name.slice(0, 1)" shape="circle" size="small" /><div><div>{{ data.name }}</div><div class="text-xs muted">{{ data.email }}</div></div></div></template></Column><Column header="角色"><template #body="{ data }"><Select v-model="data.role" :options="roleOptions" size="small" /></template></Column><Column field="lastActive" header="最近活跃" /><Column header="" style="width: 100px"><template #body="{ data }"><Button label="移除" text severity="danger" size="small" @click="removeMember(data.name)" /></template></Column></DataTable></div></SectionCard>
          <SectionCard title="邀请成员" class="mt-6"><InputGroup class="invite-group"><InputText placeholder="成员邮箱" /><Button label="邀请" icon="pi pi-send" @click="invite" /></InputGroup></SectionCard>
        </TabPanel>
        <TabPanel value="4">
          <div class="col gap-6"><Card><template #title>当前计划：Pro</template><template #content><div class="flex items-center justify-between gap-3 wrap"><div><div class="text-2xl font-bold">¥99 <span class="text-sm muted">/ 月</span></div><div class="text-sm muted mt-1">下一次扣款：2026-10-01</div></div><Tag value="使用中" severity="success" /></div></template></Card><div class="flex items-center justify-between"><span class="font-medium">选择计费周期</span><SelectButton v-model="billingCycle" :options="['月', '年']" :allow-empty="false" /></div><div class="grid grid-3"><Card v-for="plan in plans" :key="plan.name" class="plan-card"><template #title><div class="flex items-center justify-between gap-2"><span>{{ plan.name }}</span><Tag v-if="plan.recommended" value="推荐" /></div></template><template #content><div class="text-2xl font-bold mb-4">{{ plan.price === null ? "联系销售" : `¥${billingCycle === '年' ? plan.price * 10 : plan.price}` }}<span v-if="plan.price !== null" class="text-sm muted"> / {{ billingCycle }}</span></div><ul class="feature-list"><li v-for="feature in plan.features" :key="feature"><i class="pi pi-check" />{{ feature }}</li></ul><Button :label="plan.name === 'Pro' ? '当前计划' : '选择计划'" :outlined="plan.name !== 'Pro'" fluid /></template></Card></div><SectionCard title="发票记录" flush><div class="table-scroll"><DataTable :value="invoices" size="small"><Column field="id" header="发票号" /><Column field="date" header="日期" /><Column field="amount" header="金额"><template #body="{ data }">¥{{ data.amount }}</template></Column><Column field="status" header="状态"><template #body="{ data }"><StatusTag :status="data.status" /></template></Column><Column header=""><template #body><Button icon="pi pi-download" text rounded severity="secondary" aria-label="下载发票" /></template></Column></DataTable></div></SectionCard><Card class="danger-card"><template #title>危险区</template><template #content><div class="flex items-center justify-between gap-3 wrap"><div><div class="font-medium">删除账号</div><div class="text-sm muted">此操作不可撤销，请谨慎操作。</div></div><Button label="删除账号" severity="danger" outlined @click="deleteDialog = true" /></div></template></Card></div>
        </TabPanel>
      </TabPanels>
    </Tabs>
    <Dialog v-model:visible="deleteDialog" modal header="删除账号" :style="{ width: 'min(420px, calc(100vw - 32px))' }"><p class="text-sm muted">请输入 DELETE 以确认删除账号。</p><InputText v-model="deleteText" class="mt-3" fluid placeholder="DELETE" /><template #footer><Button label="取消" severity="secondary" text @click="deleteDialog = false" /><Button label="确认删除" severity="danger" :disabled="deleteText !== 'DELETE'" @click="confirmDelete" /></template></Dialog>
  </div>
</template>

<style scoped>
.settings-tabs { display: grid; grid-template-columns: 220px minmax(0, 1fr); gap: 16px; align-items: start; }
.settings-tabs :deep(.p-tablist) { overflow: visible; }
.settings-tabs :deep(.p-tablist-tab-list) { flex-direction: column; align-items: stretch; gap: 2px; border: 0; }
.settings-tabs :deep(.p-tab) { justify-content: flex-start; width: 100%; }
.settings-tabs :deep(.p-tablist-active-bar) { display: none; }
.settings-tabs :deep(.p-tabpanels) { min-width: 0; padding-top: 0; }
.profile-layout { display: grid; grid-template-columns: 160px minmax(0, 560px); gap: 32px; }
.form-stack { display: flex; flex-direction: column; gap: 16px; min-width: 0; } .narrow { max-width: 520px; }
.field { display: flex; flex-direction: column; gap: 6px; }
.security-layout { display: flex; gap: 32px; align-items: center; flex-wrap: wrap; }
.qr-placeholder { width: 160px; height: 160px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 8px; border: 1px dashed var(--p-primary-color); color: var(--p-primary-color); }
.qr-placeholder i { font-size: 2.5rem; }
.session-list, .notification-list { display: flex; flex-direction: column; gap: 4px; }
.session-row, .notification-row { display: flex; align-items: center; gap: 12px; padding: 12px 0; border-bottom: 1px solid var(--p-content-border-color); }
.notification-row { justify-content: space-between; }
.feature-list { display: flex; flex-direction: column; gap: 10px; padding: 0; margin: 0 0 20px; list-style: none; } .feature-list i { color: var(--p-green-500); margin-right: 8px; }
.danger-card { border: 1px solid var(--p-red-500); }
@media (max-width: 767px) { .settings-tabs { display: block; } .settings-tabs :deep(.p-tablist) { width: 100%; overflow-x: auto; } .settings-tabs :deep(.p-tablist-tab-list) { flex-direction: row; min-width: max-content; border-bottom: 1px solid var(--p-tabs-tablist-border-color); } .settings-tabs :deep(.p-tab) { width: auto; justify-content: center; } .settings-tabs :deep(.p-tablist-active-bar) { display: block; } .settings-tabs :deep(.p-tabpanels) { padding-top: 16px; } .profile-layout { grid-template-columns: 1fr; } .invite-group { flex-wrap: wrap; } }
</style>

// apps/angular-material/src/app/pages/settings.page.ts
import { BreakpointObserver } from '@angular/cdk/layout';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import invoices from '@ui-gallery/spec/mock/invoices.json';
import plans from '@ui-gallery/spec/mock/plans.json';
import sessions from '@ui-gallery/spec/mock/sessions.json';
import team from '@ui-gallery/spec/mock/team.json';
import { SHARED_IMPORTS } from '../shared/material';

@Component({
  selector: 'app-delete-account-dialog',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <h2 mat-dialog-title>删除账户</h2>
    <mat-dialog-content>
      <p>删除账户会永久移除团队、订单和所有配置，无法恢复。</p>
      <mat-form-field appearance="outline" class="full">
        <mat-label>输入 DELETE 确认</mat-label>
        <input matInput [formControl]="confirmation" autocomplete="off">
        @if (confirmation.value && confirmation.value !== 'DELETE') {<mat-error>请输入大写 DELETE</mat-error>}
      </mat-form-field>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>取消</button>
      <button mat-flat-button color="warn" [disabled]="confirmation.value !== 'DELETE'" (click)="confirm()">永久删除</button>
    </mat-dialog-actions>
  `,
})
export class DeleteAccountDialog {
  readonly confirmation = inject(FormBuilder).nonNullable.control('');
  private readonly dialogRef = inject(MatDialogRef<DeleteAccountDialog>);
  readonly accountName = inject<{ accountName: string }>(MAT_DIALOG_DATA).accountName;

  confirm(): void {
    this.dialogRef.close(true);
  }
}

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: SHARED_IMPORTS,
  template: `
    <main class="page settings-page">
      <header class="page-header"><div><p class="eyebrow">WORKSPACE</p><h1>设置</h1><p class="muted">管理个人资料、团队与订阅偏好。</p></div><button mat-flat-button color="primary" (click)="save()">保存更改</button></header>
      <div class="settings-layout">
        <nav class="settings-nav" aria-label="设置导航">
          @for (item of tabs; track item.key) {<button mat-button [class.active-setting]="activeTab() === item.key" (click)="activeTab.set(item.key)"><mat-icon [svgIcon]="item.icon"></mat-icon>{{ item.label }}</button>}
        </nav>
        <section class="settings-content">
          @if (mobile()) {
            <mat-tab-group animationDuration="0ms" [selectedIndex]="tabIndex()" (selectedIndexChange)="activeTab.set(tabs[$event].key)">
              @for (item of tabs; track item.key) {<mat-tab [label]="item.label"></mat-tab>}
            </mat-tab-group>
          }
          @switch (activeTab()) {
            @case ('profile') {
              <mat-card><mat-card-header><mat-card-title>个人资料</mat-card-title><mat-card-subtitle>这些信息会显示在团队活动和邀请中。</mat-card-subtitle></mat-card-header><mat-card-content>
                <div class="profile-banner"><span class="avatar avatar-large">林</span><div><h3>林晓</h3><p class="muted">管理员 · Acme Console</p></div><button mat-stroked-button>更换头像</button></div>
                <form class="form-grid" [formGroup]="profileForm"><mat-form-field appearance="outline"><mat-label>姓名</mat-label><input matInput formControlName="name"><mat-error>请输入姓名</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>邮箱</mat-label><input matInput formControlName="email" readonly></mat-form-field><mat-form-field appearance="outline"><mat-label>语言</mat-label><mat-select formControlName="language"><mat-option value="zh">简体中文</mat-option><mat-option value="en">English</mat-option></mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>时区</mat-label><input matInput formControlName="timezone" [matAutocomplete]="timezoneOptions"><mat-autocomplete #timezoneOptions="matAutocomplete"><mat-option value="Asia/Shanghai">Asia/Shanghai</mat-option><mat-option value="America/Los_Angeles">America/Los_Angeles</mat-option></mat-autocomplete></mat-form-field><mat-form-field appearance="outline" class="full-span"><mat-label>个人简介</mat-label><textarea matInput formControlName="bio" rows="4"></textarea><mat-hint align="end">{{ profileForm.controls.bio.value.length }}/160</mat-hint></mat-form-field></form>
              </mat-card-content></mat-card>
            }
            @case ('security') {
              <mat-card><mat-card-header><mat-card-title>账号安全</mat-card-title><mat-card-subtitle>定期更新密码并检查活跃设备。</mat-card-subtitle></mat-card-header><mat-card-content class="stack">
                <form class="form-grid" [formGroup]="passwordForm"><mat-form-field appearance="outline"><mat-label>当前密码</mat-label><input matInput type="password" formControlName="current"><mat-error>请输入当前密码</mat-error></mat-form-field><span></span><mat-form-field appearance="outline"><mat-label>新密码</mat-label><input matInput type="password" formControlName="next"><mat-hint>至少 8 个字符</mat-hint><mat-error>请输入至少 8 个字符</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>确认新密码</mat-label><input matInput type="password" formControlName="confirm"><mat-error>两次密码不一致</mat-error></mat-form-field></form>
                <mat-divider></mat-divider><div class="spread"><div><h3>两步验证</h3><p class="muted">登录时要求输入验证码，保护账户安全。</p></div><mat-slide-toggle checked></mat-slide-toggle></div><div class="qr-placeholder"><mat-icon svgIcon="shield"></mat-icon><span>扫码绑定验证器</span></div><mat-divider></mat-divider><h3>活跃会话</h3><mat-list>@for (session of sessions; track session.device) {<mat-list-item><mat-icon matListItemIcon [svgIcon]="session.current ? 'laptop' : 'phone'"></mat-icon><span matListItemTitle>{{ session.device }} @if (session.current) {<span class="chip">当前设备</span>}</span><span matListItemLine>{{ session.location }} · {{ session.time }}</span><button mat-icon-button matListItemMeta matTooltip="注销会话"><mat-icon svgIcon="log-out"></mat-icon></button></mat-list-item>}</mat-list>
              </mat-card-content></mat-card>
            }
            @case ('notifications') {
              <mat-card><mat-card-header><mat-card-title>通知偏好</mat-card-title><mat-card-subtitle>选择希望接收哪些工作台通知。</mat-card-subtitle></mat-card-header><mat-card-content class="stack"><mat-button-toggle-group value="all" aria-label="通知渠道"><mat-button-toggle value="all">全部</mat-button-toggle><mat-button-toggle value="email">邮件</mat-button-toggle><mat-button-toggle value="push">推送</mat-button-toggle><mat-button-toggle value="in-app">站内</mat-button-toggle></mat-button-toggle-group>@for (item of notificationGroups; track item.title) {<div class="spread setting-row"><div><b>{{ item.title }}</b><p class="muted">{{ item.description }}</p></div><mat-slide-toggle [checked]="item.enabled"></mat-slide-toggle></div>}</mat-card-content></mat-card>
            }
            @case ('team') {
              <mat-card><mat-card-header><mat-card-title>团队成员</mat-card-title><mat-card-subtitle>管理成员角色和访问权限。</mat-card-subtitle></mat-card-header><mat-card-content><div class="invite-row"><mat-form-field appearance="outline" class="full"><mat-label>邀请成员邮箱</mat-label><input matInput placeholder="teammate@example.com"></mat-form-field><button mat-flat-button color="primary">发送邀请</button></div><div class="table-wrap"><table mat-table [dataSource]="team"><ng-container matColumnDef="member"><th mat-header-cell *matHeaderCellDef>成员</th><td mat-cell *matCellDef="let member"><div class="row"><span class="avatar">{{ member.name.slice(0, 1) }}</span><span>{{ member.name }}<small class="muted">{{ member.email }}</small></span></div></td></ng-container><ng-container matColumnDef="role"><th mat-header-cell *matHeaderCellDef>角色</th><td mat-cell *matCellDef="let member"><mat-select [value]="member.role"><mat-option value="owner">Owner</mat-option><mat-option value="admin">Admin</mat-option><mat-option value="member">Member</mat-option><mat-option value="viewer">Viewer</mat-option></mat-select></td></ng-container><ng-container matColumnDef="active"><th mat-header-cell *matHeaderCellDef>最近活跃</th><td mat-cell *matCellDef="let member">{{ member.lastActive }}</td></ng-container><tr mat-header-row *matHeaderRowDef="teamColumns"></tr><tr mat-row *matRowDef="let row; columns: teamColumns"></tr></table></div></mat-card-content></mat-card>
            }
            @case ('billing') {
              <div class="stack"><mat-card><mat-card-header><mat-card-title>当前计划</mat-card-title><mat-card-subtitle>Pro · 下次扣款 2026 年 10 月 1 日</mat-card-subtitle></mat-card-header><mat-card-content><div class="billing-current"><div><span class="price">¥99<span class="muted">/月</span></span><p class="muted">已使用 8 / 10 个席位</p></div><button mat-stroked-button>管理订阅</button></div></mat-card-content></mat-card><div class="grid grid-3">@for (plan of plans; track plan.name) {<mat-card [class.recommended-plan]="plan.recommended"><mat-card-content class="card-pad"><div class="spread"><h3>{{ plan.name }}</h3>@if (plan.recommended) {<span class="chip">推荐</span>}</div><div class="price">{{ plan.price === null ? '定制' : plan.price === 0 ? '免费' : '¥' + plan.price }}</div>@for (feature of plan.features; track feature) {<p class="muted">✓ {{ feature }}</p>}<button mat-stroked-button class="full">选择方案</button></mat-card-content></mat-card>}</div><mat-card><mat-card-header><mat-card-title>发票</mat-card-title></mat-card-header><mat-card-content class="table-wrap"><table mat-table [dataSource]="invoices"><ng-container matColumnDef="id"><th mat-header-cell *matHeaderCellDef>编号</th><td mat-cell *matCellDef="let invoice">{{ invoice.id }}</td></ng-container><ng-container matColumnDef="date"><th mat-header-cell *matHeaderCellDef>日期</th><td mat-cell *matCellDef="let invoice">{{ invoice.date }}</td></ng-container><ng-container matColumnDef="amount"><th mat-header-cell *matHeaderCellDef>金额</th><td mat-cell *matCellDef="let invoice">¥{{ invoice.amount }}</td></ng-container><tr mat-header-row *matHeaderRowDef="invoiceColumns"></tr><tr mat-row *matRowDef="let row; columns: invoiceColumns"></tr></table></mat-card-content></mat-card></div>
            }
          }
          <mat-card appearance="outlined" class="danger-zone"><mat-card-header><mat-card-title>危险区域</mat-card-title><mat-card-subtitle>删除账户和工作区数据，操作不可撤销。</mat-card-subtitle></mat-card-header><mat-card-content><div class="spread"><div><b>删除 Acme Console 账户</b><p class="muted">所有订单、成员和配置都会被永久移除。</p></div><button mat-stroked-button color="warn" (click)="deleteAccount()">删除账户</button></div></mat-card-content></mat-card>
        </section>
      </div>
    </main>
  `,
})
export class SettingsPage {
  readonly tabs = [
    { key: 'profile', label: '个人资料', icon: 'user' },
    { key: 'security', label: '账号安全', icon: 'shield' },
    { key: 'notifications', label: '通知', icon: 'bell' },
    { key: 'team', label: '团队', icon: 'users' },
    { key: 'billing', label: '计费', icon: 'credit-card' },
  ] as const;
  readonly activeTab = signal<(typeof this.tabs)[number]['key']>('profile');
  readonly mobile = signal(false);
  readonly profileForm = inject(FormBuilder).nonNullable.group({
    name: ['', Validators.required],
    email: [{ value: 'lin.xiao@acme.dev', disabled: true }],
    language: ['zh'],
    timezone: ['Asia/Shanghai'],
    bio: ['负责 Acme Console 的产品与增长。'],
  });
  readonly passwordForm = inject(FormBuilder).nonNullable.group({
    current: ['', Validators.required],
    next: ['', [Validators.required, Validators.minLength(8)]],
    confirm: ['', Validators.required],
  });
  readonly sessions = sessions;
  readonly team = team;
  readonly plans = plans;
  readonly invoices = invoices;
  readonly teamColumns = ['member', 'role', 'active'];
  readonly invoiceColumns = ['id', 'date', 'amount'];
  readonly notificationGroups = [
    { title: '订单状态更新', description: '支付、退款和发货状态变化', enabled: true },
    { title: '团队活动', description: '成员评论、提及和权限变化', enabled: true },
    { title: '产品更新', description: '新功能和维护通知', enabled: false },
  ];
  private readonly breakpoint = inject(BreakpointObserver);
  private readonly dialog = inject(MatDialog);
  private readonly snackBar = inject(MatSnackBar);

  constructor() {
    this.breakpoint.observe('(max-width: 959px)').subscribe((state) => this.mobile.set(state.matches));
  }

  tabIndex(): number {
    return this.tabs.findIndex((tab) => tab.key === this.activeTab());
  }

  save(): void {
    this.snackBar.open('设置已保存', '知道了', { duration: 2400 });
  }

  deleteAccount(): void {
    const ref = this.dialog.open(DeleteAccountDialog, { width: '440px', data: { accountName: 'Acme Console' } });
    ref.afterClosed().subscribe((confirmed: boolean | undefined) => {
      if (confirmed) {
        this.snackBar.open('账户删除请求已提交', '知道了', { duration: 3200 });
      }
    });
  }
}
