// apps/arco-design-vue/src/layouts/AppShell.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { RouterLink, RouterView, useRoute, useRouter } from "vue-router"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { Icon } from "@/lib/icons"
import { theme, toggleTheme } from "@/lib/settings"

const route = useRoute()
const router = useRouter()
const collapsed = ref(false)
const mobileOpen = ref(false)
const current = computed(() => nav.find((item) => item.path === route.path)?.label ?? "仪表盘")
const unread = notifications.filter((item) => item.unread).length
const groups = [
  { title: "工作区", keys: ["dashboard", "orders", "form", "chat"] },
  { title: "资源", keys: ["components", "landing", "settings", "login"] },
]

function go(key: string) {
  const target = nav.find((item) => item.key === key)
  if (target) router.push({ path: target.path, query: route.query })
  mobileOpen.value = false
}
</script>

<template>
  <a-layout class="shell">
    <a-layout-sider
      class="shell-sider hide-mobile"
      :collapsed="collapsed"
      collapsible
      hide-trigger
      :width="240"
      :collapsed-width="64"
      breakpoint="lg"
      @collapse="(value: boolean) => (collapsed = value)"
    >
      <div class="shell-brand">
        <a-avatar :size="32" shape="square" :style="{ backgroundColor: 'rgb(var(--primary-6))' }">A</a-avatar>
        <span v-if="!collapsed" class="shell-brand-text">Acme Console</span>
      </div>
      <a-menu :selected-keys="[nav.find((item) => item.path === route.path)?.key ?? 'dashboard']" :collapsed="collapsed" :default-open-keys="['g0', 'g1']" @menu-item-click="go">
        <a-sub-menu v-for="(group, index) in groups" :key="`g${index}`">
          <template #icon><Icon name="boxes" /></template>
          <template #title>{{ group.title }}</template>
          <a-menu-item v-for="key in group.keys" :key="key">
            <template #icon><Icon :name="nav.find((item) => item.key === key)?.icon ?? 'circle-help'" /></template>
            <span class="between">
              {{ nav.find((item) => item.key === key)?.label }}
              <a-badge v-if="nav.find((item) => item.key === key)?.badge" :count="nav.find((item) => item.key === key)?.badge" :offset="[0, 0]" :color="'rgb(var(--red-7))'" />
            </span>
          </a-menu-item>
        </a-sub-menu>
      </a-menu>
      <div class="shell-sider-footer">
        <a-button type="text" size="small" @click="collapsed = !collapsed">
          <template #icon><Icon :name="collapsed ? 'chevron-right' : 'chevron-left'" /></template>
        </a-button>
        <RouterLink v-if="!collapsed" :to="{ path: '/settings', query: route.query }" class="shell-user">
          <a-avatar :size="28">林</a-avatar>
          <span class="stack" style="gap: 0">
            <span>林晓</span>
            <span class="muted small">owner · Acme</span>
          </span>
        </RouterLink>
      </div>
    </a-layout-sider>

    <a-drawer :visible="mobileOpen" placement="left" :width="280" :footer="false" title="Acme Console" unmount-on-close @cancel="mobileOpen = false">
      <a-menu :selected-keys="[nav.find((item) => item.path === route.path)?.key ?? 'dashboard']" :default-open-keys="['g0', 'g1']" @menu-item-click="go">
        <a-sub-menu v-for="(group, index) in groups" :key="`g${index}`">
          <template #title>{{ group.title }}</template>
          <a-menu-item v-for="key in group.keys" :key="key">
            <template #icon><Icon :name="nav.find((item) => item.key === key)?.icon ?? 'circle-help'" /></template>
            {{ nav.find((item) => item.key === key)?.label }}
          </a-menu-item>
        </a-sub-menu>
      </a-menu>
    </a-drawer>

    <a-layout class="shell-main">
      <a-layout-header class="shell-header">
        <a-button class="show-mobile" type="text" @click="mobileOpen = true">
          <template #icon><Icon name="menu" /></template>
        </a-button>
        <a-breadcrumb class="hide-mobile">
          <a-breadcrumb-item><RouterLink :to="{ path: '/', query: route.query }">Acme Console</RouterLink></a-breadcrumb-item>
          <a-breadcrumb-item>{{ current }}</a-breadcrumb-item>
        </a-breadcrumb>
        <div class="shell-actions">
          <a-input-search class="hide-mobile shell-search" placeholder="全局搜索..." allow-clear />
          <a-popover trigger="click" position="br" title="通知">
            <a-badge :count="unread" dot>
              <a-button type="text" shape="circle">
                <template #icon><Icon name="bell" /></template>
              </a-button>
            </a-badge>
            <template #content>
              <a-list size="small" :bordered="false" style="width: 280px">
                <a-list-item v-for="item in notifications" :key="item.title">
                  <a-list-item-meta :title="item.title" :description="item.time">
                    <template #avatar><a-badge :count="item.unread ? 1 : 0" dot><a-avatar :size="24"><Icon name="bell" :size="12" /></a-avatar></a-badge></template>
                  </a-list-item-meta>
                </a-list-item>
              </a-list>
            </template>
          </a-popover>
          <a-tooltip content="切换主题">
            <a-button type="text" shape="circle" @click="toggleTheme()">
              <template #icon><Icon :name="theme === 'dark' ? 'sun' : 'moon'" /></template>
            </a-button>
          </a-tooltip>
          <a-dropdown position="br" @select="(value: unknown) => value === 'settings' && go('settings')">
            <a-avatar :size="32" style="cursor: pointer">林</a-avatar>
            <template #content>
              <a-doption value="profile"><template #icon><Icon name="user" /></template>个人资料</a-doption>
              <a-doption value="settings"><template #icon><Icon name="settings" /></template>账户设置</a-doption>
              <a-doption value="team"><template #icon><Icon name="users" /></template>切换团队</a-doption>
              <a-doption value="help"><template #icon><Icon name="circle-help" /></template>帮助中心</a-doption>
              <a-doption value="logout"><template #icon><Icon name="log-out" /></template>退出登录</a-doption>
            </template>
          </a-dropdown>
        </div>
      </a-layout-header>
      <a-layout-content class="shell-content">
        <RouterView />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<style scoped>
.shell {
  min-height: 100vh;
}

.shell-sider {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
}

.shell-sider :deep(.arco-layout-sider-children) {
  display: flex;
  flex-direction: column;
}

.shell-sider :deep(.arco-menu) {
  flex: 1;
}

.shell-brand {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 16px;
  font-weight: 600;
}

.shell-brand-text {
  white-space: nowrap;
}

.shell-sider-footer {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px;
  border-top: 1px solid var(--color-border-2);
}

.shell-user {
  display: flex;
  align-items: center;
  gap: 8px;
  color: inherit;
  text-decoration: none;
  font-size: 13px;
}

.shell-main {
  min-width: 0;
}

.shell-header {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  gap: 12px;
  height: 60px;
  padding: 0 16px;
  background: var(--color-bg-2);
  border-bottom: 1px solid var(--color-border-2);
}

.shell-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-left: auto;
}

.shell-search {
  width: 220px;
}

.shell-content {
  padding: 24px;
  min-width: 0;
}

@media (max-width: 767px) {
  .shell-content {
    padding: 16px;
  }
}
</style>

// apps/mantine/src/layouts/app-shell.tsx
import { useState, type ReactNode } from "react"
import { Link, useLocation } from "react-router-dom"
import {
  ActionIcon,
  Anchor,
  AppShell as MantineAppShell,
  Avatar,
  Badge,
  Breadcrumbs,
  Burger,
  Group,
  Indicator,
  Menu,
  NavLink,
  Popover,
  ScrollArea,
  Stack,
  Text,
  TextInput,
  ThemeIcon,
  Tooltip,
  UnstyledButton,
} from "@mantine/core"
import { useDisclosure } from "@mantine/hooks"
import { Icon } from "@ui-gallery/icons-react"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { useThemeToggle } from "@/theme"
import { muted } from "@/pages/shared"

export function Brand({ compact = false }: { compact?: boolean }) {
  return (
    <UnstyledButton component={Link} to="/">
      <Group gap="xs" wrap="nowrap">
        <ThemeIcon size="md" radius="md">
          <Text fw={700} size="sm">A</Text>
        </ThemeIcon>
        {compact ? null : <Text fw={600}>Acme Console</Text>}
      </Group>
    </UnstyledButton>
  )
}

function Navigation({ collapsed, onNavigate }: { collapsed: boolean; onNavigate?: () => void }) {
  const location = useLocation()
  return (
    <Stack gap={2}>
      {nav.map((item) => {
        const link = (
          <NavLink
            key={item.key}
            component={Link}
            to={item.path}
            onClick={onNavigate}
            active={location.pathname === item.path}
            label={collapsed ? undefined : item.label}
            leftSection={<Icon name={item.icon} size={16} />}
            rightSection={!collapsed && item.badge ? <Badge size="xs" circle>{item.badge}</Badge> : undefined}
            px={collapsed ? "xs" : "sm"}
            style={{ borderRadius: "var(--mantine-radius-sm)" }}
          />
        )
        return collapsed ? (
          <Tooltip key={item.key} label={item.label} position="right">
            {link}
          </Tooltip>
        ) : (
          link
        )
      })}
    </Stack>
  )
}

export function AppShell({ children }: { children: ReactNode }) {
  const location = useLocation()
  const [mobileOpened, { toggle: toggleMobile, close: closeMobile }] = useDisclosure()
  const [collapsed, setCollapsed] = useState(false)
  const { computed, toggle } = useThemeToggle()
  const current = nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const unread = notifications.filter((n) => n.unread).length

  return (
    <MantineAppShell
      header={{ height: 60 }}
      navbar={{ width: collapsed ? 72 : 260, breakpoint: "sm", collapsed: { mobile: !mobileOpened } }}
      padding="md"
    >
      <MantineAppShell.Header>
        <Group h="100%" px="md" justify="space-between" wrap="nowrap">
          <Group gap="sm" wrap="nowrap">
            <Burger opened={mobileOpened} onClick={toggleMobile} hiddenFrom="sm" size="sm" w={40} h={40} aria-label="打开导航" />
            <Breadcrumbs visibleFrom="xs">
              <Anchor component={Link} to="/" size="sm">Acme Console</Anchor>
              <Text size="sm">{current}</Text>
            </Breadcrumbs>
          </Group>
          <Group gap="xs" wrap="nowrap">
            <TextInput placeholder="搜索..." leftSection={<Icon name="search" size={15} />} visibleFrom="md" w={220} size="sm" aria-label="全局搜索" />
            <Popover width={320} position="bottom-end" shadow="md">
              <Popover.Target>
                <Indicator label={unread} size={16} disabled={!unread} offset={4}>
                  <ActionIcon size={40} variant="subtle" color="gray" aria-label="通知"><Icon name="bell" size={18} /></ActionIcon>
                </Indicator>
              </Popover.Target>
              <Popover.Dropdown>
                <Stack gap="xs">
                  <Text fw={600} size="sm">通知</Text>
                  {notifications.map((n) => (
                    <Group key={n.title} justify="space-between" wrap="nowrap">
                      <div>
                        <Text size="sm" fw={n.unread ? 600 : 400}>{n.title}</Text>
                        <Text size="xs" c={muted}>{n.time}</Text>
                      </div>
                      {n.unread ? <Badge size="xs" variant="dot">未读</Badge> : null}
                    </Group>
                  ))}
                </Stack>
              </Popover.Dropdown>
            </Popover>
            <Tooltip label="切换主题">
              <ActionIcon size={40} variant="subtle" color="gray" onClick={toggle} aria-label="切换主题"><Icon name={computed === "dark" ? "sun" : "moon"} size={18} /></ActionIcon>
            </Tooltip>
            <Menu position="bottom-end" width={200}>
              <Menu.Target>
                <UnstyledButton aria-label="账户菜单"><Avatar radius="xl" color="blue">林</Avatar></UnstyledButton>
              </Menu.Target>
              <Menu.Dropdown>
                <Menu.Label>林晓 · m0@acme.dev</Menu.Label>
                <Menu.Item component={Link} to="/settings" leftSection={<Icon name="user" size={14} />}>个人资料</Menu.Item>
                <Menu.Item component={Link} to="/settings" leftSection={<Icon name="settings" size={14} />}>账户设置</Menu.Item>
                <Menu.Item leftSection={<Icon name="users" size={14} />}>切换团队</Menu.Item>
                <Menu.Item leftSection={<Icon name="circle-help" size={14} />}>帮助中心</Menu.Item>
                <Menu.Divider />
                <Menu.Item color="red" component={Link} to="/login" leftSection={<Icon name="log-out" size={14} />}>退出登录</Menu.Item>
              </Menu.Dropdown>
            </Menu>
          </Group>
        </Group>
      </MantineAppShell.Header>

      <MantineAppShell.Navbar p="sm">
        <MantineAppShell.Section>
          <Group justify={collapsed ? "center" : "space-between"} wrap="nowrap" mb="sm">
            <Brand compact={collapsed} />
            <ActionIcon size={40} variant="subtle" color="gray" visibleFrom="sm" onClick={() => setCollapsed((v) => !v)} aria-label="折叠侧栏">
              <Icon name={collapsed ? "chevron-right" : "chevron-left"} size={16} />
            </ActionIcon>
          </Group>
        </MantineAppShell.Section>
        <MantineAppShell.Section grow component={ScrollArea}>
          {!collapsed ? <Text size="xs" c={muted} fw={600} px="sm" mb={4}>工作区</Text> : null}
          <Navigation collapsed={collapsed} onNavigate={closeMobile} />
        </MantineAppShell.Section>
        <MantineAppShell.Section>
          <UnstyledButton component={Link} to="/settings" w="100%">
            <Group gap="sm" wrap="nowrap" justify={collapsed ? "center" : "flex-start"}>
              <Avatar radius="xl" color="blue" size="sm">林</Avatar>
              {!collapsed ? (
                <div style={{ minWidth: 0 }}>
                  <Text size="sm" fw={500} truncate>林晓</Text>
                  <Text size="xs" c={muted} truncate>m0@acme.dev</Text>
                </div>
              ) : null}
            </Group>
          </UnstyledButton>
        </MantineAppShell.Section>
      </MantineAppShell.Navbar>

      <MantineAppShell.Main style={{ minWidth: 0 }}>{children}</MantineAppShell.Main>
    </MantineAppShell>
  )
}
