// apps/vuetify/src/layouts/AppShell.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { useRoute, useRouter } from "vue-router"
import { useDisplay, useTheme } from "vuetify"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import Icon from "@/components/Icon.vue"
import type { IconName } from "@/icons"

const route = useRoute()
const router = useRouter()
const theme = useTheme()
const { mdAndUp } = useDisplay()

const drawer = ref(mdAndUp.value)
const rail = ref(false)
const isDark = computed(() => theme.global.current.value.dark)
const current = computed(() => nav.find((item) => item.path === route.path)?.label ?? "仪表盘")
const unread = computed(() => notifications.filter((n) => n.unread).length)

function toggleTheme() {
  const next = isDark.value ? "light" : "dark"
  theme.global.name.value = next
  router.replace({ path: route.path, query: { ...route.query, theme: next } })
}
function toggleNav() {
  if (mdAndUp.value) rail.value = !rail.value
  else drawer.value = !drawer.value
}
</script>

<template>
  <v-navigation-drawer v-model="drawer" :rail="rail && mdAndUp" :permanent="mdAndUp" :temporary="!mdAndUp" width="256">
    <v-list nav density="compact">
      <v-list-item :to="{ path: '/', query: route.query }" title="Acme Console" subtitle="Vuetify">
        <template #prepend><v-avatar color="primary" size="32" rounded="lg">A</v-avatar></template>
      </v-list-item>
    </v-list>
    <v-divider />
    <v-list nav density="compact">
      <v-list-subheader>工作区</v-list-subheader>
      <v-list-item v-for="item in nav" :key="item.key" :to="{ path: item.path, query: route.query }" :title="item.label" :active="route.path === item.path" color="primary" rounded="lg">
        <template #prepend><Icon :name="item.icon as IconName" size="20" /></template>
        <template v-if="item.badge" #append><v-badge :content="item.badge" color="primary" inline /></template>
      </v-list-item>
    </v-list>
    <template #append>
      <v-divider />
      <v-list nav density="compact">
        <v-list-item :to="{ path: '/settings', query: route.query }" title="林晓" subtitle="owner@acme.dev">
          <template #prepend><v-avatar color="secondary" size="28">林</v-avatar></template>
        </v-list-item>
      </v-list>
    </template>
  </v-navigation-drawer>

  <v-app-bar flat border="b" density="comfortable">
    <v-app-bar-nav-icon aria-label="切换导航" @click="toggleNav" />
    <v-breadcrumbs class="d-none d-sm-flex pl-0" :items="[{ title: 'Acme Console', to: { path: '/', query: route.query } }, { title: current, disabled: true }]" />
    <v-spacer />
    <v-text-field class="d-none d-md-flex mr-2" style="max-width: 240px" density="compact" variant="outlined" hide-details placeholder="搜索..." aria-label="全局搜索">
      <template #prepend-inner><Icon name="search" size="18" /></template>
    </v-text-field>
    <v-menu :close-on-content-click="false" location="bottom end" width="320">
      <template #activator="{ props }">
        <v-btn v-bind="props" icon aria-label="通知">
          <v-badge :content="unread" color="error" :model-value="unread > 0"><Icon name="bell" /></v-badge>
        </v-btn>
      </template>
      <v-card title="通知" subtitle="最近的更新">
        <v-list lines="two" density="compact">
          <v-list-item v-for="n in notifications" :key="n.title" :title="n.title" :subtitle="n.time">
            <template #prepend><v-badge dot :color="n.unread ? 'primary' : 'grey'" inline /></template>
          </v-list-item>
        </v-list>
      </v-card>
    </v-menu>
    <v-tooltip text="切换主题" location="bottom">
      <template #activator="{ props }">
        <v-btn v-bind="props" icon aria-label="切换主题" @click="toggleTheme"><Icon :name="isDark ? 'sun' : 'moon'" /></v-btn>
      </template>
    </v-tooltip>
    <v-menu location="bottom end">
      <template #activator="{ props }">
        <v-btn v-bind="props" icon aria-label="账户菜单"><v-avatar color="secondary" size="32">林</v-avatar></v-btn>
      </template>
      <v-list density="compact" min-width="200">
        <v-list-item title="林晓" subtitle="owner@acme.dev" />
        <v-divider />
        <v-list-item :to="{ path: '/settings', query: route.query }" title="账户设置"><template #prepend><Icon name="settings" size="18" /></template></v-list-item>
        <v-list-item title="团队"><template #prepend><Icon name="users" size="18" /></template></v-list-item>
        <v-list-item title="帮助中心"><template #prepend><Icon name="circle-help" size="18" /></template></v-list-item>
        <v-list-item title="快捷键"><template #prepend><Icon name="terminal" size="18" /></template></v-list-item>
        <v-divider />
        <v-list-item :to="{ path: '/login', query: route.query }" title="退出登录"><template #prepend><Icon name="log-out" size="18" /></template></v-list-item>
      </v-list>
    </v-menu>
  </v-app-bar>

  <v-main>
    <v-container fluid class="pa-4 pa-sm-6" style="min-width: 0">
      <router-view />
    </v-container>
  </v-main>
</template>

// apps/mantine/src/layouts/app-shell.tsx
import { useState, type ReactNode } from "react"
import { Link, useLocation } from "react-router-dom"
import {
  ActionIcon,
  Anchor,
  AppShell as MantineAppShell,
  Avatar,
  Badge,
  Breadcrumbs,
  Burger,
  Group,
  Indicator,
  Menu,
  NavLink,
  Popover,
  ScrollArea,
  Stack,
  Text,
  TextInput,
  ThemeIcon,
  Tooltip,
  UnstyledButton,
} from "@mantine/core"
import { useDisclosure } from "@mantine/hooks"
import { Icon } from "@ui-gallery/icons-react"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { useThemeToggle } from "@/theme"

export function Brand({ compact = false }: { compact?: boolean }) {
  return (
    <UnstyledButton component={Link} to="/">
      <Group gap="xs" wrap="nowrap">
        <ThemeIcon size="md" radius="md">
          <Text fw={700} size="sm">A</Text>
        </ThemeIcon>
        {compact ? null : <Text fw={600}>Acme Console</Text>}
      </Group>
    </UnstyledButton>
  )
}

function Navigation({ collapsed, onNavigate }: { collapsed: boolean; onNavigate?: () => void }) {
  const location = useLocation()
  return (
    <Stack gap={2}>
      {nav.map((item) => {
        const link = (
          <NavLink
            key={item.key}
            component={Link}
            to={item.path}
            onClick={onNavigate}
            active={location.pathname === item.path}
            label={collapsed ? undefined : item.label}
            leftSection={<Icon name={item.icon} size={16} />}
            rightSection={!collapsed && item.badge ? <Badge size="xs" circle>{item.badge}</Badge> : undefined}
            px={collapsed ? "xs" : "sm"}
            style={{ borderRadius: "var(--mantine-radius-sm)" }}
          />
        )
        return collapsed ? (
          <Tooltip key={item.key} label={item.label} position="right">
            {link}
          </Tooltip>
        ) : (
          link
        )
      })}
    </Stack>
  )
}

export function AppShell({ children }: { children: ReactNode }) {
  const location = useLocation()
  const [mobileOpened, { toggle: toggleMobile, close: closeMobile }] = useDisclosure()
  const [collapsed, setCollapsed] = useState(false)
  const { computed, toggle } = useThemeToggle()
  const current = nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const unread = notifications.filter((n) => n.unread).length

  return (
    <MantineAppShell
      header={{ height: 60 }}
      navbar={{ width: collapsed ? 72 : 260, breakpoint: "sm", collapsed: { mobile: !mobileOpened } }}
      padding="md"
    >
      <MantineAppShell.Header>
        <Group h="100%" px="md" justify="space-between" wrap="nowrap">
          <Group gap="sm" wrap="nowrap">
            <Burger opened={mobileOpened} onClick={toggleMobile} hiddenFrom="sm" size="sm" aria-label="打开导航" />
            <Breadcrumbs visibleFrom="xs">
              <Anchor component={Link} to="/" size="sm">Acme Console</Anchor>
              <Text size="sm">{current}</Text>
            </Breadcrumbs>
          </Group>
          <Group gap="xs" wrap="nowrap">
            <TextInput placeholder="搜索..." leftSection={<Icon name="search" size={15} />} visibleFrom="md" w={220} size="sm" aria-label="全局搜索" />
            <Popover width={320} position="bottom-end" shadow="md">
              <Popover.Target>
                <Indicator label={unread} size={16} disabled={!unread} offset={4}>
                  <ActionIcon variant="subtle" color="gray" aria-label="通知"><Icon name="bell" size={18} /></ActionIcon>
                </Indicator>
              </Popover.Target>
              <Popover.Dropdown>
                <Stack gap="xs">
                  <Text fw={600} size="sm">通知</Text>
                  {notifications.map((n) => (
                    <Group key={n.title} justify="space-between" wrap="nowrap">
                      <div>
                        <Text size="sm" fw={n.unread ? 600 : 400}>{n.title}</Text>
                        <Text size="xs" c="dimmed">{n.time}</Text>
                      </div>
                      {n.unread ? <Badge size="xs" variant="dot">未读</Badge> : null}
                    </Group>
                  ))}
                </Stack>
              </Popover.Dropdown>
            </Popover>
            <Tooltip label="切换主题">
              <ActionIcon variant="subtle" color="gray" onClick={toggle} aria-label="切换主题"><Icon name={computed === "dark" ? "sun" : "moon"} size={18} /></ActionIcon>
            </Tooltip>
            <Menu position="bottom-end" width={200}>
              <Menu.Target>
                <UnstyledButton aria-label="账户菜单"><Avatar radius="xl" color="blue">林</Avatar></UnstyledButton>
              </Menu.Target>
              <Menu.Dropdown>
                <Menu.Label>林晓 · m0@acme.dev</Menu.Label>
                <Menu.Item component={Link} to="/settings" leftSection={<Icon name="user" size={14} />}>个人资料</Menu.Item>
                <Menu.Item component={Link} to="/settings" leftSection={<Icon name="settings" size={14} />}>账户设置</Menu.Item>
                <Menu.Item leftSection={<Icon name="users" size={14} />}>切换团队</Menu.Item>
                <Menu.Item leftSection={<Icon name="circle-help" size={14} />}>帮助中心</Menu.Item>
                <Menu.Divider />
                <Menu.Item color="red" component={Link} to="/login" leftSection={<Icon name="log-out" size={14} />}>退出登录</Menu.Item>
              </Menu.Dropdown>
            </Menu>
          </Group>
        </Group>
      </MantineAppShell.Header>

      <MantineAppShell.Navbar p="sm">
        <MantineAppShell.Section>
          <Group justify={collapsed ? "center" : "space-between"} wrap="nowrap" mb="sm">
            <Brand compact={collapsed} />
            <ActionIcon variant="subtle" color="gray" visibleFrom="sm" onClick={() => setCollapsed((v) => !v)} aria-label="折叠侧栏">
              <Icon name={collapsed ? "chevron-right" : "chevron-left"} size={16} />
            </ActionIcon>
          </Group>
        </MantineAppShell.Section>
        <MantineAppShell.Section grow component={ScrollArea}>
          {!collapsed ? <Text size="xs" c="dimmed" fw={600} px="sm" mb={4}>工作区</Text> : null}
          <Navigation collapsed={collapsed} onNavigate={closeMobile} />
        </MantineAppShell.Section>
        <MantineAppShell.Section>
          <UnstyledButton component={Link} to="/settings" w="100%">
            <Group gap="sm" wrap="nowrap" justify={collapsed ? "center" : "flex-start"}>
              <Avatar radius="xl" color="blue" size="sm">林</Avatar>
              {!collapsed ? (
                <div style={{ minWidth: 0 }}>
                  <Text size="sm" fw={500} truncate>林晓</Text>
                  <Text size="xs" c="dimmed" truncate>m0@acme.dev</Text>
                </div>
              ) : null}
            </Group>
          </UnstyledButton>
        </MantineAppShell.Section>
      </MantineAppShell.Navbar>

      <MantineAppShell.Main style={{ minWidth: 0 }}>{children}</MantineAppShell.Main>
    </MantineAppShell>
  )
}
