// apps/primereact/src/layouts/app-shell.tsx
import { useRef, useState, type ReactNode } from "react"
import { Link, useLocation, useNavigate } from "react-router-dom"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { Avatar } from "primereact/avatar"
import { Badge } from "primereact/badge"
import { Button } from "primereact/button"
import { InputText } from "primereact/inputtext"
import { Menu } from "primereact/menu"
import { OverlayPanel } from "primereact/overlaypanel"
import { PanelMenu } from "primereact/panelmenu"
import { Sidebar } from "primereact/sidebar"
import { BreadCrumb } from "primereact/breadcrumb"
import { Icon } from "@/components/icon"

function Brand() { return <Link to="/" className="flex align-items-center gap-2 no-underline font-semibold text-color"><span className="flex align-items-center justify-content-center border-round bg-primary text-primary-contrast" style={{ width: 32, height: 32 }}>A</span><span>Acme Console</span></Link> }
export function AppShell({ children }: { children: ReactNode }) {
  const location = useLocation(), navigate = useNavigate()
  const [drawer, setDrawer] = useState(false), [collapsed, setCollapsed] = useState(false)
  const notificationsRef = useRef<OverlayPanel>(null)
  const profileRef = useRef<Menu>(null)
  const theme = document.documentElement.classList.contains("dark") ? "dark" : "light"
  const current = nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const themeToggle = () => {
    const next = theme === "dark" ? "light" : "dark"
    const params = new URLSearchParams(window.location.search); params.set("theme", next)
    navigate(`${location.pathname}?${params.toString()}`)
  }
  const model = nav.map((item) => ({ label: item.label, icon: <Icon name={item.icon} />, badge: item.badge, template: () => <Link to={item.path} onClick={() => setDrawer(false)} className={`flex align-items-center gap-2 p-menuitem-link ${location.pathname === item.path ? "surface-200" : ""}`}><Icon name={item.icon} /><span>{item.label}</span>{item.badge ? <Badge value={item.badge} className="ml-auto" /> : null}</Link> }))
  const menu = [{ label: "账户设置", icon: <Icon name="settings" />, command: () => navigate("/settings") }, { label: "帮助中心", icon: <Icon name="circle-help" /> }, { separator: true }, { label: "退出登录", icon: <Icon name="log-out" /> }]
  const side = <div className="h-full flex flex-column p-3"><Brand /><div className="mt-4 flex-1"><p className="text-xs uppercase muted px-2">工作区</p><PanelMenu model={model} className="border-none" /></div><Link to="/settings" className="flex align-items-center gap-2 p-2 no-underline text-color"><Avatar label="林" shape="circle" /><span>林晓</span></Link></div>
  return <div className="flex min-h-screen"><aside className={`hidden md:block flex-shrink-0 surface-section border-right-1 surface-border transition-duration-200 ${collapsed ? "w-5rem" : "w-18rem"}`}>{collapsed ? <div className="p-3 flex flex-column align-items-center gap-4"><Button text icon={<Icon name="menu" />} onClick={() => setCollapsed(false)} /><Link to="/"><Avatar label="A" shape="circle" /></Link><PanelMenu model={model.map((x) => ({ ...x, template: () => <Link to={nav.find((n) => n.label === x.label)?.path ?? "/"} className="flex justify-content-center p-menuitem-link"><Icon name={nav.find((n) => n.label === x.label)?.icon ?? "grid"} /></Link> }))} /></div> : side}</aside><Sidebar visible={drawer} onHide={() => setDrawer(false)} position="left" className="w-18rem">{side}</Sidebar><div className="flex-1 min-w-0"><header className="sticky top-0 z-5 surface-card border-bottom-1 surface-border px-3 md:px-4 py-3 flex align-items-center gap-2"><Button text icon={<Icon name="menu" />} className="md:hidden" onClick={() => setDrawer(true)} /><BreadCrumb model={[{ label: current }]} home={{ template: () => <Link to="/" className="no-underline text-color">Acme Console</Link> }} className="hidden md:flex border-none p-0" /><div className="ml-auto flex align-items-center gap-2"><span className="p-input-icon-left hidden md:inline-flex"><Icon name="search" /><InputText placeholder="搜索..." className="w-14rem" /></span><Button text rounded icon={<Icon name="bell" />} onClick={(e) => notificationsRef.current?.toggle(e)} badge="2" /><OverlayPanel ref={notificationsRef}><div style={{ width: 260 }}><strong>通知</strong>{notifications.map((item) => <div className="py-2 border-bottom-1 surface-border" key={item.title}><div className="text-sm">{item.title}</div><small className="muted">{item.time}</small></div>)}</div></OverlayPanel><Button text rounded icon={<Icon name={theme === "dark" ? "sun" : "moon"} />} onClick={themeToggle} /><Button text rounded icon={<Avatar label="林" shape="circle" />} onClick={(e) => profileRef.current?.toggle(e)} /><Menu ref={profileRef} popup model={menu} /></div></header><main className="page-main">{children}</main></div></div>
}

// apps/element-plus/src/layouts/AppShell.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { useRoute, useRouter } from "vue-router"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import Icon from "@/icons/Icon.vue"
import { useMobile } from "@/composables/useMobile"
import { setTheme } from "@/lib/url-settings"

const route = useRoute()
const router = useRouter()
const mobile = useMobile()
const drawer = ref(false)
const collapsed = ref(false)
const dark = ref(document.documentElement.classList.contains("dark"))
const current = computed(() => nav.find((item) => item.path === route.path)?.label ?? "仪表盘")
const navigate = (path: string) => { router.push(path); drawer.value = false }
const toggleTheme = () => {
  dark.value = !dark.value
  setTheme(dark.value ? "dark" : "light")
  const params = new URLSearchParams(window.location.search)
  params.set("theme", dark.value ? "dark" : "light")
  router.replace({ path: route.path, query: Object.fromEntries(params.entries()) })
}
</script>

<template>
  <el-container class="shell">
    <el-aside v-if="!mobile" :width="collapsed ? '64px' : '240px'" class="sidebar">
      <div class="brand" @click="navigate('/')"><span class="brand-mark">A</span><span v-if="!collapsed">Acme Console</span></div>
      <el-menu :default-active="route.path" :collapse="collapsed" router>
        <el-menu-item v-for="item in nav" :key="item.key" :index="item.path">
          <Icon :name="item.icon" /><template #title>{{ item.label }}<el-badge v-if="item.badge" :value="item.badge" /></template>
        </el-menu-item>
      </el-menu>
      <div class="sidebar-user" @click="navigate('/settings')"><el-avatar size="small">林</el-avatar><span v-if="!collapsed">林晓</span></div>
      <el-button class="collapse-button" text @click="collapsed = !collapsed"><Icon :name="collapsed ? 'arrow-right' : 'arrow-left'" /></el-button>
    </el-aside>
    <el-drawer v-else v-model="drawer" direction="ltr" size="270px" :with-header="false">
      <div class="brand"><span class="brand-mark">A</span><span>Acme Console</span></div>
      <el-menu :default-active="route.path" router @select="drawer = false">
        <el-menu-item v-for="item in nav" :key="item.key" :index="item.path"><Icon :name="item.icon" /><template #title>{{ item.label }}</template></el-menu-item>
      </el-menu>
    </el-drawer>
    <el-container>
      <el-header class="topbar">
        <el-button v-if="mobile" text @click="drawer = true"><Icon name="menu" :size="20" /></el-button>
        <el-breadcrumb><el-breadcrumb-item><router-link to="/">Acme Console</router-link></el-breadcrumb-item><el-breadcrumb-item>{{ current }}</el-breadcrumb-item></el-breadcrumb>
        <el-input class="global-search" placeholder="搜索..." :prefix-icon="undefined"><template #prefix><Icon name="search" /></template></el-input>
        <el-popover placement="bottom-end" width="300" trigger="click">
          <template #reference><el-badge :value="notifications.filter((n) => n.unread).length"><el-button text><Icon name="bell" /></el-button></el-badge></template>
          <div v-for="note in notifications" :key="note.title" class="notification"><b>{{ note.title }}</b><span class="muted">{{ note.time }}</span></div>
        </el-popover>
        <el-button text @click="toggleTheme"><Icon :name="dark ? 'sun' : 'moon'" /></el-button>
        <el-dropdown>
          <span class="avatar-trigger"><el-avatar size="small">林</el-avatar></span>
          <template #dropdown><el-dropdown-menu><el-dropdown-item>个人资料</el-dropdown-item><el-dropdown-item>偏好设置</el-dropdown-item><el-dropdown-item divided>帮助中心</el-dropdown-item><el-dropdown-item>快捷键</el-dropdown-item><el-dropdown-item>退出登录</el-dropdown-item></el-dropdown-menu></template>
        </el-dropdown>
      </el-header>
      <el-main><router-view /></el-main>
    </el-container>
  </el-container>
</template>

<style scoped>
.shell { min-height: 100vh; }
.sidebar { position: relative; display: flex; flex-direction: column; border-right: 1px solid var(--el-border-color); background: var(--el-bg-color); transition: width .2s; }
.brand { display: flex; align-items: center; gap: 10px; height: 64px; padding: 0 18px; font-weight: 700; cursor: pointer; white-space: nowrap; }
.brand-mark { display: grid; width: 32px; height: 32px; place-items: center; border-radius: 8px; color: var(--el-color-white); background: var(--el-color-primary); }
.sidebar :deep(.el-menu) { border-right: 0; flex: 1; }
.sidebar-user { display: flex; align-items: center; gap: 10px; padding: 18px; border-top: 1px solid var(--el-border-color); cursor: pointer; }
.collapse-button { position: absolute; right: 8px; bottom: 80px; }
.topbar { display: flex; align-items: center; gap: 14px; border-bottom: 1px solid var(--el-border-color); background: var(--el-bg-color); }
.global-search { width: 240px; margin-left: auto; }
.avatar-trigger { display: inline-flex; cursor: pointer; }
.notification { display: grid; gap: 4px; padding: 10px 0; border-bottom: 1px solid var(--el-border-color-lighter); }
@media (max-width: 767px) { .topbar { padding: 0 14px; } .global-search { display: none; } .topbar :deep(.el-breadcrumb) { flex: 1; } }
</style>
