// apps/heroui/src/pages/landing.tsx
import { useNavigate } from "react-router-dom"
import { Accordion, Avatar, Button, Card, Chip, Separator } from "@heroui/react"
import { Icon } from "@/components/icon"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import series from "@ui-gallery/spec/mock/series.json"
import stats from "@ui-gallery/spec/mock/stats.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import { StatusBadge } from "./shared"
import { Brand } from "@/layouts/app-shell"

export function LandingPage() {
  const navigate = useNavigate()
  return (
    <div className="min-h-svh bg-background text-foreground">
      <header className="sticky top-0 z-10 border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4">
          <Brand />
          <nav className="hidden gap-6 text-sm text-muted md:flex"><a href="#features">功能</a><a href="#pricing">定价</a><a href="#faq">常见问题</a></nav>
          <div className="flex gap-2"><Button variant="ghost" size="sm" onPress={() => navigate("/login")}>登录</Button><Button size="sm" onPress={() => navigate("/login")}>{landing.hero.primary}</Button></div>
        </div>
      </header>
      <section className="mx-auto max-w-6xl px-4 py-20 text-center">
        <Chip variant="soft" color="accent" className="mb-4">{landing.hero.social}</Chip>
        <h1 className="mx-auto max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">{landing.hero.title}</h1>
        <p className="mx-auto mt-4 max-w-2xl text-lg text-muted">{landing.hero.subtitle}</p>
        <div className="mt-8 flex flex-wrap justify-center gap-3"><Button size="lg" onPress={() => navigate("/login")}>{landing.hero.primary}<Icon name="arrow-right" size={16} /></Button><Button size="lg" variant="secondary" onPress={() => navigate("/")}>{landing.hero.secondary}</Button></div>
        <div className="mt-14 overflow-hidden rounded-2xl border border-border bg-surface-secondary shadow-xl" aria-label="产品截图占位" role="img">
          <div className="flex items-center gap-2 border-b border-border px-4 py-2.5">
            <span className="size-2.5 rounded-full bg-danger/70" /><span className="size-2.5 rounded-full bg-warning/70" /><span className="size-2.5 rounded-full bg-success/70" />
            <span className="ml-3 rounded-md bg-surface px-3 py-0.5 text-xs text-muted">acme.dev/console</span>
          </div>
          <div className="grid text-left md:grid-cols-[160px_minmax(0,1fr)]">
            <div className="hidden flex-col gap-1 border-r border-border p-3 md:flex">
              {["仪表盘", "订单", "客户", "报表", "AI 助手", "设置"].map((item, index) => (
                <span key={item} className={`rounded-md px-3 py-1.5 text-xs ${index === 0 ? "bg-surface font-medium" : "text-muted"}`}>{item}</span>
              ))}
            </div>
            <div className="grid min-w-0 gap-3 p-3 sm:p-4">
              <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
                {stats.map((item) => (
                  <div key={item.key} className="rounded-xl bg-surface p-3">
                    <p className="truncate text-xs text-muted">{item.label}</p>
                    <p className="mt-1 text-lg font-semibold">{item.unit === "CNY" ? "¥" : ""}{item.value.toLocaleString()}</p>
                    <p className={`text-xs ${item.delta >= 0 ? "text-success" : "text-danger"}`}>{item.delta >= 0 ? "+" : ""}{item.delta}%</p>
                  </div>
                ))}
              </div>
              <div className="grid gap-3 lg:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]">
                <div className="rounded-xl bg-surface p-3">
                  <p className="text-xs text-muted">收入趋势</p>
                  <div className="mt-3 flex h-28 items-end gap-2">
                    {series.revenue.map((value, index) => (
                      <div key={series.months[index]} className="flex min-w-0 flex-1 flex-col items-center gap-1">
                        <div className="w-full rounded-t-md bg-accent/80" style={{ height: `${(value / Math.max(...series.revenue)) * 100}%` }} />
                        <span className="text-[10px] text-muted">{series.months[index]}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="hidden rounded-xl bg-surface p-3 sm:block">
                  <p className="text-xs text-muted">最近订单</p>
                  <ul className="mt-2 divide-y divide-border text-xs">
                    {orders.slice(0, 4).map((order) => (
                      <li key={order.id} className="flex items-center justify-between gap-2 py-1.5"><span className="truncate">{order.id} · {order.customer}</span><StatusBadge value={order.status} /></li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="features" className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">一切功能，一个控制台</h2>
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {landing.features.map((feature) => (
            <Card key={feature.title}>
              <Card.Header>
                <div className="mb-2 grid size-10 place-items-center rounded-lg bg-accent-soft text-accent-soft-foreground"><Icon name={feature.icon} size={20} /></div>
                <Card.Title>{feature.title}</Card.Title>
                <Card.Description>{feature.desc}</Card.Description>
              </Card.Header>
            </Card>
          ))}
        </div>
      </section>
      <section className="border-y border-border bg-surface-secondary">
        <div className="mx-auto grid max-w-6xl gap-6 px-4 py-14 sm:grid-cols-2 lg:grid-cols-4">
          {landing.numbers.map((item) => <div key={item.label} className="text-center"><p className="text-4xl font-semibold">{item.value}</p><p className="mt-1 text-sm text-muted">{item.label}</p></div>)}
        </div>
      </section>
      <section id="pricing" className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">简单透明的定价</h2>
        <div className="mt-10 grid gap-4 md:grid-cols-3">
          {plans.map((plan) => (
            <Card key={plan.name} className={plan.recommended ? "border-accent shadow-lg" : undefined}>
              <Card.Header>
                <div className="flex items-center justify-between"><Card.Title>{plan.name}</Card.Title>{plan.recommended ? <Chip color="accent" size="sm">推荐</Chip> : null}</div>
                <p className="text-3xl font-semibold">{plan.price === null ? "定制" : plan.price === 0 ? "¥0" : `¥${plan.price}`}<span className="text-sm font-normal text-muted">{plan.price ? " /月" : ""}</span></p>
              </Card.Header>
              <Card.Content><ul className="space-y-2 text-sm">{plan.features.map((f) => <li key={f} className="flex items-center gap-2"><Icon name="check" size={14} />{f}</li>)}</ul></Card.Content>
              <Card.Footer><Button fullWidth variant={plan.recommended ? "primary" : "secondary"}>{plan.price === null ? "联系销售" : "开始使用"}</Button></Card.Footer>
            </Card>
          ))}
        </div>
      </section>
      <section className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">客户怎么说</h2>
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {landing.testimonials.map((item) => (
            <Card key={item.name} className="min-w-0">
              <Card.Content className="space-y-4">
                <p className="text-sm">“{item.quote}”</p>
                <div className="flex items-center gap-3"><Avatar size="sm"><Avatar.Fallback>{item.name.slice(0, 1)}</Avatar.Fallback></Avatar><div><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted">{item.company}</p></div></div>
              </Card.Content>
            </Card>
          ))}
        </div>
      </section>
      <section id="faq" className="mx-auto max-w-3xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">常见问题</h2>
        <Accordion className="mt-8">
          {landing.faq.map((item, index) => (
            <Accordion.Item key={item.q} id={`faq-${index}`}>
              <Accordion.Heading><Accordion.Trigger>{item.q}<Accordion.Indicator /></Accordion.Trigger></Accordion.Heading>
              <Accordion.Panel><Accordion.Body>{item.a}</Accordion.Body></Accordion.Panel>
            </Accordion.Item>
          ))}
        </Accordion>
      </section>
      <section className="mx-auto max-w-6xl px-4 pb-20">
        <div className="rounded-2xl bg-accent px-6 py-14 text-center text-accent-foreground">
          <h2 className="text-3xl font-semibold">{landing.hero.title}</h2>
          <p className="mt-2 opacity-90">{landing.hero.subtitle}</p>
          <Button className="mt-6" variant="secondary" size="lg" onPress={() => navigate("/login")}>{landing.hero.primary}</Button>
        </div>
      </section>
      <footer className="border-t border-border">
        <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 text-sm text-muted sm:flex-row sm:items-center sm:justify-between">
          <Brand />
          <Separator orientation="vertical" className="hidden h-4 sm:block" />
          <p>© 2026 Acme Console · HeroUI 参考实现</p>
        </div>
      </footer>
    </div>
  )
}

// apps/skeleton/src/pages/Landing.svelte
<script lang="ts">
  import { Accordion, Avatar, Dialog, Portal } from "@skeletonlabs/skeleton-svelte"
  import landing from "@ui-gallery/spec/mock/landing.json"
  import nav from "@ui-gallery/spec/mock/nav.json"
  import plans from "@ui-gallery/spec/mock/plans.json"
  import stats from "@ui-gallery/spec/mock/stats.json"
  import team from "@ui-gallery/spec/mock/team.json"
  import Icon from "../lib/Icon.svelte"
  import type { IconName } from "../lib/icons"
  import { link, router } from "../lib/router.svelte"
  import { initials, money, number } from "../lib/format"
  import { isDark, setDark } from "../lib/settings"

  let dark = $state(isDark())
  let menuOpen = $state(false)
  let yearly = $state(false)
  const logos = landing.testimonials.map((t) => t.company)
  const navLinks = [
    ["#features", "功能"],
    ["#pricing", "定价"],
    ["#testimonials", "客户"],
    ["#faq", "FAQ"],
  ]
  const footerColumns: [string, [string, string][]][] = [
    ["产品", navLinks.map(([href, label]) => [href, label])],
    ["控制台", nav.slice(0, 4).map((n) => [router.href(n.path), n.label])],
    ["方案", plans.map((p) => ["#pricing", p.name])],
  ]
</script>

<div class="min-h-screen bg-surface-50-950">
  <header class="sticky top-0 z-30 border-b border-surface-200-800 bg-surface-50-950/90 backdrop-blur">
    <nav class="mx-auto max-w-6xl px-4 h-16 flex items-center justify-between gap-4" aria-label="主导航">
      <a class="flex items-center gap-2 font-bold" href={router.href("/landing")} use:link>
        <span class="btn-icon btn-icon-sm preset-filled-primary-500">A</span>Acme Console
      </a>
      <ul class="hidden md:flex items-center gap-6 text-sm">
        {#each navLinks as [href, label] (href)}<li><a class="hover:text-primary-500" {href}>{label}</a></li>{/each}
      </ul>
      <div class="flex items-center gap-2">
        <button type="button" class="btn-icon min-w-10 min-h-10 hover:preset-tonal" aria-label="切换主题" onclick={() => { dark = !dark; setDark(dark) }}><Icon name={dark ? "sun" : "moon"} class="size-5" /></button>
        <a class="btn btn-sm hover:preset-tonal hidden sm:inline-flex" href={router.href("/login")} use:link>登录</a>
        <a class="btn btn-sm preset-filled-primary-500 hidden sm:inline-flex" href={router.href("/login")} use:link>{landing.hero.primary}</a>
        <Dialog open={menuOpen} onOpenChange={(d) => (menuOpen = d.open)}>
          <Dialog.Trigger class="btn-icon min-w-10 min-h-10 hover:preset-tonal md:hidden" aria-label="菜单"><Icon name="menu" class="size-5" /></Dialog.Trigger>
          <Portal>
            <Dialog.Backdrop class="fixed inset-0 z-50 bg-surface-50-950/50" />
            <Dialog.Positioner class="fixed inset-0 z-50 flex justify-end">
              <Dialog.Content class="h-screen w-72 max-w-[85vw] bg-surface-50-950 p-4 shadow-xl space-y-4">
                <div class="flex justify-between items-center"><Dialog.Title class="font-bold">菜单</Dialog.Title><Dialog.CloseTrigger class="btn-icon min-w-10 min-h-10 hover:preset-tonal" aria-label="关闭"><Icon name="x" /></Dialog.CloseTrigger></div>
                <ul class="space-y-1">
                  {#each navLinks as [href, label] (href)}<li><a class="btn hover:preset-tonal w-full justify-start" {href} onclick={() => (menuOpen = false)}>{label}</a></li>{/each}
                </ul>
                <hr class="hr" />
                <a class="btn preset-outlined-surface-500 w-full" href={router.href("/login")} use:link>登录</a>
                <a class="btn preset-filled-primary-500 w-full" href={router.href("/login")} use:link>{landing.hero.primary}</a>
              </Dialog.Content>
            </Dialog.Positioner>
          </Portal>
        </Dialog>
      </div>
    </nav>
  </header>

  <main>
    <section class="mx-auto max-w-6xl px-4 py-16 md:py-24 text-center space-y-6">
      <span class="badge preset-tonal-primary"><Icon name="sparkles" class="size-3" />{landing.hero.social}</span>
      <h1 class="h1 max-w-3xl mx-auto">{landing.hero.title}</h1>
      <p class="text-lg opacity-70 max-w-2xl mx-auto">{landing.hero.subtitle}</p>
      <div class="flex flex-col sm:flex-row justify-center gap-3">
        <a class="btn btn-lg preset-filled-primary-500" href={router.href("/login")} use:link>{landing.hero.primary}<Icon name="arrow-right" /></a>
        <a class="btn btn-lg preset-outlined-surface-500" href={router.href("/")} use:link><Icon name="play" />{landing.hero.secondary}</a>
      </div>
      <div class="card bg-surface-100-900 border border-surface-200-800 p-3 md:p-6 mt-8 text-left shadow-xl max-w-4xl mx-auto">
        <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
          {#each stats as s (s.key)}
            <div class="card bg-surface-50-950 p-3 space-y-1">
              <p class="text-xs opacity-60">{s.label}</p>
              <p class="text-lg font-bold tabular-nums">{s.unit === "CNY" ? money(s.value) : s.unit === "%" ? `${s.value}%` : number(s.value)}</p>
              <p class="text-xs font-medium {s.delta >= 0 ? 'text-success-900-100' : 'text-error-900-100'}">{s.delta >= 0 ? "+" : ""}{s.delta}%</p>
            </div>
          {/each}
        </div>
      </div>
    </section>

    <section class="border-y border-surface-200-800 bg-surface-100-900 py-8" aria-label="客户">
      <div class="mx-auto max-w-6xl px-4 flex flex-wrap justify-center gap-x-10 gap-y-4 opacity-60 font-semibold uppercase tracking-wider text-sm">
        {#each logos as l (l)}<span class="flex items-center gap-2"><Icon name="grid" class="size-4" />{l}</span>{/each}
      </div>
    </section>

    <section id="features" class="mx-auto max-w-6xl px-4 py-16 space-y-10">
      <div class="text-center space-y-2"><h2 class="h2">一切所需，尽在一处</h2><p class="opacity-70">面向现代团队的核心能力</p></div>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {#each landing.features as f (f.title)}
          <article class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-3 hover:shadow-lg transition">
            <span class="inline-grid place-items-center size-10 rounded-lg preset-tonal-primary"><Icon name={f.icon as IconName} class="size-5" /></span>
            <h3 class="h5">{f.title}</h3>
            <p class="text-sm opacity-70">{f.desc}</p>
          </article>
        {/each}
      </div>
    </section>

    <section class="mx-auto max-w-6xl px-4 py-16 grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
      <div class="space-y-4">
        <span class="badge preset-tonal-secondary">实时看板</span>
        <h2 class="h2">数据驱动每一次决策</h2>
        <p class="opacity-70">收入、订单、转化率一屏掌握，支持多维筛选与导出，AI 助手随时回答业务问题。</p>
        <ul class="space-y-2 text-sm">
          {#each landing.features.slice(0, 3) as f (f.title)}<li class="flex gap-2"><Icon name="circle-check" class="size-4 text-success-500 shrink-0 mt-0.5" />{f.desc}</li>{/each}
        </ul>
        <a class="btn preset-filled-primary-500" href={router.href("/")} use:link>进入控制台<Icon name="arrow-right" /></a>
      </div>
      <div class="card bg-surface-100-900 border border-surface-200-800 p-4 space-y-3">
        {#each team.slice(0, 4) as m (m.email)}
          <div class="flex items-center gap-3 card bg-surface-50-950 p-3">
            <Avatar class="size-9"><Avatar.Fallback class="preset-filled-secondary-500 text-xs">{initials(m.name)}</Avatar.Fallback></Avatar>
            <div class="flex-1 min-w-0"><p class="text-sm font-medium truncate">{m.name}</p><p class="text-xs opacity-60">{m.role}</p></div>
            <span class="text-xs opacity-60">{m.lastActive}</span>
          </div>
        {/each}
      </div>
    </section>

    <section class="bg-primary-500 text-primary-contrast-500 py-12">
      <div class="mx-auto max-w-6xl px-4 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
        {#each landing.numbers as n (n.label)}
          <div><p class="text-3xl md:text-4xl font-bold">{n.value}</p><p class="text-sm opacity-80">{n.label}</p></div>
        {/each}
      </div>
    </section>

    <section id="pricing" class="mx-auto max-w-6xl px-4 py-16 space-y-10">
      <div class="text-center space-y-4">
        <h2 class="h2">简单透明的定价</h2>
        <label class="inline-flex items-center gap-3 text-sm">
          <span>按月</span><input class="switch" type="checkbox" role="switch" bind:checked={yearly} aria-label="按年计费" /><span>按年 <span class="badge preset-tonal-success">省 20%</span></span>
        </label>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-stretch">
        {#each plans as p (p.name)}
          <article class="card p-6 space-y-4 flex flex-col {p.recommended ? 'preset-filled-primary-500 shadow-xl md:-my-4' : 'bg-surface-50-950 border border-surface-200-800'}">
            <div class="flex items-center justify-between"><h3 class="h4">{p.name}</h3>{#if p.recommended}<span class="badge preset-filled-surface-50-950">最受欢迎</span>{/if}</div>
            <p class="text-4xl font-bold">
              {#if p.price === null}定制{:else}¥{yearly ? Math.round(p.price * 0.8) : p.price}<span class="text-base font-normal opacity-70">/月</span>{/if}
            </p>
            <ul class="space-y-2 text-sm flex-1">{#each p.features as f (f)}<li class="flex gap-2"><Icon name="check" class="size-4 shrink-0 mt-0.5" />{f}</li>{/each}</ul>
            <a class="btn w-full {p.recommended ? 'preset-filled-surface-50-950' : 'preset-outlined-surface-500'}" href={router.href("/login")} use:link>{p.price === null ? "联系销售" : "开始使用"}</a>
          </article>
        {/each}
      </div>
    </section>

    <section id="testimonials" class="bg-surface-100-900 py-16">
      <div class="mx-auto max-w-6xl px-4 space-y-10">
        <h2 class="h2 text-center">客户怎么说</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {#each landing.testimonials as t (t.name)}
            <blockquote class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-3">
              <div class="flex gap-0.5 text-warning-500">{#each { length: 5 }, i (i)}<Icon name="star" class="size-4 fill-current" />{/each}</div>
              <p>“{t.quote}”</p>
              <footer class="flex items-center gap-2 text-sm">
                <Avatar class="size-8"><Avatar.Fallback class="preset-filled-tertiary-500 text-xs">{initials(t.name)}</Avatar.Fallback></Avatar>
                <span><span class="font-medium">{t.name}</span> <span class="opacity-60">· {t.company}</span></span>
              </footer>
            </blockquote>
          {/each}
        </div>
      </div>
    </section>

    <section id="faq" class="mx-auto max-w-3xl px-4 py-16 space-y-8">
      <h2 class="h2 text-center">常见问题</h2>
      <Accordion multiple class="card bg-surface-50-950 border border-surface-200-800 divide-y divide-surface-200-800">
        {#each landing.faq as item, i (item.q)}
          <Accordion.Item value={String(i)}>
            <Accordion.ItemTrigger class="flex w-full items-center justify-between gap-3 p-4 text-left font-medium hover:preset-tonal">
              {item.q}
              <Accordion.ItemIndicator class="[&[data-state=open]]:rotate-180 transition"><Icon name="chevron-down" /></Accordion.ItemIndicator>
            </Accordion.ItemTrigger>
            <Accordion.ItemContent class="px-4 pb-4 text-sm opacity-80">{item.a}</Accordion.ItemContent>
          </Accordion.Item>
        {/each}
      </Accordion>
    </section>

    <section class="mx-auto max-w-6xl px-4 pb-16">
      <div class="card preset-filled-primary-500 p-8 md:p-12 text-center space-y-4">
        <h2 class="h2">准备好开始了吗？</h2>
        <p class="opacity-80">{landing.hero.social}</p>
        <div class="flex flex-col sm:flex-row justify-center gap-3">
          <a class="btn btn-lg preset-filled-surface-50-950" href={router.href("/login")} use:link>{landing.hero.primary}</a>
          <a class="btn btn-lg preset-outlined" href={router.href("/chat")} use:link>{landing.hero.secondary}</a>
        </div>
      </div>
    </section>
  </main>

  <footer class="border-t border-surface-200-800 bg-surface-100-900">
    <div class="mx-auto max-w-6xl px-4 py-12 grid grid-cols-2 md:grid-cols-4 gap-8 text-sm">
      <div class="col-span-2 md:col-span-1 space-y-2">
        <p class="font-bold flex items-center gap-2"><span class="btn-icon btn-icon-sm preset-filled-primary-500">A</span>Acme Console</p>
        <p class="opacity-60">{landing.hero.subtitle}</p>
      </div>
      {#each footerColumns as [title, links] (title)}
        <div class="space-y-2">
          <p class="font-medium">{title}</p>
          <ul class="space-y-1 opacity-70">{#each links as [href, label] (label)}<li><a class="hover:text-primary-500" {href} use:link>{label}</a></li>{/each}</ul>
        </div>
      {/each}
    </div>
    <div class="border-t border-surface-200-800 py-4 text-center text-xs opacity-60">© 2026 Acme Console · Skeleton</div>
  </footer>
</div>
