// apps/shadcn-svelte/src/routes/Dashboard.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import Icon from "$lib/icons/Icon.svelte"
  import stats from "@ui-gallery/spec/mock/stats.json"
  import series from "@ui-gallery/spec/mock/series.json"
  import orders from "@ui-gallery/spec/mock/orders.json"
  import activity from "@ui-gallery/spec/mock/activity.json"
  import tasks from "@ui-gallery/spec/mock/tasks.json"
  import * as Card from "$lib/components/ui/card"
  import * as Badge from "$lib/components/ui/badge"
  import * as Avatar from "$lib/components/ui/avatar"
  import * as Progress from "$lib/components/ui/progress"
  import * as Skeleton from "$lib/components/ui/skeleton"
  import * as Tabs from "$lib/components/ui/tabs"
  import * as Dropdown from "$lib/components/ui/dropdown-menu"
  import { Button } from "$lib/components/ui/button"

  let loading = $state(new URLSearchParams(window.location.search).get("state") === "loading")
  let period = $state("周")
  const statusLabels: Record<string, string> = {
    paid: "已支付",
    pending: "待处理",
    shipped: "已发货",
    refunded: "已退款",
    failed: "失败",
  }
  const statsMap = Object.fromEntries(stats.map((stat) => [stat.key, stat])) as Record<
    string,
    { value: number; delta: number; trend: number[] }
  >
  onMount(() => {
    if (!loading) setTimeout(() => (loading = false), 600)
  })
  const cards = [
    { key: "revenue", label: "总收入", unit: "¥", format: (v: number) => v.toLocaleString() },
    { key: "orders", label: "订单数", unit: "", format: (v: number) => v.toLocaleString() },
    { key: "users", label: "活跃用户", unit: "", format: (v: number) => v.toLocaleString() },
    { key: "conversion", label: "转化率", unit: "", format: (v: number) => `${v}%` },
  ] as const
</script>

{#if loading}
  <div class="space-y-6">
    <div><Skeleton.Root class="h-8 w-40" /><Skeleton.Root class="mt-2 h-4 w-64" /></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {#each cards as _}<Skeleton.Root class="h-32 rounded-xl" />{/each}
    </div>
    <Skeleton.Root class="h-72 rounded-xl" />
  </div>
{:else}
  <div class="space-y-6">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">仪表盘</h1>
      <p class="text-sm text-muted-foreground">查看业务指标和团队最新动态。</p>
    </div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {#each cards as card}
        {@const value = statsMap[card.key]}
        <Card.Root
          ><Card.Header class="flex flex-row items-center justify-between space-y-0 pb-2"
            ><Card.Title class="text-sm font-medium">{card.label}</Card.Title><span
              class="text-xs text-muted-foreground">{card.key === "revenue" ? "本月" : "同比"}</span
            ></Card.Header
          ><Card.Content
            ><div class="text-2xl font-bold">{card.unit}{card.format(value.value)}</div>
            <div
              class="mt-1 flex items-center gap-1 text-xs {value.delta >= 0
                ? 'text-emerald-600'
                : 'text-destructive'}"
            >
              {#if value.delta >= 0}<Icon name="arrow-up" size={12} />{:else}<Icon
                  name="arrow-down"
                  size={12}
                />{/if}{Math.abs(value.delta)}% <span class="text-muted-foreground">较上期</span>
            </div>
            <svg
              class="mt-3 h-8 w-full"
              viewBox="0 0 120 30"
              preserveAspectRatio="none"
              aria-label="趋势"
              ><polyline
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                points={value.trend
                  .map(
                    (point: number, i: number) =>
                      `${i * 20},${28 - (point / Math.max(...value.trend)) * 24}`
                  )
                  .join(" ")}
              /></svg
            ></Card.Content
          ></Card.Root
        >
      {/each}
    </div>
    <Tabs.Root bind:value={period} class="space-y-4">
      <Tabs.List class="h-10"
        ><Tabs.Trigger class="h-10 min-h-9 px-4" data-qa="hit" value="日">日</Tabs.Trigger
        ><Tabs.Trigger class="h-10 min-h-9 px-4" data-qa="hit" value="周">周</Tabs.Trigger
        ><Tabs.Trigger class="h-10 min-h-9 px-4" data-qa="hit" value="月">月</Tabs.Trigger
        ></Tabs.List
      >
      <Tabs.Content value={period}
        ><div class="grid gap-4 lg:grid-cols-3">
          <Card.Root class="lg:col-span-2"
            ><Card.Header
              ><Card.Title>收入趋势</Card.Title><Card.Description
                >近七个月的收入变化</Card.Description
              ></Card.Header
            ><Card.Content
              ><svg
                class="h-56 w-full overflow-visible"
                viewBox="0 0 700 240"
                preserveAspectRatio="none"
                role="img"
                aria-label="收入趋势折线图"
                ><g stroke="var(--border)" stroke-width="1" opacity="0.7"
                  ><line x1="0" y1="30" x2="700" y2="30" /><line
                    x1="0"
                    y1="90"
                    x2="700"
                    y2="90"
                  /><line x1="0" y1="150" x2="700" y2="150" /><line
                    x1="0"
                    y1="210"
                    x2="700"
                    y2="210"
                  /></g
                ><polyline
                  fill="none"
                  stroke="var(--primary)"
                  stroke-width="4"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  points={series.revenue
                    .map((point, i) => `${i * 116},${210 - (point / 140) * 180}`)
                    .join(" ")}
                />{#each series.revenue as point, i}<circle
                    cx={i * 116}
                    cy={210 - (point / 140) * 180}
                    r="4"
                    fill="var(--primary)"
                  />{/each}</svg
              >
              <div class="flex justify-between text-xs text-muted-foreground">
                {#each series.months as month}<span>{month}</span>{/each}
              </div></Card.Content
            ></Card.Root
          >
          <Card.Root
            ><Card.Header
              ><Card.Title>渠道分布</Card.Title><Card.Description>订单来源占比</Card.Description
              ></Card.Header
            ><Card.Content class="flex items-center justify-center"
              ><div class="relative flex size-44 items-center justify-center">
                <svg
                  viewBox="0 0 120 120"
                  class="size-full -rotate-90"
                  role="img"
                  aria-label="渠道分布环形图"
                >
                  <circle
                    cx="60"
                    cy="60"
                    r="42"
                    fill="none"
                    stroke="var(--muted)"
                    stroke-width="16"
                  />
                  {#each series.byChannel as channel, i}
                    {@const start = series.byChannel
                      .slice(0, i)
                      .reduce((sum, item) => sum + item.value, 0)}
                    <circle
                      cx="60"
                      cy="60"
                      r="42"
                      fill="none"
                      stroke={[
                        "var(--primary)",
                        "var(--accent-foreground)",
                        "var(--ring)",
                        "var(--muted-foreground)",
                      ][i]}
                      stroke-width="16"
                      stroke-dasharray={`${channel.value * 2.639} ${263.9 - channel.value * 2.639}`}
                      stroke-dashoffset={-start * 2.639}
                    />
                  {/each}
                </svg>
                <div
                  class="absolute flex size-24 items-center justify-center rounded-full bg-background text-center text-xs text-muted-foreground"
                >
                  渠道<br />占比
                </div>
              </div></Card.Content
            ><Card.Footer class="grid grid-cols-2 gap-2 text-xs"
              >{#each series.byChannel as channel}<div class="flex justify-between">
                  <span>{channel.name}</span><span class="font-medium">{channel.value}%</span>
                </div>{/each}</Card.Footer
            ></Card.Root
          >
        </div></Tabs.Content
      >
    </Tabs.Root>
    <Card.Root>
      <Card.Header
        ><Card.Title>订单趋势</Card.Title><Card.Description>各月订单数量</Card.Description
        ></Card.Header
      >
      <Card.Content>
        <svg
          class="h-48 w-full"
          viewBox="0 0 700 220"
          preserveAspectRatio="none"
          role="img"
          aria-label="订单柱状图"
        >
          <g stroke="var(--border)" stroke-width="1" opacity="0.7">
            <line x1="0" y1="30" x2="700" y2="30" /><line x1="0" y1="90" x2="700" y2="90" />
            <line x1="0" y1="150" x2="700" y2="150" /><line x1="0" y1="210" x2="700" y2="210" />
          </g>
          {#each series.orders as value, i}
            {@const height = (value / 1100) * 180}
            <rect
              x={i * 100 + 26}
              y={210 - height}
              width="48"
              {height}
              rx="5"
              fill="var(--primary)"
              opacity="0.85"
            />
          {/each}
        </svg>
        <div class="flex justify-around text-xs text-muted-foreground">
          {#each series.months as month}<span>{month}</span>{/each}
        </div>
      </Card.Content>
    </Card.Root>
    <div class="grid gap-4 xl:grid-cols-3">
      <Card.Root class="xl:col-span-2"
        ><Card.Header><Card.Title>最近订单</Card.Title></Card.Header><Card.Content
          ><div class="overflow-x-auto">
            <table class="w-full text-sm">
              <thead
                ><tr class="border-b text-left text-muted-foreground"
                  ><th class="pb-3">客户</th><th class="pb-3">产品</th><th class="pb-3">状态</th><th
                    class="pb-3 text-right">金额</th
                  ><th></th></tr
                ></thead
              ><tbody
                >{#each orders.slice(0, 5) as order}<tr class="border-b last:border-0"
                    ><td class="py-3"
                      ><div class="flex items-center gap-2">
                        <Avatar.Root class="size-7"
                          ><Avatar.Fallback>{order.customer.slice(0, 1)}</Avatar.Fallback
                          ></Avatar.Root
                        ><span>{order.customer}</span>
                      </div></td
                    ><td>{order.product}</td><td
                      ><Badge.Root variant={order.status === "paid" ? "default" : "secondary"}
                        >{statusLabels[order.status]}</Badge.Root
                      ></td
                    ><td class="text-right">{order.currency}{order.amount}</td><td
                      class="text-right"
                      ><Dropdown.Root
                        ><Dropdown.Trigger
                          ><Button
                            variant="ghost"
                            size="icon"
                            class="size-10"
                            data-qa="hit"
                            aria-label="订单操作"><Icon name="more-horizontal" size={16} /></Button
                          ></Dropdown.Trigger
                        ><Dropdown.Content
                          ><Dropdown.Item>查看详情</Dropdown.Item><Dropdown.Item
                            >复制订单号</Dropdown.Item
                          ></Dropdown.Content
                        ></Dropdown.Root
                      ></td
                    ></tr
                  >{/each}</tbody
              >
            </table>
          </div></Card.Content
        ></Card.Root
      >
      <div class="space-y-4">
        <Card.Root
          ><Card.Header><Card.Title>团队动态</Card.Title></Card.Header><Card.Content
            ><div class="space-y-4">
              {#each activity as item}<div class="flex gap-3">
                  <span class="mt-1.5 size-2 shrink-0 rounded-full bg-primary"></span>
                  <div class="text-sm">
                    <p>{item.user} {item.action}</p>
                    <p class="text-xs text-muted-foreground">{item.time}</p>
                  </div>
                </div>{/each}
            </div></Card.Content
          ></Card.Root
        ><Card.Root
          ><Card.Header><Card.Title>任务进度</Card.Title></Card.Header><Card.Content
            class="space-y-4"
            >{#each tasks as task}<div class="space-y-1">
                <div class="flex justify-between text-sm">
                  <span>{task.title}</span><span class="text-muted-foreground"
                    >{task.progress}%</span
                  >
                </div>
                <Progress.Root value={task.progress} />
              </div>{/each}</Card.Content
          ></Card.Root
        >
      </div>
    </div>
  </div>
{/if}

// apps/element-plus/src/pages/Dashboard.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import stats from "@ui-gallery/spec/mock/stats.json"
import series from "@ui-gallery/spec/mock/series.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import activity from "@ui-gallery/spec/mock/activity.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import EChart from "@/components/EChart.vue"
import Icon from "@/icons/Icon.vue"
const loading = ref(true)
window.setTimeout(() => { loading.value = false }, 600)
const money = (stat: typeof stats[number]) => stat.unit === "CNY" ? `¥${stat.value.toLocaleString()}` : `${stat.value}${stat.unit ?? ""}`
const lineOption = computed(() => ({ tooltip: { trigger: "axis" }, xAxis: { type: "category", data: series.months }, yAxis: { type: "value" }, series: [{ type: "line", smooth: true, data: series.revenue, areaStyle: {} }] }))
const barOption = computed(() => ({ tooltip: { trigger: "axis" }, xAxis: { type: "category", data: series.months }, yAxis: { type: "value" }, series: [{ type: "bar", data: series.orders, barMaxWidth: 24 }] }))
const pieOption = computed(() => ({ tooltip: { trigger: "item" }, series: [{ type: "pie", radius: ["45%", "70%"], data: series.byChannel.map((item) => ({ name: item.name, value: item.value })) }] }))
const tagType = (status: string) => ({ paid: "success", pending: "warning", refunded: "info", failed: "danger", shipped: "" }[status] ?? "info") as any
</script>

<template>
  <div class="page">
    <div class="page-header"><div><h1 class="page-title">仪表盘</h1><p class="page-subtitle">欢迎回来，林晓。这里是团队的最新概览。</p></div><el-button type="primary"><Icon name="download" />导出报告</el-button></div>
    <el-skeleton v-if="loading" :rows="4" animated />
    <template v-else>
      <el-row :gutter="16"><el-col v-for="stat in stats" :key="stat.key" :xs="24" :sm="12" :lg="6"><el-card class="stat-card"><div class="stat-head"><span class="muted">{{ stat.label }}</span><Icon :name="stat.key === 'revenue' ? 'bar-chart' : stat.key === 'orders' ? 'shopping-cart' : stat.key === 'users' ? 'users' : 'activity'" /></div><strong>{{ money(stat) }}</strong><div class="stat-foot"><el-tag :type="stat.delta >= 0 ? 'success' : 'danger'">{{ stat.delta >= 0 ? "+" : "" }}{{ stat.delta }}%</el-tag><span class="muted">较上月</span></div><svg class="sparkline" viewBox="0 0 120 30" preserveAspectRatio="none"><polyline :points="stat.trend.map((v, i) => `${i * 20},${30 - v / Math.max(...stat.trend) * 25}`).join(' ')" fill="none" stroke="var(--el-color-primary)" stroke-width="2" /></svg></el-card></el-col></el-row>
      <el-card class="chart-card"><template #header><div class="card-header"><span>业务趋势</span><el-tabs model-value="month"><el-tab-pane label="日" name="day" /><el-tab-pane label="周" name="week" /><el-tab-pane label="月" name="month" /></el-tabs></div></template><el-row :gutter="16"><el-col :xs="24" :lg="12"><h3>收入</h3><EChart :option="lineOption" /></el-col><el-col :xs="24" :sm="12" :lg="6"><h3>订单</h3><EChart :option="barOption" height="280px" /></el-col><el-col :xs="24" :sm="12" :lg="6"><h3>渠道</h3><EChart :option="pieOption" height="280px" /></el-col></el-row></el-card>
      <el-row :gutter="16"><el-col :xs="24" :lg="14"><el-card><template #header><div class="card-header"><span>最近订单</span><el-link type="primary" href="/apps/element-plus/orders">查看全部</el-link></div></template><div class="scroll-x"><el-table :data="orders.slice(0, 5)" style="min-width: 620px"><el-table-column prop="id" label="订单号" /><el-table-column label="客户"><template #default="{ row }"><el-avatar :size="24">{{ row.customer.slice(0, 1) }}</el-avatar> {{ row.customer }}</template></el-table-column><el-table-column prop="product" label="产品" /><el-table-column label="金额"><template #default="{ row }">¥{{ row.amount.toLocaleString() }}</template></el-table-column><el-table-column label="状态"><template #default="{ row }"><el-tag :type="tagType(row.status)" size="small">{{ row.status }}</el-tag></template></el-table-column><el-table-column width="60"><template #default><el-dropdown><el-button text><Icon name="more-horizontal" /></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item>查看</el-dropdown-item><el-dropdown-item>编辑</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table></div></el-card></el-col><el-col :xs="24" :lg="5"><el-card><template #header>团队动态</template><el-timeline><el-timeline-item v-for="item in activity.slice(0, 4)" :key="item.action" :timestamp="item.time">{{ item.user }}{{ item.action }}</el-timeline-item></el-timeline></el-card></el-col><el-col :xs="24" :lg="5"><el-card><template #header>任务进度</template><div v-for="task in tasks" :key="task.title" class="task"><div><span>{{ task.title }}</span><small>{{ task.owner }}</small></div><el-progress :percentage="task.progress" :stroke-width="8" /></div></el-card></el-col></el-row>
    </template>
  </div>
</template>

<style scoped>
.stat-card { position: relative; overflow: hidden; }.stat-head, .stat-foot, .card-header { display: flex; align-items: center; justify-content: space-between; gap: 8px; }.stat-card strong { display: block; margin: 12px 0; font-size: 28px; }.stat-foot { justify-content: flex-start; }.sparkline { position: absolute; right: 12px; bottom: 18px; width: 100px; height: 30px; opacity: .6; }.chart-card, .stat-card { margin-bottom: 16px; }.chart-card :deep(.el-tabs__header) { margin: -12px 0; }.task { display: grid; gap: 5px; margin-bottom: 18px; }.task div { display: flex; justify-content: space-between; gap: 8px; font-size: 13px; }.task small { color: var(--el-text-color-secondary); }
</style>
