// apps/shadcn-svelte/src/routes/Settings.svelte
<script lang="ts">
  import Icon from "$lib/icons/Icon.svelte"
  import sessions from "@ui-gallery/spec/mock/sessions.json"
  import team from "@ui-gallery/spec/mock/team.json"
  import plans from "@ui-gallery/spec/mock/plans.json"
  import invoices from "@ui-gallery/spec/mock/invoices.json"
  import { Button } from "$lib/components/ui/button"
  import * as Card from "$lib/components/ui/card"
  import * as Avatar from "$lib/components/ui/avatar"
  import * as Tabs from "$lib/components/ui/tabs"
  import * as Switch from "$lib/components/ui/switch"
  import * as Dialog from "$lib/components/ui/alert-dialog"
  import * as Badge from "$lib/components/ui/badge"
  let tab = $state("profile"),
    dangerOpen = $state(false),
    confirmText = $state("")
</script>

<div class="space-y-6">
  <div>
    <h1 class="text-2xl font-semibold">设置</h1>
    <p class="text-sm text-muted-foreground">管理个人资料、团队和账单。</p>
  </div>
  <Tabs.Root
    bind:value={tab}
    orientation="vertical"
    class="grid gap-6 lg:grid-cols-[200px_minmax(0,1fr)]"
    ><div class="w-full overflow-x-auto lg:overflow-visible">
      <Tabs.List
        class="h-auto w-max min-w-full justify-start lg:w-auto lg:min-w-0 lg:flex-col lg:items-stretch [&_[data-slot=tabs-trigger]]:min-h-10 lg:[&_[data-slot=tabs-trigger]]:w-full"
        ><Tabs.Trigger value="profile">个人资料</Tabs.Trigger><Tabs.Trigger value="security"
          >账号安全</Tabs.Trigger
        ><Tabs.Trigger value="notifications">通知</Tabs.Trigger><Tabs.Trigger value="team"
          >团队</Tabs.Trigger
        ><Tabs.Trigger value="billing">计费</Tabs.Trigger></Tabs.List
      >
    </div>
    <div class="min-w-0">
      <Tabs.Content value="profile"
        ><Card.Root
          ><Card.Header
            ><Card.Title>个人资料</Card.Title><Card.Description
              >更新你的头像和个人信息。</Card.Description
            ></Card.Header
          ><Card.Content class="space-y-5"
            ><div class="flex items-center gap-4">
              <Avatar.Root class="size-16"><Avatar.Fallback>AC</Avatar.Fallback></Avatar.Root
              ><Button variant="outline"
                ><Icon name="image" size={16} class="mr-2" />上传头像</Button
              >
            </div>
            <label class="block space-y-2 text-sm font-medium"
              >姓名<input class="h-9 w-full rounded-md border px-3" value="Acme Team" /></label
            ><label class="block space-y-2 text-sm font-medium"
              >简介<textarea class="min-h-24 w-full rounded-md border p-3"
                >负责 Acme Console 的团队协作。</textarea
              ></label
            >
            <div class="grid gap-4 sm:grid-cols-2">
              <label class="space-y-2 text-sm font-medium"
                >语言<select class="h-9 w-full rounded-md border bg-background px-3"
                  ><option>简体中文</option><option>English</option></select
                ></label
              ><label class="space-y-2 text-sm font-medium"
                >时区<select class="h-9 w-full rounded-md border bg-background px-3"
                  ><option>Asia/Shanghai</option><option>America/Los_Angeles</option></select
                ></label
              >
            </div></Card.Content
          ><Card.Footer><Button>保存更改</Button></Card.Footer></Card.Root
        ></Tabs.Content
      >
      <Tabs.Content value="security"
        ><div class="space-y-4">
          <Card.Root
            ><Card.Header><Card.Title>账号安全</Card.Title></Card.Header><Card.Content
              class="space-y-4"
              ><label class="block space-y-2 text-sm"
                >当前密码<input type="password" class="h-9 w-full rounded-md border px-3" /></label
              ><label class="block space-y-2 text-sm"
                >新密码<input type="password" class="h-9 w-full rounded-md border px-3" /></label
              ><Button>修改密码</Button>
              <div class="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <p class="font-medium">两步验证</p>
                  <p class="text-sm text-muted-foreground">为账号增加额外保护。</p>
                </div>
                <Switch.Root />
              </div>
              <div
                class="flex size-32 items-center justify-center border-4 border-foreground bg-muted text-center text-xs"
              >
                二维码占位
              </div></Card.Content
            ></Card.Root
          ><Card.Root
            ><Card.Header><Card.Title>活跃会话</Card.Title></Card.Header><Card.Content
              class="space-y-3"
              >{#each sessions as session}<div
                  class="flex items-center justify-between border-b py-3 last:border-0"
                >
                  <div>
                    <p class="font-medium">{session.device}</p>
                    <p class="text-xs text-muted-foreground">{session.location} · {session.time}</p>
                  </div>
                  <Button variant="outline" size="sm">注销</Button>
                </div>{/each}</Card.Content
            ></Card.Root
          >
        </div></Tabs.Content
      >
      <Tabs.Content value="notifications"
        ><Card.Root
          ><Card.Header><Card.Title>通知偏好</Card.Title></Card.Header><Card.Content
            class="space-y-1"
            >{#each ["产品更新", "团队活动", "安全提醒", "账单通知"] as item}<div
                class="flex items-center justify-between border-b py-4 last:border-0"
              >
                <span>{item}</span><Switch.Root />
              </div>{/each}
            <div class="pt-4">
              <p class="mb-3 text-sm font-medium">接收方式</p>
              <div class="flex gap-2">
                <Button variant="secondary">邮件</Button><Button variant="outline">推送</Button
                ><Button variant="outline">站内</Button>
              </div>
            </div></Card.Content
          ></Card.Root
        ></Tabs.Content
      >
      <Tabs.Content value="team"
        ><Card.Root
          ><Card.Header
            ><Card.Title>团队成员</Card.Title><Card.Description>管理团队权限。</Card.Description
            ></Card.Header
          ><Card.Content
            ><div class="mb-4 flex gap-2">
              <input
                class="h-9 flex-1 rounded-md border px-3 text-sm"
                placeholder="输入邮箱邀请成员"
              /><Button>邀请</Button>
            </div>
            <div class="overflow-x-auto">
              <table class="w-full text-sm">
                <tbody
                  >{#each team as member}<tr class="border-b last:border-0"
                      ><td class="py-3"
                        ><div class="flex items-center gap-2">
                          <Avatar.Root class="size-8"
                            ><Avatar.Fallback>{member.name.slice(0, 1)}</Avatar.Fallback
                            ></Avatar.Root
                          >{member.name}
                        </div></td
                      ><td>{member.email}</td><td
                        ><select class="rounded border bg-background px-2 py-1"
                          ><option>{member.role}</option><option>成员</option></select
                        ></td
                      ><td class="text-right"><Button variant="ghost" size="sm">移除</Button></td
                      ></tr
                    >{/each}</tbody
                >
              </table>
            </div></Card.Content
          ></Card.Root
        ></Tabs.Content
      >
      <Tabs.Content value="billing"
        ><div class="space-y-4">
          <Card.Root
            ><Card.Header><Card.Title>当前计划</Card.Title></Card.Header><Card.Content
              ><div class="flex items-center justify-between">
                <div>
                  <p class="text-2xl font-bold">Pro</p>
                  <p class="text-sm text-muted-foreground">适合成长中的团队</p>
                </div>
                <Badge.Root>当前计划</Badge.Root>
              </div></Card.Content
            ></Card.Root
          >
          <div class="grid gap-4 md:grid-cols-3">
            {#each plans as plan}<Card.Root class={plan.recommended ? "border-primary" : ""}
                ><Card.Header
                  ><Card.Title>{plan.name}</Card.Title>{#if plan.recommended}<Badge.Root
                      >推荐</Badge.Root
                    >{/if}</Card.Header
                ><Card.Content
                  ><p class="mb-4 text-2xl font-bold">
                    ¥{plan.price}<span class="text-sm font-normal text-muted-foreground">/月</span>
                  </p>
                  <ul class="space-y-2 text-sm">
                    {#each plan.features as feature}<li>✓ {feature}</li>{/each}
                  </ul></Card.Content
                ></Card.Root
              >{/each}
          </div>
          <Card.Root
            ><Card.Header><Card.Title>发票记录</Card.Title></Card.Header><Card.Content
              ><div class="overflow-x-auto">
                <table class="w-full text-sm">
                  <thead
                    ><tr class="border-b text-left"
                      ><th class="py-2">编号</th><th>日期</th><th>金额</th><th>状态</th></tr
                    ></thead
                  ><tbody
                    >{#each invoices as invoice}<tr class="border-b last:border-0"
                        ><td class="py-2">{invoice.id}</td><td>{invoice.date}</td><td
                          >{invoice.amount}</td
                        ><td>{invoice.status}</td></tr
                      >{/each}</tbody
                  >
                </table>
              </div></Card.Content
            ></Card.Root
          >
        </div></Tabs.Content
      >
    </div></Tabs.Root
  >
  <Card.Root class="border-destructive"
    ><Card.Header
      ><Card.Title class="text-destructive">危险区域</Card.Title><Card.Description
        >删除账号后所有数据无法恢复。</Card.Description
      ></Card.Header
    ><Card.Footer
      ><Button variant="destructive" onclick={() => (dangerOpen = true)}
        ><Icon name="trash" size={16} class="mr-2" />删除账号</Button
      ></Card.Footer
    ></Card.Root
  >
</div>
<Dialog.Root bind:open={dangerOpen}
  ><Dialog.Content
    ><Dialog.Header
      ><Dialog.Title>确认删除账号</Dialog.Title><Dialog.Description
        >请输入 DELETE 以确认。</Dialog.Description
      ></Dialog.Header
    ><input
      bind:value={confirmText}
      class="h-9 w-full rounded-md border px-3"
      placeholder="DELETE"
    /><Dialog.Footer
      ><Dialog.Cancel>取消</Dialog.Cancel><Dialog.Action disabled={confirmText !== "DELETE"}
        >确认删除</Dialog.Action
      ></Dialog.Footer
    ></Dialog.Content
  ></Dialog.Root
>

// apps/element-plus/src/pages/Settings.vue
<script setup lang="ts">
import { ref } from "vue"
import { ElMessage, ElMessageBox } from "element-plus"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import { Plus } from "@element-plus/icons-vue"
import { useMobile } from "@/composables/useMobile"
const mobile = useMobile()
const tab = ref("profile")
const danger = ref(false)
const confirm = ref("")
const twoFactor = ref(false)
const removeAccount = async () => {
  if (confirm.value !== "DELETE") return ElMessage.warning("请输入 DELETE")
  await ElMessageBox.confirm("此操作不可撤销，确定继续吗？", "删除账号", { type: "warning" })
  danger.value = false
  ElMessage.success("演示账号已标记为删除")
}
</script>

<template>
  <div class="page">
    <div class="page-header">
      <div>
        <h1 class="page-title">设置</h1>
        <p class="page-subtitle">管理个人资料、团队与订阅偏好。</p>
      </div>
    </div>
    <el-card>
      <el-tabs v-model="tab" :tab-position="mobile ? 'top' : 'left'" class="settings-tabs">
        <el-tab-pane :label="mobile ? '资料' : '个人资料'" name="profile"><el-form label-position="top" class="settings-form"><el-form-item label="头像"><el-upload action="#" list-type="picture-card" :auto-upload="false"><el-icon :size="24"><Plus /></el-icon></el-upload></el-form-item><el-form-item label="姓名"><el-input model-value="林晓" /></el-form-item><el-form-item label="简介"><el-input type="textarea" model-value="负责 Acme Console 的运营与增长。" /></el-form-item><el-form-item label="语言"><el-select model-value="zh-CN"><el-option label="简体中文" value="zh-CN" /><el-option label="English" value="en" /></el-select></el-form-item><el-form-item label="时区"><el-select model-value="Asia/Shanghai" filterable><el-option label="中国标准时间 (UTC+8)" value="Asia/Shanghai" /><el-option
          label="太平洋时间 (UTC-8)"
          value="America/Los_Angeles"
        /></el-select></el-form-item><el-button type="primary" @click="ElMessage.success('资料已保存')">保存更改</el-button></el-form></el-tab-pane>
        <el-tab-pane :label="mobile ? '安全' : '账号安全'" name="security"><el-form label-position="top" class="settings-form"><el-form-item label="当前密码"><el-input type="password" show-password /></el-form-item><el-form-item label="新密码"><el-input type="password" show-password /></el-form-item><el-button type="primary">更新密码</el-button></el-form><el-divider />
          <div class="security-row">
            <div>
              <h3>两步验证</h3>
              <p class="muted">使用验证器应用保护账号。</p>
            </div>
            <el-switch v-model="twoFactor" />
          </div>
          <div v-if="twoFactor" class="qr-placeholder">二维码占位</div>
          <el-divider />
          <h3>活跃会话</h3>
          <el-card v-for="session in sessions" :key="session.device" shadow="never" class="session"><div>
                                                                                                      <b>{{ session.device }}</b>
                                                                                                      <p class="muted">{{ session.location }} · {{ session.time }}</p>
                                                                                                    </div>
            <el-tag v-if="session.current" type="success">当前设备</el-tag><el-button v-else text type="danger">注销</el-button></el-card></el-tab-pane>
        <el-tab-pane label="通知" name="notifications"><el-segmented :options="['邮件', '推送', '站内']" /><el-divider />
          <div v-for="item in ['订单状态更新', '团队动态', '产品公告', '安全提醒']" :key="item" class="security-row">
            <span>{{ item }}</span><el-switch :model-value="item !== '产品公告'" /></div></el-tab-pane>
        <el-tab-pane label="团队" name="team"><div class="invite"><el-input placeholder="成员邮箱" /><el-button type="primary">邀请</el-button></div>
          <el-table :data="team"><el-table-column label="成员" width="150" min-width="150"><template #default="{ row }"><el-avatar :size="28">{{ row.name.slice(0, 1) }}</el-avatar> {{ row.name }}</template></el-table-column><el-table-column prop="email" width="180" min-width="180" label="邮箱" /><el-table-column
            label="角色"
            width="120"
            min-width="120"
          ><template #default="{ row }"><el-select v-model="row.role" size="small"><el-option label="所有者" value="owner" /><el-option label="管理员" value="admin" /><el-option
            label="成员"
            value="member"
          /><el-option label="查看者" value="viewer" /></el-select></template></el-table-column><el-table-column prop="lastActive" width="120" min-width="120" label="最近活跃" /><el-table-column
            label="操作"
            width="100"
            min-width="100"
          ><template #default><el-button text type="danger">移除</el-button></template></el-table-column></el-table></el-tab-pane>
        <el-tab-pane label="计费" name="billing"><el-card shadow="never"><template #header>当前计划</template><strong>Pro · ¥99 / 月</strong>
                                                 <p class="muted">下次续费：2026-10-01</p></el-card><el-row :gutter="12" class="plans"><el-col v-for="plan in plans" :key="plan.name" :xs="24" :md="8"><el-card :class="{ recommended: plan.recommended }"><el-tag v-if="plan.recommended" type="success">推荐</el-tag>
                                                   <h3>{{ plan.name }}</h3>
                                                   <strong class="price">{{ plan.price === null ? "联系销售" : plan.price === 0 ? "免费" : `¥${plan.price}/月` }}</strong>
                                                   <p v-for="feature in plan.features" :key="feature">✓ {{ feature }}</p>
                                                   <el-button :type="plan.recommended ? 'primary' : 'default'" class="full-width">选择计划</el-button></el-card></el-col></el-row>
          <h3>发票</h3>
          <el-table :data="invoices"><el-table-column prop="id" label="编号" /><el-table-column prop="date" label="日期" /><el-table-column
            prop="amount"
            label="金额"
          ><template #default="{ row }">¥{{ row.amount }}</template></el-table-column><el-table-column label="状态"><template #default="{ row }"><el-tag :type="row.status === 'paid' ? 'success' : 'warning'">{{ row.status }}</el-tag></template></el-table-column></el-table></el-tab-pane>
      </el-tabs> </el-card><el-card class="danger-zone"><template #header>危险区</template>
      <p>删除账号将永久移除所有团队数据。</p>
      <el-button type="danger" @click="danger = true">删除账号</el-button></el-card><el-dialog v-model="danger" title="删除账号" width="420px"><p>请输入 DELETE 以确认此操作。</p>
      <el-input v-model="confirm" placeholder="DELETE" /><template #footer><el-button @click="danger = false">取消</el-button><el-button type="danger" @click="removeAccount">确认删除</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.settings-tabs :deep(.el-tab-pane) {
  padding: 0 0 0 28px;
}
.settings-form {
  max-width: 620px;
}
.security-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
.security-row h3 {
  margin: 0;
}
.session {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin: 10px 0;
}
.session p {
  margin: 4px 0 0;
}
.qr-placeholder {
  display: grid;
  width: 140px;
  height: 140px;
  place-items: center;
  margin: 18px 0;
  border: 10px solid var(--el-text-color-primary);
  color: var(--el-bg-color);
  background: repeating-linear-gradient(45deg, var(--el-text-color-primary) 0 4px, var(--el-bg-color) 4px 8px);
  font-size: 12px;
}
.invite {
  display: flex;
  gap: 10px;
  max-width: 480px;
  margin-bottom: 18px;
}
.plans {
  margin: 16px 0 28px;
}
.plans h3 {
  margin-bottom: 8px;
}
.price {
  display: block;
  margin-bottom: 14px;
  font-size: 24px;
}
.recommended {
  border-color: var(--el-color-primary);
}
.danger-zone {
  margin-top: 18px;
  border-color: var(--el-color-danger);
}
@media (max-width: 767px) {
  .settings-tabs :deep(.el-tab-pane) {
    padding: 16px 0 0;
  }
  .settings-tabs :deep(.el-tabs__item) {
    padding: 0 12px;
  }
}
</style>
