// apps/kobalte/src/pages/login.tsx
import { createSignal } from "solid-js"
import { A } from "@solidjs/router"
import { Alert } from "@/ui/alert"
import { Button } from "@/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/ui/card"
import { Checkbox } from "@/ui/checkbox"
import { SectionDivider } from "./shared"
import { TextField } from "@/ui/text-field"
import { Icon } from "@/icons"

export function LoginPage() {
  const [email, setEmail] = createSignal("")
  const [password, setPassword] = createSignal("")
  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal("")
  const [submitted, setSubmitted] = createSignal(false)
  const validEmail = () => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email())
  const submit = (event: SubmitEvent) => {
    event.preventDefault()
    setSubmitted(true)
    if (!validEmail() || !password()) return
    setLoading(true)
    setError("")
    window.setTimeout(() => { setLoading(false); setError("邮箱或密码不正确") }, 1200)
  }
 return <div class="grid min-h-screen place-items-center bg-zinc-50 p-4 dark:bg-zinc-950"><Card class="w-full max-w-md"><CardHeader class="space-y-4"><A href="/" class="flex items-center gap-2 font-semibold"><span class="grid size-8 place-items-center rounded-lg bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900">A</span>Acme Console</A><div><CardTitle class="text-2xl">欢迎回来</CardTitle><CardDescription>登录 Acme Console，继续你的工作。</CardDescription></div></CardHeader><CardContent class="space-y-6">{error() ? <Alert level="error"><div class="flex gap-2"><Icon name="alert-circle" size={18} /><span>{error()}</span></div></Alert> : null}<form class="space-y-5" noValidate onSubmit={submit}><TextField label="邮箱" type="email" placeholder="you@example.com" value={email()} required error={submitted() && !validEmail() ? "请输入有效的邮箱地址" : undefined} onInput={(event) => setEmail(event.currentTarget.value)} prefix={<Icon name="mail" size={16} />} /><TextField label="密码" type="password" placeholder="请输入密码" value={password()} required error={submitted() && !password() ? "请输入密码" : undefined} onInput={(event) => setPassword(event.currentTarget.value)} prefix={<Icon name="lock" size={16} />} /><div class="flex items-center justify-between gap-4"><Checkbox label="记住我" /><A href="#forgot" class="text-sm text-blue-600 hover:underline dark:text-blue-400">忘记密码？</A></div><Button type="submit" class="w-full" loading={loading()}>登录</Button></form><SectionDivider label="或" /><div class="grid gap-2 sm:grid-cols-3"><Button variant="outline"><Icon name="globe" size={16} />Google</Button><Button variant="outline"><Icon name="github" size={16} />GitHub</Button><Button variant="outline"><Icon name="message-circle" size={16} />微信</Button></div></CardContent><CardFooter class="justify-center text-sm text-zinc-500">还没有账户？ <A href="#register" class="ml-1 text-zinc-900 underline dark:text-zinc-100">立即注册</A></CardFooter></Card></div>
}

// apps/primereact/src/pages/login.tsx
import { useState } from "react"
import { Link } from "react-router-dom"
import { Button } from "primereact/button"
import { Card } from "primereact/card"
import { Checkbox } from "primereact/checkbox"
import { Divider } from "primereact/divider"
import { IconField } from "primereact/iconfield"
import { InputIcon } from "primereact/inputicon"
import { InputText } from "primereact/inputtext"
import { Message } from "primereact/message"
import { Password } from "primereact/password"
import { Icon } from "@/components/icon"

export function LoginPage() {
  const [submitted, setSubmitted] = useState(false), [loading, setLoading] = useState(false), [remember, setRemember] = useState(false)
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); setLoading(true); window.setTimeout(() => setLoading(false), 1200) }
  return <div className="min-h-screen flex align-items-center justify-content-center p-3"><Card className="w-full md:w-30rem" title={<Link to="/" className="flex align-items-center gap-2 no-underline text-color"><span className="flex align-items-center justify-content-center border-round bg-primary text-primary-contrast" style={{ width: 32, height: 32 }}>A</span>Acme Console</Link>} subTitle={<div className="mt-4"><h1 className="text-2xl m-0">欢迎回来</h1><p className="font-normal muted">登录 Acme Console，继续你的工作。</p></div>}><div className="flex flex-column gap-4"><Message severity="error" text="演示错误状态：提交空表单时会显示验证错误。" /><form className="flex flex-column gap-3" onSubmit={submit}><label>邮箱<IconField iconPosition="left" className="w-full mt-2"><InputIcon className="pi pi-envelope" /><InputText className={`w-full ${submitted ? "p-invalid" : ""}`} type="email" placeholder="you@example.com" /></IconField>{submitted ? <small className="p-error">请输入工作邮箱。</small> : null}</label><label>密码<Password className="w-full mt-2" inputClassName={`w-full ${submitted ? "p-invalid" : ""}`} toggleMask placeholder="••••••••" feedback={false} />{submitted ? <small className="p-error">请输入密码。</small> : null}</label><div className="flex align-items-center justify-content-between"><label className="flex align-items-center gap-2 text-sm"><Checkbox checked={remember} onChange={(e) => setRemember(Boolean(e.checked))} />记住我</label><a href="#forgot" className="text-sm">忘记密码？</a></div><Button type="submit" label="登录" loading={loading} /></form><Divider align="center">或</Divider><div className="grid"><Button outlined label="Google" icon={<Icon name="globe" />} className="col" /><Button outlined label="GitHub" icon={<Icon name="github" />} className="col" /><Button outlined label="微信" icon={<Icon name="message-circle" />} className="col" /></div><p className="text-center text-sm muted mb-0">还没有账户？ <a href="#register">立即注册</a></p></div></Card></div>
}
