// apps/kobalte/src/pages/dashboard.tsx
import { createSignal, For, onCleanup, onMount, Show } from "solid-js"
import activity from "@ui-gallery/spec/mock/activity.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import series from "@ui-gallery/spec/mock/series.json"
import stats from "@ui-gallery/spec/mock/stats.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import { Icon } from "@/icons"
import { Avatar } from "@/ui/avatar"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/ui/card"
import { ChartCanvas } from "@/ui/chart"
import { DropdownMenu } from "@/ui/dropdown-menu"
import { Progress } from "@/ui/progress"
import { Skeleton } from "@/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/ui/table"
import { Tabs } from "@/ui/tabs"
import { PageHeader, StatusBadge } from "./shared"

const money = (value: number) => `¥${value.toLocaleString()}`

function sparkline(values: number[]) {
  const max = Math.max(...values)
  const min = Math.min(...values)
  return values.map((value, index) => `${(index / (values.length - 1)) * 100},${40 - ((value - min) / Math.max(1, max - min)) * 34}`).join(" ")
}

function Sparkline(props: { values: number[] }) {
  return <svg viewBox="0 0 100 40" class="h-12 w-full text-blue-600" aria-hidden="true"><polyline points={sparkline(props.values)} fill="none" stroke="currentColor" stroke-width="2" /></svg>
}

export function DashboardPage() {
  const [ready, setReady] = createSignal(false)
  onMount(() => {
    if (new URLSearchParams(window.location.search).get("state") === "loading") return
    const timer = window.setTimeout(() => setReady(true), 600)
    onCleanup(() => window.clearTimeout(timer))
  })
  const lineConfig = { type: "line" as const, data: { labels: series.months, datasets: [{ label: "收入", data: series.revenue, borderColor: "#2563eb", backgroundColor: "#2563eb22", fill: true }, { label: "订单", data: series.orders, borderColor: "#10b981", backgroundColor: "#10b98122", fill: true }] }, options: { responsive: true, maintainAspectRatio: false } }
  const barConfig = { type: "bar" as const, data: { labels: series.months, datasets: [{ label: "订单", data: series.orders, backgroundColor: "#2563eb" }] }, options: { responsive: true, maintainAspectRatio: false } }
  const doughnutConfig = { type: "doughnut" as const, data: { labels: series.byChannel.map((item) => item.name), datasets: [{ data: series.byChannel.map((item) => item.value), backgroundColor: ["#2563eb", "#10b981", "#f59e0b", "#71717a"] }] }, options: { responsive: true, maintainAspectRatio: false } }
  return <div class="space-y-6">
    <PageHeader title="仪表盘" description="欢迎回来，林晓。这里是今天的业务概况。" action={<Button><Icon name="plus" />新建项目</Button>} />
    <Show when={ready()} fallback={<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><For each={[1, 2, 3, 4]}>{() => <Card><CardHeader><Skeleton class="h-4 w-24" /><Skeleton class="h-8 w-32" /></CardHeader><CardContent><Skeleton class="h-12 w-full" /></CardContent></Card>}</For></div>}>
      <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><For each={stats}>{(item) => <Card><CardHeader class="pb-2"><div class="flex items-center justify-between text-sm text-zinc-500 dark:text-zinc-400"><CardDescription>{item.label}</CardDescription><Badge variant={item.delta > 0 ? "default" : "destructive"}>{item.delta > 0 ? "↑" : "↓"} {Math.abs(item.delta)}%</Badge></div><CardTitle class="text-2xl">{item.unit === "CNY" ? money(item.value) : `${item.value}${item.unit ?? ""}`}</CardTitle></CardHeader><CardContent><Sparkline values={item.trend} /></CardContent></Card>}</For></div>
      <Tabs.Root defaultValue="month"><Tabs.List class="flex w-fit gap-1 rounded-md bg-zinc-100 p-1 dark:bg-zinc-800"><Tabs.Trigger value="day" class="h-10 min-w-10 rounded px-3 text-sm data-[selected]:bg-white dark:data-[selected]:bg-zinc-700">日</Tabs.Trigger><Tabs.Trigger value="week" class="h-10 min-w-10 rounded px-3 text-sm data-[selected]:bg-white dark:data-[selected]:bg-zinc-700">周</Tabs.Trigger><Tabs.Trigger value="month" class="h-10 min-w-10 rounded px-3 text-sm data-[selected]:bg-white dark:data-[selected]:bg-zinc-700">月</Tabs.Trigger></Tabs.List></Tabs.Root>
      <div class="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><Card><CardHeader><CardTitle>收入趋势</CardTitle><CardDescription>过去 7 个月的收入与订单</CardDescription></CardHeader><CardContent><div class="h-64"><ChartCanvas config={lineConfig} /></div></CardContent></Card><Card><CardHeader><CardTitle>订单渠道</CardTitle><CardDescription>不同渠道的订单分布</CardDescription></CardHeader><CardContent><div class="h-64"><ChartCanvas config={doughnutConfig} /></div></CardContent></Card></div>
      <div class="grid gap-4 xl:grid-cols-3"><Card><CardHeader><CardTitle>订单趋势</CardTitle></CardHeader><CardContent><div class="h-56"><ChartCanvas config={barConfig} /></div></CardContent></Card><Card class="xl:col-span-2"><CardHeader><CardTitle>最近订单</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>订单</TableHead><TableHead>客户</TableHead><TableHead>产品</TableHead><TableHead>状态</TableHead><TableHead class="text-right">金额</TableHead><TableHead class="w-12" /></TableRow></TableHeader><TableBody><For each={orders.slice(0, 5)}>{(order) => <TableRow><TableCell>{order.id}</TableCell><TableCell><div class="flex items-center gap-2"><Avatar name={order.customer} />{order.customer}</div></TableCell><TableCell>{order.product}</TableCell><TableCell><StatusBadge value={order.status} /></TableCell><TableCell class="text-right tabular-nums">{money(order.amount)}</TableCell><TableCell><DropdownMenu.Root><DropdownMenu.Trigger as={Button} variant="ghost" size="icon" aria-label="订单操作">⋯</DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content class="z-50 rounded-md border border-zinc-200 bg-white p-1 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><DropdownMenu.Item class="min-h-10 px-3 py-2 text-sm">查看</DropdownMenu.Item><DropdownMenu.Item class="min-h-10 px-3 py-2 text-sm">编辑</DropdownMenu.Item><DropdownMenu.Item class="min-h-10 px-3 py-2 text-sm text-red-600 dark:text-red-400">删除</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root></TableCell></TableRow>}</For></TableBody></Table></CardContent></Card></div>
      <div class="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>团队动态</CardTitle></CardHeader><CardContent class="grid gap-4"><For each={activity}>{(item) => <div class="flex gap-3"><Avatar name={item.user} /><div class="min-w-0 flex-1 text-sm"><p><strong>{item.user}</strong> {item.action}</p><p class="text-xs text-zinc-500 dark:text-zinc-400">{item.time}</p></div></div>}</For></CardContent></Card><Card><CardHeader><CardTitle>任务进度</CardTitle></CardHeader><CardContent class="grid gap-5"><For each={tasks}>{(task) => <Progress value={task.progress} label={task.title} />}</For></CardContent></Card></div>
    </Show>
  </div>
}

// apps/shadcn-svelte/src/routes/Dashboard.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import { ArrowDownRight, ArrowUpRight, MoreHorizontal } from "@lucide/svelte"
  import stats from "@ui-gallery/spec/mock/stats.json"
  import series from "@ui-gallery/spec/mock/series.json"
  import orders from "@ui-gallery/spec/mock/orders.json"
  import activity from "@ui-gallery/spec/mock/activity.json"
  import tasks from "@ui-gallery/spec/mock/tasks.json"
  import * as Card from "$lib/components/ui/card"
  import * as Badge from "$lib/components/ui/badge"
  import * as Avatar from "$lib/components/ui/avatar"
  import * as Progress from "$lib/components/ui/progress"
  import * as Skeleton from "$lib/components/ui/skeleton"
  import * as Tabs from "$lib/components/ui/tabs"
  import * as Dropdown from "$lib/components/ui/dropdown-menu"

  let loading = $state(new URLSearchParams(window.location.search).get("state") === "loading")
  let period = $state("周")
  const statsMap = Object.fromEntries(stats.map((stat) => [stat.key, stat])) as Record<
    string,
    { value: number; delta: number; trend: number[] }
  >
  onMount(() => {
    if (!loading) setTimeout(() => (loading = false), 600)
  })
  const cards = [
    { key: "revenue", label: "总收入", unit: "¥", format: (v: number) => v.toLocaleString() },
    { key: "orders", label: "订单数", unit: "", format: (v: number) => v.toLocaleString() },
    { key: "users", label: "活跃用户", unit: "", format: (v: number) => v.toLocaleString() },
    { key: "conversion", label: "转化率", unit: "", format: (v: number) => `${v}%` },
  ] as const
</script>

{#if loading}
  <div class="space-y-6">
    <div><Skeleton.Root class="h-8 w-40" /><Skeleton.Root class="mt-2 h-4 w-64" /></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {#each cards as _}<Skeleton.Root class="h-32 rounded-xl" />{/each}
    </div>
    <Skeleton.Root class="h-72 rounded-xl" />
  </div>
{:else}
  <div class="space-y-6">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">仪表盘</h1>
      <p class="text-sm text-muted-foreground">查看业务指标和团队最新动态。</p>
    </div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {#each cards as card}
        {@const value = statsMap[card.key]}
        <Card.Root
          ><Card.Header class="flex flex-row items-center justify-between space-y-0 pb-2"
            ><Card.Title class="text-sm font-medium">{card.label}</Card.Title><span
              class="text-xs text-muted-foreground">{card.key === "revenue" ? "本月" : "同比"}</span
            ></Card.Header
          ><Card.Content
            ><div class="text-2xl font-bold">{card.unit}{card.format(value.value)}</div>
            <div
              class="mt-1 flex items-center gap-1 text-xs {value.delta >= 0
                ? 'text-emerald-600'
                : 'text-destructive'}"
            >
              {#if value.delta >= 0}<ArrowUpRight class="size-3" />{:else}<ArrowDownRight
                  class="size-3"
                />{/if}{Math.abs(value.delta)}% <span class="text-muted-foreground">较上期</span>
            </div>
            <svg
              class="mt-3 h-8 w-full"
              viewBox="0 0 120 30"
              preserveAspectRatio="none"
              aria-label="趋势"
              ><polyline
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                points={value.trend
                  .map(
                    (point: number, i: number) =>
                      `${i * 20},${28 - (point / Math.max(...value.trend)) * 24}`
                  )
                  .join(" ")}
              /></svg
            ></Card.Content
          ></Card.Root
        >
      {/each}
    </div>
    <Tabs.Root bind:value={period} class="space-y-4">
      <Tabs.List
        ><Tabs.Trigger value="日">日</Tabs.Trigger><Tabs.Trigger value="周">周</Tabs.Trigger
        ><Tabs.Trigger value="月">月</Tabs.Trigger></Tabs.List
      >
      <Tabs.Content value={period}
        ><div class="grid gap-4 lg:grid-cols-3">
          <Card.Root class="lg:col-span-2"
            ><Card.Header
              ><Card.Title>收入趋势</Card.Title><Card.Description
                >近七个月的收入变化</Card.Description
              ></Card.Header
            ><Card.Content
              ><svg
                class="h-56 w-full overflow-visible"
                viewBox="0 0 700 220"
                preserveAspectRatio="none"
                ><polyline
                  fill="none"
                  stroke="hsl(var(--primary))"
                  stroke-width="3"
                  points={series.revenue.map((point, i) => `${i * 116},${210 - point}`).join(" ")}
                />{#each series.revenue as point, i}<circle
                    cx={i * 116}
                    cy={210 - point}
                    r="4"
                    fill="hsl(var(--primary))"
                  />{/each}</svg
              >
              <div class="flex justify-between text-xs text-muted-foreground">
                {#each series.months as month}<span>{month}</span>{/each}
              </div></Card.Content
            ></Card.Root
          >
          <Card.Root
            ><Card.Header
              ><Card.Title>渠道分布</Card.Title><Card.Description>订单来源占比</Card.Description
              ></Card.Header
            ><Card.Content class="flex items-center justify-center"
              ><div
                class="relative flex size-44 items-center justify-center rounded-full"
                style="background: conic-gradient(hsl(var(--primary)) 0 52%, hsl(var(--chart-2)) 52% 75%, hsl(var(--chart-3)) 75% 92%, hsl(var(--chart-4)) 92% 100%)"
              >
                <div
                  class="flex size-24 items-center justify-center rounded-full bg-background text-center text-xs text-muted-foreground"
                >
                  渠道<br />占比
                </div>
              </div></Card.Content
            ><Card.Footer class="grid grid-cols-2 gap-2 text-xs"
              >{#each series.byChannel as channel}<div class="flex justify-between">
                  <span>{channel.name}</span><span class="font-medium">{channel.value}%</span>
                </div>{/each}</Card.Footer
            ></Card.Root
          >
        </div></Tabs.Content
      >
    </Tabs.Root>
    <div class="grid gap-4 xl:grid-cols-3">
      <Card.Root class="xl:col-span-2"
        ><Card.Header><Card.Title>最近订单</Card.Title></Card.Header><Card.Content
          ><div class="overflow-x-auto">
            <table class="w-full text-sm">
              <thead
                ><tr class="border-b text-left text-muted-foreground"
                  ><th class="pb-3">客户</th><th class="pb-3">产品</th><th class="pb-3">状态</th><th
                    class="pb-3 text-right">金额</th
                  ><th></th></tr
                ></thead
              ><tbody
                >{#each orders.slice(0, 5) as order}<tr class="border-b last:border-0"
                    ><td class="py-3"
                      ><div class="flex items-center gap-2">
                        <Avatar.Root class="size-7"
                          ><Avatar.Fallback>{order.customer.slice(0, 1)}</Avatar.Fallback
                          ></Avatar.Root
                        ><span>{order.customer}</span>
                      </div></td
                    ><td>{order.product}</td><td
                      ><Badge.Root variant={order.status === "paid" ? "default" : "secondary"}
                        >{order.status}</Badge.Root
                      ></td
                    ><td class="text-right">{order.currency}{order.amount}</td><td
                      class="text-right"
                      ><Dropdown.Root
                        ><Dropdown.Trigger
                          ><button class="rounded p-1 hover:bg-muted" aria-label="订单操作"
                            ><MoreHorizontal class="size-4" /></button
                          ></Dropdown.Trigger
                        ><Dropdown.Content
                          ><Dropdown.Item>查看详情</Dropdown.Item><Dropdown.Item
                            >复制订单号</Dropdown.Item
                          ></Dropdown.Content
                        ></Dropdown.Root
                      ></td
                    ></tr
                  >{/each}</tbody
              >
            </table>
          </div></Card.Content
        ></Card.Root
      >
      <div class="space-y-4">
        <Card.Root
          ><Card.Header><Card.Title>团队动态</Card.Title></Card.Header><Card.Content
            ><div class="space-y-4">
              {#each activity as item}<div class="flex gap-3">
                  <span class="mt-1.5 size-2 shrink-0 rounded-full bg-primary"></span>
                  <div class="text-sm">
                    <p>{item.user} {item.action}</p>
                    <p class="text-xs text-muted-foreground">{item.time}</p>
                  </div>
                </div>{/each}
            </div></Card.Content
          ></Card.Root
        ><Card.Root
          ><Card.Header><Card.Title>任务进度</Card.Title></Card.Header><Card.Content
            class="space-y-4"
            >{#each tasks as task}<div class="space-y-1">
                <div class="flex justify-between text-sm">
                  <span>{task.title}</span><span class="text-muted-foreground"
                    >{task.progress}%</span
                  >
                </div>
                <Progress.Root value={task.progress} />
              </div>{/each}</Card.Content
          ></Card.Root
        >
      </div>
    </div>
  </div>
{/if}
