// apps/radix-themes/src/pages/form.tsx
import { useState } from "react"
import {
  Badge,
  Box,
  Button,
  Card,
  Checkbox,
  CheckboxGroup,
  Flex,
  Heading,
  Popover,
  RadioGroup,
  Select,
  Separator,
  Slider,
  Switch,
  Text,
  TextArea,
  TextField,
  Tooltip,
} from "@radix-ui/themes"
import team from "@ui-gallery/spec/mock/team.json"
import { Icon } from "@/icons"
import { FieldLabel, Help, PageHeader } from "./shared"

export function FormPage() {
  const [step, setStep] = useState(1)
  const [name, setName] = useState("")
  const [tags, setTags] = useState<string[]>([])
  const [tag, setTag] = useState("")
  const [done, setDone] = useState(false)
  const [assignee, setAssignee] = useState("")
  const [agree, setAgree] = useState(false)
  const addTag = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter" && tag.trim()) {
      event.preventDefault()
      setTags((current) => [...current, tag.trim()])
      setTag("")
    }
  }
  return (
    <Box>
      <PageHeader title="新建项目" description="用三步完成项目配置。" />
      <Flex align="center" gap="2" mb="6">
        {["基本信息", "详细配置", "确认"].map((label, index) => (
          <Flex key={label} align="center" gap="2" flexGrow="1" minWidth="0">
            <Badge size="3" color={step >= index + 1 ? "indigo" : "gray"}>
              {index + 1}
            </Badge>
            <Text
              size="2"
              weight={step === index + 1 ? "bold" : "regular"}
              style={{ whiteSpace: "nowrap", flexShrink: 0 }}
            >
              {label}
            </Text>
            {index < 2 ? <Separator size="4" style={{ flexGrow: 1 }} /> : null}
          </Flex>
        ))}
      </Flex>
      {done ? (
        <Card>
          <Flex direction="column" align="center" gap="4" p="6">
            <Icon name="check-circle" size={40} />
            <Heading size="6">项目创建成功</Heading>
            <Text color="gray">你的配置已经保存。</Text>
            <Button
              onClick={() => {
                setDone(false)
                setStep(1)
              }}
            >
              创建另一个
            </Button>
          </Flex>
        </Card>
      ) : (
        <Card>
          <Flex direction="column" gap="5">
            {step === 1 ? (
              <>
                <label>
                  <FieldLabel required>项目名称</FieldLabel>
                  <TextField.Root
                    mt="2"
                    value={name}
                    onChange={(event) => setName(event.target.value)}
                    placeholder="输入项目名称"
                  />
                </label>
                {!name ? (
                  <Text size="1" color="red">
                    项目名称为必填项
                  </Text>
                ) : null}
                <label>
                  <FieldLabel>预算</FieldLabel>
                  <TextField.Root mt="2" type="number" placeholder="0" />
                </label>
                <label>
                  <FieldLabel required>联系邮箱</FieldLabel>
                  <TextField.Root
                    mt="2"
                    type="email"
                    placeholder="user@example.com"
                  />
                </label>
                <label>
                  <FieldLabel>联系电话</FieldLabel>
                  <Flex mt="2" gap="2">
                    <Select.Root defaultValue="+86">
                      <Select.Trigger />
                      <Select.Content>
                        <Select.Item value="+86">+86</Select.Item>
                        <Select.Item value="+1">+1</Select.Item>
                        <Select.Item value="+44">+44</Select.Item>
                      </Select.Content>
                    </Select.Root>
                    <TextField.Root
                      placeholder="手机号"
                      style={{ flexGrow: 1, minWidth: 0 }}
                    />
                  </Flex>
                </label>
                <label>
                  <FieldLabel>项目说明</FieldLabel>
                  <TextArea mt="2" placeholder="描述项目目标" />
                  <Help>最多 500 字</Help>
                </label>
                <RadioGroup.Root defaultValue="internal">
                  <Flex gap="4">
                    <RadioGroup.Item value="internal">内部</RadioGroup.Item>
                    <RadioGroup.Item value="external">外部</RadioGroup.Item>
                  </Flex>
                </RadioGroup.Root>
                <CheckboxGroup.Root defaultValue={["analytics"]}>
                  <Flex direction="column" gap="2">
                    <CheckboxGroup.Item value="analytics">
                      启用分析
                    </CheckboxGroup.Item>
                    <CheckboxGroup.Item value="reports">
                      每周报告
                    </CheckboxGroup.Item>
                  </Flex>
                </CheckboxGroup.Root>
                <Flex align="center" gap="3">
                  <Switch defaultChecked />
                  <Text size="2">启用通知</Text>
                </Flex>
              </>
            ) : step === 2 ? (
              <>
                <label>
                  <FieldLabel>项目负责人</FieldLabel>
                  <Popover.Root>
                    <Popover.Trigger>
                      <TextField.Root
                        mt="2"
                        value={assignee}
                        onChange={(event) => setAssignee(event.target.value)}
                        placeholder="搜索团队成员"
                      />
                    </Popover.Trigger>
                    <Popover.Content>
                      <Flex direction="column" gap="1">
                        {team.map((member) => (
                          <Button
                            key={member.email}
                            variant="ghost"
                            onClick={() => setAssignee(member.name)}
                          >
                            {member.name}
                          </Button>
                        ))}
                      </Flex>
                    </Popover.Content>
                  </Popover.Root>
                </label>
                <label>
                  <FieldLabel>项目类型</FieldLabel>
                  <Select.Root defaultValue="product">
                    <Select.Trigger mt="2" />
                    <Select.Content>
                      <Select.Item value="product">产品</Select.Item>
                      <Select.Item value="marketing">营销</Select.Item>
                      <Select.Item value="research">研究</Select.Item>
                    </Select.Content>
                  </Select.Root>
                </label>
                <label>
                  <FieldLabel>计划日期</FieldLabel>
                  <Flex gap="2" mt="2">
                    <TextField.Root type="date" />
                    <TextField.Root type="time" />
                  </Flex>
                </label>
                <label>
                  <FieldLabel>日期范围</FieldLabel>
                  <Flex gap="2" mt="2">
                    <TextField.Root type="date" />
                    <TextField.Root type="date" />
                  </Flex>
                </label>
                <label>
                  <FieldLabel>预算区间</FieldLabel>
                  <Slider defaultValue={[20, 80]} mt="3" />
                </label>
                <Flex direction="column" gap="2">
                  <FieldLabel>评分</FieldLabel>
                  <Flex>
                    {[1, 2, 3, 4, 5].map((value) => (
                      <Button key={value} size="1" variant="ghost">
                        <Icon name={value <= 4 ? "star" : "star"} />
                      </Button>
                    ))}
                  </Flex>
                </Flex>
                <Flex align="center" gap="3">
                  <FieldLabel>颜色</FieldLabel>
                  <Box asChild>
                    <input
                      type="color"
                      defaultValue="#888888"
                      aria-label="颜色"
                    />
                  </Box>
                </Flex>
                <Box p="5" style={{ border: "1px dashed var(--gray-a7)" }}>
                  <Flex direction="column" align="center" gap="2">
                    <Icon name="upload" size={28} />
                    <Text>拖拽文件到这里</Text>
                    <Button variant="outline">选择文件</Button>
                  </Flex>
                </Box>
                <label>
                  <FieldLabel>标签</FieldLabel>
                  <TextField.Root
                    mt="2"
                    value={tag}
                    onChange={(event) => setTag(event.target.value)}
                    onKeyDown={addTag}
                    placeholder="输入后按 Enter"
                  />
                </label>
                <Flex gap="2" wrap="wrap">
                  {tags.map((value) => (
                    <Badge key={value}>{value}</Badge>
                  ))}
                </Flex>
                <Tooltip content="项目成员可以在创建后继续编辑">
                  <Button variant="ghost" size="1">
                    <Icon name="info" />
                    需要帮助？
                  </Button>
                </Tooltip>
              </>
            ) : (
              <>
                <Heading size="4">确认项目配置</Heading>
                <Box>
                  <Text color="gray">项目名称</Text>
                  <Text as="div" weight="medium">
                    {name || "未填写"}
                  </Text>
                </Box>
                <Box>
                  <Text color="gray">负责人</Text>
                  <Text as="div" weight="medium">
                    {assignee || "未选择"}
                  </Text>
                </Box>
                <Flex align="center" gap="2">
                  <Checkbox
                    checked={agree}
                    onCheckedChange={(value) => setAgree(value === true)}
                  />
                  <Text>我同意服务条款</Text>
                </Flex>
              </>
            )}
            {step < 3 ? (
              <Flex justify="end" gap="3">
                <Button
                  disabled={step === 1 && !name}
                  onClick={() => setStep((value) => value + 1)}
                >
                  下一步
                </Button>
              </Flex>
            ) : (
              <Flex justify="end" gap="3">
                <Button variant="soft" onClick={() => setStep(2)}>
                  上一步
                </Button>
                <Button disabled={!agree} onClick={() => setDone(true)}>
                  提交
                </Button>
              </Flex>
            )}
          </Flex>
        </Card>
      )}
    </Box>
  )
}

// apps/shadcn-svelte/src/routes/Form.svelte
<script lang="ts">
  import { Check, ChevronLeft, ChevronRight, Info, Upload, X } from "@lucide/svelte"
  import { Button } from "$lib/components/ui/button"
  import * as Card from "$lib/components/ui/card"
  import * as Badge from "$lib/components/ui/badge"
  import * as Checkbox from "$lib/components/ui/checkbox"
  import * as Radio from "$lib/components/ui/radio-group"
  import * as Switch from "$lib/components/ui/switch"
  import * as Slider from "$lib/components/ui/slider"
  import * as Popover from "$lib/components/ui/popover"
  import * as Calendar from "$lib/components/ui/calendar"
  import * as Empty from "$lib/components/ui/empty"
  import * as Item from "$lib/components/ui/item"
  import * as Tooltip from "$lib/components/ui/tooltip"

  let step = $state(Number(new URLSearchParams(window.location.search).get("step") ?? "1"))
  let name = $state(""),
    email = $state(""),
    description = $state(""),
    range = $state([20, 60]),
    accepted = $state(false),
    done = $state(false)
  let tags = $state(["设计", "产品"])
  let error = $state("")
  const steps = ["基本信息", "详细配置", "确认"]
  function next() {
    if (step === 1 && (!name || !email.includes("@"))) {
      error = "请填写必填字段并检查邮箱格式"
      return
    }
    error = ""
    step = Math.min(3, step + 1)
  }
</script>

<div class="space-y-6">
  <div>
    <h1 class="text-2xl font-semibold">创建项目</h1>
    <p class="text-sm text-muted-foreground">用三步完成项目初始化。</p>
  </div>
  <div class="mx-auto flex max-w-2xl items-center justify-between">
    {#each steps as label, i}<div class="flex items-center gap-2">
        <div
          class="flex size-8 items-center justify-center rounded-full {step >= i + 1
            ? 'bg-primary text-primary-foreground'
            : 'border text-muted-foreground'}"
        >
          {step > i + 1 ? "✓" : i + 1}
        </div>
        <span class="hidden text-sm sm:inline">{label}</span>
      </div>
      {#if i < 2}<div class="h-px flex-1 bg-border"></div>{/if}{/each}
  </div>
  <Card.Root class="mx-auto max-w-3xl"
    ><Card.Content class="space-y-6 p-6">
      {#if error}<p class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
          {error}
        </p>{/if}
      {#if step === 1}
        <div class="grid gap-4 sm:grid-cols-2">
          <label class="space-y-2 text-sm font-medium"
            >项目名称 *<input
              bind:value={name}
              aria-invalid={!name && !!error}
              class="h-9 w-full rounded-md border px-3"
              placeholder="例如：增长计划"
            /></label
          ><label class="space-y-2 text-sm font-medium"
            >预算<input
              type="number"
              class="h-9 w-full rounded-md border px-3"
              placeholder="10000"
            /></label
          ><label class="space-y-2 text-sm font-medium"
            >邮箱 *<input
              type="email"
              bind:value={email}
              aria-invalid={!!error}
              class="h-9 w-full rounded-md border px-3"
              placeholder="team@example.com"
            /></label
          ><label class="space-y-2 text-sm font-medium"
            >联系电话<input
              type="tel"
              class="h-9 w-full rounded-md border px-3"
              placeholder="+86 138..."
            /></label
          >
        </div>
        <label class="space-y-2 text-sm font-medium"
          >项目说明<textarea
            bind:value={description}
            maxlength="200"
            class="min-h-28 w-full rounded-md border p-3"
            placeholder="简要介绍项目目标..."
          ></textarea><span class="block text-xs text-muted-foreground"
            >{description.length}/200</span
          ></label
        >
        <div class="space-y-3">
          <p class="text-sm font-medium">项目类型</p>
          <Radio.Root value="internal" class="flex items-center gap-2 whitespace-nowrap"
            ><Radio.Item value="internal" />内部项目</Radio.Root
          ><Radio.Root value="client" class="flex items-center gap-2 whitespace-nowrap"
            ><Radio.Item value="client" />客户项目</Radio.Root
          >
        </div>
        <div class="flex flex-wrap gap-4 text-sm">
          <label class="inline-flex items-center gap-2 whitespace-nowrap"
            ><Checkbox.Root />需要审批</label
          >
          <label class="inline-flex items-center gap-2 whitespace-nowrap"
            ><Switch.Root />启用通知</label
          >
        </div>
      {:else if step === 2}
        <div class="grid gap-5 sm:grid-cols-2">
          <label class="space-y-2 text-sm font-medium"
            >优先级<select class="h-9 w-full rounded-md border bg-background px-3"
              ><option>标准</option><option>高</option><option>紧急</option></select
            ></label
          ><label class="space-y-2 text-sm font-medium"
            >开始时间<input
              type="time"
              class="h-9 w-full rounded-md border px-3"
              value="09:00"
            /></label
          ><label class="space-y-2 text-sm font-medium"
            >开始日期<input type="date" class="h-9 w-full rounded-md border px-3" /></label
          ><label class="space-y-2 text-sm font-medium"
            >结束日期<input type="date" class="h-9 w-full rounded-md border px-3" /></label
          >
        </div>
        <div class="space-y-3">
          <div class="flex items-center gap-2 text-sm font-medium">
            预算范围 <Tooltip.Root
              ><Tooltip.Trigger><Info class="size-4 text-muted-foreground" /></Tooltip.Trigger
              ><Tooltip.Content>拖动两个滑块设置范围</Tooltip.Content></Tooltip.Root
            >
          </div>
          <Slider.Root type="multiple" bind:value={range} min={0} max={100} step={1} />
          <div class="flex justify-between text-xs text-muted-foreground">
            <span>{range[0]}%</span><span>{range[1]}%</span>
          </div>
        </div>
        <div>
          <p class="mb-2 text-sm font-medium">标签</p>
          <div class="flex flex-wrap gap-2">
            {#each tags as tag}<Badge.Root variant="secondary"
                >{tag}<button
                  class="ml-1"
                  onclick={() => (tags = tags.filter((item) => item !== tag))}
                  ><X class="size-3" /></button
                ></Badge.Root
              >{/each}<input class="h-8 w-24 rounded border px-2 text-sm" placeholder="添加标签" />
          </div>
        </div>
        <div class="rounded-lg border border-dashed p-8 text-center">
          <Upload class="mx-auto mb-2 size-6 text-muted-foreground" />
          <p class="text-sm font-medium">拖拽文件到此处上传</p>
          <p class="text-xs text-muted-foreground">支持 PDF、PNG、DOCX</p>
        </div>
        <Item.Root variant="outline"
          ><Item.Media variant="icon"><Upload /></Item.Media><Item.Content
            ><Item.Title>项目资料.pdf</Item.Title><Item.Description
              >2.4 MB · 已上传</Item.Description
            ></Item.Content
          ></Item.Root
        >
      {:else if !done}
        <h2 class="text-lg font-semibold">确认项目资料</h2>
        <dl class="grid gap-3 rounded-lg bg-muted/40 p-4 text-sm sm:grid-cols-2">
          <div>
            <dt class="text-muted-foreground">项目名称</dt>
            <dd>{name || "未填写"}</dd>
          </div>
          <div>
            <dt class="text-muted-foreground">邮箱</dt>
            <dd>{email || "未填写"}</dd>
          </div>
          <div>
            <dt class="text-muted-foreground">项目说明</dt>
            <dd>{description || "未填写"}</dd>
          </div>
          <div>
            <dt class="text-muted-foreground">预算范围</dt>
            <dd>{range[0]}% - {range[1]}%</dd>
          </div>
        </dl>
        <label class="flex items-center gap-2 text-sm"
          ><Checkbox.Root bind:checked={accepted} />我已阅读并同意服务条款</label
        >
      {:else}<Empty.Root
          ><Empty.Header
            ><Empty.Media variant="icon"><Check /></Empty.Media><Empty.Title
              >项目创建成功</Empty.Title
            ><Empty.Description>项目已创建，可以开始协作。</Empty.Description></Empty.Header
          ><Button onclick={() => (done = false)}>创建另一个项目</Button></Empty.Root
        >{/if}
    </Card.Content><Card.Footer class="justify-between"
      >{#if step > 1 && !done}<Button variant="outline" onclick={() => (step -= 1)}
          ><ChevronLeft class="mr-1 size-4" />上一步</Button
        >{:else}<span></span>{/if}{#if !done}{#if step < 3}<Button onclick={next}
            >下一步<ChevronRight class="ml-1 size-4" /></Button
          >{:else}<Button disabled={!accepted} onclick={() => (done = true)}>提交项目</Button
          >{/if}{/if}</Card.Footer
    ></Card.Root
  >
</div>
