// apps/heroui/src/pages/landing.tsx
import { useNavigate } from "react-router-dom"
import { Accordion, Avatar, Button, Card, Chip, Separator } from "@heroui/react"
import { Icon } from "@ui-gallery/icons-react"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { Brand } from "@/layouts/app-shell"

export function LandingPage() {
  const navigate = useNavigate()
  return (
    <div className="min-h-svh bg-background text-foreground">
      <header className="sticky top-0 z-10 border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4">
          <Brand />
          <nav className="hidden gap-6 text-sm text-muted md:flex"><a href="#features">功能</a><a href="#pricing">定价</a><a href="#faq">常见问题</a></nav>
          <div className="flex gap-2"><Button variant="ghost" size="sm" onPress={() => navigate("/login")}>登录</Button><Button size="sm" onPress={() => navigate("/login")}>{landing.hero.primary}</Button></div>
        </div>
      </header>
      <section className="mx-auto max-w-6xl px-4 py-20 text-center">
        <Chip variant="soft" color="accent" className="mb-4">{landing.hero.social}</Chip>
        <h1 className="mx-auto max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">{landing.hero.title}</h1>
        <p className="mx-auto mt-4 max-w-2xl text-lg text-muted">{landing.hero.subtitle}</p>
        <div className="mt-8 flex flex-wrap justify-center gap-3"><Button size="lg" onPress={() => navigate("/login")}>{landing.hero.primary}<Icon name="arrow-right" size={16} /></Button><Button size="lg" variant="secondary" onPress={() => navigate("/")}>{landing.hero.secondary}</Button></div>
        <div className="mt-14 aspect-video w-full overflow-hidden rounded-2xl border border-border bg-surface-secondary">
          <div className="grid h-full grid-cols-3 gap-3 p-4">
            {landing.numbers.map((item) => <div key={item.label} className="rounded-xl bg-surface p-4 text-left"><p className="text-2xl font-semibold">{item.value}</p><p className="text-xs text-muted">{item.label}</p></div>)}
          </div>
        </div>
      </section>
      <section id="features" className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">一切功能，一个控制台</h2>
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {landing.features.map((feature) => (
            <Card key={feature.title}>
              <Card.Header>
                <div className="mb-2 grid size-10 place-items-center rounded-lg bg-accent-soft text-accent-soft-foreground"><Icon name={feature.icon} size={20} /></div>
                <Card.Title>{feature.title}</Card.Title>
                <Card.Description>{feature.desc}</Card.Description>
              </Card.Header>
            </Card>
          ))}
        </div>
      </section>
      <section className="border-y border-border bg-surface-secondary">
        <div className="mx-auto grid max-w-6xl gap-6 px-4 py-14 sm:grid-cols-2 lg:grid-cols-4">
          {landing.numbers.map((item) => <div key={item.label} className="text-center"><p className="text-4xl font-semibold">{item.value}</p><p className="mt-1 text-sm text-muted">{item.label}</p></div>)}
        </div>
      </section>
      <section id="pricing" className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">简单透明的定价</h2>
        <div className="mt-10 grid gap-4 md:grid-cols-3">
          {plans.map((plan) => (
            <Card key={plan.name} className={plan.recommended ? "border-accent shadow-lg" : undefined}>
              <Card.Header>
                <div className="flex items-center justify-between"><Card.Title>{plan.name}</Card.Title>{plan.recommended ? <Chip color="accent" size="sm">推荐</Chip> : null}</div>
                <p className="text-3xl font-semibold">{plan.price === null ? "定制" : plan.price === 0 ? "¥0" : `¥${plan.price}`}<span className="text-sm font-normal text-muted">{plan.price ? " /月" : ""}</span></p>
              </Card.Header>
              <Card.Content><ul className="space-y-2 text-sm">{plan.features.map((f) => <li key={f} className="flex items-center gap-2"><Icon name="check" size={14} />{f}</li>)}</ul></Card.Content>
              <Card.Footer><Button fullWidth variant={plan.recommended ? "primary" : "secondary"}>{plan.price === null ? "联系销售" : "开始使用"}</Button></Card.Footer>
            </Card>
          ))}
        </div>
      </section>
      <section className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">客户怎么说</h2>
        <div className="mt-10 flex snap-x gap-4 overflow-x-auto pb-4">
          {landing.testimonials.map((item) => (
            <Card key={item.name} className="w-72 shrink-0 snap-start">
              <Card.Content className="space-y-4">
                <p className="text-sm">“{item.quote}”</p>
                <div className="flex items-center gap-3"><Avatar size="sm"><Avatar.Fallback>{item.name.slice(0, 1)}</Avatar.Fallback></Avatar><div><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted">{item.company}</p></div></div>
              </Card.Content>
            </Card>
          ))}
        </div>
      </section>
      <section id="faq" className="mx-auto max-w-3xl px-4 py-16">
        <h2 className="text-center text-3xl font-semibold">常见问题</h2>
        <Accordion className="mt-8">
          {landing.faq.map((item, index) => (
            <Accordion.Item key={item.q} id={`faq-${index}`}>
              <Accordion.Heading><Accordion.Trigger>{item.q}<Accordion.Indicator /></Accordion.Trigger></Accordion.Heading>
              <Accordion.Panel><Accordion.Body>{item.a}</Accordion.Body></Accordion.Panel>
            </Accordion.Item>
          ))}
        </Accordion>
      </section>
      <section className="mx-auto max-w-6xl px-4 pb-20">
        <div className="rounded-2xl bg-accent px-6 py-14 text-center text-accent-foreground">
          <h2 className="text-3xl font-semibold">{landing.hero.title}</h2>
          <p className="mt-2 opacity-90">{landing.hero.subtitle}</p>
          <Button className="mt-6" variant="secondary" size="lg" onPress={() => navigate("/login")}>{landing.hero.primary}</Button>
        </div>
      </section>
      <footer className="border-t border-border">
        <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 text-sm text-muted sm:flex-row sm:items-center sm:justify-between">
          <Brand />
          <Separator orientation="vertical" className="hidden h-4 sm:block" />
          <p>© 2026 Acme Console · HeroUI 参考实现</p>
        </div>
      </footer>
    </div>
  )
}

// apps/shadcn-svelte/src/routes/Landing.svelte
<script lang="ts">
  import landing from "@ui-gallery/spec/mock/landing.json"
  import plans from "@ui-gallery/spec/mock/plans.json"
  import Icon from "$lib/icons/Icon.svelte"
  import { Button } from "$lib/components/ui/button"
  import * as Card from "$lib/components/ui/card"
  import * as Badge from "$lib/components/ui/badge"
  import * as Accordion from "$lib/components/ui/accordion"
  import * as AspectRatio from "$lib/components/ui/aspect-ratio"
  import * as Avatar from "$lib/components/ui/avatar"
  import * as Sheet from "$lib/components/ui/sheet"
  let yearly = $state(false)
  let mobileOpen = $state(false)
</script>

<div class="min-h-screen bg-background">
  <nav class="mx-auto flex max-w-6xl items-center justify-between px-4 py-5">
    <a href="/" class="flex items-center gap-2 font-semibold"
      ><span
        class="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"
        ><Icon name="sparkles" size={16} /></span
      >Acme Console</a
    >
    <div class="hidden items-center gap-6 text-sm text-muted-foreground md:flex">
      <a href="#features">功能</a><a href="#product">产品</a><a href="#pricing">定价</a><a
        href="#stories">客户故事</a
      ><a href="#faq">FAQ</a>
    </div>
    <div class="flex items-center gap-2">
      <Button variant="ghost" class="hidden sm:inline-flex">登录</Button><Button
        class="hidden sm:inline-flex">免费开始</Button
      ><Button
        variant="ghost"
        size="icon"
        class="md:hidden"
        aria-label="菜单"
        onclick={() => (mobileOpen = true)}><Icon name="menu" size={16} /></Button
      >
    </div>
  </nav>
  <main>
    <section
      class="mx-auto grid max-w-6xl items-center gap-10 px-4 pt-16 pb-20 lg:grid-cols-2 lg:pt-24"
    >
      <div>
        <Badge.Root variant="secondary">新一代团队工作台</Badge.Root>
        <h1 class="mt-5 text-4xl font-bold tracking-tight sm:text-6xl">{landing.hero.title}</h1>
        <p class="mt-5 text-lg text-muted-foreground">{landing.hero.subtitle}</p>
        <div class="mt-8 flex flex-wrap gap-3">
          <Button size="lg"
            >{landing.hero.primary}<Icon name="arrow-right" size={16} class="ml-2" /></Button
          ><Button size="lg" variant="outline">{landing.hero.secondary}</Button>
        </div>
        <div class="mt-8 flex items-center gap-3">
          <div class="flex -space-x-2">
            {#each ["林", "王", "A", "M", "陈"] as initial}<Avatar.Root
                class="size-9 border-2 border-background"
                ><Avatar.Fallback>{initial}</Avatar.Fallback></Avatar.Root
              >{/each}
          </div>
          <span class="text-sm text-muted-foreground">{landing.hero.social}</span>
        </div>
      </div>
      <AspectRatio.Root
        ratio={16 / 10}
        class="overflow-hidden rounded-2xl border bg-muted shadow-2xl"
        ><div class="flex h-full flex-col p-5">
          <div class="mb-5 flex gap-2">
            <span class="size-3 rounded-full bg-red-400"></span><span
              class="size-3 rounded-full bg-yellow-400"
            ></span><span class="size-3 rounded-full bg-green-400"></span>
          </div>
          <div class="grid flex-1 grid-cols-3 gap-3">
            <div class="col-span-2 rounded-lg bg-background p-4">
              <div class="h-3 w-1/3 rounded bg-muted"></div>
              <div class="mt-6 h-24 rounded bg-primary/15"></div>
              <div class="mt-3 h-3 w-2/3 rounded bg-muted"></div>
            </div>
            <div class="rounded-lg bg-background p-4">
              <div class="h-3 w-1/2 rounded bg-muted"></div>
              <div class="mt-4 space-y-3">
                <div class="h-3 rounded bg-muted"></div>
                <div class="h-3 rounded bg-muted"></div>
                <div class="h-3 rounded bg-muted"></div>
              </div>
            </div>
          </div>
        </div></AspectRatio.Root
      >
    </section>
    <section aria-label="合作团队" class="border-b py-8">
      <div
        class="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-10 gap-y-4 px-4 text-sm font-semibold text-muted-foreground/60"
      >
        {#each ["Northstar", "Mosaic", "Orbit", "Acme Labs", "Vela", "Juniper"] as logo}<span
            >{logo}</span
          >{/each}
      </div>
    </section>
    <section class="border-y bg-muted/30 py-10">
      <div class="mx-auto grid max-w-6xl grid-cols-2 gap-8 px-4 text-center sm:grid-cols-4">
        {#each landing.numbers as number}<div>
            <p class="text-3xl font-bold">{number.value}</p>
            <p class="mt-1 text-sm text-muted-foreground">{number.label}</p>
          </div>{/each}
      </div>
    </section>
    <section id="features" class="mx-auto max-w-6xl px-4 py-20">
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="text-3xl font-bold">一套工具，连接整个团队</h2>
        <p class="mt-3 text-muted-foreground">从数据到协作，所有工作都在一个清晰的界面里完成。</p>
      </div>
      <div class="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {#each landing.features as feature}<Card.Root
            ><Card.Header
              ><div
                class="mb-2 flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary"
              >
                <Icon name={feature.icon} />
              </div>
              <Card.Title>{feature.title}</Card.Title><Card.Description
                >{feature.desc}</Card.Description
              ></Card.Header
            ></Card.Root
          >{/each}
      </div>
    </section>
    <section id="product" class="mx-auto max-w-6xl space-y-16 px-4 py-12">
      <div class="grid items-center gap-10 md:grid-cols-2">
        <div class="rounded-2xl bg-muted p-10">
          <div class="h-48 rounded-xl bg-background shadow-inner"></div>
        </div>
        <div>
          <Badge.Root variant="outline">统一视图</Badge.Root>
          <h2 class="mt-4 text-3xl font-bold">让复杂工作变得简单</h2>
          <p class="mt-4 text-muted-foreground">
            清晰的模块和实时状态，让每个人都能快速找到下一步。
          </p>
        </div>
      </div>
      <div class="grid items-center gap-10 md:grid-cols-2">
        <div class="order-2 md:order-1">
          <Badge.Root variant="outline">智能协作</Badge.Root>
          <h2 class="mt-4 text-3xl font-bold">洞察就在行动之前</h2>
          <p class="mt-4 text-muted-foreground">把团队经验沉淀为可复用的工作流。</p>
        </div>
        <div class="order-1 rounded-2xl bg-primary/10 p-10 md:order-2">
          <div class="h-48 rounded-xl bg-background shadow-inner"></div>
        </div>
      </div>
    </section>
    <section id="pricing" class="bg-muted/30 px-4 py-20">
      <div class="mx-auto max-w-6xl">
        <div class="text-center">
          <h2 class="text-3xl font-bold">选择适合你的计划</h2>
          <div
            class="mt-5 inline-flex items-center gap-2 rounded-full border bg-background p-1 text-sm"
          >
            <button
              class:font-semibold={!yearly}
              class="rounded-full px-3 py-1"
              onclick={() => (yearly = false)}>按月</button
            ><button
              class:font-semibold={yearly}
              class="rounded-full px-3 py-1"
              onclick={() => (yearly = true)}>按年</button
            >
          </div>
        </div>
        <div class="mt-10 grid gap-5 md:grid-cols-3">
          {#each plans as plan}<Card.Root
              class={`relative ${plan.recommended ? "border-primary" : ""}`}
              ><Card.Header
                >{#if plan.recommended}<Badge.Root class="absolute top-5 right-5">推荐</Badge.Root
                  >{/if}<Card.Title>{plan.name}</Card.Title><Card.Description
                  >适合不同规模的团队</Card.Description
                ></Card.Header
              ><Card.Content
                ><p class="text-3xl font-bold">
                  {plan.price === null
                    ? "联系销售"
                    : `¥${yearly ? Math.round(plan.price * 10) : plan.price}`}<span
                    class="text-sm font-normal text-muted-foreground"
                    >{plan.price === null ? "" : "/年"}</span
                  >
                </p>
                <ul class="mt-6 space-y-3 text-sm">
                  {#each plan.features as feature}<li class="flex gap-2">
                      <Icon name="check" size={16} class="text-primary" />{feature}
                    </li>{/each}
                </ul>
                <Button class="mt-8 w-full" variant={plan.recommended ? "default" : "outline"}
                  >选择计划</Button
                ></Card.Content
              ></Card.Root
            >{/each}
        </div>
      </div>
    </section>
    <section id="stories" class="mx-auto max-w-6xl px-4 py-20">
      <h2 class="text-center text-3xl font-bold">团队正在这样使用</h2>
      <div class="mt-10 grid gap-4 md:grid-cols-3">
        {#each landing.testimonials as testimonial}<Card.Root
            ><Card.Content class="pt-6"
              ><p>“{testimonial.quote}”</p>
              <p class="mt-5 text-sm font-medium">{testimonial.name}</p>
              <p class="text-xs text-muted-foreground">{testimonial.company}</p></Card.Content
            ></Card.Root
          >{/each}
      </div>
    </section>
    <section id="faq" class="mx-auto max-w-3xl px-4 pb-20">
      <h2 class="text-center text-3xl font-bold">常见问题</h2>
      <Accordion.Root type="single" class="mt-8"
        >{#each landing.faq as faq, i}<Accordion.Item value={String(i)}
            ><Accordion.Trigger>{faq.q}</Accordion.Trigger><Accordion.Content
              >{faq.a}</Accordion.Content
            ></Accordion.Item
          >{/each}</Accordion.Root
      >
    </section>
    <section
      id="cta"
      class="mx-4 mb-20 rounded-2xl bg-primary px-6 py-12 text-center text-primary-foreground sm:mx-auto sm:max-w-6xl"
    >
      <h2 class="text-3xl font-bold">准备好开始了吗？</h2>
      <p class="mx-auto mt-3 max-w-xl text-primary-foreground/80">
        用一个清晰的工作台，让团队把时间留给真正重要的事情。
      </p>
      <Button class="mt-6 bg-background text-foreground hover:bg-background/90">免费开始</Button>
    </section>
  </main>
  <footer class="border-t">
    <div class="mx-auto grid max-w-6xl gap-8 px-4 py-12 sm:grid-cols-4">
      <div>
        <p class="font-semibold">Acme Console</p>
        <p class="mt-2 text-sm text-muted-foreground">让团队专注于重要的事。</p>
      </div>
      {#each ["产品", "资源", "公司"] as title}<div>
          <p class="font-medium">{title}</p>
          <div class="mt-3 space-y-2 text-sm text-muted-foreground">
            <a class="block" href="#features">功能介绍</a><a class="block" href="#pricing"
              >价格方案</a
            ><a class="block" href="#faq">帮助中心</a>
          </div>
        </div>{/each}
    </div>
    <div class="mx-auto max-w-6xl border-t px-4 py-5 text-sm text-muted-foreground">
      © 2025 Acme Console · 简体中文
    </div>
  </footer>
</div>

<Sheet.Root bind:open={mobileOpen}>
  <Sheet.Content side="left">
    <Sheet.Header
      ><Sheet.Title>Acme Console</Sheet.Title><Sheet.Description
        >快速访问落地页内容。</Sheet.Description
      ></Sheet.Header
    >
    <nav class="mt-6 grid gap-4 text-sm">
      <a href="#features" onclick={() => (mobileOpen = false)}>功能</a>
      <a href="#product" onclick={() => (mobileOpen = false)}>产品</a>
      <a href="#pricing" onclick={() => (mobileOpen = false)}>定价</a>
      <a href="#stories" onclick={() => (mobileOpen = false)}>客户故事</a>
      <a href="#faq" onclick={() => (mobileOpen = false)}>FAQ</a>
    </nav>
  </Sheet.Content>
</Sheet.Root>
