// apps/radix-themes/src/pages/orders.tsx
import { useMemo, useState } from "react"
import { AlertDialog, Badge, Box, Button, Card, Checkbox, DataList, Dialog, DropdownMenu, Flex, IconButton, Popover, Select, Skeleton, Table, Tabs, Text, TextArea, TextField } from "@radix-ui/themes"
import orders from "@ui-gallery/spec/mock/orders.json"
import { Icon } from "@/icons"
import { useToast } from "@/toast"
import { PageHeader, StatusBadge } from "./shared"

type Order = (typeof orders)[number]
export function OrdersPage() {
  const [query, setQuery] = useState("")
  const [status, setStatus] = useState("all")
  const [sortAsc, setSortAsc] = useState(false)
  const [selected, setSelected] = useState<Order | null>(null)
  const [state, setState] = useState("normal")
  const { show } = useToast()
  const filtered = useMemo(() => orders.filter((item) => `${item.id} ${item.customer}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || item.status === status)).sort((a, b) => sortAsc ? a.amount - b.amount : b.amount - a.amount), [query, sortAsc, status])
  return (
    <Box>
      <PageHeader title="订单管理" description="搜索、筛选并查看全部订单。" action={<Button variant="outline"><Icon name="download" />导出</Button>} />
      <Card>
        <Flex direction="column" gap="4">
          <Flex gap="3" wrap="wrap">
            <TextField.Root placeholder="搜索订单号..." value={query} onChange={(event) => setQuery(event.target.value)} style={{ flex: "1 1 220px", minWidth: 0 }}>
              <TextField.Slot><Icon name="search" size={16} /></TextField.Slot>
            </TextField.Root>
            <Select.Root value={status} onValueChange={setStatus}>
              <Select.Trigger placeholder="状态" />
              <Select.Content>
                <Select.Item value="all">全部状态</Select.Item>
                {["paid", "pending", "shipped", "refunded", "failed"].map((value) => <Select.Item key={value} value={value}>{value}</Select.Item>)}
              </Select.Content>
            </Select.Root>
            <TextField.Root type="date" />
            <TextField.Root type="date" />
            <Popover.Root>
              <Popover.Trigger><Button variant="soft"><Icon name="filter" />渠道</Button></Popover.Trigger>
              <Popover.Content>
                <Flex direction="column" gap="2">
                  <Text weight="bold">渠道</Text>
                  {["web", "ios", "android", "api"].map((channel) => <Flex key={channel} gap="2" align="center"><Checkbox defaultChecked /><Text>{channel}</Text></Flex>)}
                </Flex>
              </Popover.Content>
            </Popover.Root>
            <DropdownMenu.Root>
              <DropdownMenu.Trigger><Button variant="outline"><Icon name="sliders" />列</Button></DropdownMenu.Trigger>
              <DropdownMenu.Content><DropdownMenu.CheckboxItem checked>客户</DropdownMenu.CheckboxItem><DropdownMenu.CheckboxItem checked>金额</DropdownMenu.CheckboxItem><DropdownMenu.CheckboxItem checked>状态</DropdownMenu.CheckboxItem></DropdownMenu.Content>
            </DropdownMenu.Root>
          </Flex>
          <Flex gap="2">
            <Button size="1" variant={state === "normal" ? "soft" : "ghost"} onClick={() => setState("normal")}>正常</Button>
            <Button size="1" variant={state === "empty" ? "soft" : "ghost"} onClick={() => setState("empty")}>空</Button>
            <Button size="1" variant={state === "loading" ? "soft" : "ghost"} onClick={() => setState("loading")}>加载</Button>
            <Button size="1" variant={state === "error" ? "soft" : "ghost"} onClick={() => setState("error")}>错误</Button>
          </Flex>
          {state === "empty" ? <Flex direction="column" align="center" gap="3" p="8"><Icon name="inbox" size={32} /><Text color="gray">没有找到订单</Text><Button variant="outline" onClick={() => { setQuery(""); setStatus("all") }}>清除筛选</Button></Flex> : state === "loading" ? <Flex direction="column" gap="3">{[1, 2, 3].map((item) => <Skeleton key={item} loading><Box height="40px" /></Skeleton>)}</Flex> : state === "error" ? <Flex direction="column" gap="3" align="start"><Badge color="red">加载失败</Badge><Text color="gray">订单数据暂时无法加载。</Text><Button onClick={() => setState("normal")}>重试</Button></Flex> : (
            <Box style={{ overflowX: "auto", minWidth: 0 }}>
              <Table.Root variant="surface">
                <Table.Header><Table.Row><Table.ColumnHeaderCell><Checkbox checked="indeterminate" /></Table.ColumnHeaderCell><Table.ColumnHeaderCell onClick={() => setSortAsc((value) => !value)}>订单 <Icon name={sortAsc ? "arrow-up" : "chevrons-up-down"} size={14} /></Table.ColumnHeaderCell><Table.ColumnHeaderCell>客户</Table.ColumnHeaderCell><Table.ColumnHeaderCell>状态</Table.ColumnHeaderCell><Table.ColumnHeaderCell>日期</Table.ColumnHeaderCell><Table.ColumnHeaderCell align="right">金额</Table.ColumnHeaderCell><Table.ColumnHeaderCell>操作</Table.ColumnHeaderCell></Table.Row></Table.Header>
                <Table.Body>{filtered.slice(0, 10).map((order) => <Table.Row key={order.id} onClick={() => setSelected(order)} style={{ cursor: "pointer" }}><Table.Cell><Checkbox onClick={(event) => event.stopPropagation()} /></Table.Cell><Table.Cell>{order.id}</Table.Cell><Table.Cell>{order.customer}</Table.Cell><Table.Cell><StatusBadge value={order.status} /></Table.Cell><Table.Cell>{order.date}</Table.Cell><Table.Cell align="right">¥{order.amount.toLocaleString()}</Table.Cell><Table.Cell><DropdownMenu.Root><DropdownMenu.Trigger><IconButton size="1" variant="ghost" onClick={(event) => event.stopPropagation()}><Icon name="more-horizontal" /></IconButton></DropdownMenu.Trigger><DropdownMenu.Content><DropdownMenu.Item>编辑</DropdownMenu.Item><AlertDialog.Root><AlertDialog.Trigger><DropdownMenu.Item color="red" onSelect={(event) => event.preventDefault()}>删除</DropdownMenu.Item></AlertDialog.Trigger><AlertDialog.Content><AlertDialog.Title>删除订单？</AlertDialog.Title><AlertDialog.Description>此操作无法撤销。</AlertDialog.Description><Flex justify="end" gap="3" mt="4"><AlertDialog.Cancel><Button variant="soft">取消</Button></AlertDialog.Cancel><AlertDialog.Action><Button color="red" onClick={() => show("订单已删除")}>确认删除</Button></AlertDialog.Action></Flex></AlertDialog.Content></AlertDialog.Root></DropdownMenu.Content></DropdownMenu.Root></Table.Cell></Table.Row>)}</Table.Body>
              </Table.Root>
            </Box>
          )}
          <Flex justify="between" align="center">
            <Text size="2" color="gray">共 {filtered.length} 条</Text>
            <Flex gap="2"><Button size="1" variant="soft">1</Button><Button size="1" variant="ghost">2</Button><Select.Root defaultValue="10"><Select.Trigger placeholder="10 / 页" /><Select.Content><Select.Item value="10">10 / 页</Select.Item><Select.Item value="20">20 / 页</Select.Item><Select.Item value="50">50 / 页</Select.Item></Select.Content></Select.Root></Flex>
          </Flex>
        </Flex>
      </Card>
      <Dialog.Root open={!!selected} onOpenChange={(open) => !open && setSelected(null)}>
        <Dialog.Content style={{ position: "fixed", inset: "0 0 0 auto", width: "min(420px, 100vw)", maxWidth: "100vw", height: "100vh", borderRadius: 0, overflowY: "auto", transform: "none" }}>
          <Dialog.Title>{selected?.id ?? "订单详情"}</Dialog.Title><Dialog.Description>查看订单完整信息。</Dialog.Description>
          {selected ? <Flex direction="column" gap="4" mt="5"><DataList.Root><DataList.Item><DataList.Label>客户</DataList.Label><DataList.Value>{selected.customer}</DataList.Value></DataList.Item><DataList.Item><DataList.Label>邮箱</DataList.Label><DataList.Value>{selected.email}</DataList.Value></DataList.Item><DataList.Item><DataList.Label>状态</DataList.Label><DataList.Value><StatusBadge value={selected.status} /></DataList.Value></DataList.Item><DataList.Item><DataList.Label>金额</DataList.Label><DataList.Value>¥{selected.amount.toLocaleString()}</DataList.Value></DataList.Item></DataList.Root><Tabs.Root defaultValue="details"><Tabs.List><Tabs.Trigger value="details">详情</Tabs.Trigger><Tabs.Trigger value="notes">备注</Tabs.Trigger></Tabs.List><Tabs.Content value="notes" mt="3"><TextArea placeholder="备注" /></Tabs.Content></Tabs.Root><Button color="red" onClick={() => { show("订单已删除"); setSelected(null) }}>删除订单</Button></Flex> : null}
        </Dialog.Content>
      </Dialog.Root>
    </Box>
  )
}

// apps/shadcn-svelte/src/routes/Orders.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import orders from "@ui-gallery/spec/mock/orders.json"
  import Icon from "$lib/icons/Icon.svelte"
  import { Button } from "$lib/components/ui/button"
  import { Input } from "$lib/components/ui/input"
  import { NativeSelect } from "$lib/components/ui/native-select"
  import * as Card from "$lib/components/ui/card"
  import * as Badge from "$lib/components/ui/badge"
  import * as Checkbox from "$lib/components/ui/checkbox"
  import * as Empty from "$lib/components/ui/empty"
  import * as Alert from "$lib/components/ui/alert"
  import * as Skeleton from "$lib/components/ui/skeleton"
  import * as Sheet from "$lib/components/ui/sheet"
  import * as Dropdown from "$lib/components/ui/dropdown-menu"
  import * as Dialog from "$lib/components/ui/alert-dialog"
  import * as Pagination from "$lib/components/ui/pagination"
  import * as Popover from "$lib/components/ui/popover"
  import * as RangeCalendar from "$lib/components/ui/range-calendar"
  import * as Tabs from "$lib/components/ui/tabs"
  import activity from "@ui-gallery/spec/mock/activity.json"
  import { toast } from "svelte-sonner"

  let query = $state("")
  let status = $state("all")
  let selected = $state<string[]>([])
  let rows = $state([...orders])
  let open = $state(false)
  let deleteOpen = $state(false)
  let detail = $state<(typeof orders)[number] | null>(null)
  let deleteTarget = $state<(typeof orders)[number] | null>(null)
  let sortAsc = $state(false)
  const statusLabels: Record<string, string> = {
    paid: "已支付",
    pending: "待处理",
    shipped: "已发货",
    refunded: "已退款",
    failed: "失败",
  }
  let loading = $state(new URLSearchParams(window.location.search).get("state") === "loading")
  let error = $state(new URLSearchParams(window.location.search).get("state") === "error")
  onMount(() => {
    if (!loading) loading = false
  })
  const filtered = $derived(
    rows
      .filter(
        (order) =>
          (!query ||
            `${order.id} ${order.customer} ${order.product}`
              .toLowerCase()
              .includes(query.toLowerCase())) &&
          (status === "all" || order.status === status)
      )
      .sort((a, b) => (sortAsc ? a.amount - b.amount : b.amount - a.amount))
      .slice(0, 10)
  )
  const allSelected = $derived(filtered.length > 0 && selected.length === filtered.length)
  function toggleAll() {
    selected = allSelected ? [] : filtered.map((order) => order.id)
  }
  function showOrder(order: (typeof orders)[number]) {
    detail = order
    open = true
  }
  function remove() {
    deleteOpen = false
    open = false
    const detailId = deleteTarget?.id
    if (detailId) rows = rows.filter((order) => order.id !== detailId)
    if (detailId) selected = selected.filter((id) => id !== detailId)
    toast.success("订单已删除")
  }
</script>

<div class="space-y-6">
  <div class="flex flex-wrap items-center justify-between gap-3">
    <div>
      <h1 class="text-2xl font-semibold">订单</h1>
      <p class="text-sm text-muted-foreground">管理和追踪所有订单。</p>
    </div>
    <Button variant="outline" class="h-10"
      ><Icon name="download" size={16} class="mr-2" />导出</Button
    >
  </div>
  {#if error}<Alert.Root variant="destructive"
      ><Alert.Title>订单加载失败</Alert.Title><Alert.Description
        class="flex items-center justify-between"
        >暂时无法读取订单列表。<Button variant="outline" size="sm" onclick={() => (error = false)}
          ><Icon name="refresh" size={16} class="mr-2" />重试</Button
        ></Alert.Description
      ></Alert.Root
    >{/if}
  <Card.Root
    ><Card.Content class="flex flex-wrap gap-3 p-4"
      ><div class="relative min-w-48 flex-1">
        <Icon name="search" size={16} class="absolute top-3 left-3 text-muted-foreground" /><Input
          bind:value={query}
          class="h-10 w-full pr-3 pl-9"
          placeholder="搜索订单、客户或产品"
        />
      </div>
      <NativeSelect bind:value={status} class="[&>select]:h-10"
        ><option value="all">全部状态</option><option value="paid">已支付</option><option
          value="pending">待处理</option
        ><option value="shipped">已发货</option><option value="refunded">已退款</option><option
          value="failed">失败</option
        ></NativeSelect
      ><Popover.Root
        ><Popover.Trigger><Button variant="outline" class="h-10">日期范围</Button></Popover.Trigger
        ><Popover.Content class="w-auto p-0"><RangeCalendar.RangeCalendar /></Popover.Content
        ></Popover.Root
      ><Dropdown.Root
        ><Dropdown.Trigger
          ><Button variant="outline" class="h-10"
            >渠道 <Icon name="chevron-down" size={16} class="ml-2" /></Button
          ></Dropdown.Trigger
        ><Dropdown.Content
          ><Dropdown.CheckboxItem checked>Web</Dropdown.CheckboxItem><Dropdown.CheckboxItem
            >iOS</Dropdown.CheckboxItem
          ><Dropdown.CheckboxItem>Android</Dropdown.CheckboxItem></Dropdown.Content
        ></Dropdown.Root
      ><NativeSelect class="[&>select]:h-10" aria-label="每页条数"
        ><option>10 条/页</option><option>20 条/页</option><option>50 条/页</option></NativeSelect
      ><Dropdown.Root
        ><Dropdown.Trigger><Button variant="outline" class="h-10">列显示</Button></Dropdown.Trigger
        ><Dropdown.Content
          ><Dropdown.CheckboxItem checked>客户</Dropdown.CheckboxItem><Dropdown.CheckboxItem checked
            >产品</Dropdown.CheckboxItem
          ><Dropdown.CheckboxItem checked>状态</Dropdown.CheckboxItem></Dropdown.Content
        ></Dropdown.Root
      ></Card.Content
    ></Card.Root
  >
  {#if loading}<Card.Root class="space-y-3 p-6"
      >{#each Array(6) as _}<Skeleton.Root class="h-10 w-full" />{/each}</Card.Root
    >{:else if filtered.length === 0}<Card.Root
      ><Empty.Root
        ><Empty.Header
          ><Empty.Media variant="icon"><Icon name="search" size={18} /></Empty.Media><Empty.Title
            >没有找到订单</Empty.Title
          ><Empty.Description>尝试调整搜索关键词或筛选条件。</Empty.Description></Empty.Header
        ></Empty.Root
      ></Card.Root
    >{:else}<Card.Root
      ><Card.Content class="p-0"
        ><div class="space-y-3 sm:hidden">
          {#each filtered as order (order.id)}
            <button class="w-full rounded-lg border p-4 text-left" onclick={() => showOrder(order)}>
              <div class="flex items-start justify-between gap-3">
                <div>
                  <p class="font-medium">{order.id}</p>
                  <p class="text-sm text-muted-foreground">{order.customer}</p>
                </div>
                <Badge.Root
                  variant={order.status === "paid"
                    ? "default"
                    : order.status === "failed"
                      ? "destructive"
                      : "secondary"}>{statusLabels[order.status]}</Badge.Root
                >
              </div>
              <div class="mt-3 flex justify-between text-sm">
                <span>{order.product}</span><span>{order.currency}{order.amount.toFixed(2)}</span>
              </div>
            </button>
          {/each}
        </div>
        <div class="hidden overflow-x-auto sm:block">
          <table class="w-full min-w-[720px] text-sm">
            <thead
              ><tr class="border-b text-left text-muted-foreground"
                ><th class="px-4 py-3"
                  ><Checkbox.Root
                    checked={allSelected}
                    indeterminate={selected.length > 0 && !allSelected}
                    onchange={toggleAll}
                  /></th
                ><th class="cursor-pointer px-4 py-3" onclick={() => (sortAsc = !sortAsc)}
                  >订单号 {#if sortAsc}<Icon
                      name="chevron-up"
                      size={12}
                      class="inline"
                    />{:else}<Icon name="chevron-down" size={12} class="inline" />{/if}</th
                ><th class="px-4 py-3">客户</th><th class="px-4 py-3">产品</th><th class="px-4 py-3"
                  >渠道</th
                ><th class="px-4 py-3">状态</th><th class="px-4 py-3 text-right">金额</th><th
                  class="px-4 py-3"
                ></th></tr
              ></thead
            ><tbody
              >{#each filtered as order (order.id)}<tr
                  class="cursor-pointer border-b last:border-0 hover:bg-muted/40"
                  onclick={() => showOrder(order)}
                  ><td class="px-4 py-3" onclick={(event) => event.stopPropagation()}
                    ><Checkbox.Root
                      checked={selected.includes(order.id)}
                      onchange={() =>
                        (selected = selected.includes(order.id)
                          ? selected.filter((id) => id !== order.id)
                          : [...selected, order.id])}
                    /></td
                  ><td class="px-4 py-3 font-medium">{order.id}</td><td class="px-4 py-3"
                    >{order.customer}
                    <div class="text-xs text-muted-foreground">{order.email}</div></td
                  ><td class="px-4 py-3">{order.product}</td><td class="px-4 py-3"
                    >{order.channel}</td
                  ><td class="px-4 py-3"
                    ><Badge.Root
                      variant={order.status === "paid"
                        ? "default"
                        : order.status === "failed"
                          ? "destructive"
                          : "secondary"}>{statusLabels[order.status]}</Badge.Root
                    ></td
                  ><td class="px-4 py-3 text-right">{order.currency}{order.amount.toFixed(2)}</td
                  ><td class="px-4 py-3 text-right" onclick={(event) => event.stopPropagation()}
                    ><Dropdown.Root
                      ><Dropdown.Trigger
                        ><Button
                          variant="ghost"
                          size="icon"
                          class="size-10"
                          data-qa="hit"
                          aria-label="订单操作"><Icon name="more-horizontal" size={16} /></Button
                        ></Dropdown.Trigger
                      ><Dropdown.Content
                        ><Dropdown.Item onclick={() => showOrder(order)}>编辑</Dropdown.Item
                        ><Dropdown.Item
                          class="text-destructive"
                          onclick={() => {
                            deleteTarget = order
                            deleteOpen = true
                          }}>删除</Dropdown.Item
                        ></Dropdown.Content
                      ></Dropdown.Root
                    ></td
                  ></tr
                >{/each}</tbody
            >
          </table>
        </div></Card.Content
      ><Card.Footer class="flex items-center justify-between border-t"
        ><span class="text-xs text-muted-foreground">显示 {rows.length} 条订单</span
        ><Pagination.Root count={rows.length} perPage={10} /></Card.Footer
      ></Card.Root
    >{/if}
</div>

{#if detail}
  <Sheet.Root bind:open
    ><Sheet.Content side="right" class="w-full sm:max-w-lg"
      ><Sheet.Header
        ><Sheet.Title>{detail.id}</Sheet.Title><Sheet.Description
          >订单详情和处理记录</Sheet.Description
        ></Sheet.Header
      >
      <div class="space-y-6 p-4">
        <Tabs.Root value="detail">
          <Tabs.List
            ><Tabs.Trigger value="detail">详情</Tabs.Trigger><Tabs.Trigger value="activity"
              >处理记录</Tabs.Trigger
            ><Tabs.Trigger value="notes">备注</Tabs.Trigger></Tabs.List
          >
          <Tabs.Content value="detail">
            <dl class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <dt class="text-muted-foreground">客户</dt>
                <dd class="font-medium">{detail.customer}</dd>
              </div>
              <div>
                <dt class="text-muted-foreground">日期</dt>
                <dd>{detail.date}</dd>
              </div>
              <div>
                <dt class="text-muted-foreground">产品</dt>
                <dd>{detail.product}</dd>
              </div>
              <div>
                <dt class="text-muted-foreground">渠道</dt>
                <dd>{detail.channel}</dd>
              </div>
            </dl>
          </Tabs.Content>
          <Tabs.Content value="activity">
            <ul class="space-y-3 text-sm">
              {#each activity.slice(0, 3) as item}<li class="border-b pb-3 last:border-0">
                  {item.user}
                  {item.action}<span class="block text-xs text-muted-foreground">{item.time}</span>
                </li>{/each}
            </ul>
          </Tabs.Content>
          <Tabs.Content value="notes">
            <div>
              <label for="note" class="text-sm font-medium">备注</label><textarea
                id="note"
                class="mt-2 min-h-24 w-full rounded-md border bg-background p-3 text-sm"
                placeholder="添加订单备注..."
              ></textarea>
            </div>
          </Tabs.Content>
        </Tabs.Root>
        <Button
          variant="destructive"
          onclick={() => {
            deleteTarget = detail
            deleteOpen = true
          }}><Icon name="trash" size={16} class="mr-2" />删除订单</Button
        >
      </div></Sheet.Content
    ></Sheet.Root
  >
{/if}
<Dialog.Root bind:open={deleteOpen}
  ><Dialog.Content
    ><Dialog.Header
      ><Dialog.Title>确认删除订单？</Dialog.Title><Dialog.Description
        >此操作无法撤销，订单记录将被移除。</Dialog.Description
      ></Dialog.Header
    ><Dialog.Footer
      ><Dialog.Cancel>取消</Dialog.Cancel><Dialog.Action onclick={remove}>确认删除</Dialog.Action
      ></Dialog.Footer
    ></Dialog.Content
  ></Dialog.Root
>
