// apps/shadcn-svelte/src/routes/Settings.svelte
<script lang="ts">
  import Icon from "$lib/icons/Icon.svelte"
  import sessions from "@ui-gallery/spec/mock/sessions.json"
  import team from "@ui-gallery/spec/mock/team.json"
  import plans from "@ui-gallery/spec/mock/plans.json"
  import invoices from "@ui-gallery/spec/mock/invoices.json"
  import { Button } from "$lib/components/ui/button"
  import * as Card from "$lib/components/ui/card"
  import * as Avatar from "$lib/components/ui/avatar"
  import * as Tabs from "$lib/components/ui/tabs"
  import * as Switch from "$lib/components/ui/switch"
  import * as Dialog from "$lib/components/ui/alert-dialog"
  import * as Badge from "$lib/components/ui/badge"
  let tab = $state("profile"),
    dangerOpen = $state(false),
    confirmText = $state("")
</script>

<div class="space-y-6">
  <div>
    <h1 class="text-2xl font-semibold">设置</h1>
    <p class="text-sm text-muted-foreground">管理个人资料、团队和账单。</p>
  </div>
  <Tabs.Root
    bind:value={tab}
    orientation="vertical"
    class="grid gap-6 lg:grid-cols-[200px_minmax(0,1fr)]"
    ><div class="w-full overflow-x-auto lg:overflow-visible">
      <Tabs.List
        class="h-auto w-max min-w-full justify-start lg:w-auto lg:min-w-0 lg:flex-col lg:items-stretch [&_[data-slot=tabs-trigger]]:min-h-10 lg:[&_[data-slot=tabs-trigger]]:w-full"
        ><Tabs.Trigger value="profile">个人资料</Tabs.Trigger><Tabs.Trigger value="security"
          >账号安全</Tabs.Trigger
        ><Tabs.Trigger value="notifications">通知</Tabs.Trigger><Tabs.Trigger value="team"
          >团队</Tabs.Trigger
        ><Tabs.Trigger value="billing">计费</Tabs.Trigger></Tabs.List
      >
    </div>
    <div class="min-w-0">
      <Tabs.Content value="profile"
        ><Card.Root
          ><Card.Header
            ><Card.Title>个人资料</Card.Title><Card.Description
              >更新你的头像和个人信息。</Card.Description
            ></Card.Header
          ><Card.Content class="space-y-5"
            ><div class="flex items-center gap-4">
              <Avatar.Root class="size-16"><Avatar.Fallback>AC</Avatar.Fallback></Avatar.Root
              ><Button variant="outline"
                ><Icon name="image" size={16} class="mr-2" />上传头像</Button
              >
            </div>
            <label class="block space-y-2 text-sm font-medium"
              >姓名<input class="h-9 w-full rounded-md border px-3" value="Acme Team" /></label
            ><label class="block space-y-2 text-sm font-medium"
              >简介<textarea class="min-h-24 w-full rounded-md border p-3"
                >负责 Acme Console 的团队协作。</textarea
              ></label
            >
            <div class="grid gap-4 sm:grid-cols-2">
              <label class="space-y-2 text-sm font-medium"
                >语言<select class="h-9 w-full rounded-md border bg-background px-3"
                  ><option>简体中文</option><option>English</option></select
                ></label
              ><label class="space-y-2 text-sm font-medium"
                >时区<select class="h-9 w-full rounded-md border bg-background px-3"
                  ><option>Asia/Shanghai</option><option>America/Los_Angeles</option></select
                ></label
              >
            </div></Card.Content
          ><Card.Footer><Button>保存更改</Button></Card.Footer></Card.Root
        ></Tabs.Content
      >
      <Tabs.Content value="security"
        ><div class="space-y-4">
          <Card.Root
            ><Card.Header><Card.Title>账号安全</Card.Title></Card.Header><Card.Content
              class="space-y-4"
              ><label class="block space-y-2 text-sm"
                >当前密码<input type="password" class="h-9 w-full rounded-md border px-3" /></label
              ><label class="block space-y-2 text-sm"
                >新密码<input type="password" class="h-9 w-full rounded-md border px-3" /></label
              ><Button>修改密码</Button>
              <div class="flex items-center justify-between rounded-lg border p-4">
                <div>
                  <p class="font-medium">两步验证</p>
                  <p class="text-sm text-muted-foreground">为账号增加额外保护。</p>
                </div>
                <Switch.Root />
              </div>
              <div
                class="flex size-32 items-center justify-center border-4 border-foreground bg-muted text-center text-xs"
              >
                二维码占位
              </div></Card.Content
            ></Card.Root
          ><Card.Root
            ><Card.Header><Card.Title>活跃会话</Card.Title></Card.Header><Card.Content
              class="space-y-3"
              >{#each sessions as session}<div
                  class="flex items-center justify-between border-b py-3 last:border-0"
                >
                  <div>
                    <p class="font-medium">{session.device}</p>
                    <p class="text-xs text-muted-foreground">{session.location} · {session.time}</p>
                  </div>
                  <Button variant="outline" size="sm">注销</Button>
                </div>{/each}</Card.Content
            ></Card.Root
          >
        </div></Tabs.Content
      >
      <Tabs.Content value="notifications"
        ><Card.Root
          ><Card.Header><Card.Title>通知偏好</Card.Title></Card.Header><Card.Content
            class="space-y-1"
            >{#each ["产品更新", "团队活动", "安全提醒", "账单通知"] as item}<div
                class="flex items-center justify-between border-b py-4 last:border-0"
              >
                <span>{item}</span><Switch.Root />
              </div>{/each}
            <div class="pt-4">
              <p class="mb-3 text-sm font-medium">接收方式</p>
              <div class="flex gap-2">
                <Button variant="secondary">邮件</Button><Button variant="outline">推送</Button
                ><Button variant="outline">站内</Button>
              </div>
            </div></Card.Content
          ></Card.Root
        ></Tabs.Content
      >
      <Tabs.Content value="team"
        ><Card.Root
          ><Card.Header
            ><Card.Title>团队成员</Card.Title><Card.Description>管理团队权限。</Card.Description
            ></Card.Header
          ><Card.Content
            ><div class="mb-4 flex gap-2">
              <input
                class="h-9 flex-1 rounded-md border px-3 text-sm"
                placeholder="输入邮箱邀请成员"
              /><Button>邀请</Button>
            </div>
            <div class="overflow-x-auto">
              <table class="w-full text-sm">
                <tbody
                  >{#each team as member}<tr class="border-b last:border-0"
                      ><td class="py-3"
                        ><div class="flex items-center gap-2">
                          <Avatar.Root class="size-8"
                            ><Avatar.Fallback>{member.name.slice(0, 1)}</Avatar.Fallback
                            ></Avatar.Root
                          >{member.name}
                        </div></td
                      ><td>{member.email}</td><td
                        ><select class="rounded border bg-background px-2 py-1"
                          ><option>{member.role}</option><option>成员</option></select
                        ></td
                      ><td class="text-right"><Button variant="ghost" size="sm">移除</Button></td
                      ></tr
                    >{/each}</tbody
                >
              </table>
            </div></Card.Content
          ></Card.Root
        ></Tabs.Content
      >
      <Tabs.Content value="billing"
        ><div class="space-y-4">
          <Card.Root
            ><Card.Header><Card.Title>当前计划</Card.Title></Card.Header><Card.Content
              ><div class="flex items-center justify-between">
                <div>
                  <p class="text-2xl font-bold">Pro</p>
                  <p class="text-sm text-muted-foreground">适合成长中的团队</p>
                </div>
                <Badge.Root>当前计划</Badge.Root>
              </div></Card.Content
            ></Card.Root
          >
          <div class="grid gap-4 md:grid-cols-3">
            {#each plans as plan}<Card.Root class={plan.recommended ? "border-primary" : ""}
                ><Card.Header
                  ><Card.Title>{plan.name}</Card.Title>{#if plan.recommended}<Badge.Root
                      >推荐</Badge.Root
                    >{/if}</Card.Header
                ><Card.Content
                  ><p class="mb-4 text-2xl font-bold">
                    ¥{plan.price}<span class="text-sm font-normal text-muted-foreground">/月</span>
                  </p>
                  <ul class="space-y-2 text-sm">
                    {#each plan.features as feature}<li>✓ {feature}</li>{/each}
                  </ul></Card.Content
                ></Card.Root
              >{/each}
          </div>
          <Card.Root
            ><Card.Header><Card.Title>发票记录</Card.Title></Card.Header><Card.Content
              ><div class="overflow-x-auto">
                <table class="w-full text-sm">
                  <thead
                    ><tr class="border-b text-left"
                      ><th class="py-2">编号</th><th>日期</th><th>金额</th><th>状态</th></tr
                    ></thead
                  ><tbody
                    >{#each invoices as invoice}<tr class="border-b last:border-0"
                        ><td class="py-2">{invoice.id}</td><td>{invoice.date}</td><td
                          >{invoice.amount}</td
                        ><td>{invoice.status}</td></tr
                      >{/each}</tbody
                  >
                </table>
              </div></Card.Content
            ></Card.Root
          >
        </div></Tabs.Content
      >
    </div></Tabs.Root
  >
  <Card.Root class="border-destructive"
    ><Card.Header
      ><Card.Title class="text-destructive">危险区域</Card.Title><Card.Description
        >删除账号后所有数据无法恢复。</Card.Description
      ></Card.Header
    ><Card.Footer
      ><Button variant="destructive" onclick={() => (dangerOpen = true)}
        ><Icon name="trash" size={16} class="mr-2" />删除账号</Button
      ></Card.Footer
    ></Card.Root
  >
</div>
<Dialog.Root bind:open={dangerOpen}
  ><Dialog.Content
    ><Dialog.Header
      ><Dialog.Title>确认删除账号</Dialog.Title><Dialog.Description
        >请输入 DELETE 以确认。</Dialog.Description
      ></Dialog.Header
    ><input
      bind:value={confirmText}
      class="h-9 w-full rounded-md border px-3"
      placeholder="DELETE"
    /><Dialog.Footer
      ><Dialog.Cancel>取消</Dialog.Cancel><Dialog.Action disabled={confirmText !== "DELETE"}
        >确认删除</Dialog.Action
      ></Dialog.Footer
    ></Dialog.Content
  ></Dialog.Root
>

// apps/radix-themes/src/pages/settings.tsx
import { useState } from "react"
import { AlertDialog, Avatar, Badge, Box, Button, Card, Flex, Grid, Heading, IconButton, Select, SegmentedControl, Switch, Table, Tabs, Text, TextField } from "@radix-ui/themes"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import team from "@ui-gallery/spec/mock/team.json"
import { Icon } from "@/icons"
import { PageHeader } from "./shared"

export function SettingsPage() {
  const [danger, setDanger] = useState("")
  return <Box>
    <PageHeader title="设置" description="管理你的个人资料、团队和订阅。" />
    <Tabs.Root defaultValue="profile">
      <Box className="rt-scroll-x"><Tabs.List><Tabs.Trigger value="profile">个人资料</Tabs.Trigger><Tabs.Trigger value="security">账号安全</Tabs.Trigger><Tabs.Trigger value="notifications">通知</Tabs.Trigger><Tabs.Trigger value="team">团队</Tabs.Trigger><Tabs.Trigger value="billing">计费</Tabs.Trigger></Tabs.List></Box>
      <Tabs.Content value="profile">
        <Card mt="4"><Flex direction="column" gap="4">
          <Flex align="center" gap="4"><Avatar size="6" fallback="林" /><Button variant="outline">上传头像</Button></Flex>
          <Grid columns={{ initial: "1", sm: "2" }} gap="4"><label><Text size="2" weight="medium">姓名</Text><TextField.Root mt="2" defaultValue="林晓" /></label><label><Text size="2" weight="medium">邮箱</Text><TextField.Root mt="2" defaultValue={team[0].email} /></label></Grid>
          <label><Text size="2" weight="medium">语言</Text><Select.Root defaultValue="zh"><Select.Trigger mt="2" style={{ width: "100%" }} /><Select.Content><Select.Item value="zh">简体中文</Select.Item><Select.Item value="en">English</Select.Item></Select.Content></Select.Root></label>
          <label><Text size="2" weight="medium">时区</Text><TextField.Root mt="2" defaultValue="Asia/Shanghai" /></label>
          <Button>保存更改</Button>
        </Flex></Card>
      </Tabs.Content>
      <Tabs.Content value="security">
        <Grid columns={{ initial: "1", md: "2" }} gap="4" mt="4"><Card><Heading size="4" mb="4">修改密码</Heading><Flex direction="column" gap="3"><TextField.Root type="password" placeholder="当前密码" /><TextField.Root type="password" placeholder="新密码" /><Button>更新密码</Button></Flex></Card><Card><Heading size="4" mb="4">两步验证</Heading><Flex align="center" justify="between"><Text>启用两步验证</Text><Switch /></Flex><Box mt="4" width="160px" height="160px" style={{ background: "var(--gray-3)" }}><Flex align="center" justify="center" height="100%"><Text>二维码</Text></Flex></Box></Card></Grid>
        <Card mt="4"><Heading size="4" mb="4">活跃会话</Heading><Flex direction="column" gap="3">{sessions.map((session) => <Flex key={session.device} align="center" justify="between"><Box><Text weight="medium">{session.device}</Text><Text as="div" size="1" color="gray">{session.location} · {session.time}</Text></Box>{session.current ? <Badge color="green">当前</Badge> : <Button size="1" variant="outline">注销</Button>}</Flex>)}</Flex></Card>
      </Tabs.Content>
      <Tabs.Content value="notifications">
        <Card mt="4"><Flex direction="column" gap="4"><Heading size="4">通知偏好</Heading>{["订单更新", "团队动态", "产品新闻"].map((label) => <Flex key={label} justify="between"><Text>{label}</Text><Switch defaultChecked /></Flex>)}<SegmentedControl.Root defaultValue="email"><SegmentedControl.Item value="email">邮件</SegmentedControl.Item><SegmentedControl.Item value="push">推送</SegmentedControl.Item><SegmentedControl.Item value="inapp">站内</SegmentedControl.Item></SegmentedControl.Root></Flex></Card>
      </Tabs.Content>
      <Tabs.Content value="team">
        <Card mt="4"><Box style={{ overflowX: "auto" }}><Table.Root variant="surface"><Table.Header><Table.Row><Table.ColumnHeaderCell>成员</Table.ColumnHeaderCell><Table.ColumnHeaderCell>角色</Table.ColumnHeaderCell><Table.ColumnHeaderCell>最近活跃</Table.ColumnHeaderCell><Table.ColumnHeaderCell /></Table.Row></Table.Header><Table.Body>{team.map((member) => <Table.Row key={member.email}><Table.Cell><Flex align="center" gap="2"><Avatar size="2" fallback={member.name.slice(0, 1)} /><Box><Text>{member.name}</Text><Text as="div" size="1" color="gray">{member.email}</Text></Box></Flex></Table.Cell><Table.Cell><Select.Root defaultValue={member.role}><Select.Trigger /><Select.Content>{["owner", "admin", "member", "viewer"].map((role) => <Select.Item key={role} value={role}>{role}</Select.Item>)}</Select.Content></Select.Root></Table.Cell><Table.Cell>{member.lastActive}</Table.Cell><Table.Cell><IconButton variant="ghost"><Icon name="trash" /></IconButton></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box><Flex gap="2" mt="4"><TextField.Root placeholder="邀请邮箱" style={{ flexGrow: 1, minWidth: 0 }} /><Button>邀请</Button></Flex></Card>
      </Tabs.Content>
      <Tabs.Content value="billing">
        <Card mt="4"><Heading size="4">当前计划</Heading><Text color="gray" as="p" mt="2">Pro · ¥99 / 月</Text></Card>
        <Grid columns={{ initial: "1", md: "3" }} gap="4" mt="4">{plans.map((plan) => <Card key={plan.name}><Flex justify="between"><Heading size="4">{plan.name}</Heading>{plan.recommended ? <Badge color="green">推荐</Badge> : null}</Flex><Heading size="6" mt="3">{plan.price === null ? "联系销售" : `¥${plan.price}`}</Heading><Flex direction="column" gap="2" mt="4">{plan.features.map((feature) => <Text key={feature} size="2"><Icon name="check" /> {feature}</Text>)}</Flex><Button variant={plan.recommended ? "solid" : "outline"} mt="4">选择计划</Button></Card>)}</Grid>
        <Card mt="4"><Heading size="4" mb="3">发票</Heading><Table.Root><Table.Body>{invoices.map((invoice) => <Table.Row key={invoice.id}><Table.Cell>{invoice.id}</Table.Cell><Table.Cell>{invoice.date}</Table.Cell><Table.Cell>¥{invoice.amount}</Table.Cell><Table.Cell><Badge color={invoice.status === "paid" ? "green" : "amber"}>{invoice.status}</Badge></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Card>
      </Tabs.Content>
    </Tabs.Root>
    <Card mt="5" style={{ border: "1px solid var(--red-7)" }}><Flex direction="column" gap="3"><Heading size="4" color="red">危险区</Heading><Text color="gray">删除账号后所有数据将无法恢复。</Text><AlertDialog.Root><AlertDialog.Trigger><Button color="red" variant="soft">删除账号</Button></AlertDialog.Trigger><AlertDialog.Content><AlertDialog.Title>确认删除账号？</AlertDialog.Title><AlertDialog.Description>请输入 DELETE 以继续。</AlertDialog.Description><TextField.Root mt="4" value={danger} onChange={(event) => setDanger(event.target.value)} placeholder="DELETE" /><Flex justify="end" gap="3" mt="4"><AlertDialog.Cancel><Button variant="soft">取消</Button></AlertDialog.Cancel><AlertDialog.Action><Button color="red" disabled={danger !== "DELETE"}>确认删除</Button></AlertDialog.Action></Flex></AlertDialog.Content></AlertDialog.Root></Flex></Card>
  </Box>
}
