// apps/skeleton/src/pages/Orders.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import { Avatar, Dialog, Menu, Pagination, Popover, Portal, SegmentedControl, Tabs } from "@skeletonlabs/skeleton-svelte"
  import ordersData from "@ui-gallery/spec/mock/orders.json"
  import Icon from "../lib/Icon.svelte"
  import StatusBadge from "../lib/StatusBadge.svelte"
  import { money, initials } from "../lib/format"
  import { toaster } from "../lib/toaster"

  type Order = (typeof ordersData)[number]
  type SortKey = "id" | "customer" | "amount" | "date" | "status"

  const statuses = [
    { value: "all", label: "全部状态" },
    { value: "paid", label: "已支付" },
    { value: "pending", label: "待处理" },
    { value: "shipped", label: "已发货" },
    { value: "refunded", label: "已退款" },
    { value: "failed", label: "失败" },
  ]
  const channels = [
    { value: "web", label: "Web" },
    { value: "ios", label: "iOS" },
    { value: "android", label: "Android" },
    { value: "api", label: "API" },
  ]
  const allColumns = [
    { key: "customer", label: "客户" },
    { key: "product", label: "产品" },
    { key: "channel", label: "渠道" },
    { key: "status", label: "状态" },
    { key: "date", label: "日期" },
    { key: "amount", label: "金额" },
  ] as const
  type ColumnKey = (typeof allColumns)[number]["key"]

  let orders = $state<Order[]>([...ordersData])
  let view = $state<"data" | "loading" | "empty" | "error">("loading")
  let query = $state("")
  let status = $state("all")
  let selectedChannels = $state<string[]>([])
  let dateFrom = $state("")
  let dateTo = $state("")
  let sortKey = $state<SortKey>("date")
  let sortDir = $state<"asc" | "desc">("desc")
  let page = $state(1)
  let pageSize = $state(10)
  let selected = $state<string[]>([])
  let hidden = $state<ColumnKey[]>([])
  let detail = $state<Order | null>(null)
  let pendingDelete = $state<Order | null>(null)
  let note = $state("")

  onMount(() => {
    const t = setTimeout(() => (view = "data"), 400)
    return () => clearTimeout(t)
  })

  const filtered = $derived.by(() => {
    const q = query.trim().toLowerCase()
    return orders
      .filter((o) => (status === "all" ? true : o.status === status))
      .filter((o) => (selectedChannels.length ? selectedChannels.includes(o.channel) : true))
      .filter((o) => (dateFrom ? o.date >= dateFrom : true))
      .filter((o) => (dateTo ? o.date <= dateTo : true))
      .filter((o) => (q ? [o.id, o.customer, o.email, o.product].some((v) => v.toLowerCase().includes(q)) : true))
      .sort((a, b) => {
        const av = a[sortKey]
        const bv = b[sortKey]
        const cmp = typeof av === "number" && typeof bv === "number" ? av - bv : String(av).localeCompare(String(bv))
        return sortDir === "asc" ? cmp : -cmp
      })
  })
  const total = $derived(filtered.length)
  const pageCount = $derived(Math.max(1, Math.ceil(total / pageSize)))
  const rows = $derived(filtered.slice((page - 1) * pageSize, page * pageSize))
  const allOnPage = $derived(rows.length > 0 && rows.every((r) => selected.includes(r.id)))
  const visible = $derived(allColumns.filter((c) => !hidden.includes(c.key)))

  $effect(() => {
    if (page > pageCount) page = pageCount
  })

  function sortBy(key: SortKey) {
    if (sortKey === key) sortDir = sortDir === "asc" ? "desc" : "asc"
    else {
      sortKey = key
      sortDir = "asc"
    }
  }
  function toggleAll() {
    selected = allOnPage ? selected.filter((id) => !rows.some((r) => r.id === id)) : [...new Set([...selected, ...rows.map((r) => r.id)])]
  }
  function toggle(id: string) {
    selected = selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id]
  }
  function toggleColumn(key: ColumnKey) {
    hidden = hidden.includes(key) ? hidden.filter((k) => k !== key) : [...hidden, key]
  }
  function toggleChannel(value: string) {
    selectedChannels = selectedChannels.includes(value) ? selectedChannels.filter((v) => v !== value) : [...selectedChannels, value]
    page = 1
  }
  function resetFilters() {
    query = ""
    status = "all"
    selectedChannels = []
    dateFrom = ""
    dateTo = ""
    page = 1
  }
  function exportCsv() {
    toaster.success({ title: "导出已开始", description: `正在导出 ${selected.length || total} 条订单` })
  }
  function confirmDelete() {
    if (!pendingDelete) return
    const id = pendingDelete.id
    orders = orders.filter((o) => o.id !== id)
    selected = selected.filter((x) => x !== id)
    if (detail?.id === id) detail = null
    pendingDelete = null
    toaster.success({ title: "订单已删除", description: `${id} 已从列表移除` })
  }
  function saveNote() {
    toaster.info({ title: "备注已保存", description: detail?.id })
    note = ""
  }
  function channelLabel(v: string) {
    return channels.find((c) => c.value === v)?.label ?? v
  }
</script>

<header class="flex flex-wrap items-end justify-between gap-3">
  <div>
    <h1 class="h3">订单</h1>
    <p class="text-sm opacity-70">共 {orders.length} 条订单，已选 {selected.length} 条</p>
  </div>
  <div class="flex items-center gap-2">
    <SegmentedControl value={view} onValueChange={(d) => (view = d.value as typeof view)}>
      <SegmentedControl.Control>
        <SegmentedControl.Indicator />
        <SegmentedControl.Item value="data"><SegmentedControl.ItemText>数据</SegmentedControl.ItemText><SegmentedControl.ItemHiddenInput /></SegmentedControl.Item>
        <SegmentedControl.Item value="loading"><SegmentedControl.ItemText>加载</SegmentedControl.ItemText><SegmentedControl.ItemHiddenInput /></SegmentedControl.Item>
        <SegmentedControl.Item value="empty"><SegmentedControl.ItemText>空</SegmentedControl.ItemText><SegmentedControl.ItemHiddenInput /></SegmentedControl.Item>
        <SegmentedControl.Item value="error"><SegmentedControl.ItemText>错误</SegmentedControl.ItemText><SegmentedControl.ItemHiddenInput /></SegmentedControl.Item>
      </SegmentedControl.Control>
    </SegmentedControl>
    <button type="button" class="btn preset-filled-primary-500" onclick={exportCsv}><Icon name="download" /><span>导出</span></button>
  </div>
</header>

<section class="card bg-surface-50-950 border border-surface-200-800 p-3 flex flex-wrap items-center gap-2" aria-label="筛选">
  <label class="relative flex-1 min-w-48">
    <span class="sr-only">搜索订单</span>
    <span class="absolute left-3 top-1/2 -translate-y-1/2 opacity-60"><Icon name="search" /></span>
    <input class="input pl-9" type="search" placeholder="搜索订单号、客户、邮箱…" bind:value={query} oninput={() => (page = 1)} />
  </label>
  <select class="select w-36" bind:value={status} onchange={() => (page = 1)} aria-label="状态">
    {#each statuses as s (s.value)}<option value={s.value}>{s.label}</option>{/each}
  </select>
  <Popover positioning={{ placement: "bottom-start" }}>
    <Popover.Trigger class="btn preset-outlined-surface-500">
      <Icon name="filter" /><span>渠道</span>
      {#if selectedChannels.length}<span class="badge preset-filled-primary-500">{selectedChannels.length}</span>{/if}
    </Popover.Trigger>
    <Portal>
      <Popover.Positioner class="z-40">
        <Popover.Content class="card p-3 bg-surface-100-900 shadow-xl space-y-2 w-48">
          {#each channels as c (c.value)}
            <label class="flex items-center gap-2 text-sm">
              <input class="checkbox" type="checkbox" checked={selectedChannels.includes(c.value)} onchange={() => toggleChannel(c.value)} />
              <span>{c.label}</span>
            </label>
          {/each}
        </Popover.Content>
      </Popover.Positioner>
    </Portal>
  </Popover>
  <div class="flex items-center gap-1">
    <input class="input w-36" type="date" bind:value={dateFrom} aria-label="开始日期" />
    <span class="opacity-60">–</span>
    <input class="input w-36" type="date" bind:value={dateTo} aria-label="结束日期" />
  </div>
  <Popover positioning={{ placement: "bottom-end" }}>
    <Popover.Trigger class="btn preset-outlined-surface-500"><Icon name="sliders" /><span class="hidden sm:inline">列</span></Popover.Trigger>
    <Portal>
      <Popover.Positioner class="z-40">
        <Popover.Content class="card p-3 bg-surface-100-900 shadow-xl space-y-2 w-40">
          {#each allColumns as c (c.key)}
            <label class="flex items-center justify-between text-sm">
              <span>{c.label}</span>
              <input class="switch" type="checkbox" role="switch" checked={!hidden.includes(c.key)} onchange={() => toggleColumn(c.key)} />
            </label>
          {/each}
        </Popover.Content>
      </Popover.Positioner>
    </Portal>
  </Popover>
  <button type="button" class="btn hover:preset-tonal" onclick={resetFilters}><Icon name="refresh" /><span class="hidden sm:inline">重置</span></button>
</section>

{#if selected.length}
  <div class="card preset-tonal-primary p-2 px-3 flex items-center justify-between gap-2 text-sm">
    <span>已选择 {selected.length} 条</span>
    <div class="flex gap-2">
      <button type="button" class="btn btn-sm preset-filled" onclick={exportCsv}>导出所选</button>
      <button type="button" class="btn btn-sm preset-outlined" onclick={() => (selected = [])}>取消选择</button>
    </div>
  </div>
{/if}

<section class="card bg-surface-50-950 border border-surface-200-800 overflow-hidden">
  {#if view === "loading"}
    <div class="p-4 space-y-3" aria-busy="true">
      {#each { length: 8 }, i (i)}
        <div class="flex gap-3 items-center">
          <div class="placeholder animate-pulse size-4"></div>
          <div class="placeholder animate-pulse h-4 w-24"></div>
          <div class="placeholder animate-pulse h-4 flex-1"></div>
          <div class="placeholder animate-pulse h-4 w-16"></div>
        </div>
      {/each}
    </div>
  {:else if view === "error"}
    <div class="p-12 text-center space-y-3">
      <Icon name="triangle-alert" class="size-10 mx-auto text-error-500" />
      <h2 class="h5">加载失败</h2>
      <p class="text-sm opacity-70">无法获取订单数据，请稍后重试。</p>
      <button type="button" class="btn preset-filled" onclick={() => (view = "data")}><Icon name="refresh" /><span>重试</span></button>
    </div>
  {:else if view === "empty" || rows.length === 0}
    <div class="p-12 text-center space-y-3">
      <Icon name="inbox" class="size-10 mx-auto opacity-40" />
      <h2 class="h5">暂无订单</h2>
      <p class="text-sm opacity-70">没有符合条件的订单，尝试调整筛选条件。</p>
      <button type="button" class="btn preset-outlined-surface-500" onclick={() => { view = "data"; resetFilters() }}>清除筛选</button>
    </div>
  {:else}
    <div class="table-wrap hidden md:block">
      <table class="table">
        <thead>
          <tr>
            <th class="w-10"><input class="checkbox" type="checkbox" checked={allOnPage} onchange={toggleAll} aria-label="选择本页" /></th>
            <th><button type="button" class="flex items-center gap-1" onclick={() => sortBy("id")}>订单号 <Icon name={sortKey === "id" ? (sortDir === "asc" ? "arrow-up" : "arrow-down") : "arrow-up-down"} class="size-3" /></button></th>
            {#each visible as c (c.key)}
              <th class={c.key === "amount" ? "text-right" : ""}>
                {#if c.key === "customer" || c.key === "amount" || c.key === "date" || c.key === "status"}
                  <button type="button" class="inline-flex items-center gap-1" onclick={() => sortBy(c.key)}>{c.label} <Icon name={sortKey === c.key ? (sortDir === "asc" ? "arrow-up" : "arrow-down") : "arrow-up-down"} class="size-3" /></button>
                {:else}{c.label}{/if}
              </th>
            {/each}
            <th class="w-12"><span class="sr-only">操作</span></th>
          </tr>
        </thead>
        <tbody class="[&>tr]:hover:preset-tonal-primary">
          {#each rows as o (o.id)}
            <tr class={selected.includes(o.id) ? "preset-tonal-primary" : ""}>
              <td><input class="checkbox" type="checkbox" checked={selected.includes(o.id)} onchange={() => toggle(o.id)} aria-label={`选择 ${o.id}`} /></td>
              <td><button type="button" class="anchor font-mono text-xs" onclick={() => (detail = o)}>{o.id}</button></td>
              {#each visible as c (c.key)}
                {#if c.key === "customer"}
                  <td>
                    <div class="flex items-center gap-2">
                      <Avatar class="size-7"><Avatar.Fallback class="preset-filled-secondary-500 text-[10px]">{initials(o.customer)}</Avatar.Fallback></Avatar>
                      <div class="min-w-0"><p class="truncate">{o.customer}</p><p class="text-xs opacity-60 truncate">{o.email}</p></div>
                    </div>
                  </td>
                {:else if c.key === "status"}<td><StatusBadge status={o.status} /></td>
                {:else if c.key === "amount"}<td class="text-right tabular-nums font-medium">{money(o.amount, o.currency)}</td>
                {:else if c.key === "channel"}<td><span class="chip preset-outlined-surface-500">{channelLabel(o.channel)}</span></td>
                {:else}<td>{o[c.key]}</td>{/if}
              {/each}
              <td>
                <Menu positioning={{ placement: "bottom-end" }}>
                  <Menu.Trigger class="btn-icon min-w-10 min-h-10 hover:preset-tonal" aria-label="操作"><Icon name="ellipsis-horizontal" /></Menu.Trigger>
                  <Portal>
                    <Menu.Positioner class="z-40">
                      <Menu.Content class="card p-1 bg-surface-100-900 shadow-xl min-w-36">
                        <Menu.Item value="view" onclick={() => (detail = o)}><Icon name="eye" /><Menu.ItemText>查看详情</Menu.ItemText></Menu.Item>
                        <Menu.Item value="copy" onclick={() => toaster.info({ title: "已复制", description: o.id })}><Icon name="copy" /><Menu.ItemText>复制订单号</Menu.ItemText></Menu.Item>
                        <Menu.Separator />
                        <Menu.Item value="delete" class="text-error-500" onclick={() => (pendingDelete = o)}><Icon name="trash" /><Menu.ItemText>删除</Menu.ItemText></Menu.Item>
                      </Menu.Content>
                    </Menu.Positioner>
                  </Portal>
                </Menu>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>

    <ul class="md:hidden divide-y divide-surface-200-800">
      {#each rows as o (o.id)}
        <li class="p-3 flex gap-3 items-start">
          <input class="checkbox mt-1" type="checkbox" checked={selected.includes(o.id)} onchange={() => toggle(o.id)} aria-label={`选择 ${o.id}`} />
          <button type="button" class="flex-1 min-w-0 text-left space-y-1" onclick={() => (detail = o)}>
            <div class="flex items-center justify-between gap-2">
              <span class="font-mono text-xs">{o.id}</span>
              <StatusBadge status={o.status} />
            </div>
            <p class="font-medium truncate">{o.customer}</p>
            <div class="flex items-center justify-between text-sm opacity-70">
              <span class="truncate">{o.product}</span>
              <span class="tabular-nums font-medium">{money(o.amount, o.currency)}</span>
            </div>
          </button>
        </li>
      {/each}
    </ul>

    <footer class="flex flex-wrap items-center justify-between gap-3 p-3 border-t border-surface-200-800">
      <div class="flex items-center gap-2 text-sm">
        <span class="opacity-70 hidden sm:inline">每页</span>
        <select class="select w-20" bind:value={pageSize} onchange={() => (page = 1)} aria-label="每页条数">
          <option value={5}>5</option><option value={10}>10</option><option value={20}>20</option>
        </select>
        <span class="opacity-70">第 {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, total)} / {total} 条</span>
      </div>
      <Pagination count={total} {pageSize} {page} onPageChange={(d) => (page = d.page)} siblingCount={1}>
        <Pagination.PrevTrigger class="btn-icon min-w-10 min-h-10 preset-outlined-surface-500" aria-label="上一页"><Icon name="chevron-left" /></Pagination.PrevTrigger>
        <Pagination.Context>
          {#snippet children(api)}
            {#each api().pages as p, i (i)}
              {#if p.type === "page"}
                <Pagination.Item {...p} class="btn-icon min-w-10 min-h-10 {p.value === page ? 'preset-filled-primary-500' : 'preset-outlined-surface-500'}">{p.value}</Pagination.Item>
              {:else}
                <Pagination.Ellipsis index={i} class="btn-icon min-w-10 min-h-10">…</Pagination.Ellipsis>
              {/if}
            {/each}
          {/snippet}
        </Pagination.Context>
        <Pagination.NextTrigger class="btn-icon min-w-10 min-h-10 preset-outlined-surface-500" aria-label="下一页"><Icon name="chevron-right" /></Pagination.NextTrigger>
      </Pagination>
    </footer>
  {/if}
</section>

<Dialog open={detail !== null} onOpenChange={(d) => { if (!d.open) detail = null }}>
  <Portal>
    <Dialog.Backdrop class="fixed inset-0 z-50 bg-surface-50-950/50" />
    <Dialog.Positioner class="fixed inset-0 z-50 flex justify-end">
      <Dialog.Content class="h-screen w-full max-w-md bg-surface-50-950 shadow-xl flex flex-col">
        {#if detail}
          <header class="flex items-start justify-between p-4 border-b border-surface-200-800">
            <div>
              <Dialog.Title class="h5">订单 {detail.id}</Dialog.Title>
              <Dialog.Description class="text-sm opacity-70">{detail.date} · {channelLabel(detail.channel)}</Dialog.Description>
            </div>
            <Dialog.CloseTrigger class="btn-icon min-w-10 min-h-10 hover:preset-tonal" aria-label="关闭"><Icon name="x" /></Dialog.CloseTrigger>
          </header>
          <div class="flex-1 overflow-y-auto p-4">
            <Tabs defaultValue="detail">
              <Tabs.List>
                <Tabs.Trigger value="detail">详情</Tabs.Trigger>
                <Tabs.Trigger value="timeline">时间线</Tabs.Trigger>
                <Tabs.Trigger value="notes">备注</Tabs.Trigger>
                <Tabs.Indicator />
              </Tabs.List>
              <Tabs.Content value="detail">
                <dl class="grid grid-cols-[auto_1fr] gap-x-4 gap-y-3 text-sm">
                  <dt class="opacity-60">客户</dt><dd>{detail.customer}</dd>
                  <dt class="opacity-60">邮箱</dt><dd class="break-all">{detail.email}</dd>
                  <dt class="opacity-60">产品</dt><dd>{detail.product}</dd>
                  <dt class="opacity-60">金额</dt><dd class="font-medium tabular-nums">{money(detail.amount, detail.currency)}</dd>
                  <dt class="opacity-60">状态</dt><dd><StatusBadge status={detail.status} /></dd>
                </dl>
              </Tabs.Content>
              <Tabs.Content value="timeline">
                <ol class="relative border-s border-surface-200-800 ms-2 space-y-4 text-sm">
                  <li class="ms-4"><span class="absolute -start-1.5 mt-1.5 size-3 rounded-full bg-primary-500"></span>订单创建 <time class="block text-xs opacity-60">{detail.date}</time></li>
                  <li class="ms-4"><span class="absolute -start-1.5 mt-1.5 size-3 rounded-full bg-surface-300-700"></span>状态更新为「{detail.status}」</li>
                </ol>
              </Tabs.Content>
              <Tabs.Content value="notes">
                <label class="label">
                  <span class="label-text">内部备注</span>
                  <textarea class="textarea" rows="4" placeholder="记录跟进信息…" bind:value={note}></textarea>
                </label>
                <button type="button" class="btn preset-filled-primary-500 mt-3" onclick={saveNote} disabled={!note.trim()}>保存备注</button>
              </Tabs.Content>
            </Tabs>
          </div>
          <footer class="p-4 border-t border-surface-200-800 flex justify-between gap-2">
            <button type="button" class="btn preset-outlined-error-500" onclick={() => (pendingDelete = detail)}><Icon name="trash" /><span>删除</span></button>
            <button type="button" class="btn preset-filled-primary-500" onclick={() => toaster.success({ title: "已发送发票", description: detail?.email })}>发送发票</button>
          </footer>
        {/if}
      </Dialog.Content>
    </Dialog.Positioner>
  </Portal>
</Dialog>

<Dialog open={pendingDelete !== null} onOpenChange={(d) => { if (!d.open) pendingDelete = null }} role="alertdialog">
  <Portal>
    <Dialog.Backdrop class="fixed inset-0 z-[60] bg-surface-50-950/50" />
    <Dialog.Positioner class="fixed inset-0 z-[60] grid place-items-center p-4">
      <Dialog.Content class="card bg-surface-50-950 p-6 w-full max-w-sm space-y-4 shadow-xl">
        <Dialog.Title class="h5">删除订单？</Dialog.Title>
        <Dialog.Description class="text-sm opacity-70">订单 {pendingDelete?.id} 将被永久删除，此操作无法撤销。</Dialog.Description>
        <div class="flex justify-end gap-2">
          <Dialog.CloseTrigger class="btn preset-tonal">取消</Dialog.CloseTrigger>
          <button type="button" class="btn preset-filled-error-500" onclick={confirmDelete}>删除</button>
        </div>
      </Dialog.Content>
    </Dialog.Positioner>
  </Portal>
</Dialog>

// apps/primer-react/src/pages/orders.tsx
import { useEffect, useMemo, useRef, useState } from "react"
import { ActionList, ActionMenu, Avatar, Banner, Button, Checkbox, ConfirmationDialog, Dialog, FormControl, IconButton, Label, Pagination, Popover, Select, SelectPanel, SegmentedControl, Spinner, Text, TextInput, Textarea, type SelectPanelItemInput } from "@primer/react"
import { Blankslate, Table, UnderlinePanels } from "@primer/react/experimental"
import ordersData from "@ui-gallery/spec/mock/orders.json"
import { Icon, iconFor } from "@/lib/icon"
import { avatarFor } from "@/lib/avatar"
import { PageHeader, StatusBadge } from "./shared"

type Order = (typeof ordersData)[number]
type SortKey = "id" | "customer" | "amount" | "date" | "status"
type ViewState = "data" | "loading" | "empty" | "error"

const statuses = ["all", "paid", "pending", "refunded", "failed", "shipped"] as const
const statusLabel: Record<string, string> = { all: "全部状态", paid: "已支付", pending: "待处理", refunded: "已退款", failed: "失败", shipped: "已发货" }
const channelItems: SelectPanelItemInput[] = Array.from(new Set(ordersData.map((o) => o.channel))).map((c) => ({ id: c, text: c }))
const columns = [
  { key: "customer", label: "客户" },
  { key: "product", label: "产品" },
  { key: "channel", label: "渠道" },
  { key: "date", label: "日期" },
] as const
type ColumnKey = (typeof columns)[number]["key"]

function SortHeader({ label, active, direction, onClick }: { label: string; active: boolean; direction: "asc" | "desc"; onClick: () => void }) {
  return (
    <button type="button" className="sort-header" aria-sort={active ? (direction === "asc" ? "ascending" : "descending") : "none"} onClick={onClick}>
      <span>{label}</span>
      <Icon name={active ? (direction === "asc" ? "sort-asc" : "sort-desc") : "triangle-down"} size={12} />
    </button>
  )
}

export function OrdersPage() {
  const [view, setView] = useState<ViewState>("data")
  const [query, setQuery] = useState("")
  const [status, setStatus] = useState<string>("all")
  const [dateFrom, setDateFrom] = useState("")
  const [dateTo, setDateTo] = useState("")
  const [dateOpen, setDateOpen] = useState(false)
  const [channelOpen, setChannelOpen] = useState(false)
  const [channels, setChannels] = useState<SelectPanelItemInput[]>([])
  const [channelFilter, setChannelFilter] = useState("")
  const [visible, setVisible] = useState<Record<ColumnKey, boolean>>({ customer: true, product: true, channel: true, date: true })
  const [sortKey, setSortKey] = useState<SortKey>("date")
  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc")
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [selectedIds, setSelectedIds] = useState<string[]>([])
  const [rows, setRows] = useState<Order[]>(ordersData)
  const [detail, setDetail] = useState<Order | null>(null)
  const [editing, setEditing] = useState<Order | null>(null)
  const [pendingDelete, setPendingDelete] = useState<Order[] | null>(null)
  const [toast, setToast] = useState<string | null>(null)
  const [note, setNote] = useState("")
  const dateAnchor = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    if (!toast) return
    const timer = window.setTimeout(() => setToast(null), 4000)
    return () => window.clearTimeout(timer)
  }, [toast])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    const selectedChannels = channels.map((c) => String(c.id))
    const list = rows.filter((o) => {
      if (q && !`${o.id} ${o.customer} ${o.email} ${o.product}`.toLowerCase().includes(q)) return false
      if (status !== "all" && o.status !== status) return false
      if (selectedChannels.length && !selectedChannels.includes(o.channel)) return false
      if (dateFrom && o.date < dateFrom) return false
      if (dateTo && o.date > dateTo) return false
      return true
    })
    const dir = sortDir === "asc" ? 1 : -1
    return [...list].sort((a, b) => {
      const av = a[sortKey]
      const bv = b[sortKey]
      if (typeof av === "number" && typeof bv === "number") return (av - bv) * dir
      return String(av).localeCompare(String(bv), "zh-Hans-CN") * dir
    })
  }, [rows, query, status, channels, dateFrom, dateTo, sortKey, sortDir])

  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize))
  const currentPage = Math.min(page, pageCount)
  const pageRows = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const allOnPageSelected = pageRows.length > 0 && pageRows.every((r) => selectedIds.includes(r.id))
  const someOnPageSelected = pageRows.some((r) => selectedIds.includes(r.id))

  const toggleSort = (key: SortKey) => {
    if (sortKey === key) setSortDir(sortDir === "asc" ? "desc" : "asc")
    else { setSortKey(key); setSortDir("asc") }
  }
  const toggleRow = (id: string) => setSelectedIds(selectedIds.includes(id) ? selectedIds.filter((x) => x !== id) : [...selectedIds, id])
  const togglePage = () => setSelectedIds(allOnPageSelected ? selectedIds.filter((id) => !pageRows.some((r) => r.id === id)) : Array.from(new Set([...selectedIds, ...pageRows.map((r) => r.id)])))
  const confirmDelete = (gesture: string) => {
    if (gesture === "confirm" && pendingDelete) {
      const ids = pendingDelete.map((o) => o.id)
      setRows(rows.filter((o) => !ids.includes(o.id)))
      setSelectedIds(selectedIds.filter((id) => !ids.includes(id)))
      if (detail && ids.includes(detail.id)) setDetail(null)
      setToast(`已删除 ${ids.length} 个订单：${ids.join("、")}`)
    }
    setPendingDelete(null)
  }
  const resetFilters = () => { setQuery(""); setStatus("all"); setChannels([]); setDateFrom(""); setDateTo(""); setPage(1) }
  const isFiltered = query || status !== "all" || channels.length || dateFrom || dateTo

  return (
    <div className="page-stack">
      <PageHeader
        title="订单"
        description={`共 ${rows.length} 个订单，可搜索、筛选、排序与批量操作。`}
        action={
          <div className="flex items-center gap-2 wrap">
            <SegmentedControl aria-label="页面状态" size="small" onChange={(index) => setView((["data", "loading", "empty", "error"] as ViewState[])[index])}>
              <SegmentedControl.Button selected={view === "data"}>数据</SegmentedControl.Button>
              <SegmentedControl.Button selected={view === "loading"}>加载</SegmentedControl.Button>
              <SegmentedControl.Button selected={view === "empty"}>空态</SegmentedControl.Button>
              <SegmentedControl.Button selected={view === "error"}>错误</SegmentedControl.Button>
            </SegmentedControl>
            <Button leadingVisual={iconFor("download")}>导出 CSV</Button>
            <Button variant="primary" leadingVisual={iconFor("plus")}>新建订单</Button>
          </div>
        }
      />

      <section className="card stack-4">
        <div className="toolbar">
          <TextInput className="toolbar-search" aria-label="搜索订单" placeholder="搜索订单号、客户、邮箱..." leadingVisual={iconFor("search")} value={query} onChange={(e) => { setQuery(e.target.value); setPage(1) }} block />
          <Select aria-label="状态筛选" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}>
            {statuses.map((s) => <Select.Option key={s} value={s}>{statusLabel[s]}</Select.Option>)}
          </Select>
          <SelectPanel
            title="按渠道筛选"
            placeholder="搜索渠道"
            renderAnchor={({ children, ...anchorProps }) => <Button {...anchorProps} leadingVisual={iconFor("filter")} trailingAction={iconFor("triangle-down")}>{children || (channels.length ? `渠道 (${channels.length})` : "渠道")}</Button>}
            open={channelOpen}
            onOpenChange={setChannelOpen}
            items={channelItems.filter((c) => c.text?.toLowerCase().includes(channelFilter.toLowerCase()))}
            selected={channels}
            onSelectedChange={(next: SelectPanelItemInput[]) => { setChannels(next); setPage(1) }}
            filterValue={channelFilter}
            onFilterChange={setChannelFilter}
            overlayProps={{ width: "small", height: "xsmall" }}
          />
          <Button ref={dateAnchor} leadingVisual={iconFor("calendar")} trailingAction={iconFor("triangle-down")} onClick={() => setDateOpen(!dateOpen)} aria-expanded={dateOpen}>
            {dateFrom || dateTo ? `${dateFrom || "…"} ~ ${dateTo || "…"}` : "日期范围"}
          </Button>
          <div className="popover-anchor">
            <Popover open={dateOpen} caret="top-left">
              <Popover.Content className="stack-3" style={{ width: 300 }}>
                <FormControl><FormControl.Label>开始日期</FormControl.Label><TextInput type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} block /></FormControl>
                <FormControl><FormControl.Label>结束日期</FormControl.Label><TextInput type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} block /></FormControl>
                <div className="flex justify-between gap-2"><Button variant="invisible" onClick={() => { setDateFrom(""); setDateTo("") }}>清除</Button><Button variant="primary" onClick={() => { setDateOpen(false); setPage(1) }}>应用</Button></div>
              </Popover.Content>
            </Popover>
          </div>
          <ActionMenu>
            <ActionMenu.Button leadingVisual={iconFor("columns")}>列</ActionMenu.Button>
            <ActionMenu.Overlay align="end">
              <ActionList selectionVariant="multiple">
                {columns.map((c) => <ActionList.Item key={c.key} selected={visible[c.key]} onSelect={() => setVisible({ ...visible, [c.key]: !visible[c.key] })}>{c.label}</ActionList.Item>)}
              </ActionList>
            </ActionMenu.Overlay>
          </ActionMenu>
          {selectedIds.length ? (
            <div className="flex items-center gap-2 bulk-bar">
              <Text size="small">已选 {selectedIds.length} 项</Text>
              <Button size="small" variant="danger" leadingVisual={iconFor("trash")} onClick={() => setPendingDelete(rows.filter((o) => selectedIds.includes(o.id)))}>批量删除</Button>
              <Button size="small" variant="invisible" onClick={() => setSelectedIds([])}>取消选择</Button>
            </div>
          ) : null}
        </div>

        {view === "loading" ? (
          <div className="state-box" role="status" aria-live="polite"><Spinner size="medium" /><Text className="muted">正在加载订单数据…</Text></div>
        ) : view === "error" ? (
          <Banner variant="critical" title="订单加载失败" description="服务暂时不可用，请稍后重试或联系管理员。" primaryAction={<Banner.PrimaryAction onClick={() => setView("data")}>重试</Banner.PrimaryAction>} secondaryAction={<Banner.SecondaryAction onClick={() => setView("empty")}>查看空态</Banner.SecondaryAction>} />
        ) : view === "empty" || filtered.length === 0 ? (
          <Blankslate border>
            <Blankslate.Visual><Icon name="inbox" size={24} /></Blankslate.Visual>
            <Blankslate.Heading>{isFiltered && view === "data" ? "没有匹配的订单" : "暂无订单"}</Blankslate.Heading>
            <Blankslate.Description>{isFiltered && view === "data" ? "试试调整搜索关键词或筛选条件。" : "当有新订单进入系统时，它们会显示在这里。"}</Blankslate.Description>
            <Button variant="primary" onClick={() => { resetFilters(); setView("data") }}>{isFiltered && view === "data" ? "清除筛选" : "新建订单"}</Button>
          </Blankslate>
        ) : (
          <>
            <div className="table-scroll desktop-only-block orders-table">
              <Table aria-label="订单列表" gridTemplateColumns={`40px minmax(120px, auto) ${visible.customer ? "minmax(180px, 1.4fr)" : ""} ${visible.product ? "minmax(120px, 1fr)" : ""} ${visible.channel ? "minmax(90px, auto)" : ""} minmax(100px, auto) ${visible.date ? "minmax(120px, auto)" : ""} minmax(110px, auto) 48px`}>
                <Table.Head>
                  <Table.Row>
                    <Table.Header><Checkbox aria-label="选择本页全部" checked={allOnPageSelected} indeterminate={!allOnPageSelected && someOnPageSelected} onChange={togglePage} /></Table.Header>
                    <Table.Header><SortHeader label="订单号" active={sortKey === "id"} direction={sortDir} onClick={() => toggleSort("id")} /></Table.Header>
                    {visible.customer ? <Table.Header><SortHeader label="客户" active={sortKey === "customer"} direction={sortDir} onClick={() => toggleSort("customer")} /></Table.Header> : null}
                    {visible.product ? <Table.Header>产品</Table.Header> : null}
                    {visible.channel ? <Table.Header>渠道</Table.Header> : null}
                    <Table.Header><SortHeader label="状态" active={sortKey === "status"} direction={sortDir} onClick={() => toggleSort("status")} /></Table.Header>
                    {visible.date ? <Table.Header><SortHeader label="日期" active={sortKey === "date"} direction={sortDir} onClick={() => toggleSort("date")} /></Table.Header> : null}
                    <Table.Header align="end"><SortHeader label="金额" active={sortKey === "amount"} direction={sortDir} onClick={() => toggleSort("amount")} /></Table.Header>
                    <Table.Header><span className="sr-only">操作</span></Table.Header>
                  </Table.Row>
                </Table.Head>
                <Table.Body>
                  {pageRows.map((order) => (
                    <Table.Row key={order.id} className={selectedIds.includes(order.id) ? "row-selected" : undefined}>
                      <Table.Cell><Checkbox aria-label={`选择 ${order.id}`} checked={selectedIds.includes(order.id)} onChange={() => toggleRow(order.id)} /></Table.Cell>
                      <Table.Cell scope="row"><button type="button" className="link-button mono" onClick={() => setDetail(order)}>{order.id}</button></Table.Cell>
                      {visible.customer ? <Table.Cell><div className="flex items-center gap-2"><Avatar src={avatarFor(order.customer)} alt="" size={24} /><div className="min-w-0"><Text as="div" className="truncate">{order.customer}</Text><Text as="div" size="small" className="muted truncate">{order.email}</Text></div></div></Table.Cell> : null}
                      {visible.product ? <Table.Cell>{order.product}</Table.Cell> : null}
                      {visible.channel ? <Table.Cell><Label>{order.channel}</Label></Table.Cell> : null}
                      <Table.Cell><StatusBadge value={order.status} /></Table.Cell>
                      {visible.date ? <Table.Cell>{order.date}</Table.Cell> : null}
                      <Table.Cell align="end">¥{order.amount.toLocaleString("zh-CN", { minimumFractionDigits: 2 })}</Table.Cell>
                      <Table.Cell>
                        <ActionMenu>
                          <ActionMenu.Anchor><IconButton size="small" variant="invisible" aria-label={`${order.id} 更多操作`} icon={iconFor("kebab-horizontal")} /></ActionMenu.Anchor>
                          <ActionMenu.Overlay align="end">
                            <ActionList>
                              <ActionList.Item onSelect={() => setDetail(order)}><ActionList.LeadingVisual><Icon name="eye" /></ActionList.LeadingVisual>查看详情</ActionList.Item>
                              <ActionList.Item onSelect={() => setEditing(order)}><ActionList.LeadingVisual><Icon name="pencil" /></ActionList.LeadingVisual>编辑</ActionList.Item>
                              <ActionList.Item onSelect={() => setToast(`${order.id} 的发票已开始下载`)}><ActionList.LeadingVisual><Icon name="download" /></ActionList.LeadingVisual>下载发票</ActionList.Item>
                              <ActionList.Divider />
                              <ActionList.Item variant="danger" onSelect={() => setPendingDelete([order])}><ActionList.LeadingVisual><Icon name="trash" /></ActionList.LeadingVisual>删除</ActionList.Item>
                            </ActionList>
                          </ActionMenu.Overlay>
                        </ActionMenu>
                      </Table.Cell>
                    </Table.Row>
                  ))}
                </Table.Body>
              </Table>
            </div>

            <ul className="order-cards mobile-only-block" aria-label="订单列表（移动端）">
              {pageRows.map((order) => (
                <li key={order.id} className="card order-card">
                  <div className="flex items-center justify-between gap-2">
                    <label className="flex items-center gap-2 check-row"><Checkbox aria-label={`选择 ${order.id}`} checked={selectedIds.includes(order.id)} onChange={() => toggleRow(order.id)} /><button type="button" className="link-button mono" onClick={() => setDetail(order)}>{order.id}</button></label>
                    <StatusBadge value={order.status} />
                  </div>
                  <div className="flex items-center gap-2"><Avatar src={avatarFor(order.customer)} alt="" size={24} /><Text>{order.customer}</Text><Text className="muted" size="small">· {order.product}</Text></div>
                  <div className="flex items-center justify-between gap-2"><Text className="muted" size="small">{order.date} · {order.channel}</Text><Text weight="semibold">¥{order.amount.toLocaleString()}</Text></div>
                </li>
              ))}
            </ul>

            <div className="pager">
              <div className="flex items-center gap-2 wrap">
                <Text size="small" className="muted">第 {(currentPage - 1) * pageSize + 1}–{Math.min(currentPage * pageSize, filtered.length)} 条，共 {filtered.length} 条</Text>
                <Select aria-label="每页条数" size="small" value={String(pageSize)} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1) }}>
                  {[5, 10, 20].map((n) => <Select.Option key={n} value={String(n)}>{n} 条/页</Select.Option>)}
                </Select>
              </div>
              <Pagination pageCount={pageCount} currentPage={currentPage} onPageChange={(e, n) => { e.preventDefault(); setPage(n) }} showPages={{ narrow: false, regular: true }} />
            </div>
          </>
        )}
      </section>

      {detail ? (
        <Dialog title={`订单 ${detail.id}`} subtitle={`${detail.customer} · ${detail.date}`} position={{ narrow: "fullscreen", regular: "right" }} width="large" onClose={() => setDetail(null)}
          footerButtons={[{ buttonType: "danger", content: "删除订单", onClick: () => setPendingDelete([detail]) }, { buttonType: "default", content: "编辑", onClick: () => setEditing(detail) }, { buttonType: "primary", content: "保存备注", onClick: () => { setToast(`已保存 ${detail.id} 的备注`); setDetail(null) } }]}>
          <div className="stack-4">
            <div className="flex items-center gap-3">
              <Avatar src={avatarFor(detail.customer)} alt="" size={48} />
              <div><Text as="div" weight="semibold">{detail.customer}</Text><Text as="div" className="muted" size="small">{detail.email}</Text></div>
              <span className="ml-auto"><StatusBadge value={detail.status} /></span>
            </div>
            <dl className="descriptions">
              <div><dt>订单号</dt><dd className="mono">{detail.id}</dd></div>
              <div><dt>产品</dt><dd>{detail.product}</dd></div>
              <div><dt>金额</dt><dd>¥{detail.amount.toLocaleString("zh-CN", { minimumFractionDigits: 2 })} {detail.currency}</dd></div>
              <div><dt>渠道</dt><dd>{detail.channel}</dd></div>
              <div><dt>下单日期</dt><dd>{detail.date}</dd></div>
              <div><dt>状态</dt><dd><StatusBadge value={detail.status} /></dd></div>
            </dl>
            <UnderlinePanels aria-label="订单详情分组">
              <UnderlinePanels.Tab>时间线</UnderlinePanels.Tab>
              <UnderlinePanels.Tab>商品</UnderlinePanels.Tab>
              <UnderlinePanels.Tab>备注</UnderlinePanels.Tab>
              <UnderlinePanels.Panel>
                <ActionList>
                  <ActionList.Item><ActionList.LeadingVisual><Icon name="check-circle" /></ActionList.LeadingVisual>订单创建<ActionList.Description variant="block">{detail.date}</ActionList.Description></ActionList.Item>
                  <ActionList.Item><ActionList.LeadingVisual><Icon name="credit-card" /></ActionList.LeadingVisual>支付状态：{statusLabel[detail.status] ?? detail.status}<ActionList.Description variant="block">来自 {detail.channel} 渠道</ActionList.Description></ActionList.Item>
                </ActionList>
              </UnderlinePanels.Panel>
              <UnderlinePanels.Panel>
                <ActionList>
                  <ActionList.Item><ActionList.LeadingVisual><Icon name="package" /></ActionList.LeadingVisual>{detail.product}<ActionList.TrailingVisual>¥{detail.amount.toLocaleString()}</ActionList.TrailingVisual></ActionList.Item>
                </ActionList>
              </UnderlinePanels.Panel>
              <UnderlinePanels.Panel>
                <FormControl><FormControl.Label>内部备注</FormControl.Label><Textarea block rows={4} value={note} onChange={(e) => setNote(e.target.value)} placeholder="记录客服沟通、发货说明等" /><FormControl.Caption>备注仅团队内部可见。</FormControl.Caption></FormControl>
              </UnderlinePanels.Panel>
            </UnderlinePanels>
          </div>
        </Dialog>
      ) : null}

      {editing ? (
        <Dialog title={`编辑 ${editing.id}`} onClose={() => setEditing(null)} width="medium" footerButtons={[{ buttonType: "default", content: "取消", onClick: () => setEditing(null) }, { buttonType: "primary", content: "保存", onClick: () => { setToast(`${editing.id} 已更新`); setEditing(null) } }]}>
          <div className="stack-3">
            <FormControl><FormControl.Label>客户</FormControl.Label><TextInput block defaultValue={editing.customer} /></FormControl>
            <FormControl><FormControl.Label>产品</FormControl.Label><TextInput block defaultValue={editing.product} /></FormControl>
            <FormControl><FormControl.Label>状态</FormControl.Label><Select block defaultValue={editing.status}>{statuses.filter((s) => s !== "all").map((s) => <Select.Option key={s} value={s}>{statusLabel[s]}</Select.Option>)}</Select></FormControl>
          </div>
        </Dialog>
      ) : null}

      {pendingDelete ? (
        <ConfirmationDialog title={pendingDelete.length > 1 ? `删除 ${pendingDelete.length} 个订单？` : `删除订单 ${pendingDelete[0].id}？`} onClose={confirmDelete} confirmButtonType="danger" confirmButtonContent="确认删除" cancelButtonContent="取消">
          此操作不可撤销，订单记录与关联发票将被永久移除。
        </ConfirmationDialog>
      ) : null}

      {toast ? (
        <div className="toast" role="status" aria-live="polite">
          <Banner variant="success" title={toast} hideTitle={false} onDismiss={() => setToast(null)} />
        </div>
      ) : null}
    </div>
  )
}
