// apps/reference/src/components/ui/card.tsx
import * as React from "react"
import { cn } from "cn"

/** 卡片：hifi .card —— surface / 1px border / radius.lg / shadow.sm / space.6 内距 */
function Card({ className, ...props }: React.ComponentProps<"section">) {
  return (
    <section
      data-slot="card"
      className={cn("min-w-0 rounded-lg border bg-surface p-6 text-fg shadow-sm", className)}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"header">) {
  return (
    <header
      data-slot="card-header"
      className={cn("mb-4 flex min-h-hit items-center justify-between gap-4", className)}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"h2">) {
  return <h2 data-slot="card-title" className={cn("text-role-title", className)} {...props} />
}

function CardDescription({ className, ...props }: React.ComponentProps<"p">) {
  return <p data-slot="card-description" className={cn("mt-1 text-role-caption text-fg-muted", className)} {...props} />
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="card-action" className={cn("-mr-3 shrink-0", className)} {...props} />
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="card-content" className={cn("min-w-0", className)} {...props} />
}

export { Card, CardHeader, CardTitle, CardDescription, CardAction, CardContent }

// apps/kobalte/src/ui/card.tsx
import type { ParentProps } from "solid-js"

export function Card(props: ParentProps<{ class?: string; id?: string }>) { return <section id={props.id} class={`min-w-0 rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900 ${props.class ?? ""}`}>{props.children}</section> }
export function CardHeader(props: ParentProps<{ class?: string }>) { return <header class={`space-y-1 p-5 ${props.class ?? ""}`}>{props.children}</header> }
export function CardTitle(props: ParentProps<{ class?: string }>) { return <h2 class={`font-semibold tracking-tight ${props.class ?? ""}`}>{props.children}</h2> }
export function CardDescription(props: ParentProps<{ class?: string }>) { return <p class={`text-sm text-zinc-500 dark:text-zinc-400 ${props.class ?? ""}`}>{props.children}</p> }
export function CardContent(props: ParentProps<{ class?: string }>) { return <div class={`p-5 pt-0 ${props.class ?? ""}`}>{props.children}</div> }
export function CardFooter(props: ParentProps<{ class?: string }>) { return <footer class={`p-5 pt-0 ${props.class ?? ""}`}>{props.children}</footer> }
