// apps/ant-design-vue/src/pages/chat.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { marked } from "marked"
import { message } from "ant-design-vue"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Icon } from "../icons"
const draft = ref("")
const active = ref(chat.conversations[0].id)
const mobileOpen = ref(false)
const empty = new URLSearchParams(location.search).get("empty") === "1"
const current = computed(() => chat.conversations.find((item) => item.id === active.value))
function markdown(value: string) { return marked.parse(value) as string }
function copy(value: string) { navigator.clipboard?.writeText(value); message.success("已复制") }
</script>
<template>
  <div class="page"><div class="page-header"><div><h1>AI 对话</h1><p class="muted">与团队智能助手协作，保留完整上下文。</p></div><a-button class="mobile-menu" @click="mobileOpen = true"><Icon name="message-square" />会话</a-button></div>
    <a-drawer v-model:open="mobileOpen" title="会话"><div class="chat-list"><a-input-search placeholder="搜索对话" /><a-button block class="section">新建对话</a-button><a-list class="section" :data-source="chat.conversations"><template #renderItem="{ item }"><a-list-item :class="{ active: active === item.id }" @click="active = item.id; mobileOpen = false"><span>{{ item.title }}<small class="muted">{{ item.time }}</small></span><a-badge v-if="item.unread" :count="item.unread" /></a-list-item></template></a-list></div></a-drawer>
    <div class="chat-layout"><aside class="chat-list"><div class="section-title"><strong>对话</strong><a-button type="text" shape="circle"><Icon name="plus" /></a-button></div><a-input-search placeholder="搜索对话" /><a-button block class="section">新建对话</a-button><a-list class="section" :data-source="chat.conversations"><template #renderItem="{ item }"><a-list-item :class="{ active: active === item.id }" @click="active = item.id"><span>{{ item.title }}<small class="muted">{{ item.time }}</small></span><a-badge v-if="item.unread" :count="item.unread" /></a-list-item></template></a-list></aside>
      <section class="chat-main"><header class="chat-header"><strong>{{ current?.title ?? "新对话" }}</strong><a-select :default-value="chat.models[0]" style="width:150px"><a-select-option v-for="model in chat.models" :key="model" :value="model">{{ model }}</a-select-option></a-select></header>
        <div v-if="empty || !current" class="chat-messages"><a-empty description="开始一次新的对话"><template #image><Icon name="bot" :size="36" /></template><a-row :gutter="[12, 12]"><a-col v-for="item in chat.suggestions" :key="item" :xs="24" :sm="12"><a-card hoverable @click="draft = item">{{ item }}</a-card></a-col></a-row></a-empty></div>
        <div v-else class="chat-messages"><div v-for="(item, index) in chat.messages" :key="index" class="message" :class="{ user: item.role === 'user' }"><a-avatar>{{ item.role === 'user' ? '林' : 'AI' }}</a-avatar><div class="bubble"><div class="muted">{{ item.role === 'user' ? '林晓' : 'AI 助手' }} · 刚刚</div><div v-if="item.role === 'assistant'" class="markdown" v-html="markdown(item.content)" /><span v-else>{{ item.content }}</span><div v-if="item.streaming" class="muted">生成中<span class="cursor">▋</span></div><div v-if="item.sources" class="source-list"><a-tag v-for="source in item.sources" :key="source">{{ source }}</a-tag></div><a-collapse v-if="item.tool" class="section"><a-collapse-panel key="tool" :header="`工具调用 · ${item.tool.name}`"><pre>{{ JSON.stringify(item.tool.args, null, 2) }}</pre></a-collapse-panel></a-collapse><a-button v-if="item.role === 'assistant' && item.content.includes('```')" size="small" class="section" @click="copy(item.content)">复制</a-button></div></div></div>
        <div class="composer"><div class="suggestions"><a-tag v-for="suggestion in chat.suggestions" :key="suggestion" @click="draft = suggestion">{{ suggestion }}</a-tag></div><a-textarea v-model:value="draft" :auto-size="{ minRows: 2, maxRows: 5 }" placeholder="向 AI 助手提问..." /><div class="composer-actions"><span class="muted">{{ draft.length }} / 2000 · Enter 发送 / Shift+Enter 换行</span><a-space><a-button type="text"><Icon name="paperclip" /></a-button><a-button type="primary" shape="circle"><Icon name="send" /></a-button></a-space></div></div>
      </section>
    </div>
  </div>
</template>
<style scoped>.chat-header { display:flex; justify-content:space-between; align-items:center; padding:16px 20px; border-bottom:1px solid var(--ant-color-border); }.chat-list :deep(.ant-list-item) { cursor:pointer; border-radius:8px; padding:10px; }.chat-list :deep(.ant-list-item.active), .chat-list :deep(.ant-list-item:hover) { background:var(--ant-color-fill-quaternary); }.chat-list small { display:block; }.suggestions { display:flex; flex-wrap:wrap; gap:8px; margin-bottom:10px; }.suggestions .ant-tag { cursor:pointer; }.composer-actions { display:flex; justify-content:space-between; align-items:center; margin-top:8px; }.markdown :deep(pre) { padding:12px; border-radius:8px; background:#111; color:#eee; overflow:auto; }.markdown :deep(table) { border-collapse:collapse; width:100%; }.markdown :deep(th), .markdown :deep(td) { border:1px solid var(--ant-color-border); padding:6px; }.source-list { display:flex; flex-wrap:wrap; gap:6px; margin-top:10px; }.cursor { animation:blink 1s infinite; } @keyframes blink { 50% { opacity:0; } } @media (max-width:767px) { .chat-layout { display:block; }.chat-layout > .chat-list { display:none; } }</style>

// apps/arco-design/src/pages/chat.tsx
import { useRef, useState, type ComponentProps } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Avatar, Badge, Button, Card, Drawer, Input, List, Message, Select, Skeleton, Space, Spin, Tag, Typography } from "@arco-design/web-react"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Icon } from "@/components/icon"
import { useIsMobile } from "@/hooks/use-mobile"
import { PageHeader } from "./shared"

const NEW_CONVERSATION = "new"

function CodeBlock({ children, ...rest }: ComponentProps<"pre">) {
  const ref = useRef<HTMLPreElement>(null)
  const copy = () => {
    void navigator.clipboard?.writeText(ref.current?.textContent ?? "")
    Message.success("代码已复制")
  }
  return <div className="chat-code"><pre ref={ref} {...rest}>{children}</pre><Button className="chat-code-copy hit-area" type="secondary" icon={<Icon name="copy" />} onClick={copy} aria-label="复制代码" /></div>
}

function ConversationList({ active, onSelect }: { active: string; onSelect: (id: string) => void }) {
  return <div className="chat-sidebar"><div className="between"><Typography.Title heading={4}>对话</Typography.Title><Button type="text" className="hit-area" icon={<Icon name="plus" />} aria-label="新建对话" onClick={() => onSelect(NEW_CONVERSATION)} /></div><Input.Search placeholder="搜索对话" /><Button type="primary" long size="large" className="hit-area" icon={<Icon name="plus" />} onClick={() => onSelect(NEW_CONVERSATION)}>新建对话</Button><List dataSource={chat.conversations} render={(item) => <List.Item key={item.id} className={item.id === active ? "chat-selected" : ""} onClick={() => onSelect(item.id)} style={{ cursor: "pointer" }}><List.Item.Meta title={item.title} description={item.time} />{item.unread ? <Badge count={item.unread} /> : null}</List.Item>} /></div>
}

export function ChatPage() {
  const isMobile = useIsMobile()
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [draft, setDraft] = useState("")
  const [active, setActive] = useState(chat.conversations[0].id)
  const conversation = chat.conversations.find((item) => item.id === active)
  const isEmpty = active === NEW_CONVERSATION
  const select = (id: string) => { setActive(id); setSidebarOpen(false) }
  return <>
    <PageHeader title="AI 对话" description="与团队智能助手协作，保留完整上下文。" />
    <div className="chat-layout">
      {!isMobile ? <aside><ConversationList active={active} onSelect={select} /></aside> : null}
      <section className="chat-thread">
        <header className="between chat-thread-header"><div className="row">{isMobile ? <Button type="text" size="large" className="hit-area" icon={<Icon name="menu" />} aria-label="打开会话列表" onClick={() => setSidebarOpen(true)} /> : null}<div><Typography.Text bold>{conversation?.title ?? "新对话"}</Typography.Text><Typography.Text type="secondary" style={{ display: "block" }}>GPT-5 · 已连接</Typography.Text></div></div><Select defaultValue="gpt" options={[{ label: "GPT-5", value: "gpt" }, { label: "Fast model", value: "fast" }]} /></header>
        {isEmpty ? <div className="chat-empty"><div style={{ textAlign: "center" }}><Avatar size={48} style={{ backgroundColor: "rgb(var(--primary-6))" }}><Icon name="sparkles" size={24} /></Avatar><Typography.Title heading={3}>今天想了解什么？</Typography.Title><Typography.Text type="secondary">选择一个建议开始，或直接输入问题。</Typography.Text><div className="chat-suggestion-grid">{chat.suggestions.map((suggestion) => <Card key={suggestion} size="small" hoverable onClick={() => setDraft(suggestion)}><Typography.Text>{suggestion}</Typography.Text></Card>)}</div></div></div> : <div className="chat-messages">{chat.messages.map((message, index) => <div className={`chat-message ${message.role}`} key={`${message.role}-${index}`}><Avatar style={message.role === "assistant" ? { backgroundColor: "rgb(var(--primary-6))" } : undefined}>{message.role === "user" ? "林" : "AI"}</Avatar><div className="chat-bubble"><Typography.Text bold>{message.role === "user" ? "林晓" : "AI 助手"}</Typography.Text>{message.role === "assistant" ? <ReactMarkdown remarkPlugins={[remarkGfm]} components={{ pre: CodeBlock }}>{message.content}</ReactMarkdown> : <Typography.Paragraph>{message.content}</Typography.Paragraph>}{message.sources ? <Space wrap>{message.sources.map((source) => <Tag key={source} icon={<Icon name="paperclip" />}>{source}</Tag>)}</Space> : null}{message.tool ? <Card size="small" title={`工具调用 · ${message.tool.name}`}><pre>{JSON.stringify(message.tool.args, null, 2)}</pre></Card> : null}{message.streaming ? <div className="row"><Spin size={14} /><Typography.Text type="secondary">AI 正在输入...</Typography.Text></div> : null}</div></div>)}</div>}
        <div className="chat-composer"><Space wrap>{chat.suggestions.map((suggestion) => <Button className="hit-area" key={suggestion} onClick={() => setDraft(suggestion)}>{suggestion}</Button>)}</Space><Input.TextArea value={draft} onChange={setDraft} placeholder="向 AI 助手提问..." autoSize={{ minRows: 3, maxRows: 6 }} /><div className="between"><Space><Button type="text" className="hit-area" icon={<Icon name="paperclip" />} aria-label="添加附件" /><Typography.Text type="secondary">{draft.length} 字 · Shift + Enter 换行</Typography.Text></Space><Button type="primary" size="large" className="hit-area" icon={<Icon name="send" />}>发送</Button></div></div>
      </section>
      <Drawer placement="left" width={300} title="对话" visible={sidebarOpen} onCancel={() => setSidebarOpen(false)} footer={null}><ConversationList active={active} onSelect={select} /></Drawer>
    </div>
    {isEmpty ? <Card title="流式响应占位"><Skeleton animation text={{ rows: 2 }} /></Card> : null}
  </>
}
