// apps/element-plus/src/pages/Chat.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { marked } from "marked"
import { ElMessage } from "element-plus"
import chat from "@ui-gallery/spec/mock/chat.json"
import Icon from "@/icons/Icon.vue"
import { useMobile } from "@/composables/useMobile"
const mobile = useMobile()
const conversationsOpen = ref(false)
const active = ref(chat.conversations[0].id)
const draft = ref("")
const model = ref(chat.models[0])
const copied = ref(false)
const selected = computed(() => chat.conversations.find((item) => item.id === active.value))
const render = (content: string) => marked.parse(content) as string
const selectConversation = (id: string, closeDrawer = false) => {
  active.value = id
  if (closeDrawer) conversationsOpen.value = false
}
const send = () => {
  if (!draft.value.trim()) return
  ElMessage.success("消息已发送（演示）")
  draft.value = ""
}
const copy = (text: string) => {
  navigator.clipboard?.writeText(text)
  copied.value = true
  window.setTimeout(() => (copied.value = false), 1200)
}
</script>

<template>
  <div class="page chat-page">
    <div class="page-header">
      <div>
        <h1 class="page-title">AI 对话</h1>
        <p class="page-subtitle">与团队智能助手协作，保留完整上下文。</p>
      </div>
      <el-button v-if="mobile" @click="conversationsOpen = true"><Icon name="message-square" />对话列表</el-button>
    </div>
    <el-drawer v-if="mobile" v-model="conversationsOpen" title="对话" direction="ltr" size="290px"><div class="conversation-list">
      <el-input placeholder="搜索对话"><template #prefix><Icon name="search" /></template></el-input><el-button type="primary" class="full-width new-chat"><Icon name="plus" />新建对话</el-button><el-button
        v-for="item in chat.conversations"
        :key="item.id"
        class="conversation"
        :type="active === item.id ? 'primary' : 'default'"
        plain
        @click="selectConversation(item.id, true)"
      ><span>{{ item.title }}<small>{{ item.time }}</small></span><el-badge v-if="item.unread" :value="item.unread" /></el-button></div></el-drawer>
    <el-card class="chat-card"><aside v-if="!mobile" class="conversation-pane">
                                 <div class="conversation-heading">
                                   <b>对话</b><el-button text><Icon name="plus" /></el-button>
                                 </div>
                                 <el-input placeholder="搜索对话"><template #prefix><Icon name="search" /></template></el-input><el-button type="primary" class="full-width new-chat"><Icon name="plus" />新建对话</el-button>
                                 <div class="conversation-list">
                                   <el-button
                                     v-for="item in chat.conversations"
                                     :key="item.id"
                                     class="conversation"
                                     :type="active === item.id ? 'primary' : 'default'"
                                     plain
                                     @click="active = item.id"
                                   ><span>{{ item.title }}<small>{{ item.time }}</small></span><el-badge v-if="item.unread" :value="item.unread" /></el-button>
                                 </div>
                               </aside>
      <section class="chat-main">
        <header class="chat-header">
          <div>
            <b>{{ selected?.title }}</b><small>GPT-5 · 已连接</small>
          </div>
          <el-select v-model="model" style="width: 150px"><el-option v-for="item in chat.models" :key="item" :label="item" :value="item" /></el-select>
        </header>
        <div class="messages">
          <template v-if="selected?.id === chat.conversations[0].id"><div v-for="(message, index) in chat.messages" :key="index" class="message" :class="message.role">
            <el-avatar>{{ message.role === "user" ? "林" : "AI" }}</el-avatar>
            <div class="message-body">
              <div class="message-meta">{{ message.role === "user" ? "林晓" : "AI 助手" }} · 刚刚</div>
              <div v-if="message.role === 'assistant'" class="bubble markdown" v-html="render(message.content)" />
              <div v-else class="bubble">{{ message.content }}</div>
              <div v-if="message.role === 'assistant' && message.content.includes('```')" class="code-actions">
                <el-button @click="copy(message.content)"><Icon name="copy" />{{ copied ? "已复制" : "复制代码" }}</el-button>
              </div>
              <div v-if="message.sources" class="sources">
                <el-tag v-for="source in message.sources" :key="source" size="small" effect="plain"><Icon name="paperclip" />{{ source }}</el-tag>
              </div>
              <el-collapse v-if="message.tool" class="tool"><el-collapse-item :title="`工具调用 · ${message.tool.name}`">
                <pre>{{ JSON.stringify(message.tool.args, null, 2) }}</pre>
              </el-collapse-item></el-collapse><span v-if="message.streaming" class="typing">● ● ●</span>
            </div>
          </div></template>
          <div v-else class="chat-empty">
            <Icon name="sparkles" :size="36" />
            <h2>你好，林晓，今天想聊什么？</h2>
            <p class="muted">{{ selected?.title }} · 从一个建议开始，或直接在下方输入。</p>
            <div class="suggestion-cards">
              <el-card
                v-for="suggestion in chat.suggestions"
                :key="suggestion"
                shadow="hover"
                class="suggestion-card"
                @click="draft = suggestion"
              ><Icon name="message-square" /><span>{{ suggestion }}</span></el-card>
            </div>
          </div>
        </div>
        <div class="composer">
          <div class="suggestions">
            <el-tag v-for="suggestion in chat.suggestions" :key="suggestion" round effect="plain" @click="draft = suggestion">{{
              suggestion
            }}</el-tag>
          </div>
          <el-input
            v-model="draft"
            type="textarea"
            :autosize="{ minRows: 3, maxRows: 7 }"
            maxlength="2000"
            show-word-limit
            placeholder="向 AI 助手提问..."
            @keydown.enter.exact.prevent="send"
          />
          <div class="composer-foot">
            <div class="composer-left">
              <el-button text aria-label="附件"><Icon name="paperclip" /></el-button><span class="muted"><kbd>Enter</kbd> 发送</span>
            </div>
            <el-button type="primary" @click="send"><Icon name="send" />发送</el-button>
          </div>
        </div>
      </section>
    </el-card>
  </div>
</template>

<style scoped>
.chat-card {
  padding: 0;
  overflow: hidden;
}
.chat-card :deep(.el-card__body) {
  display: grid;
  grid-template-columns: 260px minmax(0, 1fr);
  height: calc(100vh - 190px);
  min-height: 480px;
  padding: 0;
}
.conversation-pane {
  min-width: 0;
  overflow: hidden;
  padding: 16px;
  border-right: 1px solid var(--el-border-color);
}
.conversation-heading,
.chat-header,
.composer-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
.new-chat {
  margin: 12px 0;
}
.conversation-list {
  display: flex;
  min-width: 0;
  flex-direction: column;
  gap: 6px;
  margin-top: 12px;
}
.conversation {
  display: flex;
  width: 100%;
  min-width: 0;
  height: auto;
  justify-content: space-between;
  margin-left: 0 !important;
  padding: 10px;
  text-align: left;
}
.conversation :deep(.el-badge__content.is-fixed) {
  position: static;
  transform: none;
  margin-left: 6px;
}
.conversation span {
  display: grid;
  gap: 4px;
  min-width: 0;
  flex: 1;
  overflow-wrap: anywhere;
}
.conversation small {
  color: var(--el-text-color-secondary);
}
.chat-main {
  display: flex;
  min-width: 0;
  min-height: 0;
  flex-direction: column;
}
.chat-header {
  padding: 16px;
  border-bottom: 1px solid var(--el-border-color);
}
.chat-header div {
  display: grid;
  gap: 4px;
}
.chat-header small {
  color: var(--el-text-color-secondary);
}
.messages {
  flex: 1;
  min-height: 0;
  overflow: auto;
  padding: 24px;
}
.message {
  display: flex;
  gap: 10px;
  max-width: 850px;
  min-width: 0;
  margin-bottom: 24px;
}
.message.user {
  flex-direction: row-reverse;
  margin-left: auto;
  text-align: right;
}
.message-body {
  max-width: 80%;
  min-width: 0;
}
.message-meta {
  margin-bottom: 6px;
  color: var(--el-text-color-secondary);
  font-size: 12px;
}
.bubble {
  max-width: 100%;
  overflow-wrap: anywhere;
  padding: 12px 15px;
  border-radius: 12px;
  background: var(--el-fill-color-light);
  text-align: left;
  line-height: 1.65;
}
.user .bubble {
  color: #fff;
  background: var(--el-color-primary);
}
.markdown :deep(pre) {
  max-width: 100%;
  overflow-x: auto;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  word-break: break-word;
  padding: 12px;
  border-radius: 8px;
  background: var(--el-bg-color-overlay);
}
.markdown :deep(table) {
  border-collapse: collapse;
}
.markdown :deep(th),
.markdown :deep(td) {
  padding: 6px 10px;
  border: 1px solid var(--el-border-color);
}
.sources {
  display: flex;
  gap: 6px;
  margin-top: 8px;
}
.tool {
  margin-top: 10px;
}
.tool pre {
  overflow: auto;
  font-size: 12px;
}
.code-actions {
  margin-top: 5px;
}
.typing {
  display: inline-block;
  margin-top: 8px;
  color: var(--el-text-color-secondary);
  animation: pulse 1.2s infinite;
}
.chat-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  gap: 8px;
  text-align: center;
}
.chat-empty h2 {
  margin: 8px 0 0;
  font-size: 22px;
}
.chat-empty p {
  margin: 0;
}
.suggestion-cards {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  width: 100%;
  max-width: 560px;
  margin-top: 16px;
}
.suggestion-card {
  cursor: pointer;
}
.suggestion-card :deep(.el-card__body) {
  display: flex;
  align-items: center;
  gap: 10px;
  min-height: 40px;
  padding: 14px;
  text-align: left;
}
.composer {
  padding: 16px;
  border-top: 1px solid var(--el-border-color);
}
.suggestions {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
  margin-bottom: 10px;
}
.suggestions .el-tag {
  cursor: pointer;
}
.composer-foot {
  padding-top: 8px;
}
.composer-left {
  display: flex;
  align-items: center;
  gap: 4px;
}
.muted :deep(.el-icon) {
  vertical-align: middle;
}
kbd {
  padding: 2px 5px;
  border: 1px solid var(--el-border-color);
  border-radius: 4px;
}
@keyframes pulse {
  0%,
  100% {
    opacity: 0.35;
  }
  50% {
    opacity: 1;
  }
}
@media (max-width: 767px) {
  .chat-card :deep(.el-card__body) {
    display: block;
    height: calc(100vh - 190px);
    min-height: 480px;
  }
  .messages {
    padding: 16px;
  }
  .message-body {
    max-width: 88%;
  }
  .suggestion-cards {
    grid-template-columns: 1fr;
  }
}
</style>

// apps/arco-design/src/pages/chat.tsx
import { useRef, useState, type ComponentProps } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Avatar, Badge, Button, Card, Drawer, Input, List, Message, Select, Skeleton, Space, Spin, Tag, Typography } from "@arco-design/web-react"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Icon } from "@/components/icon"
import { useIsMobile } from "@/hooks/use-mobile"
import { PageHeader } from "./shared"

const NEW_CONVERSATION = "new"

function CodeBlock({ children, ...rest }: ComponentProps<"pre">) {
  const ref = useRef<HTMLPreElement>(null)
  const copy = () => {
    void navigator.clipboard?.writeText(ref.current?.textContent ?? "")
    Message.success("代码已复制")
  }
  return <div className="chat-code"><pre ref={ref} {...rest}>{children}</pre><Button className="chat-code-copy hit-area" type="secondary" icon={<Icon name="copy" />} onClick={copy} aria-label="复制代码" /></div>
}

function ConversationList({ active, onSelect }: { active: string; onSelect: (id: string) => void }) {
  return <div className="chat-sidebar"><div className="between"><Typography.Title heading={4}>对话</Typography.Title><Button type="text" className="hit-area" icon={<Icon name="plus" />} aria-label="新建对话" onClick={() => onSelect(NEW_CONVERSATION)} /></div><Input.Search placeholder="搜索对话" /><Button type="primary" long size="large" className="hit-area" icon={<Icon name="plus" />} onClick={() => onSelect(NEW_CONVERSATION)}>新建对话</Button><List dataSource={chat.conversations} render={(item) => <List.Item key={item.id} className={item.id === active ? "chat-selected" : ""} onClick={() => onSelect(item.id)} style={{ cursor: "pointer" }}><List.Item.Meta title={item.title} description={item.time} />{item.unread ? <Badge count={item.unread} /> : null}</List.Item>} /></div>
}

export function ChatPage() {
  const isMobile = useIsMobile()
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [draft, setDraft] = useState("")
  const [active, setActive] = useState(chat.conversations[0].id)
  const conversation = chat.conversations.find((item) => item.id === active)
  const isEmpty = active === NEW_CONVERSATION
  const select = (id: string) => { setActive(id); setSidebarOpen(false) }
  return <>
    <PageHeader title="AI 对话" description="与团队智能助手协作，保留完整上下文。" />
    <div className="chat-layout">
      {!isMobile ? <aside><ConversationList active={active} onSelect={select} /></aside> : null}
      <section className="chat-thread">
        <header className="between chat-thread-header"><div className="row">{isMobile ? <Button type="text" size="large" className="hit-area" icon={<Icon name="menu" />} aria-label="打开会话列表" onClick={() => setSidebarOpen(true)} /> : null}<div><Typography.Text bold>{conversation?.title ?? "新对话"}</Typography.Text><Typography.Text type="secondary" style={{ display: "block" }}>GPT-5 · 已连接</Typography.Text></div></div><Select defaultValue="gpt" options={[{ label: "GPT-5", value: "gpt" }, { label: "Fast model", value: "fast" }]} /></header>
        {isEmpty ? <div className="chat-empty"><div style={{ textAlign: "center" }}><Avatar size={48} style={{ backgroundColor: "rgb(var(--primary-6))" }}><Icon name="sparkles" size={24} /></Avatar><Typography.Title heading={3}>今天想了解什么？</Typography.Title><Typography.Text type="secondary">选择一个建议开始，或直接输入问题。</Typography.Text><div className="chat-suggestion-grid">{chat.suggestions.map((suggestion) => <Card key={suggestion} size="small" hoverable onClick={() => setDraft(suggestion)}><Typography.Text>{suggestion}</Typography.Text></Card>)}</div></div></div> : <div className="chat-messages">{chat.messages.map((message, index) => <div className={`chat-message ${message.role}`} key={`${message.role}-${index}`}><Avatar style={message.role === "assistant" ? { backgroundColor: "rgb(var(--primary-6))" } : undefined}>{message.role === "user" ? "林" : "AI"}</Avatar><div className="chat-bubble"><Typography.Text bold>{message.role === "user" ? "林晓" : "AI 助手"}</Typography.Text>{message.role === "assistant" ? <ReactMarkdown remarkPlugins={[remarkGfm]} components={{ pre: CodeBlock }}>{message.content}</ReactMarkdown> : <Typography.Paragraph>{message.content}</Typography.Paragraph>}{message.sources ? <Space wrap>{message.sources.map((source) => <Tag key={source} icon={<Icon name="paperclip" />}>{source}</Tag>)}</Space> : null}{message.tool ? <Card size="small" title={`工具调用 · ${message.tool.name}`}><pre>{JSON.stringify(message.tool.args, null, 2)}</pre></Card> : null}{message.streaming ? <div className="row"><Spin size={14} /><Typography.Text type="secondary">AI 正在输入...</Typography.Text></div> : null}</div></div>)}</div>}
        <div className="chat-composer"><Space wrap>{chat.suggestions.map((suggestion) => <Button className="hit-area" key={suggestion} onClick={() => setDraft(suggestion)}>{suggestion}</Button>)}</Space><Input.TextArea value={draft} onChange={setDraft} placeholder="向 AI 助手提问..." autoSize={{ minRows: 3, maxRows: 6 }} /><div className="between"><Space><Button type="text" className="hit-area" icon={<Icon name="paperclip" />} aria-label="添加附件" /><Typography.Text type="secondary">{draft.length} 字 · Shift + Enter 换行</Typography.Text></Space><Button type="primary" size="large" className="hit-area" icon={<Icon name="send" />}>发送</Button></div></div>
      </section>
      <Drawer placement="left" width={300} title="对话" visible={sidebarOpen} onCancel={() => setSidebarOpen(false)} footer={null}><ConversationList active={active} onSelect={select} /></Drawer>
    </div>
    {isEmpty ? <Card title="流式响应占位"><Skeleton animation text={{ rows: 2 }} /></Card> : null}
  </>
}
