// apps/element-plus/src/pages/Login.vue
<script setup lang="ts">
import { reactive, ref } from "vue"
import { ElMessage } from "element-plus"
import Icon from "@/icons/Icon.vue"
const form = reactive({ email: "", password: "", remember: false })
const loading = ref(false)
const failed = ref(false)
const rules = {
  email: [{ required: true, message: "请输入邮箱", trigger: "blur" }, { type: "email" as const, message: "请输入有效邮箱", trigger: "blur" }],
  password: [{ required: true, message: "请输入密码", trigger: "blur" }],
}
const submit = () => { failed.value = true; loading.value = true; window.setTimeout(() => { loading.value = false; ElMessage.success("演示登录已提交") }, 1200) }
</script>

<template>
  <main class="login-page">
    <el-alert v-if="failed" title="演示环境无法连接认证服务，请检查输入后重试。" type="error" closable show-icon class="login-alert" />
    <el-card class="login-card">
      <div class="login-brand"><span class="brand-mark">A</span><h1>Acme Console</h1></div>
      <p class="muted">登录控制台，管理你的团队工作。</p>
      <el-form :model="form" :rules="rules" label-position="top" class="login-form" @submit.prevent="submit">
        <el-form-item label="邮箱" prop="email"><el-input v-model="form.email" placeholder="you@example.com"><template #prefix><Icon name="user" /></template></el-input></el-form-item>
        <el-form-item label="密码" prop="password"><el-input v-model="form.password" type="password" show-password placeholder="请输入密码"><template #prefix><Icon name="lock" /></template></el-input></el-form-item>
        <div class="login-options"><el-checkbox v-model="form.remember">记住我</el-checkbox><el-link type="primary">忘记密码？</el-link></div>
        <el-button type="primary" native-type="submit" class="full-width" :loading="loading">登录</el-button>
      </el-form>
      <el-divider>或</el-divider>
      <div class="oauth"><el-button plain><Icon name="google" /> Google</el-button><el-button plain><Icon name="github" /> GitHub</el-button><el-button plain><Icon name="wechat" /> 微信</el-button></div>
      <p class="register muted">还没有账号？<el-link type="primary">注册</el-link></p>
    </el-card>
  </main>
</template>

<style scoped>
.login-page { display: grid; min-height: 100vh; place-items: center; padding: 24px; background: var(--el-bg-color-page); }
.login-card { width: min(100%, 420px); }
.login-brand { display: flex; align-items: center; gap: 12px; }
.login-brand h1 { margin: 0; font-size: 24px; }
.brand-mark { display: grid; width: 40px; height: 40px; place-items: center; border-radius: 10px; color: var(--el-color-white); background: var(--el-color-primary); font-weight: 700; font-size: 20px; }
.login-form { margin-top: 22px; }
.login-options, .oauth { display: flex; align-items: center; justify-content: space-between; gap: 10px; }
.oauth { justify-content: center; flex-wrap: wrap; }
.register { text-align: center; margin: 20px 0 0; }
.login-alert { position: fixed; top: 20px; width: min(90%, 600px); z-index: 2; }
</style>

// apps/arco-design/src/pages/login.tsx
import { useState } from "react"
import { Link } from "react-router-dom"
import { Alert, Button, Card, Checkbox, Divider, Form, Input, Message, Space, Typography } from "@arco-design/web-react"
import { Icon } from "@/components/icon"

export function LoginPage() {
  const [visible, setVisible] = useState(false)
  const [loading, setLoading] = useState(false)
  const submit = () => {
    setLoading(true)
    window.setTimeout(() => { setLoading(false); Message.success("登录成功") }, 600)
  }
  return (
    <div className="login-page">
      <Card className="login-card">
        <Space direction="vertical" size={24} style={{ width: "100%" }}>
          <Link className="brand" to="/"><span className="brand-mark">A</span>Acme Console</Link>
          <div>
            <Typography.Title heading={2}>欢迎回来</Typography.Title>
            <Typography.Text type="secondary">登录 Acme Console，继续你的工作。</Typography.Text>
          </div>
          <Alert type="error" title="演示错误状态" content="密码错误时会在这里显示验证错误。" />
          <Form layout="vertical" onSubmit={submit}>
            <Form.Item label="邮箱" field="email" rules={[{ required: true, message: "请输入邮箱" }, { type: "email", message: "邮箱格式不正确" }]}>
              <Input prefix={<Icon name="user" />} placeholder="you@example.com" />
            </Form.Item>
            <Form.Item label="密码" field="password" rules={[{ required: true, message: "请输入密码" }]}>
              <Input.Password prefix={<Icon name="lock" />} placeholder="••••••••" visibilityToggle={!visible} onVisibilityChange={setVisible} />
            </Form.Item>
            <div className="between"><Checkbox>记住我</Checkbox><Link to="#forgot">忘记密码？</Link></div>
            <Button htmlType="submit" type="primary" long loading={loading} style={{ marginTop: 16 }}>登录</Button>
          </Form>
          <Divider>或</Divider>
          <Space wrap style={{ width: "100%" }}>
            <Button type="secondary" icon={<Icon name="globe" />}>Google</Button>
            <Button type="secondary" icon={<Icon name="github" />}>GitHub</Button>
            <Button type="secondary" icon={<Icon name="message-circle" />}>微信</Button>
          </Space>
          <Typography.Text type="secondary" style={{ textAlign: "center", display: "block" }}>还没有账户？ <Link to="#register">立即注册</Link></Typography.Text>
        </Space>
      </Card>
    </div>
  )
}
