// apps/blueprint/src/App.tsx
import type { ReactNode } from "react"
import { createBrowserRouter, RouterProvider } from "react-router-dom"
import { AppShell } from "@/layouts/app-shell"
import { ChatPage } from "@/pages/chat"
import { ComponentsPage } from "@/pages/components"
import { DashboardPage } from "@/pages/dashboard"
import { FormPage } from "@/pages/form"
import { LandingPage } from "@/pages/landing"
import { LoginPage } from "@/pages/login"
import { OrdersPage } from "@/pages/orders"
import { SettingsPage } from "@/pages/settings"

const shell = (element: ReactNode) => <AppShell>{element}</AppShell>
const router = createBrowserRouter(
  [
    { path: "/login", element: <LoginPage /> },
    { path: "/", element: shell(<DashboardPage />) },
    { path: "/orders", element: shell(<OrdersPage />) },
    { path: "/form", element: shell(<FormPage />) },
    { path: "/settings", element: shell(<SettingsPage />) },
    { path: "/components", element: shell(<ComponentsPage />) },
    { path: "/landing", element: <LandingPage /> },
    { path: "/chat", element: shell(<ChatPage />) },
  ],
  { basename: "/apps/blueprint" },
)

export default function App() {
  return <RouterProvider router={router} />
}

// apps/shadcn-svelte/src/App.svelte
<script lang="ts">
  import type { Component } from "svelte"
  import { currentPath } from "$lib/router.svelte"
  import AppShell from "$lib/layouts/AppShell.svelte"
  import Login from "./routes/Login.svelte"
  import Dashboard from "./routes/Dashboard.svelte"
  import Orders from "./routes/Orders.svelte"
  import Form from "./routes/Form.svelte"
  import Settings from "./routes/Settings.svelte"
  import Components from "./routes/Components.svelte"
  import Landing from "./routes/Landing.svelte"
  import Chat from "./routes/Chat.svelte"

  const pages: Record<string, Component> = {
    "/": Dashboard,
    "/orders": Orders,
    "/form": Form,
    "/settings": Settings,
    "/components": Components,
    "/chat": Chat,
  }
  const page = $derived(pages[currentPath.value] ?? Dashboard)
</script>

{#if currentPath.value === "/login"}
  <Login />
{:else if currentPath.value === "/landing"}
  <Landing />
{:else}
  <AppShell><svelte:component this={page} /></AppShell>
{/if}
