// apps/heroui/src/layouts/app-shell.tsx
import { useState, type ReactNode } from "react"
import { Link as RouterLink, useLocation, useNavigate } from "react-router-dom"
import { Avatar, Badge, Breadcrumbs, Button, Description, Drawer, Dropdown, Label, Popover, SearchField, Separator, Surface, Tooltip } from "@heroui/react"
import { Icon } from "@/components/icon"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import team from "@ui-gallery/spec/mock/team.json"

export function Brand({ collapsed = false }: { collapsed?: boolean }) {
  return (
    <RouterLink className="flex min-h-10 items-center gap-2 font-semibold text-foreground no-underline" to="/">
      <span className="grid size-8 place-items-center rounded-lg bg-accent text-accent-foreground">A</span>
      {collapsed ? null : <span>Acme Console</span>}
    </RouterLink>
  )
}

function Navigation({ onNavigate, collapsed = false }: { onNavigate?: () => void; collapsed?: boolean }) {
  const location = useLocation()
  return (
    <nav aria-label="主导航" className="grid gap-1">
      {nav.map((item) => {
        const active = location.pathname === item.path
        return (
          <Tooltip key={item.key}>
            <RouterLink
              to={item.path}
              onClick={onNavigate}
              aria-current={active ? "page" : undefined}
              aria-label={collapsed ? item.label : undefined}
              className={`flex min-h-10 items-center gap-2 rounded-lg px-3 py-2 text-sm no-underline transition-colors ${collapsed ? "justify-center" : ""} ${active ? "bg-accent-soft text-accent-soft-foreground font-medium" : "text-muted hover:bg-surface-secondary hover:text-foreground"}`}
            >
              <Icon name={item.icon} size={16} />
              {collapsed ? null : <span className="flex-1 truncate">{item.label}</span>}
              {!collapsed && item.badge ? <span className="rounded-full bg-accent px-1.5 text-xs text-accent-foreground">{item.badge}</span> : null}
            </RouterLink>
            {collapsed ? <Tooltip.Content placement="right">{item.label}</Tooltip.Content> : null}
          </Tooltip>
        )
      })}
    </nav>
  )
}

function useThemeToggle() {
  const location = useLocation()
  const navigate = useNavigate()
  const isDark = document.documentElement.classList.contains("dark")
  return {
    isDark,
    toggle() {
      const next = isDark ? "light" : "dark"
      document.documentElement.classList.toggle("dark", next === "dark")
      document.documentElement.classList.toggle("light", next === "light")
      const params = new URLSearchParams(window.location.search)
      params.set("theme", next)
      navigate(`${location.pathname}?${params.toString()}`)
    },
  }
}

export function AppShell({ children }: { children: ReactNode }) {
  const location = useLocation()
  const navigate = useNavigate()
  const { isDark, toggle } = useThemeToggle()
  const [mobileOpen, setMobileOpen] = useState(false)
  const [collapsed, setCollapsed] = useState(false)
  const current = nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const unread = notifications.filter((item) => item.unread).length
  const owner = team.find((member) => member.role === "owner") ?? team[0]

  return (
    <div className="flex min-h-svh w-full bg-background text-foreground">
      <Surface variant="secondary" className={`sticky top-0 hidden h-svh shrink-0 flex-col rounded-none border-r border-border transition-[width] md:flex ${collapsed ? "w-16" : "w-60"}`}>
        <div className={`flex flex-col gap-2 ${collapsed ? "items-center p-2" : "p-4"}`}><Brand collapsed={collapsed} /><Button isIconOnly variant="ghost" className="min-h-10 min-w-10" aria-label={collapsed ? "展开侧栏" : "折叠侧栏"} onPress={() => setCollapsed((value) => !value)}><Icon name={collapsed ? "chevron-right" : "chevron-left"} size={16} /></Button></div>
        <div className="flex-1 overflow-y-auto px-3">
          {collapsed ? null : <p className="px-3 pb-2 text-xs font-medium text-muted">工作区</p>}
          <Navigation collapsed={collapsed} />
        </div>
        <Separator />
        <RouterLink to="/settings" aria-label="个人设置" className={`flex min-h-10 items-center gap-2 p-4 text-sm text-foreground no-underline ${collapsed ? "justify-center" : ""}`}>
          <Avatar size="sm"><Avatar.Fallback>林</Avatar.Fallback></Avatar>
          {collapsed ? null : <span>林晓</span>}
        </RouterLink>
      </Surface>
      <div className="flex min-w-0 flex-1 flex-col">
        <header className="sticky top-0 z-10 flex h-16 items-center gap-3 border-b border-border bg-background/95 px-4 backdrop-blur sm:px-6">
          <Drawer isOpen={mobileOpen} onOpenChange={setMobileOpen}>
            <Button isIconOnly variant="ghost" size="md" aria-label="打开菜单" className="min-h-10 min-w-10 md:hidden"><Icon name="menu" /></Button>
            <Drawer.Backdrop>
              <Drawer.Content placement="left" className="w-72">
                <Drawer.Dialog>
                  <Drawer.CloseTrigger />
                  <Drawer.Header><Drawer.Heading><Brand /></Drawer.Heading><p className="text-sm text-muted">导航菜单</p></Drawer.Header>
                  <Drawer.Body><Navigation onNavigate={() => setMobileOpen(false)} /></Drawer.Body>
                </Drawer.Dialog>
              </Drawer.Content>
            </Drawer.Backdrop>
          </Drawer>
          <Breadcrumbs className="hidden sm:flex">
            <Breadcrumbs.Item onPress={() => navigate("/")}>Acme Console</Breadcrumbs.Item>
            <Breadcrumbs.Item>{current}</Breadcrumbs.Item>
          </Breadcrumbs>
          <div className="ml-auto flex items-center gap-2">
            <SearchField aria-label="搜索" className="hidden w-56 md:flex">
              <SearchField.Group>
                <SearchField.SearchIcon />
                <SearchField.Input placeholder="搜索..." />
                <SearchField.ClearButton />
              </SearchField.Group>
            </SearchField>
            <Popover>
              <Badge.Anchor>
                <Button isIconOnly variant="ghost" aria-label={`通知，${unread} 条未读`}>
                  <Icon name="bell" size={18} />
                </Button>
                {unread > 0 && <Badge color="danger" size="sm">{unread}</Badge>}
              </Badge.Anchor>
              <Popover.Content placement="bottom end" className="w-80 max-w-[calc(100vw-2rem)]">
                <Popover.Dialog aria-label="通知列表">
                  <div className="flex items-center justify-between">
                    <Popover.Heading>通知</Popover.Heading>
                    <span className="text-xs text-muted">{unread} 条未读</span>
                  </div>
                  <ul className="mt-3 divide-y divide-border">
                    {notifications.map((item) => (
                      <li key={item.title} className="flex items-start gap-3 py-3">
                        <span className={`mt-1.5 size-2 shrink-0 rounded-full ${item.unread ? "bg-accent" : "bg-transparent"}`} aria-hidden="true" />
                        <div className="min-w-0 flex-1">
                          <p className={`truncate text-sm ${item.unread ? "font-medium" : "text-muted"}`}>{item.title}</p>
                          <p className="text-xs text-muted">{item.time}</p>
                        </div>
                      </li>
                    ))}
                  </ul>
                  <Button variant="ghost" size="sm" className="mt-2 w-full" onPress={() => navigate("/settings")}>查看全部通知</Button>
                </Popover.Dialog>
              </Popover.Content>
            </Popover>
            <Tooltip>
              <Button isIconOnly variant="ghost" aria-label="切换主题" onPress={toggle}>
                <Icon name={isDark ? "sun" : "moon"} size={18} />
              </Button>
              <Tooltip.Content>切换主题</Tooltip.Content>
            </Tooltip>
            <Dropdown>
              <Button isIconOnly variant="ghost" className="rounded-full" aria-label="用户菜单">
                <Avatar size="sm"><Avatar.Fallback>林</Avatar.Fallback></Avatar>
              </Button>
              <Dropdown.Popover placement="bottom end">
                <Dropdown.Menu aria-label="用户菜单" onAction={(key) => { if (key === "profile" || key === "settings" || key === "billing") navigate("/settings"); if (key === "logout") navigate("/login") }}>
                  <Dropdown.Section>
                    <Dropdown.Item id="name" isDisabled textValue={owner.name}><Label>{owner.name}</Label><Description>{owner.email}</Description></Dropdown.Item>
                  </Dropdown.Section>
                  <Dropdown.Section>
                    <Dropdown.Item id="profile" textValue="个人资料"><Icon name="user" size={16} /><Label>个人资料</Label></Dropdown.Item>
                    <Dropdown.Item id="settings" textValue="账户设置"><Icon name="settings" size={16} /><Label>账户设置</Label></Dropdown.Item>
                    <Dropdown.Item id="billing" textValue="计费与计划"><Icon name="shopping-cart" size={16} /><Label>计费与计划</Label></Dropdown.Item>
                  </Dropdown.Section>
                  <Dropdown.Section>
                    <Dropdown.Item id="logout" textValue="退出登录"><Icon name="log-out" size={16} /><Label>退出登录</Label></Dropdown.Item>
                  </Dropdown.Section>
                </Dropdown.Menu>
              </Dropdown.Popover>
            </Dropdown>
          </div>
        </header>
        <main className="min-w-0 space-y-6 p-4 sm:p-6">{children}</main>
      </div>
    </div>
  )
}

// apps/kobalte/src/layouts/app-shell.tsx
import { createEffect, createSignal, For, Show, type ParentProps } from "solid-js"
import { A, useLocation } from "@solidjs/router"
import { useColorMode } from "@kobalte/core/color-mode"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { Icon } from "@/icons"
import { Avatar } from "@/ui/avatar"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Breadcrumbs } from "@/ui/breadcrumbs"
import { Drawer } from "@/ui/dialog"
import { DropdownMenu } from "@/ui/dropdown-menu"
import { Popover } from "@/ui/popover"
import { TextField } from "@/ui/text-field"
import { Tooltip } from "@/ui/tooltip"

export function AppShell(props: ParentProps) {
  const colorMode = useColorMode()
  const location = useLocation()
  const [collapsed, setCollapsed] = createSignal(false)
  const [mobileOpen, setMobileOpen] = createSignal(false)
  createEffect(() => {
    const dark = colorMode.colorMode() === "dark"
    document.documentElement.classList.toggle("dark", dark)
    document.documentElement.classList.toggle("light", !dark)
  })
  const current = () => nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const toggleTheme = () => {
    const next = colorMode.colorMode() === "dark" ? "light" : "dark"
    colorMode.toggleColorMode()
    const url = new URL(window.location.href)
    url.searchParams.set("theme", next)
    window.history.replaceState({}, "", url)
    document.documentElement.classList.toggle("dark", next === "dark")
  }
  const links = () => (
    <nav class="grid gap-1">
      <For each={nav.filter((item) => item.path !== "/login" && item.path !== "/landing")}>
        {(item) => (
          <Tooltip.Root openDelay={300}>
            <Tooltip.Trigger as="div">
              <A href={item.path} onClick={() => setMobileOpen(false)} class={`flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors ${location.pathname === item.path ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900" : "text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800"}`}>
                <Icon name={item.icon} size={18} />
                <Show when={!collapsed()}>
                  <span class="min-w-0 flex-1 truncate">{item.label}</span>
                  {item.badge ? <Badge variant="secondary">{item.badge}</Badge> : null}
                </Show>
              </A>
            </Tooltip.Trigger>
            <Show when={collapsed()}><Tooltip.Portal><Tooltip.Content class="z-50 rounded bg-zinc-900 px-2 py-1 text-xs text-white">{item.label}</Tooltip.Content></Tooltip.Portal></Show>
          </Tooltip.Root>
        )}
      </For>
    </nav>
  )
  return (
    <div class="min-h-screen bg-zinc-50 dark:bg-zinc-950">
      <aside class={`fixed inset-y-0 left-0 z-30 hidden border-r border-zinc-200 bg-white transition-[width] lg:flex lg:flex-col dark:border-zinc-800 dark:bg-zinc-900 ${collapsed() ? "w-16" : "w-64"}`}>
        <div class="flex h-16 items-center gap-3 border-b border-zinc-200 px-4 dark:border-zinc-800"><span class="grid size-8 shrink-0 place-items-center rounded-lg bg-zinc-900 font-semibold text-white dark:bg-zinc-100 dark:text-zinc-900">A</span><Show when={!collapsed()}><span class="font-semibold">Acme Console</span></Show></div>
        <div class="flex-1 space-y-6 overflow-y-auto p-3"><Show when={!collapsed()}><p class="px-3 text-xs font-medium uppercase tracking-wider text-zinc-500">工作区</p></Show>{links()}</div>
        <div class="space-y-2 border-t border-zinc-200 p-3 dark:border-zinc-800"><A href="/settings" class="flex items-center gap-3 rounded-md p-2 text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800"><Avatar name="林晓" /><Show when={!collapsed()}><span class="min-w-0 truncate">林晓</span></Show></A><Button variant="ghost" size="icon" class="w-full" aria-label="折叠侧边栏" onClick={() => setCollapsed((value) => !value)}><Icon name={collapsed() ? "chevron-right" : "chevron-left"} size={16} /></Button></div>
      </aside>
      <div class="lg:pl-64" classList={{ "lg:pl-16": collapsed() }}>
        <header class="sticky top-0 z-20 flex h-16 min-w-0 items-center gap-3 border-b border-zinc-200 bg-white/90 px-4 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/90 sm:px-6">
          <Button variant="ghost" size="icon" class="lg:hidden" aria-label="打开导航" onClick={() => setMobileOpen(true)}><Icon name="menu" size={20} /></Button>
          <div class="hidden min-w-0 sm:flex"><Breadcrumbs items={["Acme Console", current()]} /></div>
          <div class="ml-auto flex min-w-0 items-center gap-2">
            <div class="hidden w-48 md:block"><TextField placeholder="搜索..." aria-label="全局搜索" /></div>
            <Popover.Root>
              <Popover.Trigger as={Button} variant="ghost" size="icon" class="relative" aria-label="通知"><Icon name="bell" size={18} /><Badge class="absolute -right-1 -top-1 px-1">2</Badge></Popover.Trigger>
              <Popover.Portal><Popover.Content class="z-50 w-80 rounded-lg border border-zinc-200 bg-white p-4 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><p class="mb-3 font-medium">通知</p><div class="grid gap-3"><For each={notifications}>{(item) => <div class="border-b border-zinc-100 pb-3 text-sm last:border-0 dark:border-zinc-800"><p>{item.title}</p><p class="mt-1 text-xs text-zinc-500">{item.time}</p></div>}</For></div></Popover.Content></Popover.Portal>
            </Popover.Root>
            <Button variant="ghost" size="icon" aria-label="切换主题" onClick={toggleTheme}><Icon name={colorMode.colorMode() === "dark" ? "sun" : "moon"} size={18} /></Button>
            <DropdownMenu.Root><DropdownMenu.Trigger as={Button} variant="ghost" class="rounded-full p-1" aria-label="用户菜单"><Avatar name="林晓" /></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content class="z-50 min-w-48 rounded-md border border-zinc-200 bg-white p-1 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><For each={["个人资料", "账户设置", "切换团队", "帮助", "退出登录"]}>{(item) => <DropdownMenu.Item class="cursor-pointer rounded px-3 py-2 text-sm data-[highlighted]:bg-zinc-100 dark:data-[highlighted]:bg-zinc-800">{item}</DropdownMenu.Item>}</For></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>
          </div>
        </header>
        <main class="min-w-0 space-y-6 p-4 sm:p-6">{props.children}</main>
      </div>
      <Drawer open={mobileOpen()} onOpenChange={setMobileOpen} title="Acme Console" description="导航"><div class="grid gap-5">{links()}</div></Drawer>
    </div>
  )
}
