// apps/radix-themes/src/layouts/app-shell.tsx
import { useState, type ReactNode } from "react"
import { Link, useLocation } from "react-router-dom"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import team from "@ui-gallery/spec/mock/team.json"
import {
  Avatar,
  Badge,
  Box,
  Button,
  Card,
  Dialog,
  DropdownMenu,
  Flex,
  IconButton,
  Popover,
  Text,
  TextField,
} from "@radix-ui/themes"
import { Icon } from "@/icons"
import { useTheme } from "@/theme-provider"

function Brand() {
  return (
    <Link to="/" className="rt-brand">
      <Flex align="center" gap="2">
        <Box>
          <Button size="2">A</Button>
        </Box>
        <Text weight="bold">Acme Console</Text>
      </Flex>
    </Link>
  )
}

function Navigation({ onNavigate }: { onNavigate?: () => void }) {
  const location = useLocation()
  return (
    <Flex direction="column" gap="1">
      {nav.map((item) => (
        <Button
          size="3"
          key={item.key}
          asChild
          variant={location.pathname === item.path ? "soft" : "ghost"}
          color={location.pathname === item.path ? "indigo" : undefined}
          onClick={onNavigate}
          style={{
            width: "100%",
            minHeight: "40px",
            boxSizing: "border-box",
            justifyContent: "flex-start",
          }}
        >
          <Link to={item.path}>
            <Icon name={item.icon} />
            <Text>{item.label}</Text>
            {item.badge ? (
              <Badge size="1" variant="soft">
                {item.badge}
              </Badge>
            ) : null}
          </Link>
        </Button>
      ))}
    </Flex>
  )
}

export function AppShell({ children }: { children: ReactNode }) {
  const location = useLocation()
  const { appearance, toggle } = useTheme()
  const [collapsed, setCollapsed] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const current =
    nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  return (
    <Flex className="rt-page" style={{ minHeight: "100vh" }}>
      <Box
        asChild
        display={{ initial: "none", md: "block" }}
        width="260px"
        p="4"
        style={{
          borderRight: "1px solid var(--gray-a5)",
          flexShrink: 0,
          position: "sticky",
          top: 0,
          height: "100vh",
          overflowY: "auto",
          boxSizing: "border-box",
        }}
      >
        <aside>
          <Flex direction="column" gap="6" height="100%">
            <Brand />
            <Box>
              <Text size="1" color="gray">
                工作区
              </Text>
              <Box mt="3">
                <Navigation />
              </Box>
            </Box>
            <Box mt="auto">
              <Card size="1">
                <Flex align="center" gap="2">
                  <Avatar size="2" fallback="林" />
                  <Flex direction="column" gap="1">
                    <Text size="2" weight="medium">
                      {team[0].name}
                    </Text>
                    <Text size="1" color="gray">
                      {team[0].email}
                    </Text>
                  </Flex>
                </Flex>
              </Card>
            </Box>
            <IconButton
              size="3"
              variant="ghost"
              aria-label={collapsed ? "展开侧栏" : "折叠侧栏"}
              onClick={() => setCollapsed((value) => !value)}
              style={{ minHeight: "40px", minWidth: "40px" }}
            >
              <Icon name={collapsed ? "chevron-right" : "chevron-left"} />
            </IconButton>
          </Flex>
        </aside>
      </Box>
      <Flex direction="column" flexGrow="1" minWidth="0">
        <Flex
          asChild
          align="center"
          gap="3"
          p={{ initial: "3", md: "4" }}
          style={{ borderBottom: "1px solid var(--gray-a5)" }}
        >
          <header>
            <Flex
              display={{ initial: "flex", md: "none" }}
              align="center"
              gap="2"
            >
              <Dialog.Root open={mobileOpen} onOpenChange={setMobileOpen}>
                <Dialog.Trigger>
                  <IconButton
                    size="3"
                    variant="ghost"
                    style={{ minHeight: "40px", minWidth: "40px" }}
                  >
                    <Icon name="menu" />
                  </IconButton>
                </Dialog.Trigger>
                <Dialog.Content
                  style={{
                    position: "fixed",
                    inset: "0 auto 0 0",
                    width: "280px",
                    maxHeight: "100vh",
                    borderRadius: 0,
                    transform: "none",
                  }}
                >
                  <Dialog.Title>
                    <Brand />
                  </Dialog.Title>
                  <Box mt="5">
                    <Navigation onNavigate={() => setMobileOpen(false)} />
                  </Box>
                </Dialog.Content>
              </Dialog.Root>
              <Text weight="bold">Acme Console</Text>
            </Flex>
            <Flex
              display={{ initial: "none", md: "flex" }}
              align="center"
              gap="2"
            >
              <Link to="/">Acme Console</Link>
              <Icon name="chevron-right" />
              <Text color="gray">{current}</Text>
            </Flex>
            <Box
              display={{ initial: "none", md: "block" }}
              style={{ marginLeft: "auto" }}
            >
              <TextField.Root
                placeholder="搜索..."
                style={{ maxWidth: "280px" }}
              >
                <TextField.Slot>
                  <Icon name="search" size={16} />
                </TextField.Slot>
              </TextField.Root>
            </Box>
            <Popover.Root>
              <Popover.Trigger>
                <IconButton
                  size="3"
                  variant="ghost"
                  style={{ minHeight: "40px", minWidth: "40px" }}
                >
                  <Icon name="bell" />
                  <Badge size="1" color="red">
                    {notifications.filter((item) => item.unread).length}
                  </Badge>
                </IconButton>
              </Popover.Trigger>
              <Popover.Content width="320px">
                <Flex direction="column" gap="3">
                  {notifications.map((item) => (
                    <Box key={item.title}>
                      <Text size="2" weight={item.unread ? "bold" : "regular"}>
                        {item.title}
                      </Text>
                      <Text size="1" color="gray" as="div">
                        {item.time}
                      </Text>
                    </Box>
                  ))}
                </Flex>
              </Popover.Content>
            </Popover.Root>
            <IconButton
              size="3"
              variant="ghost"
              onClick={toggle}
              style={{ minHeight: "40px", minWidth: "40px" }}
            >
              <Icon name={appearance === "dark" ? "sun" : "moon"} />
            </IconButton>
            <DropdownMenu.Root>
              <DropdownMenu.Trigger>
                <IconButton
                  size="3"
                  variant="ghost"
                  style={{ minHeight: "40px", minWidth: "40px" }}
                >
                  <Avatar size="2" fallback="林" />
                </IconButton>
              </DropdownMenu.Trigger>
              <DropdownMenu.Content>
                <DropdownMenu.Label>林晓</DropdownMenu.Label>
                <DropdownMenu.Item asChild>
                  <Link to="/settings">个人资料</Link>
                </DropdownMenu.Item>
                <DropdownMenu.Item asChild>
                  <Link to="/settings">账户设置</Link>
                </DropdownMenu.Item>
                <DropdownMenu.Item asChild>
                  <Link to="/settings">团队</Link>
                </DropdownMenu.Item>
                <DropdownMenu.Item>帮助</DropdownMenu.Item>
                <DropdownMenu.Item>退出登录</DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Root>
          </header>
        </Flex>
        <Box asChild p={{ initial: "4", md: "6" }} flexGrow="1">
          <main>{children}</main>
        </Box>
      </Flex>
    </Flex>
  )
}

// apps/kobalte/src/layouts/app-shell.tsx
import { createEffect, createSignal, For, Show, type ParentProps } from "solid-js"
import { A, useLocation } from "@solidjs/router"
import { useColorMode } from "@kobalte/core/color-mode"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { Icon } from "@/icons"
import { Avatar } from "@/ui/avatar"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Breadcrumbs } from "@/ui/breadcrumbs"
import { Drawer } from "@/ui/dialog"
import { DropdownMenu } from "@/ui/dropdown-menu"
import { Popover } from "@/ui/popover"
import { TextField } from "@/ui/text-field"
import { Tooltip } from "@/ui/tooltip"

export function AppShell(props: ParentProps) {
  const colorMode = useColorMode()
  const location = useLocation()
  const [collapsed, setCollapsed] = createSignal(false)
  const [mobileOpen, setMobileOpen] = createSignal(false)
  createEffect(() => {
    const dark = colorMode.colorMode() === "dark"
    document.documentElement.classList.toggle("dark", dark)
    document.documentElement.classList.toggle("light", !dark)
  })
  const path = () => { const p = location.pathname.replace(/^\/apps\/kobalte/, "") || "/"; return p.length > 1 ? p.replace(/\/$/, "") : p }
  const current = () => nav.find((item) => item.path === path())?.label ?? "仪表盘"
  const toggleTheme = () => {
    const next = colorMode.colorMode() === "dark" ? "light" : "dark"
    colorMode.toggleColorMode()
    const url = new URL(window.location.href)
    url.searchParams.set("theme", next)
    window.history.replaceState({}, "", url)
    document.documentElement.classList.toggle("dark", next === "dark")
  }
  const links = () => (
    <nav class="grid gap-1">
      <For each={nav}>
        {(item) => (
          <Tooltip.Root openDelay={300}>
            <Tooltip.Trigger as="div">
            <A href={item.path} onClick={() => setMobileOpen(false)} class={`flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors ${path() === item.path ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900" : "text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800"}`}>
                <Icon name={item.icon} size={18} />
                <Show when={!collapsed()}>
                  <span class="min-w-0 flex-1 truncate">{item.label}</span>
                  {item.badge ? <Badge variant="secondary">{item.badge}</Badge> : null}
                </Show>
              </A>
            </Tooltip.Trigger>
            <Show when={collapsed()}><Tooltip.Portal><Tooltip.Content class="z-50 rounded bg-zinc-900 px-2 py-1 text-xs text-white">{item.label}</Tooltip.Content></Tooltip.Portal></Show>
          </Tooltip.Root>
        )}
      </For>
    </nav>
  )
  return (
    <div class="min-h-screen bg-zinc-50 dark:bg-zinc-950">
      <aside class={`fixed inset-y-0 left-0 z-30 hidden border-r border-zinc-200 bg-white transition-[width] lg:flex lg:flex-col dark:border-zinc-800 dark:bg-zinc-900 ${collapsed() ? "w-16" : "w-64"}`}>
        <div class="flex h-16 items-center gap-3 border-b border-zinc-200 px-4 dark:border-zinc-800"><span class="grid size-8 shrink-0 place-items-center rounded-lg bg-zinc-900 font-semibold text-white dark:bg-zinc-100 dark:text-zinc-900">A</span><Show when={!collapsed()}><span class="font-semibold">Acme Console</span></Show></div>
        <div class="flex-1 space-y-6 overflow-y-auto p-3"><Show when={!collapsed()}><p class="px-3 text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">工作区</p></Show>{links()}</div>
        <div class="space-y-2 border-t border-zinc-200 p-3 dark:border-zinc-800"><A href="/settings" class="flex items-center gap-3 rounded-md p-2 text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800"><Avatar name="林晓" /><Show when={!collapsed()}><span class="min-w-0 truncate">林晓</span></Show></A><Button variant="ghost" size="icon" class="w-full" aria-label="折叠侧边栏" onClick={() => setCollapsed((value) => !value)}><Icon name={collapsed() ? "chevron-right" : "chevron-left"} size={16} /></Button></div>
      </aside>
      <div class="lg:pl-64" classList={{ "lg:pl-16": collapsed() }}>
        <header class="sticky top-0 z-20 flex h-16 min-w-0 items-center gap-3 border-b border-zinc-200 bg-white/90 px-4 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/90 sm:px-6">
          <Button variant="ghost" size="icon" class="lg:hidden" aria-label="打开导航" onClick={() => setMobileOpen(true)}><Icon name="menu" size={20} /></Button>
          <div class="hidden min-w-0 sm:flex"><Breadcrumbs items={["Acme Console", current()]} /></div>
          <div class="ml-auto flex min-w-0 items-center gap-2">
            <div class="hidden w-48 md:block"><TextField placeholder="搜索..." aria-label="全局搜索" /></div>
            <Popover.Root>
              <Popover.Trigger as={Button} variant="ghost" size="icon" class="relative" aria-label="通知"><Icon name="bell" size={18} /><Badge class="absolute -right-1 -top-1 px-1">2</Badge></Popover.Trigger>
              <Popover.Portal><Popover.Content class="z-50 w-80 rounded-lg border border-zinc-200 bg-white p-4 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><p class="mb-3 font-medium">通知</p><div class="grid gap-3"><For each={notifications}>{(item) => <div class="border-b border-zinc-100 pb-3 text-sm last:border-0 dark:border-zinc-800"><p>{item.title}</p><p class="mt-1 text-xs text-zinc-500 dark:text-zinc-400">{item.time}</p></div>}</For></div></Popover.Content></Popover.Portal>
            </Popover.Root>
            <Button variant="ghost" size="icon" aria-label="切换主题" onClick={toggleTheme}><Icon name={colorMode.colorMode() === "dark" ? "sun" : "moon"} size={18} /></Button>
            <DropdownMenu.Root><DropdownMenu.Trigger as={Button} variant="ghost" class="rounded-full p-1" aria-label="用户菜单"><Avatar name="林晓" /></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content class="z-50 min-w-48 rounded-md border border-zinc-200 bg-white p-1 shadow-lg dark:border-zinc-700 dark:bg-zinc-900"><For each={["个人资料", "账户设置", "切换团队", "帮助", "退出登录"]}>{(item) => <DropdownMenu.Item class="cursor-pointer rounded px-3 py-2 text-sm data-[highlighted]:bg-zinc-100 dark:data-[highlighted]:bg-zinc-800">{item}</DropdownMenu.Item>}</For></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>
          </div>
        </header>
        <main class="min-w-0 space-y-6 p-4 sm:p-6">{props.children}</main>
      </div>
      <Drawer open={mobileOpen()} onOpenChange={setMobileOpen} title="Acme Console" description="导航"><div class="grid gap-5">{links()}</div></Drawer>
    </div>
  )
}
