// apps/kobalte/src/pages/chat.tsx
/* eslint-disable */
import { createSignal, For, Show, onMount } from "solid-js"
import { useLocation } from "@solidjs/router"
import { marked } from "marked"
import { Collapsible } from "@kobalte/core/collapsible"
import chat from "@ui-gallery/spec/mock/chat.json"
import { Icon } from "@/icons"
import { Avatar } from "@/ui/avatar"
import { Badge } from "@/ui/badge"
import { Button } from "@/ui/button"
import { Drawer } from "@/ui/dialog"
import { Select } from "@/ui/select"
import { TextArea, TextField } from "@/ui/text-field"
import { toast } from "@/ui/toast"

type ToolCall = { name: string; args: Record<string, string>; status: string }
function getTool(item: unknown): ToolCall | undefined {
  return (item as { tool?: ToolCall }).tool
}

function MarkdownMessage(props: { content: string }) {
  let container!: HTMLDivElement
  onMount(() => {
    container?.querySelectorAll("pre").forEach((pre) => {
      if (pre.querySelector("button")) return
      const button = document.createElement("button")
      button.type = "button"
      button.textContent = "复制"
      button.className = "absolute right-2 top-2 inline-flex min-h-10 min-w-10 items-center justify-center rounded-md border border-zinc-300 bg-white/90 px-3 text-xs text-zinc-700 dark:border-zinc-600 dark:bg-zinc-900/90 dark:text-zinc-200"
      pre.classList.add("relative", "overflow-x-auto", "whitespace-pre-wrap", "break-words", "rounded-lg", "bg-zinc-900", "p-4", "pt-14", "text-zinc-100")
      button.addEventListener("click", async () => {
        await navigator.clipboard?.writeText(pre.textContent ?? "")
        toast.success("代码已复制")
      })
      pre.append(button)
    })
  })
  return <div ref={container} class="prose prose-sm max-w-none dark:prose-invert [&_a]:text-blue-600 [&_code]:rounded [&_code]:bg-zinc-200 [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-xs dark:[&_code]:bg-zinc-700 [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_table]:w-full [&_table]:border [&_table]:border-zinc-300 dark:[&_table]:border-zinc-700 [&_th]:border [&_th]:border-zinc-300 [&_th]:bg-zinc-100 [&_th]:p-2 dark:[&_th]:border-zinc-700 dark:[&_th]:bg-zinc-800 [&_td]:border [&_td]:border-zinc-300 [&_td]:p-2 dark:[&_td]:border-zinc-700" innerHTML={marked.parse(props.content) as string} />
}

export function ChatPage() {
  const location = useLocation()
  const [drawer, setDrawer] = createSignal(false)
  const [message, setMessage] = createSignal("")
  const [messages, setMessages] = createSignal(chat.messages)
  const [fresh, setFresh] = createSignal(false)
  const empty = () => fresh() || new URLSearchParams(location.search).get("state") === "empty"
  const suggestions = () => chat.suggestions?.slice(0, 4) ?? chat.conversations.slice(0, 4).map((item) => item.title)
  const grow = (event: InputEvent & { currentTarget: HTMLInputElement }) => {
    const target = event.currentTarget as unknown as HTMLTextAreaElement
    target.style.height = "auto"
    const lineHeight = Number.parseFloat(getComputedStyle(target).lineHeight) || 24
    target.style.height = `${Math.min(target.scrollHeight, lineHeight * 6)}px`
    setMessage(target.value)
  }
  const send = () => {
    if (!message().trim()) return
    setMessages((items) => [...items, { role: "user", content: message(), time: "刚刚" } as never])
    setFresh(false)
    setMessage("")
  }
  const sendOnKey = (event: KeyboardEvent) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault()
      send()
    }
  }
  const selectConversation = () => {
    setFresh(false)
    setMessages(chat.messages)
    setDrawer(false)
  }
  const newConversation = () => {
    setFresh(true)
    setMessages([])
    setDrawer(false)
    toast.success("已新建对话")
  }
  return <div class="flex min-h-[calc(100vh-8rem)] min-w-0 overflow-hidden rounded-xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
    <aside class="hidden w-72 shrink-0 border-r border-zinc-200 p-4 md:block dark:border-zinc-800"><ConversationList onNew={newConversation} onSelect={selectConversation} /></aside>
    <Drawer open={drawer()} onOpenChange={setDrawer} title="对话" description="选择一个对话"><ConversationList onNew={newConversation} onSelect={selectConversation} /></Drawer>
    <section class="flex min-w-0 flex-1 flex-col">
      <div class="flex h-14 items-center gap-2 border-b border-zinc-200 px-4 dark:border-zinc-800"><Button variant="ghost" size="icon" class="md:hidden" aria-label="打开对话列表" onClick={() => setDrawer(true)}><Icon name="panel-left" /></Button><span class="font-medium">AI 助手</span></div>
      <Show when={!empty()} fallback={<div class="flex flex-1 flex-col items-center justify-center p-6 text-center"><div class="grid size-12 place-items-center rounded-full bg-blue-100 text-blue-600 dark:bg-blue-950"><Icon name="sparkles" /></div><h1 class="mt-4 text-2xl font-semibold">你好，有什么可以帮你？</h1><div class="mt-6 grid w-full max-w-2xl gap-2 sm:grid-cols-2"><For each={suggestions()}>{(item) => <button class="rounded-lg border p-3 text-left text-sm hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800" onClick={() => setMessage(item)}>{item}</button>}</For></div></div>}>
        <div class="flex-1 space-y-5 overflow-y-auto p-4 sm:p-6"><For each={messages()}>{(item) => <div class={`flex gap-3 ${item.role === "user" ? "flex-row-reverse" : ""}`}><Avatar name={item.role === "user" ? "我" : "AI"} /><div class={`min-w-0 max-w-[85%] rounded-xl p-3 text-sm ${item.role === "user" ? "bg-blue-600 text-white" : "bg-zinc-100 dark:bg-zinc-800"}`}><Show when={item.role === "assistant"} fallback={<p class="whitespace-pre-wrap">{item.content}</p>}><MarkdownMessage content={item.content} /></Show><Show when={getTool(item)}><Collapsible class="mt-3 rounded border border-zinc-300 dark:border-zinc-700"><Collapsible.Trigger class="flex min-h-10 w-full items-center justify-between p-2 text-left text-xs"><span>工具调用 · {getTool(item)?.name}</span><span>⌄</span></Collapsible.Trigger><Collapsible.Content class="border-t p-2 text-xs"><pre class="overflow-auto">{JSON.stringify(getTool(item), null, 2)}</pre></Collapsible.Content></Collapsible></Show><Show when={item.sources}><div class="mt-3 flex flex-wrap gap-1"><For each={item.sources}>{(source) => <Badge variant="secondary">{String(source)}</Badge>}</For></div></Show>{("time" in item && item.time) ? <span class="mt-2 block text-xs text-zinc-500 dark:text-zinc-400">{String(item.time)}</span> : null}<Show when={item.streaming}><span class="ml-1 inline-block h-4 w-1 animate-pulse bg-current" /></Show></div></div>}</For></div>
      </Show>
      <div class="border-t border-zinc-200 p-3 dark:border-zinc-800"><div class="flex items-end gap-2"><Button variant="ghost" size="icon" aria-label="添加附件"><Icon name="paperclip" /></Button><TextArea class="min-w-0 flex-1" rows={2} placeholder="输入消息..." value={message()} onInput={grow} onKeyDown={sendOnKey} /><Button size="icon" aria-label="发送" onClick={send}><Icon name="send" /></Button></div><div class="mt-2 flex flex-wrap items-center gap-2 text-xs text-zinc-500 dark:text-zinc-400"><div class="w-44"><Select class="w-auto min-w-40" options={chat.models.map((model) => ({ value: model, label: model }))} value={chat.models[0]} /></div><span class="hidden sm:inline">Enter 发送 · Shift+Enter 换行</span><span class="ml-auto">{message().length} / 4000</span></div><div class="mt-2 flex gap-2 overflow-x-auto"><For each={suggestions()}>{(item) => <button type="button" class="min-h-10 whitespace-nowrap rounded-full border px-3 text-xs dark:border-zinc-700" onClick={() => setMessage(item)}>{item}</button>}</For></div></div>
    </section>
  </div>
}

function ConversationList(props: { onNew: () => void; onSelect: () => void }) {
  return <div class="grid min-w-0 gap-4"><div class="flex items-center justify-between"><h2 class="font-semibold">对话</h2><Button size="sm" onClick={props.onNew}><Icon name="plus" size={14} />新建</Button></div><TextField placeholder="搜索对话" aria-label="搜索对话" /><div><p class="mb-2 text-xs font-medium text-zinc-500 dark:text-zinc-400">今天</p><div class="grid gap-1"><For each={chat.conversations}>{(conversation) => <button type="button" class="flex min-w-0 min-h-10 items-center gap-2 rounded-md p-2 text-left text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800" onClick={props.onSelect}><Icon name="message-square" size={16} /><span class="min-w-0 flex-1 truncate">{conversation.title}</span><span class="text-xs text-zinc-500 dark:text-zinc-400">{conversation.time}</span><Show when={conversation.unread}><Badge>{conversation.unread}</Badge></Show></button>}</For></div></div></div>
}

// apps/heroui/src/pages/chat.tsx
import { useMemo, useState, type ComponentProps, type ReactNode } from "react"
import Markdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Avatar, Button, Card, Chip, Drawer, Header, ListBox, ScrollShadow, SearchField, Select, Skeleton, Spinner, TextArea, TextField, toast, Tooltip } from "@heroui/react"
import { Icon } from "@/components/icon"
import chat from "@ui-gallery/spec/mock/chat.json"

type Message = (typeof chat.messages)[number] & { sources?: string[]; tool?: { name: string; args: Record<string, string>; status: string }; streaming?: boolean }
type Conversation = (typeof chat.conversations)[number]
const messages = chat.messages as Message[]
const DRAFT_MAX = 2000

function textOf(node: ReactNode): string {
  if (typeof node === "string" || typeof node === "number") return String(node)
  if (Array.isArray(node)) return node.map(textOf).join("")
  if (node && typeof node === "object" && "props" in node) return textOf((node.props as { children?: ReactNode }).children)
  return ""
}

function CodeBlock({ children, ...props }: ComponentProps<"pre">) {
  const copy = () => {
    void navigator.clipboard?.writeText(textOf(children)).then(() => toast.success("代码已复制"))
  }
  return (
    <div className="group relative min-w-0">
      <pre {...props}>{children}</pre>
      <Button isIconOnly size="md" variant="secondary" aria-label="复制代码" className="absolute right-2 top-2 min-h-10 min-w-10" onPress={copy}>
        <Icon name="copy" size={14} />
      </Button>
    </div>
  )
}

function ConversationList({ items, active, onSelect }: { items: Conversation[]; active: string; onSelect: (id: string) => void }) {
  const groups = useMemo(() => {
    const today = items.filter((c) => c.time === "刚刚" || c.time.includes("分钟") || c.time.includes("小时"))
    const earlier = items.filter((c) => !today.includes(c))
    return [{ label: "今天", items: today }, { label: "更早", items: earlier }].filter((g) => g.items.length)
  }, [items])
  if (!items.length) return <p className="px-2 py-6 text-center text-sm text-muted">没有匹配的对话</p>
  return (
    <ListBox aria-label="对话列表" selectionMode="single" selectedKeys={[active]} onSelectionChange={(keys) => { const key = [...keys][0]; if (key) onSelect(String(key)) }}>
      {groups.map((group) => (
        <ListBox.Section key={group.label}>
          <Header className="px-2 pb-1 pt-3 text-xs font-medium text-muted">{group.label}</Header>
          {group.items.map((c) => (
            <ListBox.Item key={c.id} id={c.id} textValue={c.title}>
              <div className="flex w-full items-center justify-between gap-2">
                <div className="min-w-0"><p className="truncate text-sm">{c.title}</p><p className="text-xs text-muted">{c.time}</p></div>
                {c.unread ? <Chip size="sm" color="accent">{c.unread}</Chip> : null}
              </div>
            </ListBox.Item>
          ))}
        </ListBox.Section>
      ))}
    </ListBox>
  )
}

export function ChatPage() {
  const [active, setActive] = useState(chat.conversations[0].id)
  const [draft, setDraft] = useState("")
  const [model, setModel] = useState(chat.models[0])
  const [search, setSearch] = useState("")
  const [drawerOpen, setDrawerOpen] = useState(false)
  const current = chat.conversations.find((c) => c.id === active)
  const empty = active !== chat.conversations[0].id
  const filteredConversations = chat.conversations.filter((c) => c.title.toLowerCase().includes(search.trim().toLowerCase()))
  const send = () => { if (draft.trim()) { toast.success("消息已发送"); setDraft("") } }

  const sidebar = (
    <>
      <SearchField aria-label="搜索对话" value={search} onChange={setSearch} className="mb-2">
        <SearchField.Group><SearchField.SearchIcon /><SearchField.Input placeholder="搜索对话..." /><SearchField.ClearButton /></SearchField.Group>
      </SearchField>
      <ConversationList items={filteredConversations} active={active} onSelect={(id) => { setActive(id); setDrawerOpen(false) }} />
    </>
  )

  return (
    <div className="grid h-[calc(100svh-8rem)] min-h-[560px] min-w-0 grid-cols-[minmax(0,1fr)] gap-4 lg:grid-cols-[280px_minmax(0,1fr)]">
      <Card className="hidden min-h-0 lg:flex lg:flex-col">
        <Card.Header className="flex-row items-center justify-between"><Card.Title>对话</Card.Title><Button isIconOnly size="sm" variant="ghost" aria-label="新对话" onPress={() => toast.success("已创建新对话")}><Icon name="plus" size={16} /></Button></Card.Header>
        <Card.Content className="min-h-0 flex-1 overflow-y-auto">{sidebar}</Card.Content>
      </Card>
      <Card className="flex min-h-0 min-w-0 flex-col">
        <Card.Header className="flex-row flex-wrap items-center justify-between gap-2 border-b border-border">
          <div className="flex min-w-0 items-center gap-2">
            <Drawer isOpen={drawerOpen} onOpenChange={setDrawerOpen}>
              <Button isIconOnly variant="ghost" size="md" aria-label="打开对话列表" className="min-h-10 min-w-10 lg:hidden"><Icon name="list" size={18} /></Button>
              <Drawer.Backdrop>
                <Drawer.Content placement="left" className="w-80 max-w-[85vw]">
                  <Drawer.Dialog>
                    <Drawer.CloseTrigger />
                    <Drawer.Header><Drawer.Heading>对话</Drawer.Heading><p className="text-sm text-muted">搜索并切换会话</p></Drawer.Header>
                    <Drawer.Body>{sidebar}</Drawer.Body>
                    <Drawer.Footer><Button fullWidth variant="secondary" onPress={() => { toast.success("已创建新对话"); setDrawerOpen(false) }}><Icon name="plus" size={16} />新对话</Button></Drawer.Footer>
                  </Drawer.Dialog>
                </Drawer.Content>
              </Drawer.Backdrop>
            </Drawer>
            <Card.Title className="truncate text-base">{current?.title}</Card.Title>
          </div>
          <Select aria-label="模型" value={model} onChange={(key) => setModel(String(key))} className="w-36">
            <Select.Trigger><Select.Value /><Select.Indicator /></Select.Trigger>
            <Select.Popover><ListBox>{chat.models.map((m) => <ListBox.Item key={m} id={m} textValue={m}>{m}<ListBox.ItemIndicator /></ListBox.Item>)}</ListBox></Select.Popover>
          </Select>
        </Card.Header>
        <ScrollShadow className="min-h-0 min-w-0 flex-1 px-4 pb-24 pt-4">
          {empty ? (
            <div className="flex h-full flex-col items-center justify-center gap-3 text-center">
              <div className="grid size-12 place-items-center rounded-full bg-accent-soft text-accent-soft-foreground"><Icon name="bot" /></div>
              <p className="font-medium">开始新的对话</p>
              <p className="text-sm text-muted">试试下面的建议，或直接提问。</p>
              <div className="grid w-full max-w-md gap-2 sm:grid-cols-2">{chat.suggestions.map((s) => <Button key={s} size="sm" variant="secondary" className="justify-start" onPress={() => setDraft(s)}><Icon name="sparkles" size={14} />{s}</Button>)}</div>
              <div className="mt-6 w-full max-w-md space-y-2"><Skeleton className="h-4 w-full rounded-lg" /><Skeleton className="h-4 w-3/4 rounded-lg" /></div>
            </div>
          ) : (
            <div className="min-w-0 space-y-6">
              {messages.map((message, index) => (
                <div key={index} className={`flex min-w-0 gap-3 ${message.role === "user" ? "justify-end" : ""}`}>
                  {message.role === "assistant" ? <Avatar size="sm" className="shrink-0"><Avatar.Fallback>AI</Avatar.Fallback></Avatar> : null}
                  <div className={`min-w-0 max-w-[85%] space-y-2 ${message.role === "user" ? "order-first" : ""}`}>
                    {message.tool ? (
                      <div className="flex min-w-0 items-center gap-2 rounded-lg border border-border bg-surface-secondary px-3 py-2 text-xs">
                        <Icon name="terminal" size={14} className="shrink-0" /><code className="min-w-0 break-all">{message.tool.name}({JSON.stringify(message.tool.args)})</code>
                        <Chip size="sm" color="success" className="ml-auto shrink-0">{message.tool.status}</Chip>
                      </div>
                    ) : null}
                    <div className={`prose-chat min-w-0 max-w-full overflow-hidden rounded-2xl px-4 py-3 text-sm ${message.role === "user" ? "bg-accent text-accent-foreground" : "bg-surface-secondary"}`}>
                      <Markdown remarkPlugins={[remarkGfm]} components={{ pre: CodeBlock }}>{message.content}</Markdown>
                      {message.streaming ? <span className="mt-2 inline-flex items-center gap-2 text-xs text-muted"><Spinner size="sm" />生成中…</span> : null}
                    </div>
                    {message.sources ? <div className="flex flex-wrap gap-1">{message.sources.map((s) => <Tooltip key={s}><Chip size="sm" variant="secondary">{s}</Chip><Tooltip.Content>数据来源</Tooltip.Content></Tooltip>)}</div> : null}
                  </div>
                  {message.role === "user" ? <Avatar size="sm" className="shrink-0"><Avatar.Fallback>林</Avatar.Fallback></Avatar> : null}
                </div>
              ))}
            </div>
          )}
        </ScrollShadow>
        <Card.Footer className="flex-col items-stretch gap-3 border-t border-border">
          <div className="flex flex-wrap gap-2">{chat.suggestions.slice(0, 4).map((s) => <Button key={s} size="sm" variant="secondary" onPress={() => setDraft(s)}>{s}</Button>)}</div>
          <div className="flex items-end gap-2">
            <Tooltip>
              <Button isIconOnly variant="ghost" aria-label="添加附件" onPress={() => toast.success("附件选择器已打开")}><Icon name="paperclip" size={18} /></Button>
              <Tooltip.Content>添加附件</Tooltip.Content>
            </Tooltip>
            <TextField aria-label="消息" value={draft} onChange={setDraft} className="min-w-0 flex-1" maxLength={DRAFT_MAX}>
              <TextArea placeholder="输入消息，Enter 发送…" rows={2} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send() } }} />
            </TextField>
            <Button isIconOnly aria-label="发送" isDisabled={!draft.trim()} onPress={send}><Icon name="send" size={16} /></Button>
          </div>
          <div className="flex items-center justify-between text-xs text-muted">
            <span>Enter 发送 · Shift+Enter 换行</span>
            <span aria-live="polite">{draft.length}/{DRAFT_MAX}</span>
          </div>
        </Card.Footer>
      </Card>
    </div>
  )
}
