// apps/shadcn-svelte/src/routes/Login.svelte
<script lang="ts">
  import Icon from "$lib/icons/Icon.svelte"
  import { Button } from "$lib/components/ui/button"
  import * as Card from "$lib/components/ui/card"
  import * as Checkbox from "$lib/components/ui/checkbox"
  import * as InputGroup from "$lib/components/ui/input-group"
  import * as Alert from "$lib/components/ui/alert"
  import * as Separator from "$lib/components/ui/separator"
  import Link from "$lib/Link.svelte"
  let email = "",
    password = "",
    remember = true,
    showPassword = false,
    loading = false,
    submitted = false,
    emailError = "",
    passwordError = ""
  const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  const initialError = new URLSearchParams(window.location.search).get("state") === "error"
  if (initialError) {
    submitted = true
    emailError = "请输入有效的邮箱地址"
    passwordError = "密码长度至少为 6 位"
  }
  async function submit() {
    emailError = emailPattern.test(email) ? "" : "请输入有效的邮箱地址"
    passwordError = password.length >= 6 ? "" : "密码长度至少为 6 位"
    if (emailError || passwordError) {
      submitted = false
      return
    }
    loading = true
    submitted = false
    await new Promise((resolve) => setTimeout(resolve, 1200))
    loading = false
    submitted = true
  }
</script>

<main class="flex min-h-screen items-center justify-center bg-muted/30 p-4">
  <Card.Root class="w-full max-w-md">
    <Card.Header class="space-y-4 text-center">
      <div
        class="mx-auto flex size-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"
      >
        <Icon name="sparkles" size={24} />
      </div>
      <div>
        <Card.Title class="text-2xl">欢迎回来</Card.Title><Card.Description
          >登录 Acme Console 管理你的工作台</Card.Description
        >
      </div>
    </Card.Header>
    <Card.Content class="space-y-4">
      {#if emailError || passwordError}
        <Alert.Root variant="destructive"
          ><Alert.Title>请修正表单中的错误</Alert.Title><Alert.Description
            >请检查邮箱和密码后重试。</Alert.Description
          ></Alert.Root
        >
      {:else if submitted}
        <Alert.Root variant="destructive"
          ><Alert.Title>登录失败</Alert.Title><Alert.Description
            >邮箱或密码不正确，请检查后重试。</Alert.Description
          ></Alert.Root
        >
      {/if}
      <div class="space-y-2">
        <label for="login-email" class="text-sm font-medium">邮箱</label><InputGroup.Root
          ><InputGroup.Addon><Icon name="mail" size={16} /></InputGroup.Addon><InputGroup.Input
            id="login-email"
            type="email"
            bind:value={email}
            class="h-10"
            aria-invalid={!!emailError}
            placeholder="you@example.com"
          /></InputGroup.Root
        >{#if emailError}<p class="text-sm text-destructive">{emailError}</p>{/if}
      </div>
      <div class="space-y-2">
        <label for="login-password" class="text-sm font-medium">密码</label><InputGroup.Root
          ><InputGroup.Addon><Icon name="lock" size={16} /></InputGroup.Addon><InputGroup.Input
            id="login-password"
            type={showPassword ? "text" : "password"}
            bind:value={password}
            class="h-10"
            aria-invalid={!!passwordError}
            placeholder="请输入密码"
          /><InputGroup.Button
            class="!size-10 !min-w-10 !p-0"
            data-qa="hit"
            aria-label="显示密码"
            onclick={() => (showPassword = !showPassword)}
            >{#if showPassword}<Icon name="eye-off" size={16} />{:else}<Icon
                name="eye"
                size={16}
              />{/if}</InputGroup.Button
          ></InputGroup.Root
        >
        {#if passwordError}<p class="text-sm text-destructive">{passwordError}</p>{/if}
      </div>
      <div class="flex items-center justify-between text-sm">
        <label class="flex items-center gap-2"
          ><Checkbox.Root bind:checked={remember} />记住我</label
        ><Button variant="link" class="h-10 px-2" href="#forgot" data-qa="hit">忘记密码？</Button>
      </div>
      <Button size="lg" class="h-10 w-full" disabled={loading} onclick={submit}
        >{#if loading}<Icon
            name="loader"
            size={16}
            class="mr-2 animate-spin"
          />登录中...{:else}登录{/if}</Button
      >
      <div class="flex items-center gap-3">
        <Separator.Root class="flex-1" /><span class="text-xs text-muted-foreground">或</span
        ><Separator.Root class="flex-1" />
      </div>
      <div class="grid grid-cols-3 gap-2">
        <Button variant="outline" class="h-10">Google</Button><Button variant="outline" class="h-10"
          ><Icon name="git-branch" size={16} class="mr-1" />GitHub</Button
        ><Button variant="outline" class="h-10">微信</Button>
      </div>
    </Card.Content>
    <Card.Footer class="justify-center text-sm text-muted-foreground"
      >还没有账号？ <Link
        to="/form"
        class="ml-1 inline-flex h-10 items-center px-2 text-primary hover:underline"
        data-qa="hit">立即注册</Link
      ></Card.Footer
    >
  </Card.Root>
</main>

// apps/heroui/src/pages/login.tsx
import { useState, type FormEvent } from "react"
import { useNavigate } from "react-router-dom"
import { Alert, Button, Card, Checkbox, Description, FieldError, Form, InputGroup, Label, Link, TextField } from "@heroui/react"
import { Icon } from "@/components/icon"
import { SectionDivider } from "./shared"

export function LoginPage() {
  const navigate = useNavigate()
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [emailError, setEmailError] = useState<string | null>(null)
  const [passwordError, setPasswordError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const nextEmailError = String(data.get("email")).includes("@") ? null : "请输入有效的邮箱地址"
    const nextPasswordError = String(data.get("password")).length < 6 ? "密码至少 6 位" : null
    setEmailError(nextEmailError)
    setPasswordError(nextPasswordError)
    if (nextEmailError || nextPasswordError) { setError(nextEmailError ?? nextPasswordError); return }
    setError(null); setLoading(true)
    setTimeout(() => navigate("/"), 600)
  }

  return (
    <div className="grid min-h-svh bg-background text-foreground lg:grid-cols-2">
      <div className="hidden flex-col justify-between bg-surface-secondary p-10 lg:flex">
        <div className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-accent text-accent-foreground">A</span>Acme Console</div>
        <blockquote className="space-y-2"><p className="text-lg">“把团队的工作放进一个控制台。”</p><footer className="text-sm text-muted">Acme Console · HeroUI 参考实现</footer></blockquote>
      </div>
      <div className="flex items-center justify-center p-6">
        <Card className="w-full max-w-md shadow-lg lg:p-2">
          <Card.Header><Card.Title className="text-3xl font-semibold tracking-tight">欢迎回来</Card.Title><Card.Description>输入邮箱与密码进入控制台。</Card.Description></Card.Header>
          <Card.Content>
            <Form onSubmit={submit} className="space-y-4">
              {error ? <Alert status="danger"><Alert.Indicator /><Alert.Content><Alert.Title>登录失败</Alert.Title><Alert.Description>{error}</Alert.Description></Alert.Content></Alert> : null}
              <TextField name="email" type="email" isRequired defaultValue="m0@acme.dev" isInvalid={!!emailError}>
                <Label>邮箱</Label>
                <InputGroup><InputGroup.Prefix><Icon name="mail" size={16} className="text-muted" /></InputGroup.Prefix><InputGroup.Input placeholder="you@acme.dev" /></InputGroup>
                {emailError ? <FieldError>{emailError}</FieldError> : null}
              </TextField>
              <TextField name="password" type={showPassword ? "text" : "password"} isRequired isInvalid={!!passwordError}>
                <div className="flex items-center justify-between"><Label>密码</Label><Link href="#" className="inline-flex min-h-10 items-center px-1 text-xs">忘记密码？</Link></div>
                <InputGroup>
                  <InputGroup.Input placeholder="••••••" />
                  <InputGroup.Suffix className="pr-0"><Button isIconOnly variant="ghost" size="sm" className="size-10 min-h-10 min-w-10 text-muted" aria-label={showPassword ? "隐藏密码" : "显示密码"} aria-pressed={showPassword} onPress={() => setShowPassword((v) => !v)}><Icon name={showPassword ? "eye-off" : "eye"} size={18} /></Button></InputGroup.Suffix>
                </InputGroup>
                <Description>至少 6 位字符</Description>
                {passwordError ? <FieldError>{passwordError}</FieldError> : null}
              </TextField>
              <Checkbox defaultSelected name="remember" variant="secondary"><Checkbox.Content><Checkbox.Control><Checkbox.Indicator /></Checkbox.Control>记住我</Checkbox.Content></Checkbox>
              <Button type="submit" fullWidth isPending={loading}>登录</Button>
              <SectionDivider label="或使用" />
              <div className="grid grid-cols-3 gap-2">
                <Button variant="secondary" onPress={() => navigate("/")}><Icon name="google" size={16} />Google</Button>
                <Button variant="secondary" onPress={() => navigate("/")}><Icon name="github" size={16} />GitHub</Button>
                <Button variant="secondary" onPress={() => navigate("/")}><Icon name="wechat" size={16} />微信</Button>
              </div>
            </Form>
          </Card.Content>
          <Card.Footer className="justify-center text-sm text-muted">还没有账号？<Link href="#" className="ml-1">申请试用</Link></Card.Footer>
        </Card>
      </div>
    </div>
  )
}
