// apps/shadcn-svelte/src/lib/components/ui/checkbox/checkbox.svelte
<script lang="ts">
  import { Checkbox as CheckboxPrimitive } from "bits-ui"
  import CheckIcon from "@lucide/svelte/icons/check"
  import MinusIcon from "@lucide/svelte/icons/minus"
  import { cn, type WithoutChildrenOrChild } from "$lib/utils.js"

  let {
    ref = $bindable(null),
    checked = $bindable(false),
    indeterminate = $bindable(false),
    class: className,
    ...restProps
  }: WithoutChildrenOrChild<CheckboxPrimitive.RootProps> = $props()
</script>

<CheckboxPrimitive.Root
  bind:ref
  data-slot="checkbox"
  class={cn(
    "peer relative flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input transition-colors outline-none group-has-disabled/field:opacity-50 group-has-[:focus-visible]/field-label:ring-0 after:absolute after:-inset-x-3 after:-inset-y-2 focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 aria-invalid:aria-checked:border-primary data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground group-has-[:focus-visible]/field-label:data-[state=checked]:border-primary dark:bg-input/30 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 dark:data-[state=checked]:bg-primary",
    className
  )}
  bind:checked
  bind:indeterminate
  {...restProps}
>
  {#snippet children({ checked, indeterminate })}
    <div
      data-slot="checkbox-indicator"
      class="grid place-content-center text-current transition-none [&>svg]:size-3.5"
    >
      {#if checked}
        <CheckIcon />
      {:else if indeterminate}
        <MinusIcon />
      {/if}
    </div>
  {/snippet}
</CheckboxPrimitive.Root>

// apps/reference/src/components/ui/checkbox.tsx
import * as React from "react"
import { cn } from "@/lib/cn"
import { CheckIcon } from "lucide-react"
import { Checkbox as CheckboxPrimitive } from "radix-ui"

/** 复选框：hifi .check .box —— icon.md 方框、radius.xs、勾选转 primary；外层 label 提供 size.hit 热区 */
function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer hit-area grid size-icon-md shrink-0 place-items-center rounded-xs border border-border-strong bg-surface text-on-primary transition-colors duration-(--motion-fast) ease-std hover:not-disabled:border-fg-muted data-[state=checked]:border-primary data-[state=checked]:bg-primary disabled:cursor-not-allowed disabled:border-border disabled:bg-surface-muted disabled:data-[state=checked]:border-fg-disabled disabled:data-[state=checked]:bg-fg-disabled aria-invalid:border-danger",
        className,
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator data-slot="checkbox-indicator" className="grid place-content-center [&_svg]:size-icon-sm">
        <CheckIcon strokeWidth={3} />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
}

/** 带文字的复选项：整行可点，min-h = size.hit */
function CheckboxField({
  id,
  label,
  className,
  ...props
}: React.ComponentProps<typeof Checkbox> & { id: string; label: React.ReactNode }) {
  return (
    <label
      htmlFor={id}
      data-slot="checkbox-field"
      className={cn(
        "inline-flex min-h-hit cursor-pointer items-center gap-2 text-role-body select-none has-disabled:cursor-not-allowed has-disabled:text-fg-muted",
        className,
      )}
    >
      <Checkbox id={id} {...props} />
      <span>{label}</span>
    </label>
  )
}

export { Checkbox, CheckboxField }
