// apps/kobalte/src/ui/table.tsx
import type { ParentProps } from "solid-js"
export function Table(props: ParentProps<{ class?: string }>) { return <div class="max-w-full overflow-x-auto"><table class={`w-full text-sm ${props.class ?? ""}`}>{props.children}</table></div> }
export function TableHeader(props: ParentProps) { return <thead class="border-b border-zinc-200 dark:border-zinc-800">{props.children}</thead> }
export function TableBody(props: ParentProps) { return <tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">{props.children}</tbody> }
export function TableRow(props: ParentProps<{ class?: string; onClick?: () => void }>) { return <tr class={`hover:bg-zinc-50 dark:hover:bg-zinc-800/50 ${props.class ?? ""}`} onClick={() => props.onClick?.()}>{props.children}</tr> }
export function TableHead(props: ParentProps<{ class?: string; onClick?: () => void }>) { return <th class={`whitespace-nowrap px-3 py-3 text-left text-xs font-medium uppercase tracking-wide text-zinc-500 ${props.class ?? ""}`} onClick={() => props.onClick?.()}>{props.children}</th> }
export function TableCell(props: ParentProps<{ class?: string; onClick?: (event: MouseEvent) => void }>) { return <td class={`whitespace-nowrap px-3 py-3 ${props.class ?? ""}`} onClick={props.onClick}>{props.children}</td> }

// apps/reference/src/components/ui/table.tsx
import * as React from "react"
import { cn } from "cn"

/** 表格：hifi table —— th caption/fg-muted、td space.3、hairline 行线、末行无线、首末列去内距、hover 行底 bg */
function TableWrap({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="table-wrap" className={cn("relative -mx-6 overflow-x-auto px-6", className)} {...props} />
}

function Table({ className, ...props }: React.ComponentProps<"table">) {
  return <table data-slot="table" className={cn("w-full border-collapse text-role-body", className)} {...props} />
}

function TableHeader(props: React.ComponentProps<"thead">) {
  return <thead data-slot="table-header" {...props} />
}

function TableBody({ className, ...props }: React.ComponentProps<"tbody">) {
  return <tbody data-slot="table-body" className={cn("[&_tr:last-child_td]:border-b-0", className)} {...props} />
}

function TableRow({ className, ...props }: React.ComponentProps<"tr">) {
  return <tr data-slot="table-row" className={cn("transition-colors duration-(--motion-fast) ease-std hover:[&>td]:bg-bg", className)} {...props} />
}

function TableHead({ className, ...props }: React.ComponentProps<"th">) {
  return (
    <th
      data-slot="table-head"
      className={cn("border-b px-3 py-2 text-left text-role-caption font-medium whitespace-nowrap text-fg-muted first:pl-0 last:pr-0", className)}
      {...props}
    />
  )
}

function TableCell({ className, ...props }: React.ComponentProps<"td">) {
  return <td data-slot="table-cell" className={cn("border-b p-3 align-middle whitespace-nowrap first:pl-0 last:pr-0", className)} {...props} />
}

export { TableWrap, Table, TableHeader, TableBody, TableRow, TableHead, TableCell }
