// apps/mui/src/App.tsx
import { createBrowserRouter, RouterProvider } from "react-router-dom"
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider"
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs"
import { AppTheme } from "./theme"
import { AppShell } from "./layouts/app-shell"
import { LoginPage } from "./pages/login"
import { DashboardPage } from "./pages/dashboard"
import { OrdersPage } from "./pages/orders"
import { FormPage } from "./pages/form"
import { SettingsPage } from "./pages/settings"
import { ComponentsPage } from "./pages/components"
import { LandingPage } from "./pages/landing"
import { ChatPage } from "./pages/chat"

const router = createBrowserRouter(
  [
    { path: "/login", element: <LoginPage /> },
    { path: "/landing", element: <LandingPage /> },
    {
      element: <AppShell />,
      children: [
        { path: "/", element: <DashboardPage /> },
        { path: "/orders", element: <OrdersPage /> },
        { path: "/form", element: <FormPage /> },
        { path: "/settings", element: <SettingsPage /> },
        { path: "/components", element: <ComponentsPage /> },
        { path: "/chat", element: <ChatPage /> },
      ],
    },
  ],
  { basename: "/apps/mui" }
)

export default function App() {
  return (
    <AppTheme>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <RouterProvider router={router} />
      </LocalizationProvider>
    </AppTheme>
  )
}

// apps/skeleton/src/App.svelte
<script lang="ts">
  import { Toast } from "@skeletonlabs/skeleton-svelte"
  import { router } from "./lib/router.svelte"
  import { toaster } from "./lib/toaster"
  import AppShell from "./layouts/AppShell.svelte"
  import LoginPage from "./pages/Login.svelte"
  import DashboardPage from "./pages/Dashboard.svelte"
  import OrdersPage from "./pages/Orders.svelte"
  import FormPage from "./pages/Form.svelte"
  import SettingsPage from "./pages/Settings.svelte"
  import ComponentsPage from "./pages/Components.svelte"
  import LandingPage from "./pages/Landing.svelte"
  import ChatPage from "./pages/Chat.svelte"

  const shellPages = {
    "/": DashboardPage,
    "/orders": OrdersPage,
    "/form": FormPage,
    "/settings": SettingsPage,
    "/components": ComponentsPage,
    "/chat": ChatPage,
  } as const

  const path = $derived(router.path)
  const ShellPage = $derived(path in shellPages ? shellPages[path as keyof typeof shellPages] : null)
</script>

{#if path === "/login"}
  <LoginPage />
{:else if path === "/landing"}
  <LandingPage />
{:else if ShellPage}
  <AppShell>
    <ShellPage />
  </AppShell>
{:else}
  <main class="min-h-screen grid place-items-center p-6">
    <div class="card preset-tonal p-8 text-center space-y-4">
      <h1 class="h3">404</h1>
      <a class="btn preset-filled" href={router.href("/")}>返回仪表盘</a>
    </div>
  </main>
{/if}

<Toast.Group {toaster}>
  {#snippet children(toast)}
    <Toast {toast}>
      <Toast.Message>
        <Toast.Title>{toast.title}</Toast.Title>
        <Toast.Description>{toast.description}</Toast.Description>
      </Toast.Message>
      <Toast.CloseTrigger />
    </Toast>
  {/snippet}
</Toast.Group>
