// apps/blueprint/src/App.tsx
import type { ReactNode } from "react"
import { createBrowserRouter, RouterProvider } from "react-router-dom"
import { AppShell } from "@/layouts/app-shell"
import { ChatPage } from "@/pages/chat"
import { ComponentsPage } from "@/pages/components"
import { DashboardPage } from "@/pages/dashboard"
import { FormPage } from "@/pages/form"
import { LandingPage } from "@/pages/landing"
import { LoginPage } from "@/pages/login"
import { OrdersPage } from "@/pages/orders"
import { SettingsPage } from "@/pages/settings"

const shell = (element: ReactNode) => <AppShell>{element}</AppShell>
const router = createBrowserRouter(
  [
    { path: "/login", element: <LoginPage /> },
    { path: "/", element: shell(<DashboardPage />) },
    { path: "/orders", element: shell(<OrdersPage />) },
    { path: "/form", element: shell(<FormPage />) },
    { path: "/settings", element: shell(<SettingsPage />) },
    { path: "/components", element: shell(<ComponentsPage />) },
    { path: "/landing", element: <LandingPage /> },
    { path: "/chat", element: shell(<ChatPage />) },
  ],
  { basename: "/apps/blueprint" },
)

export default function App() {
  return <RouterProvider router={router} />
}

// apps/skeleton/src/App.svelte
<script lang="ts">
  import { Toast } from "@skeletonlabs/skeleton-svelte"
  import { router } from "./lib/router.svelte"
  import { toaster } from "./lib/toaster"
  import AppShell from "./layouts/AppShell.svelte"
  import LoginPage from "./pages/Login.svelte"
  import DashboardPage from "./pages/Dashboard.svelte"
  import OrdersPage from "./pages/Orders.svelte"
  import FormPage from "./pages/Form.svelte"
  import SettingsPage from "./pages/Settings.svelte"
  import ComponentsPage from "./pages/Components.svelte"
  import LandingPage from "./pages/Landing.svelte"
  import ChatPage from "./pages/Chat.svelte"

  const shellPages = {
    "/": DashboardPage,
    "/orders": OrdersPage,
    "/form": FormPage,
    "/settings": SettingsPage,
    "/components": ComponentsPage,
    "/chat": ChatPage,
  } as const

  const path = $derived(router.path)
  const ShellPage = $derived(path in shellPages ? shellPages[path as keyof typeof shellPages] : null)
</script>

{#if path === "/login"}
  <LoginPage />
{:else if path === "/landing"}
  <LandingPage />
{:else if ShellPage}
  <AppShell>
    <ShellPage />
  </AppShell>
{:else}
  <main class="min-h-screen grid place-items-center p-6">
    <div class="card preset-tonal p-8 text-center space-y-4">
      <h1 class="h3">404</h1>
      <a class="btn preset-filled" href={router.href("/")}>返回仪表盘</a>
    </div>
  </main>
{/if}

<Toast.Group {toaster}>
  {#snippet children(toast)}
    <Toast {toast}>
      <Toast.Message>
        <Toast.Title>{toast.title}</Toast.Title>
        <Toast.Description>{toast.description}</Toast.Description>
      </Toast.Message>
      <Toast.CloseTrigger />
    </Toast>
  {/snippet}
</Toast.Group>
