// apps/kobalte/src/pages/login.tsx
import { createSignal } from "solid-js"
import { A } from "@solidjs/router"
import { Alert } from "@/ui/alert"
import { Button } from "@/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/ui/card"
import { Checkbox } from "@/ui/checkbox"
import { SectionDivider } from "./shared"
import { TextField } from "@/ui/text-field"
import { Icon } from "@/icons"

export function LoginPage() {
  const [email, setEmail] = createSignal("")
  const [password, setPassword] = createSignal("")
  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal("")
  const [submitted, setSubmitted] = createSignal(false)
  const validEmail = () => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email())
  const submit = (event: SubmitEvent) => {
    event.preventDefault()
    setSubmitted(true)
    if (!validEmail() || !password()) return
    setLoading(true)
    setError("")
    window.setTimeout(() => { setLoading(false); setError("邮箱或密码不正确") }, 1200)
  }
 return <div class="grid min-h-screen place-items-center bg-zinc-50 p-4 dark:bg-zinc-950"><Card class="w-full max-w-md"><CardHeader class="space-y-4"><A href="/" class="flex items-center gap-2 font-semibold"><span class="grid size-8 place-items-center rounded-lg bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900">A</span>Acme Console</A><div><CardTitle class="text-2xl">欢迎回来</CardTitle><CardDescription>登录 Acme Console，继续你的工作。</CardDescription></div></CardHeader><CardContent class="space-y-6">{error() ? <Alert level="error"><div class="flex gap-2"><Icon name="alert-circle" size={18} /><span>{error()}</span></div></Alert> : null}<form class="space-y-5" noValidate onSubmit={submit}><TextField label="邮箱" type="email" placeholder="you@example.com" value={email()} required error={submitted() && !validEmail() ? "请输入有效的邮箱地址" : undefined} onInput={(event) => setEmail(event.currentTarget.value)} prefix={<Icon name="mail" size={16} />} /><TextField label="密码" type="password" placeholder="请输入密码" value={password()} required error={submitted() && !password() ? "请输入密码" : undefined} onInput={(event) => setPassword(event.currentTarget.value)} prefix={<Icon name="lock" size={16} />} /><div class="flex items-center justify-between gap-4"><Checkbox label="记住我" /><A href="#forgot" class="text-sm text-blue-600 hover:underline dark:text-blue-400">忘记密码？</A></div><Button type="submit" class="w-full" loading={loading()}>登录</Button></form><SectionDivider label="或" /><div class="grid gap-2 sm:grid-cols-3"><Button variant="outline"><Icon name="globe" size={16} />Google</Button><Button variant="outline"><Icon name="github" size={16} />GitHub</Button><Button variant="outline"><Icon name="message-circle" size={16} />微信</Button></div></CardContent><CardFooter class="justify-center text-sm text-zinc-500">还没有账户？ <A href="#register" class="ml-1 text-zinc-900 underline dark:text-zinc-100">立即注册</A></CardFooter></Card></div>
}

// apps/daisyui/src/pages/login.tsx
import { useState } from "react"
import { Link } from "react-router-dom"
import { Icon } from "@ui-gallery/icons-react"

export function LoginPage() {
  const [visible, setVisible] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setSubmitting(true)
    window.setTimeout(() => setSubmitting(false), 1200)
  }
  return (
    <main className="grid min-h-svh place-items-center bg-base-200 p-4">
      <section className="card w-full max-w-md bg-base-100 shadow-xl">
        <div className="card-body gap-5">
          <Link to="/" className="flex items-center gap-2 font-semibold"><span className="grid size-9 place-items-center rounded-lg bg-primary text-primary-content">A</span>Acme Console</Link>
          <div><h1 className="text-2xl font-semibold">欢迎回来</h1><p className="mt-1 text-sm text-base-content/60">登录 Acme Console，继续你的工作。</p></div>
          <div className="alert alert-error"><Icon name="alert-circle" size={18} /><div><h2 className="font-medium">演示错误状态</h2><p className="text-xs">密码错误时会在这里显示验证错误。</p></div></div>
          <form className="space-y-4" onSubmit={submit}>
            <fieldset className="fieldset"><legend className="fieldset-legend">邮箱</legend><label className="input validator w-full"><Icon name="user" size={16} /><input name="email" type="email" placeholder="you@example.com" required /><span className="sr-only">邮箱</span></label><p className="validator-hint">请输入有效的工作邮箱。</p></fieldset>
            <fieldset className="fieldset"><legend className="fieldset-legend">密码</legend><label className="input w-full"><Icon name="lock" size={16} /><input name="password" type={visible ? "text" : "password"} placeholder="••••••••" minLength={8} required /><button type="button" className="btn btn-ghost btn-xs" onClick={() => setVisible((current) => !current)} aria-label="切换密码可见性"><Icon name={visible ? "user" : "lock"} size={15} /></button></label><p className="fieldset-label">至少 8 个字符。</p></fieldset>
            <div className="flex items-center justify-between gap-3 text-sm"><label className="label cursor-pointer gap-2"><input type="checkbox" className="checkbox checkbox-sm" />记住我</label><a className="link link-primary" href="#forgot">忘记密码？</a></div>
            <button className="btn btn-primary btn-block" type="submit" disabled={submitting}>{submitting ? <span className="loading loading-spinner loading-sm" /> : null}登录</button>
          </form>
          <div className="divider">或</div>
          <div className="grid gap-2 sm:grid-cols-3"><button className="btn btn-outline"><Icon name="globe" size={16} />Google</button><button className="btn btn-outline"><Icon name="github" size={16} />GitHub</button><button className="btn btn-outline"><Icon name="message-circle" size={16} />微信</button></div>
          <p className="text-center text-sm text-base-content/60">还没有账户？ <a href="#register" className="link link-primary">立即注册</a></p>
        </div>
      </section>
    </main>
  )
}
