// apps/tdesign-vue-next/src/pages/Form.vue
<script setup lang="ts">
import { reactive, ref, useTemplateRef } from "vue"
import { MessagePlugin, type FormInstanceFunctions, type FormRules, type UploadFile } from "tdesign-vue-next"
import Icon from "@/components/Icon.vue"
import { useIsMobile } from "@/pages/shared"

const isMobile = useIsMobile()
const step = ref(0)
const submitting = ref(false)

const basic = reactive({
  name: "",
  seats: 5,
  email: "",
  countryCode: "+86",
  phone: "",
  description: "",
  plan: "team",
  modules: ["orders", "dashboard"],
  notify: true,
})
const basicRules: FormRules<typeof basic> = {
  name: [{ required: true, message: "请输入项目名称" }, { min: 2, max: 30, message: "2-30 个字符" }],
  seats: [{ required: true, message: "请输入席位数" }, { validator: (v) => Number(v) >= 1 && Number(v) <= 500, message: "范围 1-500" }],
  email: [{ required: true, message: "请输入邮箱" }, { email: true, message: "邮箱格式不正确" }],
  phone: [{ required: true, message: "请输入手机号" }, { pattern: /^\d{6,15}$/, message: "仅数字，6-15 位" }],
  description: [{ max: 200, message: "最多 200 字" }],
  plan: [{ required: true, message: "请选择计划" }],
  modules: [{ validator: (v) => (v as string[]).length > 0, message: "至少选择一个模块" }],
}

const advanced = reactive({
  region: "",
  tags: [] as string[],
  owner: "",
  startDate: "",
  dailyTime: "",
  range: [] as string[],
  sampling: [20, 80],
  rating: 4,
  color: "#0052d9",
  files: [] as UploadFile[],
  labels: ["beta"] as string[],
})
const advancedRules: FormRules<typeof advanced> = {
  region: [{ required: true, message: "请选择部署区域" }],
  tags: [{ validator: (v) => (v as string[]).length > 0, message: "至少选择一个标签" }],
  owner: [{ required: true, message: "请输入负责人" }],
  startDate: [{ required: true, message: "请选择开始日期" }],
  dailyTime: [{ required: true, message: "请选择每日时间" }],
  range: [{ validator: (v) => (v as string[]).length === 2, message: "请选择日期范围" }],
  rating: [{ validator: (v) => Number(v) >= 1, message: "请评分" }],
}

const agreed = ref(false)
const agreedError = ref(false)

const regionOptions = [
  { label: "华东（上海）", value: "cn-east" },
  { label: "华北（北京）", value: "cn-north" },
  { label: "新加坡", value: "ap-sg" },
  { label: "法兰克福", value: "eu-fra" },
]
const tagOptions = ["生产", "预发", "测试", "内部"].map((t) => ({ label: t, value: t }))
const ownerOptions = ["林晓", "王子涵", "Alex Chen", "Maria García"].map((t) => ({ text: t }))
const countryOptions = [
  { label: "+86 中国", value: "+86" },
  { label: "+1 美国", value: "+1" },
  { label: "+44 英国", value: "+44" },
  { label: "+81 日本", value: "+81" },
]

const basicForm = useTemplateRef<FormInstanceFunctions>("basicForm")
const advancedForm = useTemplateRef<FormInstanceFunctions>("advancedForm")

async function next() {
  const form = step.value === 0 ? basicForm.value : advancedForm.value
  const result = await form?.validate()
  if (result === true) step.value += 1
  else MessagePlugin.warning("请先修正表单中的错误")
}
async function submit() {
  if (!agreed.value) {
    agreedError.value = true
    return
  }
  submitting.value = true
  await new Promise((r) => setTimeout(r, 900))
  submitting.value = false
  step.value = 3
  MessagePlugin.success("项目已创建")
}
function reset() {
  basicForm.value?.reset()
  advancedForm.value?.reset()
  agreed.value = false
  step.value = 0
}
</script>

<template>
  <div class="ug-page ug-form-page">
    <div>
      <t-typography-title level="h4" class="ug-title">创建项目</t-typography-title>
      <span class="ug-muted">三步完成一个新的工作区配置。</span>
    </div>

    <t-card :bordered="true">
      <t-steps :current="step" :layout="isMobile ? 'vertical' : 'horizontal'" readonly class="ug-steps">
        <t-step-item title="基本信息" content="名称、联系方式与计划" />
        <t-step-item title="详细配置" content="区域、时间与资源" />
        <t-step-item title="确认提交" content="核对并同意条款" />
      </t-steps>
    </t-card>

    <t-card v-show="step === 0" :bordered="true" title="基本信息" subtitle="带 * 的为必填项">
      <t-form ref="basicForm" :data="basic" :rules="basicRules" label-align="top" :required-mark="true" @submit.prevent>
        <div class="ug-grid-2">
          <t-form-item label="项目名称" name="name" help="用于在控制台中展示">
            <t-input v-model="basic.name" placeholder="例如：增长分析" clearable />
          </t-form-item>
          <t-form-item label="席位数" name="seats">
            <t-input-number v-model="basic.seats" :min="1" :max="500" theme="column" style="width: 100%" />
          </t-form-item>
          <t-form-item label="联系邮箱" name="email">
            <t-input v-model="basic.email" placeholder="name@company.com"><template #prefix-icon><Icon name="mail" /></template></t-input>
          </t-form-item>
          <t-form-item label="联系电话" name="phone">
            <t-input-adornment>
              <template #prepend>
                <t-select v-model="basic.countryCode" :options="countryOptions" borderless class="ug-country-select" />
              </template>
              <t-input v-model="basic.phone" placeholder="手机号" />
            </t-input-adornment>
          </t-form-item>
        </div>
        <t-form-item label="项目描述" name="description" help="最多 200 个字符">
          <t-textarea v-model="basic.description" placeholder="描述项目目标…" :maxlength="200" :autosize="{ minRows: 3, maxRows: 6 }" />
        </t-form-item>
        <t-form-item label="计划" name="plan">
          <t-radio-group v-model="basic.plan" variant="default-filled">
            <t-radio-button value="pro">Pro · 小型团队</t-radio-button>
            <t-radio-button value="team">Team · 协作团队</t-radio-button>
            <t-radio-button value="enterprise">Enterprise</t-radio-button>
          </t-radio-group>
        </t-form-item>
        <t-form-item label="启用模块" name="modules">
          <t-checkbox-group v-model="basic.modules">
            <t-checkbox value="dashboard">仪表盘</t-checkbox>
            <t-checkbox value="orders">订单</t-checkbox>
            <t-checkbox value="chat">AI 助手</t-checkbox>
            <t-checkbox value="billing" disabled>计费（即将推出）</t-checkbox>
          </t-checkbox-group>
        </t-form-item>
        <t-form-item label="活动通知" name="notify" help="接收项目活动提醒">
          <t-switch v-model="basic.notify" size="large" :label="['开', '关']" />
        </t-form-item>
        <div class="ug-form-actions">
          <span />
          <t-button theme="primary" size="large" @click="next">下一步<template #suffix><Icon name="arrow-right" /></template></t-button>
        </div>
      </t-form>
    </t-card>

    <t-card v-show="step === 1" :bordered="true" title="详细配置" subtitle="部署区域、时间窗口与资源">
      <t-form ref="advancedForm" :data="advanced" :rules="advancedRules" label-align="top" :required-mark="true" @submit.prevent>
        <div class="ug-grid-2">
          <t-form-item label="部署区域" name="region">
            <t-select v-model="advanced.region" :options="regionOptions" placeholder="选择区域" filterable clearable />
          </t-form-item>
          <t-form-item label="环境标签（多选）" name="tags">
            <t-select v-model="advanced.tags" :options="tagOptions" placeholder="选择标签" multiple clearable :min-collapsed-num="2" />
          </t-form-item>
          <t-form-item name="owner">
            <template #label>负责人 <t-tooltip content="支持输入时自动补全成员姓名"><Icon name="info" class="ug-help-icon" /></t-tooltip></template>
            <t-auto-complete v-model="advanced.owner" :options="ownerOptions" placeholder="输入姓名自动补全" highlight-keyword filterable clearable />
          </t-form-item>
          <t-form-item label="开始日期" name="startDate">
            <t-date-picker v-model="advanced.startDate" placeholder="选择日期" clearable style="width: 100%" />
          </t-form-item>
          <t-form-item label="每日汇报时间" name="dailyTime">
            <t-time-picker v-model="advanced.dailyTime" format="HH:mm" placeholder="选择时间" clearable style="width: 100%" />
          </t-form-item>
          <t-form-item label="有效期" name="range">
            <t-date-range-picker v-model="advanced.range" placeholder="开始 / 结束" clearable style="width: 100%" />
          </t-form-item>
          <t-form-item label="采样比例（%）" name="sampling" help="拖动两端设置区间">
            <t-slider v-model="advanced.sampling" range :marks="{ 0: '0', 50: '50', 100: '100' }" />
          </t-form-item>
          <t-form-item label="优先级评分" name="rating">
            <t-rate v-model="advanced.rating" allow-half show-text />
          </t-form-item>
          <t-form-item label="主题色" name="color">
            <t-color-picker v-model="advanced.color" format="HEX" :show-primary-color-preview="false" />
          </t-form-item>
          <t-form-item label="自定义标签" name="labels" help="回车添加">
            <t-tag-input v-model="advanced.labels" placeholder="输入后回车" clearable />
          </t-form-item>
        </div>
        <t-form-item label="附件" name="files" help="支持拖拽上传，单个不超过 5MB">
          <t-upload v-model="advanced.files" theme="file-flow" draggable multiple :auto-upload="false" :size-limit="{ size: 5, unit: 'MB' }" placeholder="拖拽文件到此处或点击上传" />
        </t-form-item>
        <div class="ug-form-actions">
          <t-button variant="outline" size="large" @click="step = 0"><template #icon><Icon name="arrow-left" /></template>上一步</t-button>
          <t-button theme="primary" size="large" @click="next">下一步<template #suffix><Icon name="arrow-right" /></template></t-button>
        </div>
      </t-form>
    </t-card>

    <t-card v-show="step === 2" :bordered="true" title="确认提交" subtitle="核对以下信息">
      <t-descriptions :column="2" bordered item-layout="horizontal" size="small">
        <t-descriptions-item label="项目名称">{{ basic.name || "—" }}</t-descriptions-item>
        <t-descriptions-item label="席位数">{{ basic.seats }}</t-descriptions-item>
        <t-descriptions-item label="联系邮箱">{{ basic.email || "—" }}</t-descriptions-item>
        <t-descriptions-item label="联系电话">{{ basic.countryCode }} {{ basic.phone || "—" }}</t-descriptions-item>
        <t-descriptions-item label="计划">{{ basic.plan }}</t-descriptions-item>
        <t-descriptions-item label="模块">{{ basic.modules.join("、") || "—" }}</t-descriptions-item>
        <t-descriptions-item label="部署区域">{{ regionOptions.find((r) => r.value === advanced.region)?.label || "—" }}</t-descriptions-item>
        <t-descriptions-item label="标签">{{ advanced.tags.join("、") || "—" }}</t-descriptions-item>
        <t-descriptions-item label="负责人">{{ advanced.owner || "—" }}</t-descriptions-item>
        <t-descriptions-item label="开始日期">{{ advanced.startDate || "—" }}</t-descriptions-item>
        <t-descriptions-item label="采样">{{ advanced.sampling.join(" – ") }}%</t-descriptions-item>
        <t-descriptions-item label="附件">{{ advanced.files.length }} 个文件</t-descriptions-item>
      </t-descriptions>
      <t-progress :percentage="agreed ? 100 : 82" :label="true" class="ug-progress" />
      <div class="ug-agree" :class="{ 'ug-agree--error': agreedError }">
        <t-checkbox v-model="agreed" @change="agreedError = false">我已阅读并同意服务条款与隐私政策</t-checkbox>
        <div v-if="agreedError" class="ug-error-text">提交前请先同意条款</div>
      </div>
      <div class="ug-form-actions">
        <t-button variant="outline" size="large" @click="step = 1"><template #icon><Icon name="arrow-left" /></template>上一步</t-button>
        <t-button theme="primary" size="large" :loading="submitting" @click="submit"><template #icon><Icon name="check" /></template>提交项目</t-button>
      </div>
    </t-card>

    <t-card v-show="step === 3" :bordered="true">
      <div class="ug-result">
        <div class="ug-result-icon"><Icon name="check-circle" :size="40" /></div>
        <t-typography-title level="h5" class="ug-title">项目创建成功</t-typography-title>
        <p class="ug-muted">工作区已准备就绪，可以邀请成员开始协作。</p>
        <t-space>
          <t-button theme="primary" size="large">进入项目</t-button>
          <t-button variant="outline" size="large" @click="reset">再创建一个</t-button>
        </t-space>
      </div>
    </t-card>
  </div>
</template>

<style>
.ug-form-page .t-form__item { margin-bottom: 20px; }
.ug-steps { overflow-x: auto; }
.ug-country-select { width: 120px; }
.ug-form-actions { display: flex; justify-content: space-between; gap: 8px; margin-top: 8px; }
.ug-help-icon { vertical-align: -2px; margin-left: 4px; color: var(--td-text-color-placeholder); }
.ug-progress { margin: 20px 0; }
.ug-agree { padding: 12px; border: 1px solid var(--td-component-stroke); border-radius: var(--td-radius-medium); }
.ug-agree--error { border-color: var(--td-error-color); }
.ug-result { display: flex; flex-direction: column; align-items: center; text-align: center; gap: 8px; padding: 32px 0; }
.ug-result-icon { color: var(--td-success-color); }
.ug-error-text { color: var(--td-error-color); font-size: 12px; margin-top: 4px; }

</style>

// apps/mantine/src/pages/form.tsx
import { useState } from "react"
import { ActionIcon, Autocomplete, Button, Card, Checkbox, ColorInput, DataList, Group, List, MultiSelect, NumberInput, Radio, RangeSlider, Rating, Select, Stack, Stepper, Switch, TagsInput, Text, TextInput, Textarea, ThemeIcon, Title, Tooltip } from "@mantine/core"
import { DatePickerInput, TimeInput } from "@mantine/dates"
import { Dropzone, type FileWithPath } from "@mantine/dropzone"
import { useForm } from "@mantine/form"
import { Icon } from "@ui-gallery/icons-react"
import team from "@ui-gallery/spec/mock/team.json"
import { muted, PageHeader } from "./shared"

const help = (label: string, tip: string) => (
  <Group gap={4} wrap="nowrap" component="span">
    {label}
    <Tooltip label={tip} withArrow>
      <span style={{ display: "inline-flex" }}><Icon name="circle-help" size={14} /></span>
    </Tooltip>
  </Group>
)

const countryCodes = [{ value: "+86", label: "+86 中国" }, { value: "+1", label: "+1 美国" }, { value: "+81", label: "+81 日本" }, { value: "+44", label: "+44 英国" }]
const regions = ["中国大陆", "新加坡", "法兰克福"]
const tiers = ["Starter", "Pro", "Enterprise"]

export function FormPage() {
  const [active, setActive] = useState(0)
  const [files, setFiles] = useState<FileWithPath[]>([])
  const [done, setDone] = useState(false)
  const form = useForm({
    initialValues: {
      name: "", seats: 5, email: "", code: "+86", phone: "", desc: "", type: "team", modules: ["orders"], notify: true,
      region: null as string | null, tags: [] as string[], owner: "", startDate: null as string | null, startTime: "", range: [null, null] as [string | null, string | null],
      budget: [20, 60] as [number, number], priority: 3, color: "#228be6", labels: ["内部"] as string[], agree: false,
    },
    validate: (v) => {
      if (active === 0) {
        return {
          name: v.name.trim().length < 2 ? "项目名称至少 2 个字符" : null,
          seats: v.seats < 1 || v.seats > 500 ? "席位 1–500" : null,
          email: /^\S+@\S+\.\S+$/.test(v.email) ? null : "请输入有效邮箱",
          phone: /^\d{6,15}$/.test(v.phone) ? null : "请输入 6–15 位数字",
          desc: v.desc.length > 200 ? "最多 200 字" : null,
          modules: v.modules.length ? null : "至少选择一个模块",
        }
      }
      if (active === 1) {
        return {
          region: v.region ? null : "请选择区域",
          tags: v.tags.length ? null : "至少选择一个计划",
          owner: v.owner ? null : "请选择负责人",
          startDate: v.startDate ? null : "请选择开始日期",
          startTime: v.startTime ? null : "请选择时间",
          range: v.range[0] && v.range[1] ? null : "请选择日期范围",
          labels: v.labels.length ? null : "至少一个标签",
        }
      }
      return { agree: v.agree ? null : "需同意服务条款" }
    },
  })

  const next = () => {
    if (form.validate().hasErrors) return
    if (active === 2) { setDone(true); return }
    setActive((a) => a + 1)
  }

  if (done) {
    return (
      <Stack gap="lg">
        <PageHeader title="新建项目" />
        <Card withBorder radius="md" padding="xl">
          <Stack align="center" gap="md" py="xl">
            <ThemeIcon size={64} radius="xl" color="teal" variant="light"><Icon name="check" size={32} /></ThemeIcon>
            <Title order={2}>项目已创建</Title>
            <Text c={muted} ta="center">项目「{form.values.name}」已创建，成员将收到邀请邮件。</Text>
            <Group><Button variant="default" onClick={() => { setDone(false); setActive(0); form.reset() }}>再建一个</Button><Button>进入项目</Button></Group>
          </Stack>
        </Card>
      </Stack>
    )
  }

  return (
    <Stack gap="lg">
      <PageHeader title="新建项目" description="三步完成项目配置。" />
      <Card withBorder radius="md" padding="lg">
        <Stepper active={active} onStepClick={setActive} allowNextStepsSelect={false} size="sm">
          <Stepper.Step label="基本信息" description="名称与联系人" />
          <Stepper.Step label="详细配置" description="区域、计划与预算" />
          <Stepper.Step label="确认" description="核对并提交" />
        </Stepper>

        <Stack gap="md" mt="xl" maw={720}>
          {active === 0 ? (
            <>
              <TextInput label="项目名称" placeholder="例如：Q4 增长计划" required description="将显示在侧边栏与邀请邮件中" {...form.getInputProps("name")} />
              <Group grow align="flex-start">
                <NumberInput label="席位数" min={1} max={500} required {...form.getInputProps("seats")} />
                <TextInput label="联系邮箱" placeholder="you@example.com" required {...form.getInputProps("email")} />
              </Group>
              <Group align="flex-start" gap="xs" wrap="nowrap">
                <Select label="国家码" data={countryCodes} w={140} {...form.getInputProps("code")} allowDeselect={false} />
                <TextInput label="电话" placeholder="13800000000" required style={{ flex: 1 }} {...form.getInputProps("phone")} />
              </Group>
              <Textarea label="项目描述" placeholder="简要描述项目目标" autosize minRows={3} maxLength={200} description={`${form.values.desc.length}/200`} {...form.getInputProps("desc")} />
              <Radio.Group label="项目类型" required {...form.getInputProps("type")}>
                <Group mt="xs"><Radio value="personal" label="个人" /><Radio value="team" label="团队" /><Radio value="enterprise" label="企业" /></Group>
              </Radio.Group>
              <Checkbox.Group label="启用模块" required {...form.getInputProps("modules")}>
                <Group mt="xs"><Checkbox value="orders" label="订单" /><Checkbox value="chat" label="AI 助手" /><Checkbox value="billing" label="计费" /></Group>
              </Checkbox.Group>
              <Switch label="创建后通知全体成员" {...form.getInputProps("notify", { type: "checkbox" })} />
            </>
          ) : null}

          {active === 1 ? (
            <>
              <Group grow align="flex-start">
                <Select label="数据区域" placeholder="选择区域" data={regions} required {...form.getInputProps("region")} />
                <MultiSelect label="订阅计划" placeholder="可多选" data={tiers} required {...form.getInputProps("tags")} />
              </Group>
              <Autocomplete label={help("负责人", "输入姓名自动补全")} placeholder="搜索成员" data={team.map((m) => m.name)} required {...form.getInputProps("owner")} />
              <Group grow align="flex-start">
                <DatePickerInput label="开始日期" placeholder="选择日期" required leftSection={<Icon name="calendar" size={15} />} {...form.getInputProps("startDate")} />
                <TimeInput label="开始时间" required leftSection={<Icon name="clock" size={15} />} {...form.getInputProps("startTime")} />
              </Group>
              <DatePickerInput type="range" label="迭代周期" placeholder="选择日期范围" required {...form.getInputProps("range")} />
              <div>
                <Text size="sm" fw={500} mb={4}>预算区间（万元）</Text>
                <RangeSlider min={0} max={100} step={5} minRange={10} marks={[{ value: 0, label: "0" }, { value: 50, label: "50" }, { value: 100, label: "100" }]} mb="lg" {...form.getInputProps("budget")} />
              </div>
              <Group grow align="flex-start">
                <div><Text size="sm" fw={500} mb={4}>优先级</Text><Rating {...form.getInputProps("priority")} /></div>
                <ColorInput label="主题色" format="hex" swatches={["#228be6", "#12b886", "#fa5252", "#7950f2", "#fd7e14"]} {...form.getInputProps("color")} />
              </Group>
              <div>
                <Text size="sm" fw={500} mb={4}>附件</Text>
                <Dropzone onDrop={(accepted) => setFiles([...files, ...accepted])} maxSize={5 * 1024 ** 2} radius="md">
                  <Group justify="center" gap="md" mih={100} style={{ pointerEvents: "none" }}>
                    <Dropzone.Accept><Icon name="upload" size={32} /></Dropzone.Accept>
                    <Dropzone.Reject><Icon name="x" size={32} /></Dropzone.Reject>
                    <Dropzone.Idle><Icon name="upload" size={32} /></Dropzone.Idle>
                    <div><Text size="sm">拖拽文件到此处或点击上传</Text><Text size="xs" c={muted}>单个文件不超过 5 MB</Text></div>
                  </Group>
                </Dropzone>
                {files.length ? (
                  <List size="sm" mt="xs" spacing={4}>
                    {files.map((f) => (
                      <List.Item key={f.name} icon={<Icon name="paperclip" size={14} />}>
                        <Group gap="xs">{f.name}<Text size="xs" c={muted}>{(f.size / 1024).toFixed(1)} KB</Text><ActionIcon size="xs" variant="subtle" color="gray" onClick={() => setFiles(files.filter((x) => x !== f))} aria-label="移除"><Icon name="x" size={12} /></ActionIcon></Group>
                      </List.Item>
                    ))}
                  </List>
                ) : null}
              </div>
              <TagsInput label="标签" placeholder="回车添加" description="用于筛选与分组" required {...form.getInputProps("labels")} />
            </>
          ) : null}

          {active === 2 ? (
            <>
              <DataList withDivider labelWidth={120}>
                <DataList.Item><DataList.ItemLabel>项目名称</DataList.ItemLabel><DataList.ItemValue>{form.values.name}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>席位 / 类型</DataList.ItemLabel><DataList.ItemValue>{form.values.seats} · {form.values.type}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>联系方式</DataList.ItemLabel><DataList.ItemValue>{form.values.email} · {form.values.code} {form.values.phone}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>区域 / 计划</DataList.ItemLabel><DataList.ItemValue>{form.values.region} · {form.values.tags.join(", ")}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>负责人</DataList.ItemLabel><DataList.ItemValue>{form.values.owner}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>开始</DataList.ItemLabel><DataList.ItemValue>{form.values.startDate} {form.values.startTime}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>周期</DataList.ItemLabel><DataList.ItemValue>{form.values.range[0]} ~ {form.values.range[1]}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>预算</DataList.ItemLabel><DataList.ItemValue>{form.values.budget[0]} – {form.values.budget[1]} 万元</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>标签</DataList.ItemLabel><DataList.ItemValue>{form.values.labels.join(", ")}</DataList.ItemValue></DataList.Item>
                <DataList.Item><DataList.ItemLabel>附件</DataList.ItemLabel><DataList.ItemValue>{files.length} 个文件</DataList.ItemValue></DataList.Item>
              </DataList>
              <Checkbox label="我已阅读并同意服务条款与隐私政策" {...form.getInputProps("agree", { type: "checkbox" })} />
            </>
          ) : null}

          <Group justify="space-between" mt="md">
            <Button variant="default" disabled={active === 0} onClick={() => setActive((a) => a - 1)}>上一步</Button>
            <Button onClick={next}>{active === 2 ? "提交" : "下一步"}</Button>
          </Group>
        </Stack>
      </Card>
    </Stack>
  )
}
