// apps/element-plus/src/pages/Landing.vue
<script setup lang="ts">
import { ref } from "vue"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import Icon from "@/icons/Icon.vue"
import { useMobile } from "@/composables/useMobile"
const mobile = useMobile()
const menu = ref(false)
const yearly = ref(false)
</script>

<template>
  <div class="landing">
    <header class="landing-nav"><div class="brand"><span class="brand-mark">A</span>Acme Console</div><el-menu mode="horizontal" ellipsis class="hide-mobile"><el-menu-item index="1">产品</el-menu-item><el-menu-item index="2">方案</el-menu-item><el-menu-item index="3">价格</el-menu-item><el-menu-item index="4">资源</el-menu-item><el-menu-item index="5">帮助</el-menu-item></el-menu><div class="nav-actions"><el-button text class="hide-mobile">登录</el-button><el-button type="primary" round>免费开始</el-button><el-button v-if="mobile" text class="icon-btn" @click="menu = true"><Icon name="menu" :size="20" /></el-button></div></header>
    <el-drawer v-model="menu" direction="rtl" size="260px"><el-menu><el-menu-item index="1">产品</el-menu-item><el-menu-item index="2">方案</el-menu-item><el-menu-item index="3">价格</el-menu-item><el-menu-item index="4">资源</el-menu-item><el-menu-item index="5">帮助</el-menu-item></el-menu></el-drawer>
    <main>
      <section class="hero"><el-tag type="success" effect="plain">新一代团队控制台</el-tag><h1>{{ landing.hero.title }}</h1><p>{{ landing.hero.subtitle }}</p><el-space><el-button type="primary" size="large">{{ landing.hero.primary }}</el-button><el-button size="large">{{ landing.hero.secondary }}</el-button></el-space><div class="hero-shot"><el-skeleton animated :rows="5" /></div><div class="social"><el-avatar-group><el-avatar v-for="name in landing.testimonials.slice(0, 5)" :key="name.name">{{ name.name.slice(0, 1) }}</el-avatar></el-avatar-group><span>{{ landing.hero.social }}</span></div></section>
      <section class="logo-cloud"><span v-for="name in ['NORTHWIND','CONTOSO','FABRIKAM','GLOBEX','INITECH','UMBRELLA']" :key="name">{{ name }}</span></section>
      <section id="features" class="section"><h2>为高效团队而生</h2><p class="section-lead">从数据到协作，所有重要工作都在一个地方。</p><el-row :gutter="16"><el-col v-for="feature in landing.features" :key="feature.title" :xs="24" :sm="12" :lg="8"><el-card class="feature-card"><Icon :name="feature.icon" :size="24" /><h3>{{ feature.title }}</h3><p>{{ feature.desc }}</p></el-card></el-col></el-row></section>
      <section class="section split" v-for="(feature, index) in landing.features.slice(0, 3)" :key="feature.title"><div><el-skeleton animated :rows="5" /></div><div><el-tag>{{ `0${index + 1}` }}</el-tag><h2>{{ feature.title }}</h2><p>{{ feature.desc }} 通过清晰的工作流，团队可以快速从想法走向结果。</p><el-link type="primary">了解更多 →</el-link></div></section>
      <section class="numbers"><div v-for="item in landing.numbers" :key="item.label"><strong>{{ item.value }}</strong><span>{{ item.label }}</span></div></section>
      <section id="pricing" class="section"><div class="section-top"><div><h2>简单透明的定价</h2><p class="section-lead">按团队规模选择合适计划。</p></div><el-switch v-model="yearly" active-text="按年付费" /></div><el-row :gutter="16"><el-col v-for="plan in plans" :key="plan.name" :xs="24" :md="8"><el-card :class="{ recommended: plan.recommended }" class="plan-card"><el-tag v-if="plan.recommended" type="success">推荐</el-tag><h3>{{ plan.name }}</h3><strong>{{ plan.price === null ? '联系销售' : plan.price === 0 ? '免费' : `¥${yearly ? plan.price * 10 : plan.price} / ${yearly ? '年' : '月'}` }}</strong><p v-for="item in plan.features" :key="item">✓ {{ item }}</p><el-button :type="plan.recommended ? 'primary' : 'default'" class="full-width">选择计划</el-button></el-card></el-col></el-row></section>
      <section class="section"><h2>团队正在这样使用</h2><div class="testimonials"><el-carousel height="180px" :autoplay="false" arrow="always" indicator-position="outside"><el-carousel-item v-for="quote in landing.testimonials" :key="quote.name"><div class="quote"><p>“{{ quote.quote }}”</p><span>{{ quote.name }} · {{ quote.company }}</span></div></el-carousel-item></el-carousel></div></section>
      <section id="faq" class="section faq"><h2>常见问题</h2><el-collapse accordion><el-collapse-item v-for="item in landing.faq" :key="item.q" :title="item.q"><p>{{ item.a }}</p></el-collapse-item></el-collapse></section>
      <section class="cta"><h2>准备好让团队更高效了吗？</h2><p>从今天开始，把工作放进一个控制台。</p><el-button type="primary" size="large">免费开始</el-button></section>
    </main>
    <footer><div class="brand"><span class="brand-mark">A</span>Acme Console</div><div class="footer-links"><el-link>产品</el-link><el-link>价格</el-link><el-link>帮助中心</el-link><el-link>隐私条款</el-link></div><span class="muted">© 2026 Acme Console · <el-select model-value="zh-CN" size="small" style="width: 110px"><el-option label="简体中文" value="zh-CN" /></el-select></span></footer>
  </div>
</template>

<style scoped>
.landing-nav, footer { display: flex; align-items: center; gap: 24px; max-width: 1200px; margin: auto; padding: 18px 24px; }
.landing-nav { justify-content: space-between; min-width: 0; }
.landing-nav :deep(.el-menu) { min-width: 0; flex: 1; }
.brand { display: flex; align-items: center; gap: 10px; font-weight: 700; white-space: nowrap; }
.brand-mark { display: grid; width: 32px; height: 32px; place-items: center; border-radius: 8px; background: var(--el-color-primary); }
.nav-actions { display: flex; gap: 8px; align-items: center; }
.hero { max-width: 900px; margin: auto; padding: 90px 24px 60px; text-align: center; }
.hero h1 { margin: 18px 0; font-size: clamp(36px, 7vw, 68px); line-height: 1.08; }
.hero p, .section-lead { color: var(--el-text-color-secondary); font-size: 18px; }
.hero-shot { max-width: 800px; height: 260px; margin: 50px auto 20px; padding: 32px; overflow: hidden; box-sizing: border-box; border: 1px solid var(--el-border-color); border-radius: 16px; box-shadow: var(--el-box-shadow-light); }
.hero-shot :deep(.el-skeleton), .hero-shot :deep(.el-skeleton__item) { width: 100%; max-width: 100%; box-sizing: border-box; }
.social { display: flex; align-items: center; justify-content: center; gap: 12px; }
.logo-cloud { display: flex; justify-content: space-around; gap: 18px; max-width: 1100px; margin: auto; padding: 30px 24px; color: var(--el-text-color-secondary); font-size: 12px; font-weight: 700; letter-spacing: 2px; flex-wrap: wrap; }
.section { max-width: 1100px; margin: auto; padding: 80px 24px; }
.section h2, .cta h2 { font-size: 34px; margin: 0 0 12px; }
.feature-card { height: 100%; margin-bottom: 16px; }
.feature-card h3 { margin-bottom: 6px; }
.split { display: grid; grid-template-columns: 1fr 1fr; gap: 60px; align-items: center; }
.split > div:first-child { min-height: 230px; padding: 28px; border-radius: 16px; background: var(--el-fill-color-light); }
.numbers { display: flex; justify-content: space-around; gap: 30px; padding: 50px 24px; background: var(--el-fill-color-light); flex-wrap: wrap; }
.numbers div { display: grid; text-align: center; gap: 8px; }
.numbers strong { font-size: 36px; }
.section-top { display: flex; justify-content: space-between; align-items: end; gap: 20px; }
.plan-card { position: relative; height: 100%; margin-bottom: 16px; }
.plan-card.recommended { border-color: var(--el-color-primary); }
.plan-card strong { display: block; margin: 20px 0; font-size: 30px; }
.testimonials { width: 100%; max-width: 100%; overflow: hidden; border-radius: 12px; }
.quote { display: grid; height: 100%; place-content: center; text-align: center; }
.quote p { font-size: 22px; }
.faq { max-width: 800px; }
.cta { max-width: 1100px; margin: 20px auto 80px; padding: 70px 24px; border-radius: 18px; color: var(--el-text-color-primary); background: var(--el-color-primary-light-9); text-align: center; }
.footer-links { display: flex; gap: 20px; flex: 1; justify-content: center; }
footer { border-top: 1px solid var(--el-border-color); max-width: none; justify-content: space-between; }
@media (max-width: 767px) { .split { grid-template-columns: 1fr; gap: 24px; }.section { padding: 56px 16px; }.hero { padding: 55px 16px 42px; }.hero-shot { height: 190px; padding: 18px; }.numbers { gap: 24px; }.numbers strong { font-size: 28px; }.footer-links { display: none; }footer { flex-wrap: wrap; padding: 22px 16px; } }
</style>

// apps/react-bootstrap/src/pages/landing.tsx
import { useState } from "react"
import { Link } from "react-router-dom"
import { Accordion, Badge, Button, Card, Col, Container, Form, Nav, Navbar, Offcanvas, Row } from "react-bootstrap"
import { Icon } from "@ui-gallery/icons-react"
import landing from "@ui-gallery/spec/mock/landing.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import { AvatarGroup, Brand, Section, SplitFeature } from "@/pages/shared"

export function LandingPage() {
  const [yearly, setYearly] = useState(false)
  return <>
    <Navbar expand="lg" className="border-bottom px-3">
      <Container><Brand /><Navbar.Toggle aria-controls="landing-nav" />
        <Navbar.Offcanvas id="landing-nav" placement="end">
          <Offcanvas.Header closeButton><Offcanvas.Title>Acme Console</Offcanvas.Title></Offcanvas.Header>
          <Offcanvas.Body><Nav className="mx-auto"><Nav.Link href="#features">特性</Nav.Link><Nav.Link href="#solutions">方案</Nav.Link><Nav.Link href="#pricing">定价</Nav.Link><Nav.Link href="#faq">FAQ</Nav.Link><Nav.Link href="#testimonials">客户故事</Nav.Link></Nav><Link className="btn btn-primary" to="/login">免费开始</Link></Offcanvas.Body>
        </Navbar.Offcanvas>
      </Container>
    </Navbar>
    <Container>
      <Row className="align-items-center py-5 g-4"><Col lg={6}><Badge bg="primary-subtle" text="primary" className="mb-3">新一代团队工作台</Badge><h1 className="display-4 fw-bold">{landing.hero.title}</h1><p className="lead text-secondary">{landing.hero.subtitle}</p><div className="d-flex flex-wrap gap-2"><Link className="btn btn-primary btn-lg" to="/login">{landing.hero.primary}</Link><Button size="lg" variant="outline-secondary">{landing.hero.secondary}</Button></div><div className="d-flex align-items-center gap-3 mt-4"><AvatarGroup names={["林晓", "Alex", "Maria"]} /><span className="text-secondary">{landing.hero.social}</span></div></Col><Col lg={6}><div className="hero-placeholder bg-body-secondary rounded-4 d-flex align-items-center justify-content-center" style={{ minHeight: 300 }}><Icon name="layout-dashboard" size={48} /></div></Col></Row>
      <div className="d-flex flex-wrap justify-content-around gap-3 border-top border-bottom py-4 text-secondary fw-semibold">{["Northwind", "Contoso", "Globex", "Fabrikam", "Initech", "Umbrella"].map((name) => <span key={name}>{name}</span>)}</div>
      <Section title="为团队而生" className="py-5"><Row id="features" className="g-3">{landing.features.map((feature) => <Col md={6} lg={4} key={feature.title}><Card className="h-100 border-0 bg-body-tertiary"><Card.Body><Icon name={feature.icon} className="text-primary mb-3" size={25} /><h2 className="h5">{feature.title}</h2><p className="text-secondary mb-0">{feature.desc}</p></Card.Body></Card></Col>)}</Row></Section>
      <section id="solutions"><SplitFeature title="统一视图" text="所有业务数据一屏掌握，让团队在同一上下文中协作。" /><SplitFeature title="智能协作" text="让 AI 成为每个团队成员的助手，自动生成洞察与行动。" reverse /><SplitFeature title="安全可靠" text="企业级权限、审计日志与稳定的基础设施。" /></section>
      <Row className="bg-primary text-white rounded-4 py-4 my-5 text-center">{landing.numbers.map((number) => <Col sm={6} lg={3} key={number.label}><div className="fs-2 fw-bold">{number.value}</div><div>{number.label}</div></Col>)}</Row>
      <Section title="简单透明的定价" className="py-5"><div id="pricing" className="d-flex justify-content-center mb-4"><Form.Check type="switch" label={yearly ? "按年付费（价格 × 10 /年）" : "按月付费"} checked={yearly} onChange={(event) => setYearly(event.target.checked)} /></div><Row className="g-3">{plans.map((plan) => <Col md={4} key={plan.name}><Card className={`h-100 ${plan.recommended ? "border-primary shadow" : ""}`}><Card.Body><div className="d-flex justify-content-between"><h2 className="h5">{plan.name}</h2>{plan.recommended && <Badge>推荐</Badge>}</div><div className="display-6 fw-semibold my-3">{plan.price === null ? "定制" : plan.price === 0 ? "免费" : `¥${yearly ? plan.price * 10 : plan.price}`}<small className="fs-6 text-secondary">{plan.price ? yearly ? "/年" : "/月" : ""}</small></div><ul className="list-unstyled">{plan.features.map((feature) => <li key={feature} className="mb-2">✓ {feature}</li>)}</ul><Button className="w-100" variant={plan.recommended ? "primary" : "outline-primary"}>选择计划</Button></Card.Body></Card></Col>)}</Row></Section>
      <Section title="客户怎么说" className="py-5"><Row id="testimonials" className="g-3">{landing.testimonials.map((item) => <Col md={6} lg={4} key={item.name}><Card className="h-100"><Card.Body><p>“{item.quote}”</p><div className="d-flex align-items-center gap-2"><span className="rounded-circle bg-primary-subtle p-2">{item.name.slice(0, 1)}</span><small>{item.name} · {item.company}</small></div></Card.Body></Card></Col>)}</Row></Section>
      <Section title="常见问题" className="py-5"><Accordion id="faq">{landing.faq.map((item, index) => <Accordion.Item eventKey={String(index)} key={item.q}><Accordion.Header>{item.q}</Accordion.Header><Accordion.Body>{item.a}</Accordion.Body></Accordion.Item>)}</Accordion></Section>
      <div className="bg-primary text-white rounded-4 p-4 p-md-5 text-center mb-5"><h2>准备好开始了吗？</h2><p>加入 1,000+ 个高效团队。</p><Link className="btn btn-light" to="/login">免费开始</Link></div>
    </Container>
    <footer className="footer-links border-top py-5"><Container><Row className="g-4"><Col md={4}><Brand /><p className="text-secondary mt-3">© 2026 Acme Console</p><div className="d-flex gap-2"><Button variant="outline-secondary" aria-label="github"><Icon name="github" /></Button><Button variant="outline-secondary" aria-label="globe"><Icon name="globe" /></Button></div></Col>{["产品", "资源", "公司", "支持"].map((title) => <Col xs={6} md key={title}><h2 className="h6">{title}</h2><a className="d-block text-secondary" href="#features">特性</a><a className="d-block text-secondary" href="#pricing">定价</a><a className="d-block text-secondary" href="#faq">帮助中心</a></Col>)}<Col xs={6} md={2}><Form.Select aria-label="语言"><option>简体中文</option><option>English</option></Form.Select></Col></Row></Container></footer>
  </>
}
