// apps/antd/src/pages/dashboard.tsx
import { useEffect, useState } from "react"
import {
  Button,
  Card,
  Col,
  Dropdown,
  Flex,
  List,
  Progress,
  Row,
  Skeleton,
  Space,
  Statistic,
  Table,
  Tabs,
  Tag,
  Timeline,
  Typography,
} from "antd"
import {
  LineChart as ReLineChart,
  Line,
  BarChart as ReBarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  Tooltip as ChartTooltip,
  XAxis,
  YAxis,
} from "recharts"
import stats from "@ui-gallery/spec/mock/stats.json"
import series from "@ui-gallery/spec/mock/series.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import activity from "@ui-gallery/spec/mock/activity.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import { Icon } from "@/icons"
import {
  PageHeader,
  avatar,
  statusColor,
  statusLabel,
  type Order,
} from "@/pages/shared"
import { Link } from "react-router-dom"
import { theme } from "antd"

function orderColumns(): Array<Record<string, unknown>> {
  return [
    {
      title: "订单号",
      dataIndex: "id",
      sorter: (a: Order, b: Order) => a.id.localeCompare(b.id),
    },
    {
      title: "客户",
      dataIndex: "customer",
      render: (value: string) => (
        <Space>
          {avatar(value)}
          {value}
        </Space>
      ),
    },
    {
      title: "状态",
      dataIndex: "status",
      render: (value: string) => (
        <Tag color={statusColor[value]}>{statusLabel[value]}</Tag>
      ),
    },
    {
      title: "金额",
      dataIndex: "amount",
      align: "right",
      render: (value: number) => `¥${value.toLocaleString()}`,
    },
    {
      title: "操作",
      key: "action",
      fixed: "right",
      width: 72,
      render: () => (
        <Dropdown
          menu={{
            items: [
              { key: "view", label: "查看详情" },
              { key: "edit", label: "编辑" },
            ],
          }}
        >
          <Button
            type="text"
            icon={<Icon name="more-horizontal" />}
            aria-label="更多操作"
          />
        </Dropdown>
      ),
    },
  ]
}

export function DashboardPage() {
  const [loading, setLoading] = useState(true)
  const [period, setPeriod] = useState("month")
  const { token } = theme.useToken()
  useEffect(() => {
    if (!loading) return
    const timer = window.setTimeout(() => setLoading(false), 600)
    return () => window.clearTimeout(timer)
  }, [loading])
  const periodTabs = (
    <Tabs
      size="small"
      activeKey={period}
      onChange={setPeriod}
      items={[
        { key: "day", label: "日" },
        { key: "week", label: "周" },
        { key: "month", label: "月" },
      ]}
    />
  )
  const header = (
    <PageHeader
      title="仪表盘"
      description="查看业务健康度与团队进展。"
      extra={
        <Space wrap>
          {periodTabs}
          <Button
            icon={<Icon name="refresh" />}
            loading={loading}
            onClick={() => setLoading(true)}
          >
            刷新
          </Button>
        </Space>
      }
    />
  )
  if (loading)
    return (
      <>
        {header}
        <Row gutter={[16, 16]}>
          {stats.map((stat) => (
            <Col xs={24} sm={12} xl={6} key={stat.key}>
              <Card>
                <Skeleton active paragraph={{ rows: 2 }} />
              </Card>
            </Col>
          ))}
        </Row>
        <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
          <Col xs={24} xl={16}>
            <Card>
              <Skeleton active paragraph={{ rows: 6 }} />
            </Card>
          </Col>
          <Col xs={24} xl={8}>
            <Card>
              <Skeleton active paragraph={{ rows: 6 }} />
            </Card>
          </Col>
        </Row>
        <Card style={{ marginTop: 16 }}>
          <Skeleton active paragraph={{ rows: 4 }} />
        </Card>
      </>
    )
  const divisor = period === "day" ? 30 : period === "week" ? 4 : 1
  const lineData = series.months.map((month, index) => ({
    month,
    revenue: Math.round(series.revenue[index] / divisor),
    orders: Math.round(series.orders[index] / divisor),
  }))
  return (
    <>
      {header}
      <Row gutter={[16, 16]}>
        {stats.map((stat) => (
          <Col xs={24} sm={12} xl={6} key={stat.key}>
            <Card>
              <Statistic
                title={stat.label}
                value={stat.value}
                suffix={stat.unit === "CNY" ? "元" : stat.unit}
              />
              <Tag
                color={stat.delta >= 0 ? "success" : "error"}
                icon={
                  <Icon name={stat.delta >= 0 ? "arrow-up" : "arrow-down"} />
                }
              >
                {Math.abs(stat.delta)}%
              </Tag>
              <div className="mini-chart">
                <ResponsiveContainer>
                  <ReLineChart
                    data={stat.trend.map((value, index) => ({ index, value }))}
                  >
                    <Line
                      dataKey="value"
                      stroke={
                        stat.delta >= 0 ? token.colorSuccess : token.colorError
                      }
                      dot={false}
                      isAnimationActive={false}
                    />
                  </ReLineChart>
                </ResponsiveContainer>
              </div>
            </Card>
          </Col>
        ))}
      </Row>
      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        <Col xs={24} xl={16}>
          <Card title="业务趋势">
            <div className="chart">
              <ResponsiveContainer>
                <ReLineChart data={lineData}>
                  <XAxis dataKey="month" />
                  <YAxis />
                  <ChartTooltip />
                  <Line
                    dataKey="revenue"
                    stroke={token.colorPrimary}
                    strokeWidth={3}
                    isAnimationActive={false}
                  />
                  <Line
                    dataKey="orders"
                    stroke={token.colorSuccess}
                    isAnimationActive={false}
                  />
                </ReLineChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </Col>
        <Col xs={24} xl={8}>
          <Card title="渠道分布">
            <div className="chart">
              <ResponsiveContainer>
                <PieChart>
                  <Pie
                    data={series.byChannel}
                    dataKey="value"
                    nameKey="name"
                    outerRadius={90}
                    label
                    isAnimationActive={false}
                  >
                    {series.byChannel.map((entry, index) => (
                      <Cell
                        key={entry.name}
                        fill={
                          [
                            token.colorPrimary,
                            token.colorSuccess,
                            token.colorWarning,
                            token.colorError,
                          ][index]
                        }
                      />
                    ))}
                  </Pie>
                  <ChartTooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </Col>
      </Row>
      <Card title="订单趋势" style={{ marginTop: 16 }}>
        <div className="chart">
          <ResponsiveContainer>
            <ReBarChart data={lineData}>
              <XAxis dataKey="month" />
              <YAxis />
              <ChartTooltip />
              <Bar
                dataKey="orders"
                fill={token.colorPrimary}
                isAnimationActive={false}
              />
            </ReBarChart>
          </ResponsiveContainer>
        </div>
      </Card>
      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        <Col xs={24} xl={15}>
          <Card title="最近订单" extra={<Link to="/orders">查看全部</Link>}>
            <Table
              rowKey="id"
              pagination={false}
              scroll={{ x: "max-content" }}
              dataSource={orders.slice(0, 5)}
              columns={orderColumns() as never}
            />
          </Card>
        </Col>
        <Col xs={24} xl={9}>
          <Card title="团队动态">
            <Timeline
              items={activity.slice(0, 5).map((item) => ({
                children: (
                  <>
                    <b>{item.user}</b> {item.action}
                    <Typography.Text
                      type="secondary"
                      style={{ display: "block" }}
                    >
                      {item.time}
                    </Typography.Text>
                  </>
                ),
              }))}
            />
          </Card>
        </Col>
      </Row>
      <Card title="任务进度" style={{ marginTop: 16 }}>
        <List
          dataSource={tasks}
          renderItem={(task) => (
            <List.Item>
              <Flex vertical style={{ width: "100%" }}>
                <Flex justify="space-between">
                  <span>{task.title}</span>
                  <Typography.Text type="secondary">
                    {task.owner}
                  </Typography.Text>
                </Flex>
                <Progress percent={task.progress} />
              </Flex>
            </List.Item>
          )}
        />
      </Card>
    </>
  )
}

// apps/tdesign-vue-next/src/pages/Dashboard.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { useRoute, useRouter } from "vue-router"
import stats from "@ui-gallery/spec/mock/stats.json"
import series from "@ui-gallery/spec/mock/series.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import activity from "@ui-gallery/spec/mock/activity.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import EChart from "@/components/EChart.vue"
import Icon from "@/components/Icon.vue"
import { initials, money, statusLabel, statusTheme } from "@/pages/shared"

const route = useRoute()
const router = useRouter()
const loading = ref(route.query.state === "loading")
const period = ref("month")
onMounted(() => {
  if (route.query.state !== "loading") loading.value = false
})

const recent = orders.slice(0, 5)
const brand = "#0052d9"
const lineOption = computed(() => ({
  tooltip: { trigger: "axis" },
  grid: { left: 40, right: 16, top: 24, bottom: 28 },
  xAxis: { type: "category", data: series.months, boundaryGap: false },
  yAxis: { type: "value", splitLine: { lineStyle: { type: "dashed" } } },
  series: [{ name: "收入（千元）", type: "line", smooth: true, data: series.revenue, areaStyle: { opacity: 0.12 }, itemStyle: { color: brand } }],
}))
const barOption = computed(() => ({
  tooltip: { trigger: "axis" },
  grid: { left: 40, right: 16, top: 24, bottom: 28 },
  xAxis: { type: "category", data: series.months },
  yAxis: { type: "value" },
  series: [{ name: "订单", type: "bar", data: series.orders, itemStyle: { color: brand, borderRadius: [4, 4, 0, 0] } }],
}))
const pieOption = computed(() => ({
  tooltip: {},
  legend: { bottom: 0 },
  series: [{ type: "pie", radius: ["50%", "72%"], center: ["50%", "44%"], data: series.byChannel, label: { show: false } }],
}))
const sparkline = (data: number[]) => ({
  grid: { left: 0, right: 0, top: 2, bottom: 2 },
  xAxis: { type: "category", show: false, data: data.map((_, i) => i) },
  yAxis: { type: "value", show: false, min: "dataMin" },
  series: [{ type: "line", smooth: true, symbol: "none", data, lineStyle: { width: 2, color: brand }, areaStyle: { opacity: 0.15, color: brand } }],
})
const columns = [
  { colKey: "customer", title: "客户", width: 200 },
  { colKey: "product", title: "商品", width: 140 },
  { colKey: "status", title: "状态", width: 110 },
  { colKey: "amount", title: "金额", align: "right" as const, width: 130 },
  { colKey: "op", title: "", width: 64 },
]
const rowMenu = [
  { content: "查看详情", value: "view" },
  { content: "编辑", value: "edit" },
  { content: "删除", value: "delete", theme: "error" as const },
]
</script>

<template>
  <div class="ug-page">
    <div class="ug-between">
      <div>
        <t-typography-title level="h4" class="ug-title">概览</t-typography-title>
        <span class="ug-muted">欢迎回来，林晓。这是团队本周的关键指标。</span>
      </div>
      <t-radio-group v-model="period" variant="default-filled">
        <t-radio-button value="day">日</t-radio-button>
        <t-radio-button value="week">周</t-radio-button>
        <t-radio-button value="month">月</t-radio-button>
      </t-radio-group>
    </div>

    <div class="ug-grid ug-cols-4">
      <t-card v-for="s in stats" :key="s.key" :bordered="true">
        <t-skeleton :loading="loading" :row-col="[{ width: '40%' }, { width: '70%', height: '28px' }, { width: '100%', height: '40px' }]">
          <div class="ug-between">
            <span class="ug-muted">{{ s.label }}</span>
            <t-tag :theme="s.delta >= 0 ? 'success' : 'danger'" variant="light" size="small">
              <Icon :name="s.delta >= 0 ? 'arrow-up' : 'arrow-down'" :size="12" /> {{ Math.abs(s.delta) }}%
            </t-tag>
          </div>
          <t-statistic :value="s.value" :decimal-places="s.unit === '%' ? 1 : 0" :suffix="s.unit === '%' ? '%' : ''" :prefix="s.unit === 'CNY' ? '¥' : ''" />
          <EChart :option="sparkline(s.trend)" :height="44" />
        </t-skeleton>
      </t-card>
    </div>

    <div class="ug-grid ug-dash-charts">
      <t-card title="收入趋势" subtitle="单位：千元" :bordered="true">
        <template #actions><t-tag variant="light">{{ period === 'day' ? '近 7 日' : period === 'week' ? '近 7 周' : '近 7 月' }}</t-tag></template>
        <t-skeleton :loading="loading" :row-col="[{ height: '260px' }]"><EChart :option="lineOption" /></t-skeleton>
      </t-card>
      <t-card title="订单量" :bordered="true">
        <t-skeleton :loading="loading" :row-col="[{ height: '260px' }]"><EChart :option="barOption" /></t-skeleton>
      </t-card>
      <t-card title="渠道占比" :bordered="true">
        <t-skeleton :loading="loading" :row-col="[{ height: '260px' }]"><EChart :option="pieOption" /></t-skeleton>
      </t-card>
    </div>

    <div class="ug-grid ug-dash-bottom">
      <t-card title="最近订单" :bordered="true">
        <template #actions><t-link theme="primary" @click="router.push({ path: '/orders', query: route.query })">查看全部</t-link></template>
        <t-table row-key="id" :data="recent" :columns="columns" :loading="loading" size="medium" hover>
          <template #customer="{ row }">
            <div class="ug-row"><t-avatar size="small">{{ initials(row.customer) }}</t-avatar><div><div>{{ row.customer }}</div><div class="ug-muted ug-small">{{ row.id }}</div></div></div>
          </template>
          <template #status="{ row }"><t-tag :theme="statusTheme[row.status]" variant="light-outline" size="small">{{ statusLabel[row.status] }}</t-tag></template>
          <template #amount="{ row }"><span class="ug-mono">{{ money(row.amount, row.currency) }}</span></template>
          <template #op>
            <t-dropdown :options="rowMenu" placement="bottom-right"><t-button variant="text" shape="square" size="small" aria-label="更多"><Icon name="more-horizontal" /></t-button></t-dropdown>
          </template>
        </t-table>
      </t-card>
      <div class="ug-stack">
        <t-card title="团队动态" :bordered="true">
          <t-skeleton :loading="loading" :row-col="[1, 1, 1, 1]">
            <t-timeline mode="same" theme="dot">
              <t-timeline-item v-for="a in activity" :key="a.action" :label="a.time"><strong>{{ a.user }}</strong> {{ a.action }}</t-timeline-item>
            </t-timeline>
          </t-skeleton>
        </t-card>
        <t-card title="任务进度" :bordered="true">
          <t-skeleton :loading="loading" :row-col="[1, 1, 1, 1]">
            <div class="ug-stack">
              <div v-for="t in tasks" :key="t.title">
                <div class="ug-between ug-small"><span>{{ t.title }}</span><span class="ug-muted">{{ t.owner }}</span></div>
                <t-progress :percentage="t.progress" :status="t.progress >= 90 ? 'success' : 'active'" />
              </div>
            </div>
          </t-skeleton>
        </t-card>
      </div>
    </div>
  </div>
</template>

<style>
.ug-title { margin: 0 0 4px !important; }
.ug-small { font-size: 12px; }
.ug-mono { font-variant-numeric: tabular-nums; }
.ug-dash-charts { grid-template-columns: 2fr 1fr 1fr; }
.ug-dash-bottom { grid-template-columns: 3fr 2fr; }
@media (max-width: 1099px) { .ug-dash-charts, .ug-dash-bottom { grid-template-columns: minmax(0, 1fr); } }
.t-card .t-table { max-width: 100%; }
.t-table__content { overflow-x: auto; }
</style>
