// apps/skeleton/src/pages/Settings.svelte
<script lang="ts">
  import { Avatar, Dialog, Portal, Tabs } from "@skeletonlabs/skeleton-svelte"
  import team from "@ui-gallery/spec/mock/team.json"
  import sessions from "@ui-gallery/spec/mock/sessions.json"
  import invoices from "@ui-gallery/spec/mock/invoices.json"
  import plans from "@ui-gallery/spec/mock/plans.json"
  import Icon from "../lib/Icon.svelte"
  import StatusBadge from "../lib/StatusBadge.svelte"
  import { initials, money } from "../lib/format"
  import { toaster } from "../lib/toaster"

  const me = team[0]
  const currentPlan = plans.find((p) => p.recommended) ?? plans[0]

  let tab = $state("profile")
  let name = $state(me.name)
  let email = $state(me.email)
  let bio = $state("")
  let twoFactor = $state(true)
  let notif = $state({ orderEmail: true, orderPush: true, weekly: false, marketing: false, security: true })
  let inviteEmail = $state("")
  let inviteRole = $state("member")
  let members = $state([...team])
  let deleteOpen = $state(false)
  let confirmText = $state("")
  let saving = $state(false)

  const roles: Record<string, string> = { owner: "所有者", admin: "管理员", member: "成员", viewer: "只读" }

  async function save() {
    saving = true
    await new Promise((r) => setTimeout(r, 600))
    saving = false
    toaster.success({ title: "已保存", description: "个人资料已更新" })
  }
  function invite(event: SubmitEvent) {
    event.preventDefault()
    if (!inviteEmail.includes("@")) return
    members = [...members, { name: inviteEmail.split("@")[0], email: inviteEmail, role: inviteRole, lastActive: "已邀请" }]
    toaster.success({ title: "邀请已发送", description: inviteEmail })
    inviteEmail = ""
  }
  function removeMember(email: string) {
    members = members.filter((m) => m.email !== email)
    toaster.warning({ title: "成员已移除", description: email })
  }
  function deleteAccount() {
    deleteOpen = false
    toaster.error({ title: "账号已计划删除", description: "30 天内可恢复" })
  }
</script>

<header>
  <h1 class="h3">设置</h1>
  <p class="text-sm opacity-70">管理你的账号、团队与计费信息。</p>
</header>

<Tabs value={tab} onValueChange={(d) => (tab = d.value)} class="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6 items-start">
  <Tabs.List class="flex-nowrap overflow-x-auto whitespace-nowrap lg:overflow-visible lg:flex-col lg:items-stretch lg:border-0">
    <Tabs.Trigger value="profile" class="shrink-0 lg:justify-start gap-2"><Icon name="user" />个人资料</Tabs.Trigger>
    <Tabs.Trigger value="security" class="shrink-0 lg:justify-start gap-2"><Icon name="shield" />账号安全</Tabs.Trigger>
    <Tabs.Trigger value="notifications" class="shrink-0 lg:justify-start gap-2"><Icon name="bell" />通知</Tabs.Trigger>
    <Tabs.Trigger value="team" class="shrink-0 lg:justify-start gap-2"><Icon name="users" />团队</Tabs.Trigger>
    <Tabs.Trigger value="billing" class="shrink-0 lg:justify-start gap-2"><Icon name="credit-card" />计费</Tabs.Trigger>
    <Tabs.Indicator class="lg:hidden" />
  </Tabs.List>

  <div class="min-w-0">
    <Tabs.Content value="profile" class="space-y-4">
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-5">
        <h2 class="h5">个人资料</h2>
        <div class="flex items-center gap-4">
          <Avatar class="size-20"><Avatar.Fallback class="preset-filled-secondary-500 text-2xl">{initials(name)}</Avatar.Fallback></Avatar>
          <div class="space-y-2">
            <div class="flex gap-2">
              <button type="button" class="btn btn-sm preset-outlined-surface-500"><Icon name="upload" />上传头像</button>
              <button type="button" class="btn btn-sm hover:preset-tonal">移除</button>
            </div>
            <p class="text-xs opacity-60">支持 JPG、PNG，最大 2MB</p>
          </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <label class="label"><span class="label-text">姓名</span><input class="input" bind:value={name} /></label>
          <label class="label"><span class="label-text">邮箱</span><input class="input" type="email" bind:value={email} /></label>
          <label class="label"><span class="label-text">角色</span><input class="input" value={roles[me.role]} disabled /></label>
          <label class="label"><span class="label-text">时区</span>
            <select class="select"><option>Asia/Shanghai (UTC+8)</option><option>Asia/Tokyo (UTC+9)</option><option>UTC</option></select>
          </label>
        </div>
        <label class="label"><span class="label-text">个人简介</span><textarea class="textarea" rows="3" bind:value={bio} placeholder="介绍一下你自己…"></textarea></label>
        <footer class="flex justify-end gap-2">
          <button type="button" class="btn hover:preset-tonal">取消</button>
          <button type="button" class="btn preset-filled-primary-500" onclick={save} disabled={saving}>{#if saving}<Icon name="loader" class="animate-spin" />{/if}保存更改</button>
        </footer>
      </section>
    </Tabs.Content>

    <Tabs.Content value="security" class="space-y-4">
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-4">
        <h2 class="h5">修改密码</h2>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <label class="label"><span class="label-text">当前密码</span><input class="input" type="password" autocomplete="current-password" /></label>
          <label class="label"><span class="label-text">新密码</span><input class="input" type="password" autocomplete="new-password" /></label>
          <label class="label"><span class="label-text">确认新密码</span><input class="input" type="password" autocomplete="new-password" /></label>
        </div>
        <div class="flex justify-end"><button type="button" class="btn preset-filled-primary-500" onclick={() => toaster.success({ title: "密码已更新" })}>更新密码</button></div>
      </section>
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-3">
        <div class="flex items-center justify-between gap-4">
          <div>
            <h2 class="h5">两步验证</h2>
            <p class="text-sm opacity-70">登录时需要额外输入验证码，提升账号安全性。</p>
          </div>
          <input class="switch" type="checkbox" role="switch" bind:checked={twoFactor} aria-label="两步验证" />
        </div>
        {#if twoFactor}<div class="card preset-tonal-success p-3 text-sm flex items-center gap-2"><Icon name="circle-check" />已启用（验证器应用）</div>{/if}
      </section>
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-3">
        <h2 class="h5">活跃会话</h2>
        <ul class="divide-y divide-surface-200-800">
          {#each sessions as s (s.device)}
            <li class="py-3 flex items-center gap-3">
              <Icon name={s.device.includes("iPhone") || s.device.includes("Android") ? "smartphone" : "globe"} class="size-5 opacity-60" />
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium truncate">{s.device} {#if s.current}<span class="badge preset-tonal-success ml-1">当前</span>{/if}</p>
                <p class="text-xs opacity-60">{s.location} · {s.time}</p>
              </div>
              {#if !s.current}<button type="button" class="btn btn-sm preset-outlined-error-500" onclick={() => toaster.info({ title: "会话已注销", description: s.device })}>注销</button>{/if}
            </li>
          {/each}
        </ul>
      </section>
      <section class="card border-2 border-error-500 p-5 space-y-3">
        <h2 class="h5 text-error-500">危险区</h2>
        <p class="text-sm opacity-70">删除账号将永久移除所有数据，且无法恢复。</p>
        <button type="button" class="btn preset-filled-error-500" onclick={() => (deleteOpen = true)}><Icon name="trash" />删除账号</button>
      </section>
    </Tabs.Content>

    <Tabs.Content value="notifications" class="space-y-4">
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-1">
        <h2 class="h5 mb-3">通知偏好</h2>
        {#each [
          ["orderEmail", "订单邮件", "新订单、退款与支付失败时发送邮件"],
          ["orderPush", "订单推送", "浏览器与移动端即时推送"],
          ["weekly", "每周摘要", "每周一发送上周数据摘要"],
          ["marketing", "产品动态", "新功能与最佳实践"],
          ["security", "安全提醒", "异常登录与密码更改（建议开启）"],
        ] as const as [key, label, desc] (key)}
          <label class="flex items-center justify-between gap-4 py-3 border-b border-surface-200-800 last:border-0">
            <span><span class="block text-sm font-medium">{label}</span><span class="block text-xs opacity-60">{desc}</span></span>
            <input class="switch" type="checkbox" role="switch" bind:checked={notif[key]} />
          </label>
        {/each}
      </section>
    </Tabs.Content>

    <Tabs.Content value="team" class="space-y-4">
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-4">
        <h2 class="h5">邀请成员</h2>
        <form class="flex flex-col sm:flex-row gap-2" onsubmit={invite}>
          <input class="input flex-1" type="email" placeholder="colleague@example.com" bind:value={inviteEmail} required />
          <select class="select sm:w-32" bind:value={inviteRole}>
            <option value="admin">管理员</option><option value="member">成员</option><option value="viewer">只读</option>
          </select>
          <button type="submit" class="btn preset-filled-primary-500"><Icon name="send" />发送邀请</button>
        </form>
      </section>
      <section class="card bg-surface-50-950 border border-surface-200-800 overflow-hidden">
        <header class="p-4 border-b border-surface-200-800 flex items-center justify-between"><h2 class="h5">成员（{members.length}）</h2></header>
        <div class="table-wrap">
          <table class="table">
            <thead><tr><th>成员</th><th class="hidden sm:table-cell">角色</th><th class="hidden md:table-cell">最近活跃</th><th class="text-right">操作</th></tr></thead>
            <tbody class="[&>tr]:hover:preset-tonal-primary">
              {#each members as m (m.email)}
                <tr>
                  <td>
                    <div class="flex items-center gap-2">
                      <Avatar class="size-8"><Avatar.Fallback class="preset-filled-secondary-500 text-xs">{initials(m.name)}</Avatar.Fallback></Avatar>
                      <div class="min-w-0"><p class="font-medium truncate">{m.name}</p><p class="text-xs opacity-60 truncate">{m.email}</p></div>
                    </div>
                  </td>
                  <td class="hidden sm:table-cell"><span class="badge {m.role === 'owner' ? 'preset-filled-primary-500' : 'preset-tonal'}">{roles[m.role] ?? m.role}</span></td>
                  <td class="hidden md:table-cell opacity-70">{m.lastActive}</td>
                  <td class="text-right">
                    {#if m.role !== "owner"}<button type="button" class="btn btn-sm hover:preset-tonal-error" onclick={() => removeMember(m.email)}>移除</button>{/if}
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </section>
    </Tabs.Content>

    <Tabs.Content value="billing" class="space-y-4">
      <section class="card bg-surface-50-950 border border-surface-200-800 p-5 space-y-4">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 class="h5">当前套餐：{currentPlan.name}</h2>
            <p class="text-sm opacity-70">{currentPlan.price === null ? "联系销售" : `${money(currentPlan.price)} / 月`} · 下次扣费 {invoices[0].date}</p>
          </div>
          <button type="button" class="btn preset-outlined-surface-500">更换套餐</button>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
          {#each plans as p (p.name)}
            <div class="card p-4 border {p.name === currentPlan.name ? 'border-primary-500 preset-tonal-primary' : 'border-surface-200-800'} space-y-2">
              <div class="flex items-center justify-between"><span class="font-medium">{p.name}</span>{#if p.recommended}<span class="badge preset-filled-primary-500">推荐</span>{/if}</div>
              <p class="text-2xl font-bold">{p.price === null ? "定制" : money(p.price)}</p>
              <ul class="text-sm opacity-80 space-y-1">{#each p.features as f (f)}<li class="flex gap-2"><Icon name="check" class="size-4 text-success-500 shrink-0" />{f}</li>{/each}</ul>
            </div>
          {/each}
        </div>
      </section>
      <section class="card bg-surface-50-950 border border-surface-200-800 overflow-hidden">
        <header class="p-4 border-b border-surface-200-800"><h2 class="h5">发票</h2></header>
        <div class="table-wrap">
          <table class="table">
            <thead><tr><th>编号</th><th>日期</th><th>状态</th><th class="text-right">金额</th><th class="text-right"><span class="sr-only">下载</span></th></tr></thead>
            <tbody class="[&>tr]:hover:preset-tonal-primary">
              {#each invoices as inv (inv.id)}
                <tr>
                  <td class="font-mono text-xs">{inv.id}</td>
                  <td>{inv.date}</td>
                  <td><StatusBadge status={inv.status} /></td>
                  <td class="text-right tabular-nums">{money(inv.amount)}</td>
                  <td class="text-right"><button type="button" class="btn-icon min-w-10 min-h-10 hover:preset-tonal" aria-label="下载发票"><Icon name="download" /></button></td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </section>
    </Tabs.Content>
  </div>
</Tabs>

<Dialog open={deleteOpen} onOpenChange={(d) => (deleteOpen = d.open)} role="alertdialog">
  <Portal>
    <Dialog.Backdrop class="fixed inset-0 z-50 bg-surface-50-950/50" />
    <Dialog.Positioner class="fixed inset-0 z-50 grid place-items-center p-4">
      <Dialog.Content class="card bg-surface-50-950 p-6 w-full max-w-md space-y-4 shadow-xl">
        <Dialog.Title class="h5 text-error-500">删除账号</Dialog.Title>
        <Dialog.Description class="text-sm opacity-70">此操作不可撤销。请输入 <code class="code">DELETE</code> 以确认。</Dialog.Description>
        <input class="input" bind:value={confirmText} placeholder="DELETE" />
        <div class="flex justify-end gap-2">
          <Dialog.CloseTrigger class="btn preset-tonal">取消</Dialog.CloseTrigger>
          <button type="button" class="btn preset-filled-error-500" disabled={confirmText !== "DELETE"} onclick={deleteAccount}>永久删除</button>
        </div>
      </Dialog.Content>
    </Dialog.Positioner>
  </Portal>
</Dialog>

// apps/tdesign-vue-next/src/pages/Settings.vue
<script setup lang="ts">
import { computed, reactive, ref } from "vue"
import { MessagePlugin, type PrimaryTableCol, type TableRowData } from "tdesign-vue-next"
import team from "@ui-gallery/spec/mock/team.json"
import sessions from "@ui-gallery/spec/mock/sessions.json"
import plans from "@ui-gallery/spec/mock/plans.json"
import invoices from "@ui-gallery/spec/mock/invoices.json"
import Icon from "@/components/Icon.vue"
import { initials, roleLabel, statusLabel, statusTheme } from "@/pages/shared"

const tab = ref("profile")
const tabs = [
  { value: "profile", label: "个人资料", icon: "user" },
  { value: "security", label: "账号安全", icon: "shield" },
  { value: "notifications", label: "通知", icon: "bell" },
  { value: "team", label: "团队", icon: "users" },
  { value: "billing", label: "计费", icon: "credit-card" },
]

const profile = reactive({ name: team[0].name, bio: "", language: "zh-CN", timezone: "Asia/Shanghai" })
const languageOptions = [{ label: "简体中文", value: "zh-CN" }, { label: "English", value: "en-US" }, { label: "日本語", value: "ja-JP" }]
const timezoneOptions = ["Asia/Shanghai", "Asia/Tokyo", "Asia/Singapore", "Europe/London", "Europe/Berlin", "America/New_York", "America/Los_Angeles"].map((z) => ({ label: z, value: z }))

const password = reactive({ current: "", next: "", confirm: "" })
const twoFactor = ref(true)
const activeSessions = ref(sessions)

const notify = reactive<Record<string, boolean>>({ orders: true, refunds: true, digest: false, mentions: true, security: true, marketing: false })
const channel = ref("email")
const notifyGroups = [
  { title: "业务", items: [{ key: "orders", label: "新订单", desc: "有新订单创建时提醒" }, { key: "refunds", label: "退款申请", desc: "客户发起退款时提醒" }, { key: "digest", label: "每日摘要", desc: "每天早上 9 点汇总" }] },
  { title: "协作与安全", items: [{ key: "mentions", label: "@提及", desc: "有人在评论中提到你" }, { key: "security", label: "安全提醒", desc: "新设备登录、密码变更" }, { key: "marketing", label: "产品更新", desc: "新功能与活动通知" }] },
]

const members = ref(team.map((m) => ({ ...m })))
const invite = ref("")
const roleOptions = Object.entries(roleLabel).map(([value, label]) => ({ value, label }))
const memberColumns: PrimaryTableCol<TableRowData>[] = [
  { colKey: "name", title: "成员", width: 240 },
  { colKey: "role", title: "角色", width: 150 },
  { colKey: "lastActive", title: "最近活跃", width: 120 },
  { colKey: "op", title: "", width: 72, align: "right" },
]
function removeMember(email: string) {
  members.value = members.value.filter((m) => m.email !== email)
  MessagePlugin.success("成员已移除")
}
function sendInvite() {
  if (!/^\S+@\S+\.\S+$/.test(invite.value)) return MessagePlugin.error("请输入有效邮箱")
  MessagePlugin.success(`邀请已发送至 ${invite.value}`)
  invite.value = ""
}

const yearly = ref(false)
const currentPlan = plans.find((p) => p.recommended) ?? plans[0]
const invoiceColumns: PrimaryTableCol<TableRowData>[] = [
  { colKey: "id", title: "发票号", width: 120 },
  { colKey: "date", title: "日期", width: 120 },
  { colKey: "amount", title: "金额", width: 100, align: "right" },
  { colKey: "status", title: "状态", width: 100 },
  { colKey: "op", title: "", width: 80, align: "right" },
]
const priceOf = (p: (typeof plans)[number]) => (p.price === null ? "联系销售" : `¥${yearly.value ? Math.round(p.price * 10) : p.price}`)
const unit = computed(() => (yearly.value ? "/年" : "/月"))

const deleteOpen = ref(false)
const deleteText = ref("")
function deleteAccount() {
  deleteOpen.value = false
  deleteText.value = ""
  MessagePlugin.warning("删除请求已提交（演示）")
}
</script>

<template>
  <div class="ug-page">
    <div>
      <t-typography-title level="h4" class="ug-title">设置</t-typography-title>
      <span class="ug-muted">管理个人资料、安全、通知、团队与计费。</span>
    </div>

    <div class="ug-settings">
      <t-tabs v-model="tab" :placement="'left'" class="ug-settings-tabs ug-desktop-only">
        <t-tab-panel v-for="t in tabs" :key="t.value" :value="t.value"><template #label><span class="ug-row"><Icon :name="t.icon" />{{ t.label }}</span></template></t-tab-panel>
      </t-tabs>
      <t-tabs v-model="tab" class="ug-mobile-only ug-settings-tabs-top">
        <t-tab-panel v-for="t in tabs" :key="t.value" :value="t.value" :label="t.label" />
      </t-tabs>

      <div class="ug-settings-body">
        <template v-if="tab === 'profile'">
          <t-card :bordered="true" title="个人资料" subtitle="更新你的公开信息">
            <t-form label-align="top" :data="profile" @submit.prevent>
              <t-form-item label="头像">
                <div class="ug-row">
                  <t-avatar size="64px" shape="round">{{ initials(profile.name) }}</t-avatar>
                  <t-upload theme="custom" accept="image/*" :auto-upload="false"><t-button variant="outline" size="small"><template #icon><Icon name="upload" /></template>上传头像</t-button></t-upload>
                  <t-button variant="text" size="small" theme="danger">移除</t-button>
                </div>
              </t-form-item>
              <div class="ug-grid-2">
                <t-form-item label="姓名" name="name"><t-input v-model="profile.name" /></t-form-item>
                <t-form-item label="邮箱"><t-input :model-value="team[0].email" readonly /></t-form-item>
              </div>
              <t-form-item label="简介" name="bio" help="最多 160 字"><t-textarea v-model="profile.bio" :maxlength="160" placeholder="介绍一下你自己…" :autosize="{ minRows: 3 }" /></t-form-item>
              <div class="ug-grid-2">
                <t-form-item label="语言" name="language"><t-select v-model="profile.language" :options="languageOptions" /></t-form-item>
                <t-form-item label="时区" name="timezone"><t-select v-model="profile.timezone" :options="timezoneOptions" filterable /></t-form-item>
              </div>
              <t-space><t-button theme="primary" @click="MessagePlugin.success('资料已保存')">保存更改</t-button><t-button variant="outline">取消</t-button></t-space>
            </t-form>
          </t-card>
        </template>

        <template v-else-if="tab === 'security'">
          <t-card :bordered="true" title="修改密码">
            <t-form label-align="top" :data="password" @submit.prevent>
              <t-form-item label="当前密码" name="current"><t-input v-model="password.current" type="password" /></t-form-item>
              <div class="ug-grid-2">
                <t-form-item label="新密码" name="next" help="至少 8 位，含字母与数字"><t-input v-model="password.next" type="password" /></t-form-item>
                <t-form-item label="确认新密码" name="confirm" :status="password.confirm && password.confirm !== password.next ? 'error' : undefined" :tips="password.confirm && password.confirm !== password.next ? '两次输入不一致' : ''"><t-input v-model="password.confirm" type="password" /></t-form-item>
              </div>
              <t-button theme="primary">更新密码</t-button>
            </t-form>
          </t-card>
          <t-card :bordered="true" title="两步验证">
            <template #actions><t-switch v-model="twoFactor" /></template>
            <div class="ug-2fa">
              <div class="ug-qr"><t-qrcode value="otpauth://totp/AcmeConsole:demo" :size="120" :status="twoFactor ? 'active' : 'expired'" /></div>
              <div>
                <p>使用身份验证器扫描二维码，或手动输入密钥。</p>
                <t-input value="ACME-DEMO-KEY" readonly class="ug-2fa-key"><template #suffix-icon><Icon name="copy" /></template></t-input>
                <t-tag :theme="twoFactor ? 'success' : 'warning'" variant="light" size="small">{{ twoFactor ? "已启用" : "未启用" }}</t-tag>
              </div>
            </div>
          </t-card>
          <t-card :bordered="true" title="活跃会话">
            <t-list :split="true">
              <t-list-item v-for="s in activeSessions" :key="s.device">
                <t-list-item-meta :title="s.device" :description="`${s.location} · ${s.time}`">
                  <template #image><t-avatar shape="round"><Icon :name="s.device.includes('iPhone') ? 'smartphone' : 'monitor'" /></t-avatar></template>
                </t-list-item-meta>
                <template #action>
                  <t-tag v-if="s.current" theme="success" variant="light" size="small">当前设备</t-tag>
                  <t-button v-else variant="outline" size="small" @click="activeSessions = activeSessions.filter((x) => x !== s)">注销</t-button>
                </template>
              </t-list-item>
            </t-list>
          </t-card>
        </template>

        <template v-else-if="tab === 'notifications'">
          <t-card :bordered="true" title="通知渠道">
            <t-radio-group v-model="channel" variant="default-filled">
              <t-radio-button value="email">邮件</t-radio-button>
              <t-radio-button value="push">推送</t-radio-button>
              <t-radio-button value="inapp">站内</t-radio-button>
            </t-radio-group>
          </t-card>
          <t-card v-for="g in notifyGroups" :key="g.title" :bordered="true" :title="g.title">
            <t-list :split="true">
              <t-list-item v-for="i in g.items" :key="i.key">
                <t-list-item-meta :title="i.label" :description="i.desc" />
                <template #action><t-switch v-model="notify[i.key]" /></template>
              </t-list-item>
            </t-list>
          </t-card>
        </template>

        <template v-else-if="tab === 'team'">
          <t-card :bordered="true" title="邀请成员">
            <div class="ug-invite">
              <t-input v-model="invite" placeholder="colleague@company.com" clearable><template #prefix-icon><Icon name="mail" /></template></t-input>
              <t-button theme="primary" @click="sendInvite"><template #icon><Icon name="send" /></template>发送邀请</t-button>
            </div>
          </t-card>
          <t-card :bordered="true" :title="`成员（${members.length}）`">
            <t-table row-key="email" :data="members" :columns="memberColumns" hover table-layout="fixed">
              <template #name="{ row }"><div class="ug-row"><t-avatar size="small">{{ initials(row.name) }}</t-avatar><div class="ug-ellipsis"><div>{{ row.name }}</div><div class="ug-muted ug-small">{{ row.email }}</div></div></div></template>
              <template #role="{ row }"><t-select v-model="row.role" :options="roleOptions" size="small" :disabled="row.role === 'owner'" /></template>
              <template #op="{ row }">
                <t-popconfirm content="确定移除该成员吗？" theme="danger" @confirm="removeMember(row.email)">
                  <t-button variant="text" size="small" shape="square" theme="danger" :disabled="row.role === 'owner'" aria-label="移除"><Icon name="trash" /></t-button>
                </t-popconfirm>
              </template>
            </t-table>
          </t-card>
        </template>

        <template v-else-if="tab === 'billing'">
          <t-card :bordered="true" title="当前计划">
            <template #actions><t-tag theme="primary" variant="light">{{ currentPlan.name }}</t-tag></template>
            <div class="ug-between">
              <div><div class="ug-price">¥{{ currentPlan.price }}<span class="ug-muted ug-small">/月</span></div><span class="ug-muted">下次扣款 {{ invoices[0].date }}</span></div>
              <t-space><t-button variant="outline">管理付款方式</t-button><t-button theme="primary">升级</t-button></t-space>
            </div>
          </t-card>
          <div class="ug-between">
            <span class="ug-muted">按 {{ yearly ? "年" : "月" }} 计费</span>
            <t-switch v-model="yearly" :label="['年付', '月付']" size="large" />
          </div>
          <div class="ug-grid-3">
            <t-card v-for="p in plans" :key="p.name" :bordered="true" :class="{ 'ug-plan--rec': p.recommended }" :title="p.name">
              <template v-if="p.recommended" #actions><t-tag theme="primary" size="small">推荐</t-tag></template>
              <div class="ug-price">{{ priceOf(p) }}<span v-if="p.price !== null" class="ug-muted ug-small">{{ unit }}</span></div>
              <ul class="ug-features"><li v-for="f in p.features" :key="f" class="ug-row"><Icon name="check" class="ug-check" />{{ f }}</li></ul>
              <t-button block :theme="p.recommended ? 'primary' : 'default'" :variant="p.recommended ? 'base' : 'outline'">{{ p.name === currentPlan.name ? "当前计划" : p.price === null ? "联系我们" : "选择" }}</t-button>
            </t-card>
          </div>
          <t-card :bordered="true" title="发票">
            <t-table row-key="id" :data="invoices" :columns="invoiceColumns" size="small" hover table-layout="fixed">
              <template #amount="{ row }"><span class="ug-mono">¥{{ row.amount }}</span></template>
              <template #status="{ row }"><t-tag :theme="statusTheme[row.status]" variant="light-outline" size="small">{{ statusLabel[row.status] }}</t-tag></template>
              <template #op><t-button variant="text" size="small" shape="square" aria-label="下载"><Icon name="download" /></t-button></template>
            </t-table>
          </t-card>
        </template>

        <t-card :bordered="true" title="危险区" class="ug-danger">
          <div class="ug-between">
            <div><div>删除账号</div><span class="ug-muted ug-small">删除后所有数据将被永久移除，无法恢复。</span></div>
            <t-button theme="danger" variant="outline" @click="deleteOpen = true"><template #icon><Icon name="trash" /></template>删除账号</t-button>
          </div>
        </t-card>
      </div>
    </div>

    <t-dialog v-model:visible="deleteOpen" theme="danger" header="确认删除账号" :confirm-btn="{ content: '永久删除', theme: 'danger', disabled: deleteText !== 'DELETE' }" cancel-btn="取消" @confirm="deleteAccount">
      <p class="ug-muted">此操作不可逆。请输入 <b>DELETE</b> 以确认。</p>
      <t-input v-model="deleteText" placeholder="DELETE" style="margin-top: 12px" />
    </t-dialog>
  </div>
</template>

<style>
.ug-settings { display: grid; grid-template-columns: 200px minmax(0, 1fr); gap: 16px; align-items: start; }
.ug-settings-tabs .t-tabs__nav { min-width: 200px; }
.ug-settings-body { display: flex; flex-direction: column; gap: 16px; min-width: 0; }
.ug-2fa { display: flex; gap: 20px; flex-wrap: wrap; align-items: flex-start; }
.ug-2fa-key { margin: 8px 0; max-width: 260px; }
.ug-invite { display: flex; gap: 8px; }
.ug-price { font-size: 28px; font-weight: 600; }
.ug-features { list-style: none; padding: 0; margin: 12px 0 16px; display: grid; gap: 8px; }
.ug-check { color: var(--td-success-color); }
.ug-plan--rec { border-color: var(--td-brand-color); }
.ug-danger { border-color: var(--td-error-color-3); }
.ug-danger .t-card__title { color: var(--td-error-color); }
@media (max-width: 767px) {
  .ug-settings { grid-template-columns: minmax(0, 1fr); }
  .ug-invite { flex-direction: column; }
}
</style>
