// apps/ant-design-vue/src/pages/dashboard.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { use } from "echarts/core"
import { CanvasRenderer } from "echarts/renderers"
import { LineChart, BarChart, PieChart } from "echarts/charts"
import { GridComponent, TooltipComponent, LegendComponent } from "echarts/components"
import VChart from "vue-echarts"
import stats from "@ui-gallery/spec/mock/stats.json"
import series from "@ui-gallery/spec/mock/series.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import activity from "@ui-gallery/spec/mock/activity.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import { PageHeader, Sparkline, statusColor, statusLabel, initials, useMobile } from "./shared"
const mobile = useMobile()
use([CanvasRenderer, LineChart, BarChart, PieChart, GridComponent, TooltipComponent, LegendComponent])
const loading = ref(true)
setTimeout(() => { if (!new URLSearchParams(location.search).has("loading")) loading.value = false }, 600)
const lineOption = computed(() => ({ animation: false, tooltip: { trigger: "axis" }, legend: { data: ["收入", "订单"] }, xAxis: { type: "category", data: series.months }, yAxis: { type: "value" }, series: [{ name: "收入", type: "line", data: series.revenue, smooth: true }, { name: "订单", type: "line", data: series.orders, smooth: true }] }))
const barOption = computed(() => ({ animation: false, tooltip: {}, xAxis: { type: "category", data: series.months }, yAxis: { type: "value" }, series: [{ type: "bar", data: series.orders }] }))
const pieOption = computed(() => ({ animation: false, tooltip: {}, legend: { bottom: 0 }, series: [{ type: "pie", radius: ["45%", "70%"], data: series.byChannel }] }))
</script>
<template>
  <div class="page">
    <PageHeader title="仪表盘" description="欢迎回来，林晓。这里是今天的业务概况。" />
    <a-skeleton v-if="loading" active :paragraph="{ rows: 8 }" />
    <template v-else>
      <div class="card-grid">
        <a-card v-for="item in stats" :key="item.key"><a-statistic :title="item.label" :value="item.value" :precision="item.unit === '%' ? 1 : 0" :prefix="item.unit === 'CNY' ? '¥' : undefined" :suffix="item.unit === '%' ? '%' : undefined" /><a-tag :color="item.delta > 0 ? 'success' : 'error'">{{ item.delta > 0 ? '↑' : '↓' }} {{ Math.abs(item.delta) }}%</a-tag><Sparkline :values="item.trend" /></a-card>
      </div>
      <div class="wide-grid section"><a-card title="收入趋势"><VChart :option="lineOption" autoresize style="height: 300px" /></a-card><a-card title="渠道分布"><VChart :option="pieOption" autoresize style="height: 300px" /></a-card></div>
      <div class="wide-grid section"><a-card title="订单趋势"><VChart :option="barOption" autoresize style="height: 280px" /></a-card><a-card title="任务进度"><div v-for="task in tasks" :key="task.title" class="task-row"><div><span>{{ task.title }}</span><span class="muted">{{ task.owner }}</span></div><a-progress :percent="task.progress" size="small" /></div></a-card></div>
      <div class="wide-grid section"><a-card title="最近订单"><a-list v-if="mobile" :data-source="orders.slice(0, 5)" class="order-list"><template #renderItem="{ item }"><a-list-item><a-list-item-meta :title="`${item.id} · ¥${item.amount.toLocaleString()}`" :description="item.customer"><template #avatar><a-avatar>{{ initials(item.customer) }}</a-avatar></template></a-list-item-meta><a-tag :color="statusColor[item.status]">{{ statusLabel[item.status] }}</a-tag></a-list-item></template></a-list><div v-else class="table-wrap"><a-table :data-source="orders.slice(0, 5)" :pagination="false" :scroll="{ x: 560 }" row-key="id"><a-table-column title="订单" data-index="id" /><a-table-column title="客户" data-index="customer"><template #default="{ record }"><a-avatar size="small">{{ initials(record.customer) }}</a-avatar> {{ record.customer }}</template></a-table-column><a-table-column title="状态"><template #default="{ record }"><a-tag :color="statusColor[record.status]">{{ statusLabel[record.status] }}</a-tag></template></a-table-column><a-table-column title="金额" data-index="amount" align="right"><template #default="{ record }">¥{{ record.amount.toLocaleString() }}</template></a-table-column></a-table></div></a-card><a-card title="团队动态"><a-timeline><a-timeline-item v-for="item in activity" :key="item.time"><strong>{{ item.user }}</strong> {{ item.action }}<div class="muted">{{ item.time }}</div></a-timeline-item></a-timeline></a-card></div>
      <a-card class="section"><a-tabs><a-tab-pane key="day" tab="日">今日数据已同步。</a-tab-pane><a-tab-pane key="week" tab="周">本周数据已同步。</a-tab-pane><a-tab-pane key="month" tab="月">本月数据已同步。</a-tab-pane></a-tabs></a-card>
    </template>
  </div>
</template>
<style scoped>.task-row { margin-bottom: 16px; }.task-row > div { display:flex; justify-content:space-between; margin-bottom: 6px; }</style>

// apps/antd/src/pages/dashboard.tsx
import { useEffect, useState } from "react"
import {
  Button,
  Card,
  Col,
  Dropdown,
  Flex,
  List,
  Progress,
  Row,
  Skeleton,
  Space,
  Statistic,
  Table,
  Tabs,
  Tag,
  Timeline,
  Typography,
} from "antd"
import {
  LineChart as ReLineChart,
  Line,
  BarChart as ReBarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  Tooltip as ChartTooltip,
  XAxis,
  YAxis,
} from "recharts"
import stats from "@ui-gallery/spec/mock/stats.json"
import series from "@ui-gallery/spec/mock/series.json"
import orders from "@ui-gallery/spec/mock/orders.json"
import activity from "@ui-gallery/spec/mock/activity.json"
import tasks from "@ui-gallery/spec/mock/tasks.json"
import { Icon } from "@/icons"
import {
  PageHeader,
  avatar,
  statusColor,
  statusLabel,
  type Order,
} from "@/pages/shared"
import { Link } from "react-router-dom"
import { theme } from "antd"

function orderColumns(): Array<Record<string, unknown>> {
  return [
    {
      title: "订单号",
      dataIndex: "id",
      sorter: (a: Order, b: Order) => a.id.localeCompare(b.id),
    },
    {
      title: "客户",
      dataIndex: "customer",
      render: (value: string) => (
        <Space>
          {avatar(value)}
          {value}
        </Space>
      ),
    },
    {
      title: "状态",
      dataIndex: "status",
      render: (value: string) => (
        <Tag color={statusColor[value]}>{statusLabel[value]}</Tag>
      ),
    },
    {
      title: "金额",
      dataIndex: "amount",
      align: "right",
      render: (value: number) => `¥${value.toLocaleString()}`,
    },
    {
      title: "操作",
      key: "action",
      fixed: "right",
      width: 72,
      render: () => (
        <Dropdown
          menu={{
            items: [
              { key: "view", label: "查看详情" },
              { key: "edit", label: "编辑" },
            ],
          }}
        >
          <Button
            type="text"
            icon={<Icon name="more-horizontal" />}
            aria-label="更多操作"
          />
        </Dropdown>
      ),
    },
  ]
}

export function DashboardPage() {
  const [loading, setLoading] = useState(true)
  const [period, setPeriod] = useState("month")
  const { token } = theme.useToken()
  useEffect(() => {
    if (!loading) return
    const timer = window.setTimeout(() => setLoading(false), 600)
    return () => window.clearTimeout(timer)
  }, [loading])
  const periodTabs = (
    <Tabs
      size="small"
      activeKey={period}
      onChange={setPeriod}
      items={[
        { key: "day", label: "日" },
        { key: "week", label: "周" },
        { key: "month", label: "月" },
      ]}
    />
  )
  const header = (
    <PageHeader
      title="仪表盘"
      description="查看业务健康度与团队进展。"
      extra={
        <Space wrap>
          {periodTabs}
          <Button
            icon={<Icon name="refresh" />}
            loading={loading}
            onClick={() => setLoading(true)}
          >
            刷新
          </Button>
        </Space>
      }
    />
  )
  if (loading)
    return (
      <>
        {header}
        <Row gutter={[16, 16]}>
          {stats.map((stat) => (
            <Col xs={24} sm={12} xl={6} key={stat.key}>
              <Card>
                <Skeleton active paragraph={{ rows: 2 }} />
              </Card>
            </Col>
          ))}
        </Row>
        <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
          <Col xs={24} xl={16}>
            <Card>
              <Skeleton active paragraph={{ rows: 6 }} />
            </Card>
          </Col>
          <Col xs={24} xl={8}>
            <Card>
              <Skeleton active paragraph={{ rows: 6 }} />
            </Card>
          </Col>
        </Row>
        <Card style={{ marginTop: 16 }}>
          <Skeleton active paragraph={{ rows: 4 }} />
        </Card>
      </>
    )
  const divisor = period === "day" ? 30 : period === "week" ? 4 : 1
  const lineData = series.months.map((month, index) => ({
    month,
    revenue: Math.round(series.revenue[index] / divisor),
    orders: Math.round(series.orders[index] / divisor),
  }))
  return (
    <>
      {header}
      <Row gutter={[16, 16]}>
        {stats.map((stat) => (
          <Col xs={24} sm={12} xl={6} key={stat.key}>
            <Card>
              <Statistic
                title={stat.label}
                value={stat.value}
                suffix={stat.unit === "CNY" ? "元" : stat.unit}
              />
              <Tag
                color={stat.delta >= 0 ? "success" : "error"}
                icon={
                  <Icon name={stat.delta >= 0 ? "arrow-up" : "arrow-down"} />
                }
              >
                {Math.abs(stat.delta)}%
              </Tag>
              <div className="mini-chart">
                <ResponsiveContainer>
                  <ReLineChart
                    data={stat.trend.map((value, index) => ({ index, value }))}
                  >
                    <Line
                      dataKey="value"
                      stroke={
                        stat.delta >= 0 ? token.colorSuccess : token.colorError
                      }
                      dot={false}
                      isAnimationActive={false}
                    />
                  </ReLineChart>
                </ResponsiveContainer>
              </div>
            </Card>
          </Col>
        ))}
      </Row>
      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        <Col xs={24} xl={16}>
          <Card title="业务趋势">
            <div className="chart">
              <ResponsiveContainer>
                <ReLineChart data={lineData}>
                  <XAxis dataKey="month" />
                  <YAxis />
                  <ChartTooltip />
                  <Line
                    dataKey="revenue"
                    stroke={token.colorPrimary}
                    strokeWidth={3}
                    isAnimationActive={false}
                  />
                  <Line
                    dataKey="orders"
                    stroke={token.colorSuccess}
                    isAnimationActive={false}
                  />
                </ReLineChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </Col>
        <Col xs={24} xl={8}>
          <Card title="渠道分布">
            <div className="chart">
              <ResponsiveContainer>
                <PieChart>
                  <Pie
                    data={series.byChannel}
                    dataKey="value"
                    nameKey="name"
                    outerRadius={90}
                    label
                    isAnimationActive={false}
                  >
                    {series.byChannel.map((entry, index) => (
                      <Cell
                        key={entry.name}
                        fill={
                          [
                            token.colorPrimary,
                            token.colorSuccess,
                            token.colorWarning,
                            token.colorError,
                          ][index]
                        }
                      />
                    ))}
                  </Pie>
                  <ChartTooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </Col>
      </Row>
      <Card title="订单趋势" style={{ marginTop: 16 }}>
        <div className="chart">
          <ResponsiveContainer>
            <ReBarChart data={lineData}>
              <XAxis dataKey="month" />
              <YAxis />
              <ChartTooltip />
              <Bar
                dataKey="orders"
                fill={token.colorPrimary}
                isAnimationActive={false}
              />
            </ReBarChart>
          </ResponsiveContainer>
        </div>
      </Card>
      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        <Col xs={24} xl={15}>
          <Card title="最近订单" extra={<Link to="/orders">查看全部</Link>}>
            <Table
              rowKey="id"
              pagination={false}
              scroll={{ x: "max-content" }}
              dataSource={orders.slice(0, 5)}
              columns={orderColumns() as never}
            />
          </Card>
        </Col>
        <Col xs={24} xl={9}>
          <Card title="团队动态">
            <Timeline
              items={activity.slice(0, 5).map((item) => ({
                children: (
                  <>
                    <b>{item.user}</b> {item.action}
                    <Typography.Text
                      type="secondary"
                      style={{ display: "block" }}
                    >
                      {item.time}
                    </Typography.Text>
                  </>
                ),
              }))}
            />
          </Card>
        </Col>
      </Row>
      <Card title="任务进度" style={{ marginTop: 16 }}>
        <List
          dataSource={tasks}
          renderItem={(task) => (
            <List.Item>
              <Flex vertical style={{ width: "100%" }}>
                <Flex justify="space-between">
                  <span>{task.title}</span>
                  <Typography.Text type="secondary">
                    {task.owner}
                  </Typography.Text>
                </Flex>
                <Progress percent={task.progress} />
              </Flex>
            </List.Item>
          )}
        />
      </Card>
    </>
  )
}
