// apps/primereact/src/layouts/app-shell.tsx
import { useRef, useState, type ReactNode } from "react"
import { Link, useLocation, useNavigate } from "react-router-dom"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import { Avatar } from "primereact/avatar"
import { Badge } from "primereact/badge"
import { Button } from "primereact/button"
import { InputText } from "primereact/inputtext"
import { Menu } from "primereact/menu"
import { OverlayPanel } from "primereact/overlaypanel"
import { PanelMenu } from "primereact/panelmenu"
import { Sidebar } from "primereact/sidebar"
import { BreadCrumb } from "primereact/breadcrumb"
import { Icon, menuIcon } from "@/components/icon"

function Brand() { return <Link to="/" className="hit flex align-items-center gap-2 no-underline font-semibold text-color"><span className="flex align-items-center justify-content-center border-round bg-primary text-primary-contrast" style={{ width: 32, height: 32 }}>A</span><span>Acme Console</span></Link> }
export function AppShell({ children }: { children: ReactNode }) {
  const location = useLocation(), navigate = useNavigate()
  const [drawer, setDrawer] = useState(false), [collapsed, setCollapsed] = useState(false)
  const notificationsRef = useRef<OverlayPanel>(null)
  const profileRef = useRef<Menu>(null)
  const themeParam = new URLSearchParams(location.search).get("theme")
  const theme = themeParam ?? (document.documentElement.classList.contains("dark") ? "dark" : "light")
  const current = nav.find((item) => item.path === location.pathname)?.label ?? "仪表盘"
  const themeToggle = () => {
    const next = theme === "dark" ? "light" : "dark"
    const params = new URLSearchParams(window.location.search); params.set("theme", next)
    navigate(`${location.pathname}?${params.toString()}`)
  }
  const model = nav.map((item) => ({ label: item.label, icon: menuIcon(item.icon), badge: item.badge, template: () => <Link to={item.path} onClick={() => setDrawer(false)} aria-current={location.pathname === item.path ? "page" : undefined} className={`flex align-items-center gap-2 p-menuitem-link no-underline ${location.pathname === item.path ? "app-nav-active" : ""}`}><Icon name={item.icon} /><span>{item.label}</span>{item.badge ? <Badge value={item.badge} className="ml-auto" /> : null}</Link> }))
  const menu = [{ label: "账户设置", icon: menuIcon("settings"), command: () => navigate("/settings") }, { label: "帮助中心", icon: menuIcon("circle-help") }, { separator: true }, { label: "退出登录", icon: menuIcon("log-out") }]
  const side = <div className="h-full flex flex-column p-3"><div className="flex align-items-center justify-content-between gap-2"><Brand /><Button text rounded icon={<Icon name="chevron-left" />} aria-label="折叠侧边栏" className="hidden md:inline-flex flex-shrink-0" onClick={() => setCollapsed(true)} /></div><div className="mt-4 flex-1 app-nav"><p className="text-xs uppercase muted px-2">工作区</p><PanelMenu model={model} className="border-none" /></div><Link to="/settings" className="app-nav-link flex align-items-center gap-2 p-2 no-underline text-color"><Avatar label="林" shape="circle" /><span>林晓</span></Link></div>
  return <div className="flex min-h-screen">
    <aside className={`app-aside hidden md:block flex-shrink-0 surface-section border-right-1 surface-border transition-duration-200 ${collapsed ? "w-5rem" : "w-18rem"}`}>
      {collapsed ? <div className="p-3 flex flex-column align-items-center gap-4 app-nav"><Button text rounded icon={<Icon name="chevron-right" />} aria-label="展开侧边栏" onClick={() => setCollapsed(false)} /><Link to="/" className="app-nav-link"><Avatar label="A" shape="circle" /></Link><PanelMenu model={model.map((x) => ({ ...x, template: () => <Link to={nav.find((n) => n.label === x.label)?.path ?? "/"} aria-label={x.label} className={`app-nav-link flex justify-content-center p-menuitem-link ${location.pathname === nav.find((n) => n.label === x.label)?.path ? "app-nav-active" : ""}`}><Icon name={nav.find((n) => n.label === x.label)?.icon ?? "grid"} /></Link> }))} /></div> : side}
    </aside>
    <Sidebar visible={drawer} onHide={() => setDrawer(false)} position="left" className="w-18rem">{side}</Sidebar>
    <div className="flex-1 min-w-0">
      <header style={{ borderColor: "var(--surface-border)" }} className="sticky top-0 z-5 surface-card border-bottom-1 px-3 md:px-4 py-3 flex align-items-center gap-2">
        <Button text icon={<Icon name="menu" />} className="md:hidden" onClick={() => setDrawer(true)} />
        <BreadCrumb model={[{ label: current }]} home={{ template: () => <Link to="/" className="hit no-underline text-color bg-transparent">Acme Console</Link> }} className="hidden md:flex border-none p-0 bg-transparent" />
        <div className="ml-auto flex align-items-center gap-2">
          <span className="p-input-icon-left hidden md:inline-flex"><Icon name="search" /><InputText placeholder="搜索..." className="w-14rem" /></span>
          <Button text rounded icon={<Icon name="bell" />} onClick={(event) => notificationsRef.current?.toggle(event)} badge="2" />
          <OverlayPanel ref={notificationsRef}><div style={{ width: 260 }}><strong>通知</strong>{notifications.map((item) => <div className="py-2 border-bottom-1 surface-border" key={item.title}><div className="text-sm">{item.title}</div><small className="muted">{item.time}</small></div>)}</div></OverlayPanel>
          <Button text rounded icon={<Icon name={theme === "dark" ? "sun" : "moon"} />} onClick={themeToggle} />
          <Button text rounded icon={<Avatar label="林" shape="circle" />} onClick={(event) => profileRef.current?.toggle(event)} />
          <Menu ref={profileRef} popup model={menu} />
        </div>
      </header>
      <main className="page-main">{children}</main>
    </div>
  </div>
}

// apps/primevue/src/layouts/AppShell.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { RouterLink, RouterView, useRoute, useRouter } from "vue-router"
import Button from "primevue/button"
import Avatar from "primevue/avatar"
import Badge from "primevue/badge"
import OverlayBadge from "primevue/overlaybadge"
import Breadcrumb from "primevue/breadcrumb"
import Drawer from "primevue/drawer"
import IconField from "primevue/iconfield"
import InputIcon from "primevue/inputicon"
import InputText from "primevue/inputtext"
import Menu from "primevue/menu"
import Popover from "primevue/popover"
import Divider from "primevue/divider"
import nav from "@ui-gallery/spec/mock/nav.json"
import notifications from "@ui-gallery/spec/mock/notifications.json"
import AppIcon from "@/icons/AppIcon.vue"
import type { IconName } from "@/icons/names"
import { toggleTheme } from "@/settings"

const route = useRoute()
const router = useRouter()
const collapsed = ref(false)
const mobileOpen = ref(false)
const dark = ref(document.documentElement.classList.contains("dark"))
const current = computed(() => nav.find((item) => item.path === route.path)?.label ?? "仪表盘")
const crumbs = computed(() => [{ label: current.value }])
const home = { label: "Acme Console", route: "/" }
const unread = notifications.filter((n) => n.unread).length

const userMenu = ref<InstanceType<typeof Menu> | null>(null)
const userItems = [
  { label: "个人资料", icon: "user", command: () => router.push("/settings") },
  { label: "账户设置", icon: "settings", command: () => router.push("/settings") },
  { label: "计费", icon: "credit-card", command: () => router.push("/settings") },
  { separator: true },
  { label: "退出登录", icon: "log-out", command: () => router.push("/login") },
]
const bell = ref<InstanceType<typeof Popover> | null>(null)

function onToggleTheme() {
  toggleTheme()
  dark.value = document.documentElement.classList.contains("dark")
}
</script>

<template>
  <div class="shell" :class="{ 'shell--collapsed': collapsed }">
    <aside class="shell__sidebar desktop-only">
      <RouterLink to="/" class="shell__brand">
        <span class="shell__logo">A</span>
        <span v-if="!collapsed" class="font-semibold">Acme Console</span>
      </RouterLink>
      <nav class="shell__nav">
        <div v-if="!collapsed" class="shell__group">工作区</div>
        <RouterLink
          v-for="item in nav"
          :key="item.key"
          :to="item.path"
          class="shell__link"
          :class="{ 'shell__link--active': route.path === item.path }"
          v-tooltip.right="collapsed ? item.label : undefined"
        >
          <AppIcon :name="item.icon as IconName" :size="18" />
          <span v-if="!collapsed" class="flex-1 truncate">{{ item.label }}</span>
          <Badge v-if="!collapsed && item.badge" :value="item.badge" severity="secondary" size="small" />
        </RouterLink>
      </nav>
      <div class="shell__footer">
        <Button
          text
          severity="secondary"
          :aria-label="collapsed ? '展开侧边栏' : '折叠侧边栏'"
          @click="collapsed = !collapsed"
        >
          <template #icon><AppIcon :name="collapsed ? 'chevrons-right' : 'chevrons-left'" /></template>
        </Button>
        <RouterLink to="/settings" class="shell__user">
          <Avatar label="林" shape="circle" />
          <div v-if="!collapsed" class="min-w-0">
            <div class="text-sm font-medium truncate">林晓</div>
            <div class="text-xs muted truncate">m0@acme.dev</div>
          </div>
        </RouterLink>
      </div>
    </aside>

    <Drawer v-model:visible="mobileOpen" header="导航菜单" class="shell__drawer" style="width: 288px">
      <template #header>
        <RouterLink to="/" class="shell__brand" @click="mobileOpen = false">
          <span class="shell__logo">A</span><span class="font-semibold">Acme Console</span>
        </RouterLink>
      </template>
      <nav class="shell__nav">
        <RouterLink
          v-for="item in nav"
          :key="item.key"
          :to="item.path"
          class="shell__link"
          :class="{ 'shell__link--active': route.path === item.path }"
          @click="mobileOpen = false"
        >
          <AppIcon :name="item.icon as IconName" :size="18" />
          <span class="flex-1">{{ item.label }}</span>
          <Badge v-if="item.badge" :value="item.badge" severity="secondary" size="small" />
        </RouterLink>
      </nav>
    </Drawer>

    <div class="shell__main">
      <header class="shell__topbar">
        <Button text severity="secondary" class="mobile-only" aria-label="打开菜单" @click="mobileOpen = true"><template #icon><AppIcon name="menu" :size="18" /></template></Button>
        <Breadcrumb :home="home" :model="crumbs" class="shell__crumbs desktop-only">
          <template #item="{ item, props }">
            <RouterLink v-if="item.route" :to="item.route" v-bind="props.action">{{ item.label }}</RouterLink>
            <span v-else class="font-medium">{{ item.label }}</span>
          </template>
        </Breadcrumb>
        <div class="flex items-center gap-2" style="margin-left: auto">
          <IconField class="desktop-only">
            <InputIcon><AppIcon name="search" /></InputIcon>
            <InputText placeholder="搜索..." size="small" style="width: 220px" />
          </IconField>
          <OverlayBadge :value="unread" severity="danger" size="small">
            <Button text severity="secondary" rounded aria-label="通知" @click="bell?.toggle($event)"><template #icon><AppIcon name="bell" :size="18" /></template></Button>
          </OverlayBadge>
          <Popover ref="bell">
            <div style="width: 300px">
              <div class="flex items-center justify-between mb-2">
                <span class="font-semibold">通知</span><span class="text-xs muted">{{ unread }} 条未读</span>
              </div>
              <template v-for="(n, i) in notifications" :key="n.title">
                <Divider v-if="i" class="p-0" style="margin: 8px 0" />
                <div class="flex items-start gap-2">
                  <span class="shell__dot" :class="{ 'shell__dot--unread': n.unread }" />
                  <div class="min-w-0"><div class="text-sm">{{ n.title }}</div><div class="text-xs muted">{{ n.time }}</div></div>
                </div>
              </template>
            </div>
          </Popover>
          <Button text severity="secondary" rounded aria-label="切换主题" v-tooltip.bottom="'切换主题'" @click="onToggleTheme"><template #icon><AppIcon :name="dark ? 'sun' : 'moon'" :size="18" /></template></Button>
          <Button text rounded severity="secondary" class="p-0" aria-label="用户菜单" aria-haspopup="true" @click="userMenu?.toggle($event)">
            <Avatar label="林" shape="circle" />
          </Button>
          <Menu ref="userMenu" :model="userItems" popup><template #itemicon="{ item, class: iconClass }"><AppIcon :name="item.icon as IconName" :class="iconClass" /></template></Menu>
        </div>
      </header>
      <main class="shell__content"><RouterView /></main>
    </div>
  </div>
</template>

<style>
.shell { display: flex; min-height: 100vh; }
.shell__sidebar {
  position: sticky; top: 0; height: 100vh; width: var(--shell-sidebar); flex: none;
  display: flex; flex-direction: column; border-right: 1px solid var(--p-content-border-color);
  background: var(--p-content-background); transition: width .2s;
}
.shell--collapsed .shell__sidebar { width: var(--shell-sidebar-collapsed); }
.shell__brand { display: flex; align-items: center; gap: 10px; padding: 16px; color: inherit; text-decoration: none !important; }
.shell__logo { display: grid; place-items: center; width: 32px; height: 32px; flex: none; border-radius: 8px; background: var(--p-primary-color); color: var(--p-primary-contrast-color); font-weight: 700; }
.shell__nav { display: flex; flex-direction: column; gap: 2px; padding: 8px; flex: 1; overflow-y: auto; }
.shell__group { font-size: 11px; color: var(--p-text-muted-color); padding: 8px 12px 4px; text-transform: uppercase; letter-spacing: .04em; }
.shell__link { display: flex; align-items: center; gap: 10px; min-height: 40px; padding: 8px 12px; border-radius: var(--p-content-border-radius); color: var(--p-text-color); text-decoration: none !important; }
.shell--collapsed .shell__link { justify-content: center; padding: 10px 0; }
.shell__link:hover { background: var(--p-content-hover-background); }
.shell__link--active { background: var(--p-highlight-background); color: var(--p-highlight-color); font-weight: 500; }
.shell__footer { border-top: 1px solid var(--p-content-border-color); padding: 8px; display: flex; flex-direction: column; gap: 4px; }
.shell__user { display: flex; align-items: center; gap: 10px; min-height: 40px; padding: 8px; border-radius: var(--p-content-border-radius); color: inherit; text-decoration: none !important; }
.shell--collapsed .shell__user { justify-content: center; }
.shell__user:hover { background: var(--p-content-hover-background); }
.shell__main { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.shell__topbar {
  position: sticky; top: 0; z-index: 10; display: flex; align-items: center; gap: 8px; height: 64px; padding: 0 24px;
  border-bottom: 1px solid var(--p-content-border-color); background: color-mix(in srgb, var(--p-content-background) 92%, transparent); backdrop-filter: blur(8px);
}
.shell__crumbs.p-breadcrumb { background: transparent; border: 0; padding: 0; }
.shell__content { padding: 24px; min-width: 0; }
.shell__dot { width: 8px; height: 8px; border-radius: 50%; margin-top: 6px; flex: none; background: var(--p-surface-300); }
.shell__dot--unread { background: var(--p-primary-color); }
@media (max-width: 767px) {
  .shell__topbar { padding: 0 12px; height: 56px; }
  .shell__content { padding: 16px; }
}
</style>
