// apps/react-bootstrap/src/App.tsx
import { useEffect } from "react"
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom"
import { AppShell } from "@/layouts/app-shell"
import { ComponentsPage } from "@/pages/components"
import { ChatPage } from "@/pages/chat"
import { DashboardPage } from "@/pages/dashboard"
import { FormPage } from "@/pages/form"
import { LandingPage } from "@/pages/landing"
import { LoginPage } from "@/pages/login"
import { OrdersPage } from "@/pages/orders"
import { SettingsPage } from "@/pages/settings"

function useUrlSettings() {
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const explicit = params.get("theme")
    const dark = explicit === "dark" || (!explicit && window.matchMedia("(prefers-color-scheme: dark)").matches)
    document.documentElement.setAttribute("data-bs-theme", dark ? "dark" : "light")
    const fonts: Record<string, string> = {
      inter: "'Inter Variable', sans-serif",
      geist: "'Geist Variable', sans-serif",
      "noto-sans-sc": "'Noto Sans SC Variable', sans-serif",
      "lxgw-wenkai": "'LXGW WenKai Screen', serif",
    }
    const font = fonts[params.get("font") ?? ""]
    if (font) document.documentElement.style.setProperty("--bs-body-font-family", font)
    else document.documentElement.style.removeProperty("--bs-body-font-family")
  }, [])
}

function App() {
  useUrlSettings()
  return <BrowserRouter basename="/apps/react-bootstrap"><Routes><Route path="/login" element={<LoginPage />} /><Route path="/landing" element={<LandingPage />} /><Route element={<AppShell><DashboardPage /></AppShell>} path="/" /><Route element={<AppShell><OrdersPage /></AppShell>} path="/orders" /><Route element={<AppShell><FormPage /></AppShell>} path="/form" /><Route element={<AppShell><SettingsPage /></AppShell>} path="/settings" /><Route element={<AppShell><ComponentsPage /></AppShell>} path="/components" /><Route element={<AppShell><ChatPage /></AppShell>} path="/chat" /><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter>
}

export default App

// apps/ant-design-vue/src/App.vue
<script setup lang="ts">
import { computed, ref, watchEffect } from "vue"
import { RouterView, useRoute } from "vue-router"
import { ConfigProvider, App as AntApp, theme } from "ant-design-vue"
import AppShell from "./layouts/app-shell.vue"
import ThemeBody from "./theme-body.vue"
import router from "./router"

const route = useRoute()
const params = new URLSearchParams(window.location.search)
const dark = ref(params.get("theme") === "dark" || (!params.get("theme") && window.matchMedia("(prefers-color-scheme: dark)").matches))
const font = params.get("font") ?? "default"
const fontMap: Record<string, string> = {
  inter: "'Inter Variable', sans-serif",
  geist: "'Geist Variable', sans-serif",
  "noto-sans-sc": "'Noto Sans SC Variable', sans-serif",
  "lxgw-wenkai": "'LXGW WenKai Screen', serif",
}
const isPublic = computed(() => route.path === "/login" || route.path === "/landing")
const configTheme = computed(() => ({ algorithm: dark.value ? theme.darkAlgorithm : theme.defaultAlgorithm, ...(fontMap[font] ? { token: { fontFamily: `var(--font-sans)` } } : {}) }))
watchEffect(() => {
  document.documentElement.classList.toggle("dark", dark.value)
  document.documentElement.style.colorScheme = dark.value ? "dark" : "light"
  document.documentElement.style.setProperty("--font-sans", fontMap[font] ?? "inherit")
})
function toggleTheme() {
  dark.value = !dark.value
  const next = new URL(window.location.href)
  next.searchParams.set("theme", dark.value ? "dark" : "light")
  router.push(`${route.path}?${next.searchParams.toString()}`)
}
</script>

<template>
  <ConfigProvider :theme="configTheme">
    <ThemeBody>
      <AntApp>
        <template v-if="isPublic">
          <RouterView />
        </template>
        <AppShell v-else :dark="dark" @toggle-theme="toggleTheme">
          <RouterView />
        </AppShell>
      </AntApp>
    </ThemeBody>
  </ConfigProvider>
</template>
